### PR TITLE
Issue #3291657 by Sutharsan, Ressinel: social_event_update_10306 does not finish

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
The update script `social_event_update_10306()` does not finish if the field `field_event_enable_enrollment` is not present or empty. This situation was encountered while updating from **Open Social** `10.2.2` to `11.3.3`.

## Solution
Also update the `current` counter when not processing the entity.

## Issue tracker
- https://www.drupal.org/project/social/issues/3291657

## Theme issue tracker
N/A

## How to test
- [ ] Difficult... but run `social_event_update_10306()` on an installation that does not have the `field_event_enable_enrollment`, run the update scripts and I'm sure that your drush output will be:
```
...
> [info] Configuration core.entity_view_display.profile.profile.teaser has been successfully updated.
>  [notice] Update completed: social_profile_update_11301
>  [notice] Update started: social_event_update_10306
...
```

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Fixed issue where social_event_update_10306 does not finish.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3050-koi0txvdx2sezfuhym7ywulxmjvptuxm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62dfecc619770b441ae76ee3

**Comment by Ressinel** [comment]
Let's close since Mergeable went mad and I don't know how to stop it 😄

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3050-azar1j1zgqhlurdbsmmikm3i33dk6v4q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62dff22ea476796b1c1d5db0

**Comment by Ressinel** [comment]
Hi, @navneet0693 

Could you review this, please? 
I think it can be an easy fix that fixes a huge problem with updating to the latest OS versions.

Thanks!

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.5.x here 8bf4b69012831d3b3eb398255145a8da45de5715

**Pull request merged**
