### PR TITLE
Issue #3338945 by vnech: Event ending status doesn't considering user timezone

### PR DESCRIPTION
**Pull request by nechai**
## Problem
We have issue that event is considered as passed for users with timezones in range `[+1h ... +12h]`.

For example, we have an event with today's end date `10:00 am (UTC)`.
I'm logged in as user with timezone `EEST (Europe/Helsinki)` with timeshift `+2h`.
If I visit an event at `10:30 am (EEST)` I can't enroll to event because event it considered as passed for me (but there is 1:30h to it ends).

## Solution
Fix event passing end date counting.

## Issue tracker
- https://www.drupal.org/project/social/issues/3338945
- https://getopensocial.atlassian.net/browse/PROD-23421

## Theme issue tracker
n/a

## How to test
- [ ] Login as CM+
- [ ] Make `UTC` as your default timezone (in user settings page)
- [ ] Create a public event that is finished in `1h`
- [ ] Login as LU
- [ ] Make `EEST (Europe/Helsinki)` as your default timezone (in user settings page)
- [ ] Visit an event and try to enroll

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Screenshot 2023-02-03 at 16 11 40

Screenshot 2023-02-03 at 16 09 46

## Release notes
Event passing date respects user timezone.

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Review by ribel — APPROVED** [review]
Changes was tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Review by nkoporec — APPROVED** [review]
Need to wait for tests to pass, then we can merge it.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3304-lpi7fpqusgtqnjmxstfzsnnrgrghp7wo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63dd17a1127cbc4c56411b88

**Comment by nkoporec** [comment]
:cherries: picked to 11.6.x,11.7.x,11.8.x

**Pull request merged**
