### PR TITLE
Internal: Unlock behat major version for CI testing

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution
In #3578 we locked the major version because alpha versions of a new release were causing the wrong update path to be tested. We're now back with a stable 12.0 release and working on 13.0 so we can test the upgrade path from the latest 12 release  to `main`

We may in the future want to test the previous marjor release to our backported current major version's upgrade path still works but that requires additional workflow code and GitHub workflow resources.

## Issue tracker
Internal no change

## How to test
- [ ] Behat test should test from latest 11.x to this PR for the update test

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3679-t3fihpme3dsoycf9iebcocoh5jhyzv5g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596b8d915a27ec46ac39078

**Review by ronaldtebrake — APPROVED** [review]

**Pull request merged**
