### PR TITLE
Added fixes for PHPCS.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Drupal coding standard check is failing due to release of new Coder module.
https://www.drupal.org/project/coder/releases/8.3.14

## Solution
Fix coding standard errors.

## Issue tracker
N.A

## How to test
- [ ] All checks should pass.

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2727-8bgmfdzafgfsvuof3peabcyrtd6r4rba.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f7a46100c7e8a758e3f57b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2727-8bgmfdzafgfsvuof3peabcyrtd6r4rba.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f7a46100c7e8a758e3f57b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2727-8bgmfdzafgfsvuof3peabcyrtd6r4rba.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f7a46100c7e8a758e3f57b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2727-8bgmfdzafgfsvuof3peabcyrtd6r4rba.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f7a46100c7e8a758e3f57b

**Review by Ressinel — APPROVED** [review]

**Pull request merged**
