### PR TITLE
Issue #3123493 by AlanHDev: Resolve missing/broken view filter on activity stream

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Follow up: https://github.com/goalgorilla/open_social/pull/1818

The Activity Stream view page for /stream displays an error on the views UI in the Filter Criteria. This is basically a filter that does not have (and never has had) an accompanying plugin. It was introduced here: https://github.com/goalgorilla/open_social/pull/539/files

## Solution
- Remove the filter from the view config files
- Add an update hook to remove from the current config.

## Issue tracker
- https://www.drupal.org/project/social/issues/3123493

## How to test
- [x] `drush en views_ui -y`
- [x] Visit `/admin/structure/views/view/activity_stream` and confirm that `'Broken/missing handler'` no longer appears in the Filter Criteria section.

## Screenshots
N/A

## Release notes
Resolved missing/broken view filter on the activity stream.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2396-mdswrd4somadf8jpaa04t0simkppxquq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60deb38cf543e7209068d6c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2396-mdswrd4somadf8jpaa04t0simkppxquq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60deb38cf543e7209068d6c1

**Review by navneet0693 — CHANGES_REQUESTED** [review]
```
The following updates are pending:

social_activity module :
  10301 -   Resolve missing filter on Activity Stream view.

Do you wish to run all pending updates? (y/n): y
Invalid argument supplied for foreach() social_activity.install:279                                                                                                           [warning]
Performing social_activity_update_10301                                                                                                                                       [ok]
Cache rebuild complete.                                                                                                                                                       [ok]
Finished performing updates.
```

**Comment by Ressinel** [comment]
> ```
> The following updates are pending:
> 
> social_activity module :
>   10301 -   Resolve missing filter on Activity Stream view.
> 
> Do you wish to run all pending updates? (y/n): y
> Invalid argument supplied for foreach() social_activity.install:279                                                                                                           [warning]
> Performing social_activity_update_10301                                                                                                                                       [ok]
> Cache rebuild complete.                                                                                                                                                       [ok]
> Finished performing updates.
> ```

Hi @navneet0693 

Try to check it now and let me know if you see that warning now.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2396-mdswrd4somadf8jpaa04t0simkppxquq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60deb38cf543e7209068d6c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2396-mdswrd4somadf8jpaa04t0simkppxquq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60deb38cf543e7209068d6c1

**Review by navneet0693 — APPROVED** [review]

**Pull request merged**
