### PR TITLE
Issue #3224249 by Ressinel: Update the Better Exposed Filters module from 3.0-alpha6 to 5.0-beta3

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Better Exposed Filters module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3224249

## How to test
- [ ] Go to `/search/content`
- [ ] Try filter content by using exposed filters

## Screenshots
N/A

## Release notes
The Better Exposed Filters module has been updated to 5.0-beta3. Please view the [release notes](https://www.drupal.org/project/better_exposed_filters/releases) from 3.0-alpha6 of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2420-3nabjqbta2hajrw1miz4te6sqolajaej.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f57b867424683dfb624534

**Comment by ronaldtebrake** [comment]
Since this is a major we can only do it as part of 11.x.x

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2420-bmmwseg8fgyfigmfxu03fvmwfo8jgim8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61274921b52cf94fa8c5b057

**Comment by navneet0693** [comment]
Let the dependabot take care of upgrade PRs ;-)

**Pull request closed without merging**
