### PR TITLE
Issue #3222381 by agami4: Improve elements where right-to-left alignment is off

### PR DESCRIPTION
**Pull request by agami4**
## Problem
Improve elements where right-to-left alignment is off

## Solution
Add improvements to the elements where right-to-left alignment is off

## Issue tracker
https://www.drupal.org/project/social/issues/3222381
https://getopensocial.atlassian.net/browse/YANG-5303

## How to test
*For example*
- [ ] Enable social_translation_manager module
- [ ] set up Arabic language
- [ ] make sure that module works correctly with Google translate extension

## Release notes
The elements where right-to-left alignment is on

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2402-pb04e8btcsd9cxlnefjixcnjm82guosp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e466b9462cdf857596894d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2402-pb04e8btcsd9cxlnefjixcnjm82guosp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e466b9462cdf857596894d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2402-pb04e8btcsd9cxlnefjixcnjm82guosp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e466b9462cdf857596894d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2402-pb04e8btcsd9cxlnefjixcnjm82guosp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e466b9462cdf857596894d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2402-pb04e8btcsd9cxlnefjixcnjm82guosp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e466b9462cdf857596894d

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 10.2.x

**Pull request merged**
