### PR TITLE
DS-1034 by ribel: When a LU comments on a post, event or a topic created by me, I want to be notified via email

### PR DESCRIPTION
**Pull request by ribel**
# HTT
- [x] Pull code from this branch to active site installation.
- [x] Run updates, Clear cache and check that nothing is broken.
- [x] Find some user with generated contents and posts, go to his account edit, and enable _"A person commented on a post, topic or event created or organised by me"_.
- [x] Add some comments to nodes and posts of this user.
- [x] Check that activity streams (community, group, profile) works as before.
- [x] Run cron and check Mail, you should receive new email for each comment.
- [x] Reinstall site and do the same steps.
- [x] Check the code (see most important changes below)

# Changes
- Add ActivityEntityCondition plugin system
- Add ActivityEntityCondition plugins for Comments
- Add entity condition field to message template edit form
- Add titles to message template output text fields for clarity
- Move getDestination and getRecipient methods from ActivityAccessControlHandler to Activity class
- Add method isValidEntityCondition for ActivityEntityCondition plugins
- Rename method getActivityRelatedEntity in ActivityFactory class
- Add OwnerActivityContext plugin
- Add check for email destination when new activity is inserted
- Replace message template single value field activity_bundle_entity with multiple values activity_bundle_entities
- Add message template 'Create comment on authors node or post'
- Move config files from activity_basics module to social_activity feature

### CODE REVIEW

**Comment by NielsGG** [comment]
Hi @ribel,
Something goes wrong with the tests (an undefined step) 
41 scenarios (40 passed, 1 undefined)
812 steps (809 passed, 1 undefined, 2 skipped)
13m48.01s (47.99Mb)
--- FeatureContext has missing steps. Define them with these snippets:
    /**
     * @When I should not see the button :arg1
     */
    public function iShouldNotSeeTheButton($arg1)
    {
        throw new PendingException();
    }

**Comment by ronaldtebrake** [comment]
Sorry for that undefined step @NielsGG, @ribel should be fixed in 8.x-1.x. Had to do with another pull request.

**Comment by NielsGG** [comment]
Hi @ribel,
Small typo in "Commented on yours content" Should be your content I suppose (in message.template.create_comment_author_node_post.yml). Functionality wise it works good, fixed a small issue related to the Docker cron container with mails. Will check the code tomorrow

**Comment by NielsGG** [comment]
Merging, the code looks clean and I like the entity condition solution!

**Pull request merged**
