### PR TITLE
Issue #3255434 by SV: Token [message:preview] includes not translatable node type string

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
Notification email about adding following tags use the `[message:preview]` token which includes not translatable node type string.

## Solution
Use label instead of machine name of the content type in the token replacement.

## Issue tracker
- https://www.drupal.org/project/social/issues/3255434
- https://getopensocial.atlassian.net/browse/SUP-1967

## How to test
*For example*
- [ ] Using the latest version of Open Social with the social_follow_taxonomy module enabled
- [ ] As an administrator, try to add NL(or any other) translation of the name of some content type,
- [ ] Switch to another user and update topic/event with a tag which admin followed
- [ ] Next, switch back to the admin and select & save that language
- [ ] After, I expect that the notification email displays a translated string but instead, I see a default name of content type (EN)
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Release notes
Fixes a translation issue for [message:preview] token in the notification email.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2665-inbmhqxx0yd7ykbmyb1pewuvpvowmx3l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1d4f05f46ed13d84d3b92

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2665-inbmhqxx0yd7ykbmyb1pewuvpvowmx3l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1d4f05f46ed13d84d3b92

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2665-inbmhqxx0yd7ykbmyb1pewuvpvowmx3l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1d4f05f46ed13d84d3b92

**Review by ribel — APPROVED** [review]
LGTM

**Comment by ribel** [comment]
🍒 picked to 10.3.x and 11.0.x

**Pull request merged**
