### PR TITLE
Issue #3096602 by agami4: Update position of css style for menu on the mobile

### PR DESCRIPTION
**Pull request by agami4**
## Problem
When the admin toolbar is visible the z-index of the main menu is changed. This is done to ensure the admin toolbar is shown on top of the main menu. However, this also causes the main menu to appear under certain page elements.

This happens in all browsers

## Solution
Don't try to change the z-index of the main menu when the admin bar is present, but instead properly update the admin toolbar's z-index.

## Issue tracker
https://www.drupal.org/project/social/issues/3096602
https://getopensocial.atlassian.net/browse/YANG-1776

Also affected https://www.drupal.org/node/3106782 where a slightly different fix was previously applied.

## How to test
- [ ] Login as user with access to the admin toolbar
- [ ] Open the menu on a mobile device
- [ ] See that the menu is under certain elements on the page.

## Release notes
The main menu no longer appear under page content on mobile devices when a user has access to the administrative menus.

## Screenshots
afbeelding

afbeelding

### CODE REVIEW

**Comment by Kingdutch** [comment]
With the changes outlined above we'll also have to remove the 'slide-open' animation from the menu on mobile devices.

**Comment by agami4** [comment]
Hey @Kingdutch, I have some questions about your comments above.
- mobile main menu and mobile profile and menu "Create new CT's" - those menus should have the same styles and behaviors of JS and markup? If this question is correct - the mobile main menu should be like a profile menu?
- when the main menu(for example) is opened and the user clicks on the profile menu, the main menu must close? (This behavior for all mobile menus)

**Comment by Kingdutch** [comment]
Hey @agami4 ,

Yes, the create content menu and the navigation menu should have the same behaviour as the profile menu currently does (I discussed this briefly with Xinyu). So we probably need to change some styling and markup to achieve this.

Only one menu should be open at a time. So indeed if a user is viewing the main menu and clicks the profile menu then the main menu should close. If a user then presses the "Create Content" menu, the profile menu should close.

**Comment by agami4** [comment]
@Kingdutch, I have a proposal about new updates for all mobile menus. Maybe I create new issue on the Distro and add those updates for mobile menus and add `z-index: 3` for `.toolbar-vertical .navbar-default` and change top position from `top: 100` to `top: initial` for `.navbar-collapse .dropdown-menu` on this PR? What do you think about it? :)

**Comment by Kingdutch** [comment]
Hi @agami4 ,

I'd prefer to fix this in the right way now instead of using a workaround first. Especially since we'll probably forget to remove the unneeded workaround later, cluttering our styles.

**Comment by ronaldtebrake** [comment]
This will need some love from @Kingdutch, timewise we probably won't be able to make it in the release. But assigned accordingly so we know Shipsters will need time to work on the feedback.

**Comment by Kingdutch** [comment]
I've fixed the styling, hopefully this fixes it once and for all :D I've also moved the button to a different template where I think it makes more sense.

I've not done the larger refactoring that I outlined in my previous comment. The reason for this is that it requires quite some interruptive changes and the menu moving the main content is only an issue for people who have access to the admin toolbar. So although we see this ourselves quite often, this bug actually doesn't impact a large part of Open Social users.

**Comment by Kingdutch** [comment]
@agami4 Could you review/test this to verify that it also still fixes the issue you were having? :)

@ronaldtebrake I've described what I've done in my previous comment and updated the PR summary as well as the drupal.org issue. If you have some time to merge and cherry-pick this then that fixes an issue for SIM :)

**Comment by agami4** [comment]
@Kingdutch, I've tested your updates and all looks good for me)

**Comment by frankgraave** [comment]
This has been ported back to 8.x-7.x and 8.x-8.x.

**8.x-7.x:**
https://github.com/goalgorilla/open_social/commit/e4ba40eb1f1dc39317ce3134838cb3af39b274db
https://github.com/goalgorilla/open_social/commit/693d3c3a32a5d146cc48525fcf991b666ea4659a

**8.x-8.x:**
https://github.com/goalgorilla/open_social/commit/a5fdc526d161bd0510abd6bafcac942bffd2b196
https://github.com/goalgorilla/open_social/commit/af79b2d0396d8eb666ba1b49cb5bd1b7b9be1433

**Pull request merged**
