### PR TITLE
Issue #3270733 by Ressinel: Move social_tour out of the Distro

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Move the social_tour module out of the distribution and make it a contrib module. This module is hardly maintained, doesn't seem to work well with the front-end we're using.

## Solution
1. Make a contrib module.
2. Allow users to declare this new module in their composer.json
3. Unsupport it and allow other maintainers to take over.

## Issue tracker
- https://www.drupal.org/project/social/issues/3270733

## Theme issue tracker
N/A

## How to test
- [ ] You should not able to use `social_tour` functionality directly from **Distro** itself anymore
- [ ] Since `social_tour` was added as contrib module you will be able to enable it as before
- [ ] You are able to install the new `social_tour` contrib module via composer https://www.drupal.org/project/social_tour yourself

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
The Social Tour module was moved out of the Distro.

We decided to move this module out of the Distro and make it unsupported since it is hardly maintained, and doesn't seem to work well with the front-end we're using.

For now, we added this module to the composer.json of Distro. But it will be removed from Open Social at all in the next major release.

We are happy to give maintainers access who want to continue development on top of this. 

Visit the module page at https://www.drupal.org/project/social_tour

## Change Record
TBD

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2845-u7tzqpyxppyuciunqubatq6tuuiql8z4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62455230d128c6acc865ff01

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2845-u7tzqpyxppyuciunqubatq6tuuiql8z4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62455230d128c6acc865ff01

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2845-u7tzqpyxppyuciunqubatq6tuuiql8z4.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62455230d128c6acc865ff01

**Comment by ronaldtebrake** [comment]
LGTM, maybe we can also include a little more as to why we are moving it out and make sure that we explain that we are stopping support but happy to give maintainers access who want to continue development on top of this.

**Comment by Ressinel** [comment]
Hi @ronaldtebrake

Thanks for your feedback!
I have updated **Release notes**.

**Comment by bramtenhove** [comment]
Is it an option also to just not include this anymore in the `composer.json` file as a dependency?

**Comment by Ressinel** [comment]
@bramtenhove We will remove it from composer.json in **Open Social 12**. See **Release notes**.

**Pull request merged**
