### PR TITLE
Issue #3275931 by tbsiqueira, Ressinel, Kingdutch, ronaldtebrake, navneet0693: Replace the asset-packagist repository with custom defined packages

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Unfortunately https://asset-packagist.org/ is not longer working, and because of it we can't install/update or test Open Social. 

## Solution
We need to replace https://asset-packagist.org/ by custom packages to be able to download the necessary libs

## Issue tracker
https://www.drupal.org/project/social/issues/3275931

## Theme issue tracker
N/A

## How to test
- [ ] One should be able to install this repository using composer;

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2890-tmtvctfnraw88ebyca5qmotddzgbz2sa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625e96b88a4c5796e7c1f3f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2890-tmtvctfnraw88ebyca5qmotddzgbz2sa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625e96b88a4c5796e7c1f3f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2890-qc5lradigqgewckgqeeumfu2piilm7lp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62974c9c86897f9cbe6f78c8

**Comment by Ressinel** [comment]
@tbsiqueira I have rebased main into this branch and master at drupal_social. After those changes build works properly.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2890-qc5lradigqgewckgqeeumfu2piilm7lp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62974c9c86897f9cbe6f78c8

**Comment by navneet0693** [comment]
@Ressinel Do we require this now? Please re-open if still relevant.

**Comment by tbsiqueira** [comment]
Yes, we are still looking to replace our repos.

**Comment by navneet0693** [comment]
@Ressinel @tbsiqueira Please re-work on this.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2890-g5yuivh4rtvqe0ut9mvx57r6xfcvsvjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62df9f95fe6282831310c815

**Comment by tbsiqueira** [comment]
This should not be a part of the distro, closing the PR

**Pull request closed without merging**
