### PR TITLE
Issue #3125293 by SV: Create "Medium Teaser" view mode for profile.

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
Currently, we already have a profile--profile--medium_teaser.html.twig template in the socialbase theme but a view mode doesn't exist and we are not able to use that template/display in the views or etc.

## Solution
Create a "Medium Teaser" view mode for the profile.

## Issue tracker
- https://getopensocial.atlassian.net/browse/YANG-2482
- https://www.drupal.org/project/social/issues/3125293

## Screenshots
Screenshot from 2020-04-10 12-45-16 (1)

### CODE REVIEW

**Comment by ribel** [comment]
@volodymyr-sydor-lemberg please add a screenshot that shows how those teasers will look like.

**Comment by ribel** [comment]
@volodymyr-sydor-lemberg could you resolve conflict here?

**Comment by ronaldtebrake** [comment]
After these are resolved it can be merged and cherry-picked :) !

**Comment by ribel** [comment]
Thanks, @ronaldtebrake!
I have fixed it by myself :)
Will wait for behat tests and then will merge.

**Comment by ribel** [comment]
This PR was cherry-picked to 8.x-8.x but had a conflict because PR #1793 was not cherry-picked.
I have resolved this conflict and cherry-picked all code both PR's.

**Pull request merged**
