### PR TITLE
Issue #3004855 by truls1502: Update addtoany 8.x-1.9 to 8.x-1.10

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
Update addtoany _8.x-1.9_ to _8.x-1.10_
Difference between the versions is a bug fix.
- AddToAny field availability for all content Entities in settings (https://www.drupal.org/project/addtoany/issues/2958727)

## Issue tracker
- https://www.drupal.org/project/social/issues/3004855

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by jaapjan** [comment]
Thanks for PR. Changes look feasible, but there is currently a pull request to replace AddToAny with Shariff. Not much reason to spend time reviewing this and/or updating this module then. I'll close this one for now.

**Comment by jaapjan** [comment]
See: https://github.com/goalgorilla/open_social/pull/1100

**Comment by truls1502** [comment]
I saw the issue. But you have decided to use it, so it is fine to close this one 😊👍

**Comment by truls1502** [comment]
@jaapjan - do you want us to reopen it since #1100 will be released on 4.0, not on 3.6?

**Comment by jaapjan** [comment]
@truls1502 I don't think that is necessary. Will save some reviewing time as well. We can keep on using 1.9 on 3.x I think.

**Comment by truls1502** [comment]
Ok. 👍

**Comment by truls1502** [comment]
I just want to try to re-open for check the MOSS for 3.x version. I have also merged with latest 3.x.

**Comment by ronaldtebrake** [comment]
HI @truls1502, we decided to merge it in anyways :) thanks for the help!

**Pull request merged**
