### PR TITLE
Issue #3258202 by chmez: Social Content Block module compatibility with Drupal 9

### PR DESCRIPTION
**Pull request by ghost**
## Problem
The "Social Content Block" module isn't compatible with Drupal 9.

## Solution
Make it compatible.

## Issue tracker
- https://www.drupal.org/project/social/issues/3258202
- https://getopensocial.atlassian.net/browse/YANG-6777

## How to test
A module that contains the "social_content_block_query_alter" hook should be enabled without any errors.

## Release notes
Make the "Social Content Block" module compatible with Drupal 9.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2689-ujdd2byizrxtifxix6nekokkhefs5acw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ded333dc579fc65dc0dfa8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2689-ujdd2byizrxtifxix6nekokkhefs5acw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ded333dc579fc65dc0dfa8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2689-ujdd2byizrxtifxix6nekokkhefs5acw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ded333dc579fc65dc0dfa8

**Review by ribel — APPROVED** [review]
I have tested changes with Drupal 9 and Social 11 and it works correctly.

**Comment by ribel** [comment]
🍒 picked to 11.0.x

**Pull request merged**
