### PR TITLE
Issue #3279904 by Ressinel: Notice: Undefined index: bulk_form_keys

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
When using bulk operation for event/group membership page shows errors (only when trying to execute an action for the first time):

`Notice: Undefined index: bulk_form_keys in Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm->viewsFormSubmit() (line 926 of modules/contrib/views_bulk_operations/src/Plugin/views/field/ViewsBulkOperationsBulkForm.php).`

`Warning: Invalid argument supplied for foreach() in Drupal\views_bulk_operations\Plugin\views\field\ViewsBulkOperationsBulkForm->viewsFormSubmit() (line 926 of modules/contrib/views_bulk_operations/src/Plugin/views/field/ViewsBulkOperationsBulkForm.php).`

screencapture-0-0-0-0-49161-node-23-all-enrollments-confirm-action-2022-05-11-16_31_36

## Solution
Add fixes for Open Social Views Bulk Operations field plugins.

## Issue tracker
- https://www.drupal.org/project/social/issues/3279904

## Theme issue tracker
N/A

## How to test
*[Required] For example*
- [ ] Enable `All messages, with backtrace information` on /admin/config/development/logging
- [ ] Go to the event/group manage membership page
- [ ] Try to use bulk operation and you will see an error described in the **Problem** section
- [ ] Apply changes from this PR, try to repeat previous steps, and you won't see errors anymore

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2927-8n8y0marclyuvrqhedsjwcryfunnig3i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627bbb7f0f15004d8ee82844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2927-8n8y0marclyuvrqhedsjwcryfunnig3i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627bbb7f0f15004d8ee82844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2927-8n8y0marclyuvrqhedsjwcryfunnig3i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627bbb7f0f15004d8ee82844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2927-8n8y0marclyuvrqhedsjwcryfunnig3i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627bbb7f0f15004d8ee82844

**Review by tbsiqueira — APPROVED** [review]

**Comment by Ressinel** [comment]
🍒-picked to [11.1.x](https://github.com/goalgorilla/open_social/commit/c75fb7aecacc0bfae35e0e4b90da79f75b1b5a55) (was fixed a conflict), 11.2.x, and 11.3.x

**Pull request merged**
