### PR TITLE
Issue #3457850: Add additional fields for content export

### PR DESCRIPTION
**Pull request by Macsym2018**
## Problem
It would be interesting for Site Managers to have further fields to enable greater filtering & analysis in the Content Export extension.

## Solution
Add extra `ContentExportPlugins` for:

- Topic Type (empty if the content is not a Topic)
- Event Type (empty if the content is not an Event)
- Event Enrollees (number of enrollees with an account)
- Event Enrollees Anonymous (number of anonymous enrollees)
- Content Tags (all tags are listed, no parent-child reference necessary)

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-28483
- https://www.drupal.org/project/social/issues/3457850

## Theme issue tracker
N/A

## How to test
- [ ] Enable social_node_statistic and social_content_export, social_topic, social_event, social_event_type, social_event_an_enroll, social_tagging  modules
- [ ] Go to content page /admin/content
- [ ] Choose content for export
- [ ] Select action "Export the selected content to CSV"
- [ ] Click. the "Apply to selected item" button
- [ ] Download CSV file and check if all column exists and has the correct value

## Screenshots
N/A

## Release notes
Add new fields for content export extension.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3956-wrztwuemfw9seddjobacchnio1rexvvx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667ebcc27de2c383925e5ec5

**Review by ribel — APPROVED** [review]
Changes were tested and works as expected.

Note: since we extend `ContentExportPluginBase` from Cablecar extension `social_content_export` we have tried approach  with [Stub](https://phpstan.org/user-guide/stub-files) files or `ignoreErrors`, but it didn't work, so in the end we were need to add those plugins to `excludePaths`.

image

**Pull request merged**
