### PR TITLE
Issue #3223589 by Ressinel: Facebook embed content not working.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
I tried to embed Facebook content but this doesn't work anymore.

## Solution

- Implement the patch from the related issue for the URL Embed module https://www.drupal.org/project/url_embed/issues/3177860#comment-13950783
- Fix conflict with patch from the previous step and from this issue https://www.drupal.org/project/social/issues/2930457#comment-13973067
- Create Facebook APP with necessary settings

## Issue tracker
- https://www.drupal.org/project/social/issues/3223589
- https://getopensocial.atlassian.net/browse/TB-5898

## How to test
App ID: `292492365949252`
App Secret: `91000d81249617340b04b0e067536bfc`
- [ ] Use this env for test https://issue-3223589-facebook-hdsgyqq-72phd64vv6oao.eu.platform.sh/
- [ ] Make sure that the new patch for the URL Embed module is applied correctly
- [ ] Go to `/admin/config/media/url_embed` and fill App ID and App Secret provided above
- [ ] Try to add the [Facebook post link](https://www.facebook.com/1022239641146386/posts/4072041979499455/?d=n) in a text editor and save content
- [ ] On frontend you must see a normal embed Facebook post instead of the link to that post

## Screenshots
Before:

before

After:

fb-post

## Release notes
Fixed issue where Facebook/Instagram embed content not working.

## Change Record

> Changes to tokenless access for User Picture and FB/IG OEmbed endpoints: By October 24, 2020, developers must leverage a user, app, or client token when querying Graph API for user profile pictures via UID, FB OEmbeds and IG OEmbeds. Developers should provide a user or app token when querying for profile pictures via a UID or ASID, though client tokens are supported as well.

It is gotten from the [official source](https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8/).

Create an App and enable **Live** mode:
https://developers.facebook.com/docs/development/create-an-app

For allows your app to get embed HTML and basic metadata for public Facebook and Instagram pages, posts, and videos need request [oEmbed Read](https://developers.facebook.com/docs/features-reference/oembed_read) feature (requires [App Review](https://developers.facebook.com/docs/app-review/)).

Once you have the request accepted you can continue with Open Social settings.

fbapp1
fbapp2

Login as SM+, go to `/admin/config/media/url_embed`, and fill **App ID** and **App Secret** from app you created.

os

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by robertragas** [comment]
@Ressinel Is this one still actively being worked on, because we do get questions from time to time about it? I think it also need some documentation similar to the social media login.

**Comment by Ressinel** [comment]
Hi @robertragas

I have left some documentation in the **Change Record** section. So, if you have an approved FB APP then Facebook and Instagram content embed will be working with changes this PR.

Let me know if I need to expand the documentation I created. And can you share a link for the social media login documentation?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by nachosalvador** [comment]
Hey @Ressinel, I review it and the patch applies and works as expected. 

I just update the PR add permisisions. We need to provide the sitemanager with the option to configure those credentials. Because the endgoal would be for them to all do it themselves  :smile: 

Also I'm working to create the documentation.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2416-o7ksranvxy7vwc7isuysidnr65vjxhby.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eed30300f236adaa0b158e

**Comment by Ressinel** [comment]
Hello @nachosalvador Nice to hear that)

You can use information from the **Change Record** section in this PR for documentation=) 
Would be great if you share it here after the documentation will be ready)

**Comment by Ressinel** [comment]
Hey @nachosalvador How is it going with documentation? 
Have you any comments about this PR whether we can merge it?

**Comment by nachosalvador** [comment]
Hey @Ressinel. I created an unpublished book page with documentation following your steps https://communitytalks.getopensocial.com/connect-facebook.
Still needs a review before to be published.

**Review by navneet0693 — APPROVED** [review]

**Pull request merged**
