### PR TITLE
Issue #3004862 by truls1502: Update features 3.7 to 3.8

### PR DESCRIPTION
**Pull request by truls1502**
## Problem &  Solution
[Full Changelog](http://cgit.drupalcode.org/features/diff/?h=8.x-3.x&id=da215a63fc650c6e6abba1c0f1ba529a79d7e1cf&id2=96e978aa58afaa45a5d6054f1500ae925f419f33)
- https://www.drupal.org/project/features/releases/8.x-3.8

## Issue tracker
- https://www.drupal.org/project/social/issues/3004862

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by robertragas** [comment]
Restarted the travis build. Locally I tested it out and works correctly.

**Comment by truls1502** [comment]
@robertragas - anything we can help you regarding `Needs MOSS work`-label?

**Comment by truls1502** [comment]
> > @robertragas - anything we can help you regarding `Needs MOSS work`-label?
> 
> No, you cannot help with this, MOSS basically is the same as travis but tests the code against our current customers and could be that they need a rebuild triggered. Normal users don't have access to see or work on this, so we have to fix this internally.

I know, but if there is anything we can help. Let us know, ok?
However, do you want me to merge with the latest `8.x-3.x`? or let it stay as it is now? 😊

**Comment by robertragas** [comment]
I retriggered the MOSS builds and fixed it for 2 enterprise clients, I expect it to turn green now.

**Comment by truls1502** [comment]
Great 👍

**Pull request merged**
