### PR TITLE
Issue #3380714: Create update hook to migrate old group types to flexible groups

### PR DESCRIPTION
**Pull request by Kingdutch**
⚠️ This should be merged after https://github.com/goalgorilla/open_social/pull/3692
⚠️ This PR is part of a set of stacked commits please do not rebase this PR but instead ping @Kingdutch

## Problem
We have platforms with a lot of old groups for the old types (public, open, closed, secret) which we want to migrate to the flexible group type. Because there are a lot of these groups with associated content and relationships we need to be efficient in our update hooks and can not load entities into memory while migrating them.

## Solution
We provide a set of update hooks with custom crafted queries. This allows the migration to happen in-database which drastically speeds the migration up and allows the migration to happen with minimal memory consumption.

We migrate all the available plugins and roles.

We provide a global opt-out hook through Drupal state for community platforms that want to provide their own migration for whatever reason.

*Note*: This PR does not yet create taxonomy terms for the group types and fill those in for associated group types during migrations. To help platforms that are using the old group types distinguish between the different types of groups they had. Since this won't be released yet we can make that change to the update hook in a future PR without delaying testing.

## Issue tracker
https://www.drupal.org/project/social/issues/3380714
Subtask https://getopensocial.atlassian.net/browse/PROD-27947

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3693-fjtydtnqrlppdvxnccpcruejkb0jjd33.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ebb175f6e0620e619e8a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3693-fjtydtnqrlppdvxnccpcruejkb0jjd33.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ebb175f6e0620e619e8a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3693-fjtydtnqrlppdvxnccpcruejkb0jjd33.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ebb175f6e0620e619e8a0

**Comment by ribel** [comment]
@Kingdutch, @nechai It looks like we can already merge this one. 
Could you check and confirm?

**Review by nechai — APPROVED** [review]

**Pull request merged**
