### PR TITLE
Add a flexible time slot for sending daily and weekly email notificat…

### PR DESCRIPTION
**Pull request by slowflyer**
## Problem
The daily and weekly email notifications are send out more or less random over 24hours of day.
If they are send out during the night, users will maybe not take as much attention to it, when clean up there mailbox in the morning compared to an email send during "business"-hours.

## Solution
Define a time slot for sending out daily and weekly notifactions. Add an administer interface to "/admin/config/opensocial/swiftmail" which should be the best place for this setting. Allow admins to define a time slot for sending out email notifications.

## Issue tracker
[*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*](https://www.drupal.org/project/social/issues/3261031)

## How to test
*For example*
- [x] Using version 11 Open Social 
- [x] As a administrator
- [x] Define a bunch of activities as daily or weekly email notifiactions
- [x] Define a time slot at /admin/config/opensocial/swiftmail (if not emails are send out by default between 0:00 and 23:55)
- [x] Check that you receive the emails during the specified timeslot (maybe first on day 2)

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*A short summary of the changes that were made that can be included in release notes.*

## Change Record
*If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2721-srvp5zfgpllr1lfighnlhqzbgy6wwgid.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3bcdd046a4b8d29481bff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2721-srvp5zfgpllr1lfighnlhqzbgy6wwgid.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3bcdd046a4b8d29481bff

**Comment by navneet0693** [comment]
@slowflyer Please merge "main" in your branch, and then change the target to 'main' branch.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2721-srvp5zfgpllr1lfighnlhqzbgy6wwgid.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3bcdd046a4b8d29481bff

**Pull request closed without merging**
