### PR TITLE
Issue #3255592 by nkoporec: Social Event Anonymous Enrolments - the data policy is incorrect

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When you enable the data_policy and social_event_an_enroll and add multiple data policies, the data policies are incorrectly displayed when an anonymous user tries to enroll in the event. It will always display just the first policy. 

## Solution
The issue is that data_policy module was updated to enable multiple data policies, this change was never updated in the social_event_an_enroll module, where the code still expects only 1 data policy.

## Issue tracker
https://www.drupal.org/project/social/issues/3255592

## How to test
1. Enable data_policy and social_event_an_enroll
2. Enable data_policy
3. Add multiple data policies and update the consent text to include all of them
4. Create a public event with anonymous enrollments enabled
5. Try to enroll in an event as an anonymous user and check the data policy

## Screenshots
Before:

After:

## Release notes
Fixed data policy display when an anonymous user tries to enroll in an event.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2667-8mhcebgg67ygj2svsrebmtgw5uymou0r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c302b25f46ed13d8574cef

**Review by nachosalvador — APPROVED** [review]
Looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2667-8mhcebgg67ygj2svsrebmtgw5uymou0r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c302b25f46ed13d8574cef

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2667-8mhcebgg67ygj2svsrebmtgw5uymou0r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c302b25f46ed13d8574cef

**Comment by nkoporec** [comment]
:cherries: picked to 11.0.x and 10.3.x.

**Pull request merged**
