### PR TITLE
Issue #3254082 - Update Drupal Core to 9.2.x

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
Update Drupal Core to 9.2.x

## Solution
Update Drupal Core to 9.2.x

## Issue tracker
https://www.drupal.org/project/social/issues/3254082

## How to test
Regression tests.

## Release notes
We are using Drupal core version 9.2.x now

## Change Record
See change recors of Drupal core 9.2.0 here:  https://www.drupal.org/project/drupal/releases/9.2.0

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2645-ubj3deiifyamb9f8pgonvyavf96nd4ri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b5ea99dc579fc65dd8033b

**Comment by navneet0693** [comment]
Since we already test green, the later changes aren't affecting the current failures, they are false positive.

**Pull request merged**
