### PR TITLE
[Internal] - Fix PHPStan errors.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
There are the same PHPStant errors for each new PR which do not mention PR changes.

## Solution
Fix those PHPStan errors directly.

## Issue tracker
N/A

## How to test
- [ ] Check PHPStan in any last PRs

## Screenshots
PHPStan errors

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2418-1crqz8p7uemkks9anms524skudadnk3r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eff7e080afb0166641f330

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2418-1crqz8p7uemkks9anms524skudadnk3r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eff7e080afb0166641f330

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2418-1crqz8p7uemkks9anms524skudadnk3r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eff7e080afb0166641f330

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2418-1crqz8p7uemkks9anms524skudadnk3r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60eff7e080afb0166641f330

**Review by navneet0693 — APPROVED** [review]

**Pull request merged**
