### PR TITLE
PROD-29886: Behat tests for visibilities and comments

### PR DESCRIPTION
**Pull request by SonikaBM**
## Problem
1. There were no Behat tests that ensure the visibilities for topics and events work as expected for different roles
2. There was no Behat test to validate hidden settings for comments

## Solution
1. Create tests to validate all visibilities in topic and event overview and accessibility of the content via direct link to ensure:

- Only public entities are accessible to anonymous and unverified users
- Only public and community entities are accessible to verified user
- All entities are accessible to content manager
- Group entities are accessible to verified members of the group

2. Create test to validate open and hidden settings of comments work as expected

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-29664
- https://getopensocial.atlassian.net/browse/PROD-29665

## Theme issue tracker

N/A

## How to test
- [ ] New tests are green

## Release notes

Adds  behat test coverage for topic/events overview content visibility

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Review by nechai — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3985-5hjxh51di7k2ts29ccrgmxojnj3aw63q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/669fb809142ffaa91650b0b9

**Review by volodymyr-sydor — APPROVED** [review]

**Pull request merged**
