### PR TITLE
Issue #3052572 by agami4: Add classes for preview button on edit node page

### PR DESCRIPTION
**Pull request by agami4**
## Problem
Button Styles Missing - on [Preview] button

## Solution
Add classes for preview button on edit node page after changed button settings

## Issue tracker
https://www.drupal.org/project/social/issues/3052572

## How to test
- [x] Should change setting of buttons
- [x] Edit some node, scroll down and check 'Preview' button size

## Release notes
'Preview' button will change after add new settings of button

### CODE REVIEW

**Comment by jaapjan** [comment]
@agami4  Did you test this correctly, could you add the exact steps?

When I follow the How to test like this:

- [ ] Go to admin/appearance/settings/socialbase and set Button size to Large
- [ ] Go to admin/appearance/settings/socialblue and set border radius for buttons to 20
- [ ] Go to node edit form, e.g. node/24/edit and I expect the buttons to align properly.

But when i try this it doesn't work. See attachment.

Screenshot 2019-05-14 at 17 43 33

**Comment by agami4** [comment]
Hey @jaapjan,
I think it's a strange case. As I see on your screenshot, you use 'SocialBlue' theme, but you changed button size in the 'SocialBase' settings. Variable 'theme settings' returns 'null'.

If you use 'SocialBlue' or 'SocialBase' themes should change theme settings for theme that you use

If this case is a bug, should fixed from BE side

**Comment by jaapjan** [comment]
Ok clear, I see now. I think that is out-of-scope. I fixed one more coding standard issue. After tests are passing we can merge this one!

**Comment by jaapjan** [comment]
Cherry-picked in 5.x as well.

**Pull request merged**
