### PR TITLE
Issue #3210685 by rolki: Add a query_access handler to the comment entity type

### PR DESCRIPTION
**Pull request by rollki**
## Problem
Access checks based on published status or ownership for comments aren't performed during an entity query. This means that these checks need to be done after an entity is loaded. This causes issues for pagination, most notably in GraphQL, as outlined in #2979294: Improve pagination DX (a core issue for the JSON:API).

This problem is illustrated by `QueryCommentsTest::testUserRequiresAccessCommentsPermission` and `QueryCommentsTest::testUserCanviewOnlyOwnOrOtherPublishedComments` introduced in https://github.com/goalgorilla/open_social/pull/2285.

## Solution
As Open Social already depends on the entity module that contains the new entity access API we can use this in our solution.

We should duplicate the access checking logic for comments into the entity access API so that these access checks can be performed at query time. This needs to be done in a backwards compatible manner since existing installations may have customised their comment access checks in a way that we can not anticipate. To achieve this we'll introduce a new configuration setting in Drupal core (enabled for new sites, disabled for existing sites, enabled when social_graphql is used). This setting will be deprecated as being removed in Open Social 11.0.0 at which point we will require all sites to use the Entity Access API and sites should have adjusted its queries if they have changed comment access checks.

To indicate that the new Entity Access API can be used by any functionality extending Open Social we will add a dependency on this module i social_core.

## Issue tracker
https://www.drupal.org/project/social/issues/3210685

## Release Notes
Open Social now includes entity query access checks for comments based on the query access API from the entity module. This is enabled for new sites by default but opt-in for existing sites using the `use_entity_access_api` setting in `social_core`. This improvement allows simplifying some queries that were previously doing their own access checks.

## How to test
- [ ] Use [this](https://github.com/goalgorilla/open_social/pull/2285) PR as a patch
- [ ] Write some GraphQL query
```
  comments(first: 10) {
    nodes {
      id
      body
    }
  }
```
- [ ] You should not see unpublished comments in the response

## Screenshots

**Before changes:**

Снимок экрана 2021-05-05 в 11 34 04
Снимок экрана 2021-05-05 в 11 38 20

**After changes:**

Снимок экрана 2021-05-05 в 11 40 59
Снимок экрана 2021-05-05 в 11 42 27

### CODE REVIEW

**Comment by rollki** [comment]
Old PR that was reverted: https://github.com/goalgorilla/open_social/pull/2312

**Comment by Kingdutch** [comment]
The force push cleans up the branch by inserting a commit revert to make the history of the code clearer.

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2332-wa8tyy6fc467oa7vliggzox2tuf4z6kk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/609ce8d33e5c6442009493dc

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2332-wa8tyy6fc467oa7vliggzox2tuf4z6kk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/609ce8d33e5c6442009493dc

**Review by Kingdutch — APPROVED** [review]

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2332-wa8tyy6fc467oa7vliggzox2tuf4z6kk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/609ce8d33e5c6442009493dc

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2332-wa8tyy6fc467oa7vliggzox2tuf4z6kk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/609ce8d33e5c6442009493dc

**Review by Kingdutch — CHANGES_REQUESTED** [review]
@rollki The tests that we wrote are failing. It looks like the `CommentQueryAccessHandler` doesn't even look at the `access comments` permission. I'm not sure why that is, any thoughts?

**Comment by rollki** [comment]
@Kingdutch That's interesting because locally all tests were passed. Not sure where is the problem. Maybe the user was created without `access comments` permission?

**Comment by Kingdutch** [comment]
@rollki This is the test output (as seen on Travis)
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...............................FFF.....                           39 / 39 (100%)

Time: 15.22 seconds, Memory: 12.00 MB

There were 3 failures:

1) Drupal\Tests\social_comment\Kernel\CommentViewAccessTest::testUserCanNotViewCommentWithoutPermission

Failed asserting that actual size 2 matches expected size 0.

/var/www/html/profiles/contrib/social/modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php:119

2) Drupal\Tests\social_comment\Kernel\CommentViewAccessTest::testUserCanNotViewOwnUnpublishedComment

Failed asserting that actual size 1 matches expected size 0.

/var/www/html/profiles/contrib/social/modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php:144

3) Drupal\Tests\social_comment\Kernel\CommentViewAccessTest::testUserCanNotViewOtherUnpublishedComment

Failed asserting that actual size 1 matches expected size 0.

/var/www/html/profiles/contrib/social/modules/social_features/social_comment/tests/src/Kernel/CommentViewAccessTest.php:172

FAILURES!

Tests: 39, Assertions: 377, Failures: 3.
```

Those tests test that users without `access comments` permission can't see any comments, but since `access comments` isn't used in the access handler they can see the comments. I get the same results locally.

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2332-wa8tyy6fc467oa7vliggzox2tuf4z6kk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/609ce8d33e5c6442009493dc

**Review by Kingdutch — APPROVED** [review]
Okay looks like it was the lack of actually enabling the query_access in the test and then having to ensure that that setting was set before the entity schema was installed, otherwise the handler wouldn't be registered.

When tests are green I believe we can merge this and should have sufficient test coverage for the new access checks.

**Comment by Kingdutch** [comment]
Merging this as test failures seem to be unrelated to this PR's changes. I've filed https://www.drupal.org/project/social/issues/3215641 as an explanation for what's going on.

The changes in this PR are all isolated to GraphQL and covered by the PHPUnit tests that successfully completed.

**Pull request merged**
