### PR TITLE
Internal: Update minimal required version of Socialblue to 2.5.4

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
Socialblue is added as a minimal requirement version for 2.5.0, but since now we have a newer socialblue version we can force it to the latest version.

This PR will also force the removal of PHP 8.0 dependency as Bootstrap is no longer supporting it, thus we might consider it a breaking change.

## Solution
Update our composer.json file to require Socialblue ~[2.5.4](https://www.drupal.org/project/socialblue/releases/2.5.4), this will also require Socialbase ~[2.5.9](https://www.drupal.org/project/socialbase/releases/2.5.9) since Socialbase is a [requirement](https://git.drupalcode.org/project/socialblue/-/blob/2.5.x/composer.json?ref_type=heads#L8) of Socialblue. Those are important versions since they are now featuring Drupal 10 forward compatibility.

## Issue tracker
N/A

## Theme issue tracker
https://www.drupal.org/project/socialbase/issues/3392441
https://www.drupal.org/project/socialbase/issues/3384177
https://www.drupal.org/project/socialblue/issues/3392440
https://www.drupal.org/project/socialblue/issues/3395525
https://www.drupal.org/project/socialblue/issues/3392337

## How to test
- [ ] Open Social theme should work as it was
- [ ] Test the associated issues linked on this document "Release Notes" section

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

### Socialbase

- [#3384177: Update drupal/bootstrap from 3.26 to 3.29](https://www.drupal.org/project/socialbase/issues/3384177)
- [#3392441: Migrate SocialBase theme to D10](https://www.drupal.org/project/socialbase/issues/3392441)

### Socialblue

- [#3392440: Migrate SocialBlue theme to D10](https://www.drupal.org/project/socialblue/issues/3392440)
- [#3395525: [UI] Improve behaviour of the active item on the secondary navigation](https://www.drupal.org/project/socialblue/issues/3395525)
- [#3392337: [UI] Add throbber icon to the enroll button](https://www.drupal.org/project/socialblue/issues/3392337)

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
Thanks @tbsiqueira 
You're absolutely right, i've marked it for 12.0.0 to make sure people don't have to upgrade PHP in a minor version even if Bootstrap did without really notifying the community / using SEMVER / I feel it makes sense so we can remove PHP 8.0 support in the Distro in 12.0.0 as well and require Drupal 10 there.

**Comment by ronaldtebrake** [comment]
Rebased the branch to make sure our fixed in #3567 are added 🙏

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3566-bjtijxgpfc5ct2wk1svr1wkwiz25bfg0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6536966e8ddc85a693fe4ebe

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3566-bjtijxgpfc5ct2wk1svr1wkwiz25bfg0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6536966e8ddc85a693fe4ebe

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3566-bjtijxgpfc5ct2wk1svr1wkwiz25bfg0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6536966e8ddc85a693fe4ebe

**Comment by ronaldtebrake** [comment]
cherry picked to 12.0.x 🍒

**Pull request merged**
