### PR TITLE
Issue #3409033 - Add an update hook to remove leftsovers of the embed_button for the ckeditor 4 to 5 migration

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
When going to the Drupal status page you will see an error message like in the screenshot below.
url_embed

## Solution
The url embed module did not migrate the old plugin to the new ckeditor5 but added a new plugin. This causes the old button still being available on admin/config/content/embed which is not compatible with ckeditor5. This will not create any issues but does pollute the status page.

To solve this we can remove this old button as we don't use it anymore and replaced it with the new one.

Only remove it when no text-formats are using ckeditor4 with this plugin

## Issue tracker
https://www.drupal.org/project/social/issues/3409033

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
Scenario 1
- [ ] Enable social_embed
- [ ] Go to the status page and see the error message
- [ ] Check out to this branch and run drush updb
- [ ] See it now is gone

Scenario 2
- [ ] Enable social_embed
- [ ] add the embed button to a text format on admin/config/content/formats with the ckeditor4 (you can create a new text format if you want)
- [ ] Check out to this branch  and run drush updb
- [ ] Notice it will keep the button (also the error message) as we dont want to remove it when people still use the button for ckeditor 4 text formats
- [ ] Now remove the button again from the text format, and change in the code social_embed.post_update the social_embed_post_update_12001_remove_old_social_embed_button to social_embed_post_update_12002 remove_old_social_embed_button
- [ ] run drush updb again and see it will get removed now, as its no longer active anymore in any text format.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
During the migration from ckeditor4 to 5 there we still some leftovers in the code that caused a warning on the Drupal status page. This has been fixed now.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by robertragas** [comment]
This still needs 1 fix for new install to remove the button from being installed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Review by vcsvinicius — APPROVED** [review]
I approved this change

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by BiaInacio** [comment]
Test done, all working fine!
No more erro regarding CKEditor
image
and the embed feature is working fine
image
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3647-esdgc3chmgjvtg1h4kxn7qpbncpdbwbf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657c54e4404f391589ee334e

**Comment by ronaldtebrake** [comment]
Cherry picked to 12.1.x and 12.0.x

**Pull request merged**
