### PR TITLE
#3045903 : Private messages permission improvements

### PR DESCRIPTION
**Pull request by slowflyer**
## Problem
You can or will have users with differet roles / permissions in the community. If users based on their roles are not allowed to use private messaging, all private messaging stuff should be hidden for them. And for users who are allowed to use Private messages, they should not be able to send a message to a user who cant read it.

## Solution
Better check for user permissions implemented 

## Issue tracker
https://www.drupal.org/project/social/issues/3045903

## How to test
- [x] Have users with the permission to use private messages and users without the permission
- [x] Login as user without the permission to use Private messages
- [x] You will see the envelope icon in menu
- [x] go to /user/inbox -> you will get a "permission denied" notice for the page, but the button will still show up
- [x] go to /all-members -> you will see "Private message" link for all users listed
- [x] install the patch
- [x] Login as user without the permission to use Private messages
- [x] You will see NO envelope icon in menu
- [x] go to /user/inbox -> you will get a "permission denied" notice for the page, NO button will show up
- [x] go to /all-members -> you will see NO "Private message" link for all users listed
- [x] Login as user WITH the permission to use Private messages
- [x] You will see the envelope icon in menu

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by slowflyer** [comment]
Here's the How to Test:
Have users with the permission to use private messages and users without the permission

Login as user without the permission to use Private messages

You will see the envelope icon in menu

go to /user/inbox -> you will get a "permission denied" notice for the page, but the button will still show up

go to /all-members -> you will see "Private message" link for all users listed

install the patch

Login as user without the permission to use Private messages

You will see NO envelope icon in menu

go to /user/inbox -> you will get a "permission denied" notice for the page, NO button will show up

go to /all-members -> you will see NO "Private message" link for all users listed

Login as user WITH the permission to use Private messages

You will see the envelope icon in menu

go to /user/inbox -> you will see the page and the button will show up

**Comment by slowflyer** [comment]
Any idea why moss is failing?

**Comment by jaapjan** [comment]
> Any idea why moss is failing?
Nope, but we will check this when reviewing! Usually it's false negative. Don't worry about it too much (even though I understand it can feel demotivating to see red check)

**Comment by jaapjan** [comment]
Could you add a how to test?

**Comment by slowflyer** [comment]
I already did.

See my coment below in the PR. I hit Enter by accident when creating the PR …

Regards,

Ullrich Neiss
Geschäftsführer

crowd-creation GmbH
Hasselborner Str. 19-21
35647 Waldsolms
Telefon:
Fax:
Email:
Web:

+49 6085 98 945 25
+49 6085 98 858 51
info@crowdcreation.de<mailto:info@crowdcreation.de>
www.crowdcreation.de<http://www.crowdcreation.de/>


Sitz der Gesellschaft: Waldsolms, Amtsgericht Wetzlar HRB 5884
Umsatzsteueridentifikationsnummer: DE 267649524
Geschäftsführung: Ullrich Neiss


Der Inhalt dieser Nachricht ist vertraulich, kann gesetzlichen Bestimmungen unterliegen, kann vertrauliche Informationen beinhalten und ist nur für den direkten Empfänger bestimmt.Sie ist Eigentum von crowd-creation. Nicht authorisierte Benutzung, unbefugte Weitergabe sowie Kopieren jeglicher Bestandteile dieser Information ist streng verboten und kann als rechtswidrige Handlung eingestuft werden. Sollten Sie diese Nachricht fälschlicherweise erhalten haben, informieren Sie bitte crowd-creation umgehend, indem Sie die Email zurückschicken und diese dann zusammen mit allen zugehörigen Kopien oder Dateianhängen zerstören.

The information contained in this communication is confidential, may be subject to legal privileges, may constitute inside information, and is intended only for the use of the addressee. It is the property of crowd-creation. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify crowd-creation immediately by return e-mail and destroy this communication and all copies thereof, including all attachments.

Von: Jaap Jan <notifications@github.com>
Gesendet: Dienstag, 9. April 2019 10:04
An: goalgorilla/open_social <open_social@noreply.github.com>
Cc: Ullrich Neiss <ullrich.neiss@crowdcreation.de>; Author <author@noreply.github.com>
Betreff: Re: [goalgorilla/open_social] #3045903 : Private messages permission improvements (#1302)


Could you add a how to test?

**Comment by Kingdutch** [comment]
The target branch of this PR has been changed to 6.x which will be the next major version. Our policy is to merge any bugfixes in the newest branch first and cherry-pick/backport any required changes. This ensures that the newest major version is the longest/least diverged branch.

**Comment by slowflyer** [comment]
Any thing I can do to move this forward?

**Comment by jaapjan** [comment]
@slowflyer not really, I think we just need to find time to review this. It does look good from conceptual point of view, but we just too busy to do the reviewing within 3 months

**Comment by jaapjan** [comment]
@slowflyer I found one small exception which caused profile contact urls to always be private message create in /all-members teasers (even though the given profile didnt have permission to use the PM system). Thats fixed in the last commit I made.

if tests are green I think we are OK with merging this.

**Comment by jaapjan** [comment]
Merged, thanks!

**Comment by jaapjan** [comment]
Will be only in 6.x. 5.x is not necessary

**Pull request merged**
