### PR TITLE
Issue #2948988 by agami4: Add an option to show event creator on event teasers

### PR DESCRIPTION
**Pull request by agami4**
## Problem
On an event it's possible to see who created an event but this is not visible on teasers even though there's some room. It would be nice if the site administrator could configure to show this.

## Issue tracker
https://www.drupal.org/project/social/issues/2948988

## How to test
-

### CODE REVIEW

**Comment by agami4** [comment]
Hey @Kingdutch,
I recreated PR for this issue. My solution is not correct and need work from BE side

**Comment by Kingdutch** [comment]
@agami4 Okay, I'm going to unassign myself because I don't have time to work on this in our current sprint and it's also not in my team's planning for upcoming sprints. 

I think with the description and our discussion in #1394 it should be pretty clear for a Back-end developer to know what needs to happen here :)

**Comment by jaapjan** [comment]
@agami4 there are merge conflicts and according to your previous comment it still needs BE work? why move it from `needs work` to `needs review`?

**Comment by agami4** [comment]
@jaapjan, merge conflict was fixed.

**Comment by Kingdutch** [comment]
This PR adds a package-lock.json. Please remove this file and use `yarn` to perform any package management that may be needed for this PR.

**Comment by jaapjan** [comment]
@agami4 did you see the comment from @Kingdutch could you fix this?

**Comment by agami4** [comment]
@jaapjan, I've updated this PR.
package-lock.json was removed

**Pull request closed without merging**
