### PR TITLE
DS-6376 - As a LU, I want to minimise the number of tabs in event.

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
The current 'manage enrollments' and 'guest enrollments' and 'enrollments' tabs should be merged into one.

## Solution
There is now a setting to minimize events on a Site on `/admin/config/opensocial/event-managers` where you can minimize the amount of tabs for Enrollments. Manage enrollments, guest enrollments and `Enrollments` are now merged in to one tab and based on the users permission you are allowed to see the list of Enrollees and perhaps also act on it.

## Issue tracker
https://jira.goalgorilla.com/browse/DS-6376

## How to test
- [x] Enable AN Enrollments + Event Organisers
- [x] Login as SM & LU and see you have a lot of tabs showing Enrollments / Guest enrollments and Manage enrollments
- [x] Enroll some users, guests / LU's so you have some data to work with
- [x] Add one Event Organizer
- [x] Login as LU who is not an Organizer and see you have one Enrollments tab
- [x] Login as Event Organizer and SM and see you still have tab for Enrollments but since you can manage them it's a Manage Enrollment tab with the same look and feel and additional VBO options / Actions.
- [x] Guest enrollees should be shown as First Name & Last Name for SM / Event Organizers.. for LU they should be shown as Guests.

## Release notes
There is now a possibility to minimize the amount of tabs for Enrollments shown on an Event reducing overhead. The tabs Manage enrollments, Guest enrollments and Enrollments are now merged in to one if you set the Minimize the amount of tabs setting.

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
TODO by ronald
- Remove the setting as discussed in shipsters sprint review.

**Comment by jaapjan** [comment]
@ronaldtebrake wondering what we should do with the old URL? `node/x/enrollments`

Also the new URL is `/node/x/manage-all-enrollments` which is perhaps not so nice if you can't manage it.

**Comment by jaapjan** [comment]
Last two acceptance criteria are not working when you open the page first as a LU (who is not an organiser of the event)

- [] Login as Event Organizer and SM and see you still have tab for Enrollments but since you can manage them it's a Manage Enrollment tab with the same look and feel and additional VBO options / Actions.
- []  Guest enrollees should be shown as First Name & Last Name for SM / Event Organizers.. for LU they should be shown as Guests.

**Comment by ronaldtebrake** [comment]
> @ronaldtebrake wondering what we should do with the old URL? `node/x/enrollments`
> 
> Also the new URL is `/node/x/manage-all-enrollments` which is perhaps not so nice if you can't manage it.

@jaapjan good point, we can still fix that as part of the coming 2 weeks.

**Comment by ronaldtebrake** [comment]
> Last two acceptance criteria are not working when you open the page first as a LU (who is not an organiser of the event)
> 
> * [] Login as Event Organizer and SM and see you still have tab for Enrollments but since you can manage them it's a Manage Enrollment tab with the same look and feel and additional VBO options / Actions.
> * []  Guest enrollees should be shown as First Name & Last Name for SM / Event Organizers.. for LU they should be shown as Guests.

Will have a look next week thx

**Comment by jaapjan** [comment]
FYI:
Added commit 730a1e5 for making sure the tabs are only being added when on an event node.

**Comment by ronaldtebrake** [comment]
Update:
Last two acceptance criteria should work:
- [ ] Login as Event Organizer and SM and see you still have tab for Enrollments but since you can manage them it's a Manage Enrollment tab with the same look and feel and additional VBO options / Actions.
- [ ] Guest enrollees should be shown as First Name & Last Name for SM / Event Organizers.. for LU they should be shown as Guests.

The defects should be fixed including these from 5.0 testing branch (the document reflects this):
- Removing enrollees as CM doesnt do anything
- Action buttons are missing for event manage enrollments
- User error: "list" is an invalid render array key for Group & Event management

- Also updated the URL to now reflect manage and not manage better (and made sure all the blocks will be there instead of on the old URL.)

**Comment by jaapjan** [comment]
Feedback:

- [ ] Warnings when there are no enrollments on an event (with social_event_an_enroll disabled, potentially also when enabled).
- [ ] When you use the actions on one enrolment (in the table itself) and the user was selected it still shows up on the "Selected users". There is no way for the user to unselect the user. (By the way @ronaldtebrake I'm also ok with removing the event enrolment actions in single enrolment)
- [ ] The token in the anonymous event enrol e-mail is not working. (might not be related)

**Comment by jaapjan** [comment]
@ronaldtebrake do you still have time to work on this during Drupalcon? If not let me know and I will reserve time tomorrow.

**Comment by ronaldtebrake** [comment]
Hi @jaapjan 

Most of the issues are addressed. The only two things left are:

> When you use the actions on one enrolment (in the table itself) and the user was selected it still shows up on the "Selected users". There is no way for the user to unselect the user. (By the way @ronaldtebrake I'm also ok with removing the event enrolment actions in single enrolment)

This is something I'm working on in a separate branch/issue. There is still some weird behaviour with updating the select amount, count and list across multiple pages. It's due to the fact its trying to remember it across multiple pages (also when there arent any multiple pages) which can give results like these. But I think I can make it work and still keep the single enrolment actions in there.

> The token in the anonymous event enrol e-mail is not working. (might not be related)

I'm very sure it's not related but tried to fix it anyway. The strange thing is if I follow the usual update paths / fresh install I can't seem to get this scenario reproducable. All the time it's getting a proper replacement for me.

**Comment by jaapjan** [comment]
@ronaldtebrake Cool, i will check it out tomorrow (Thursday)

Regarding token, maybe one-time thing and not related. Let's ignore it for now and if i have time i will dive into it on Friday.

By the way we need to check compatibility of the max event enrollment as well. #1172 

For example: where does this button go to?
Screenshot 2019-04-10 at 15 47 40

I can also do this later when I have time. Will focus first on max enrolment.

**Pull request merged**
