### PR TITLE
Issue #3413211: Unlock gin_toolbar version from composer and update from `1.0.0-rc3` to `1.0.0-rc5`

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
In our previous version we locked the Gin Toolbar module at 1.0-beta17 version [#3222350: Lock gin_toolbar to 1.0-beta17](https://www.drupal.org/project/social/issues/3222350) and it isn't be necessary anymore, so we should unlocked this version and it should be controlled by Gin module and their dependencies.

## Solution
Unlocked the Gin Toolbar module to be controlled by Gin module dependencies, which updates it to:
`drupal/gin_toolbar` requirement from 1.0.0-rc3 to 1.0.0-rc5

## Issue tracker
[PROD-27895](https://getopensocial.atlassian.net/browse/PROD-27895)
[#3413211](https://www.drupal.org/project/social/issues/3413211)

## Theme issue tracker
N/A

## How to test
Unlocked the Gin Toolbar module will upgrade two version and these versions will fix some small compatibility issue with Drupal 10, so to test it, open admin page and navigate into some pages using Admin Toolbar.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-27895]: https://getopensocial.atlassian.net/browse/PROD-27895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Review by ronaldtebrake — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Comment by BiaInacio** [comment]
admin menu works as expected!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3686-x0wdqsxtreqvqzkvwaxzz8iqyie8ao4r.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659c0fe3e08ceacf5fd85748

**Comment by vcsvinicius** [comment]
I cherry-picked it to 12.1.x branch

**Pull request merged**
