### PR TITLE
Issue #3368689 by tbsiqueira: Add PHP 8.1 compatibility to Open Social

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
PHP 8.0 will reach EOL soon, so we need to upgrade our platform to use PHP 8.1

## Solution
Upgrade our requirements to PHP 8.1

## Issue tracker
https://www.drupal.org/project/social/issues/3368689

## Theme issue tracker
N/A

## How to test
- [ ] Full regression test

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3433-efrjnyaqwrns3xiwfivpk8x3so0tckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649457b88a3005a39382a092

**Review by Kingdutch — APPROVED** [review]
We pair programmed this :D <3

**Pull request merged**
