### PR TITLE
Issue #3355561 - Change underline html tag to em to ensure translations can be imported correctly

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
```
Import of string \"<p>Dit is om te bevestigen dat je je hebt ingeschreven voor het evenement <u>[social_event:event_iam_organizing]</u>.</p>  <p>[message:preview]</p>  <p>[message:cta_button]</p> \" was skipped because of disallowed or malformed HTML. []
```

## Solution
Change `<u>` to `<em>`.

## Issue tracker
- https://www.drupal.org/project/social/issues/3355561

## Theme issue tracker
N/a

## How to test
- [ ] Add for example Dutch as a language
- [ ] Translate the source string
- [ ] Import translations
- [ ] Observe the error above is no longer shown

- [ ] Run the update hook, observe that the config item changes as expected, `drush cget message.template.user_was_enrolled_to_event`
```text:
  2:
    value: "<p>This is to confirm that you've enrolled for the event <u>[social_event:event_iam_organizing]</u>.</p>\r\n\r\n<p>[message:preview]</p>\r\n\r\n<p>[message:cta_button]</p>\r\n"
    format: full_html
```

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/a

## Release notes
Fixed an error where the translation for a string containing a `<u>` tag would not import.

## Change Record
N/a

## Translations
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3382-ig1ma3te2watiylkvxpsdaot9j0ti9ie.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64424f5289fc7aabe64998e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3382-ig1ma3te2watiylkvxpsdaot9j0ti9ie.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64424f5289fc7aabe64998e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3382-ig1ma3te2watiylkvxpsdaot9j0ti9ie.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64424f5289fc7aabe64998e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3382-ig1ma3te2watiylkvxpsdaot9j0ti9ie.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64424f5289fc7aabe64998e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3382-ig1ma3te2watiylkvxpsdaot9j0ti9ie.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64424f5289fc7aabe64998e4

**Review by tbsiqueira — APPROVED** [review]

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.8.0x

**Pull request merged**
