### PR TITLE
Issue #3386735 - Update the Data Policy module to be compatible with D10

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The current version isn't compatible with D10

## Solution
Update the Data policy module to the latest version

## Issue tracker
https://www.drupal.org/project/social/issues/3386735

Data Policy:
- https://www.drupal.org/project/data_policy/issues/3286895
- https://www.drupal.org/project/data_policy/issues/3387128

## Theme issue tracker
N/A

## How to test
- [ ] Enable Social GDPR
- [ ] Smoke test module features

### Before merge
- [x] Code/peer review is completed
- [x] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [x] All automated tests are green
- [x] Functional/manual tests of the acceptance criteria are approved
- [x] All acceptance criteria were met
- [x] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [x] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [x] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [x] This pull request has all required labels (team/type/priority)
- [x] This pull request has a milestone
- [x] This pull request has an assignee (if applicable)
- [x] Any front end changes are tested on all major browsers
- [x] New UI elements, or changes on UI elements are approved by the design team
- [x] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3520-tdjsbnqblsxoeeaa8yvnied74vqnsfdx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6500550cc2343efad22667ae

**Comment by BiaInacio** [comment]
GDPR feature is working as expected!
image

**Pull request merged**
