### PR TITLE
Issue #3428255: Event enrollments block shows incorrect amount of enrollees.

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
In the view for enrollments we show the @total count from the summary result. Because this item amount is set at 12 it will never go higher than 12. 

Screenshot 2024-03-15 at 14 01 57

## Solution
Replace it with another token to get the correct count.

- Add a custom token and use the helper method getAllEventEnrollments to get the enrollment count.
- Also set the translatable text inside the token so we can properly do plural formatting.
- Replace this token in the view.

## Issue tracker
https://www.drupal.org/project/social/issues/3428255

## How to test
- [ ] Create an event with open enrollments
- [ ] Enroll more than 12 people
- [ ] Go to the event detail page and see the block keeps stuck at 12 enrollees
- [ ] Check out to this branch and clear the cache
- [ ] See the enrollments are now correct
- [ ] Also try the same with 1 enrollment and see the grammar is now correct.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We fixed an issue for events that had more than 12 people enrolled. On the event detail page it would always show 12 enrollments. This should now show correct total amount of enrollees. Also we fixed the plural grammar error when only 1 person has enrolled.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Review by ronaldtebrake — APPROVED** [review]
Looks good to me, nice coverage as well 🙌

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by BiaInacio** [comment]
Enrollments block wording is fixed!
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3819-oxbdbcolg2ugggwsothwzceye5upctjz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f47354d95c0389471e2d7d

**Comment by robertragas** [comment]
Merged and cherry picked to 12.4.x, 12.3.x, 12.2.x and 12.1.x (even though we likely will not release 12.1.x anymore)

**Pull request merged**
