### PR TITLE
Issue #3346744 by chmez: Activity without a message

### PR DESCRIPTION
**Pull request by ghost**
## Problem
The activity entity field for a relation to the message entity can be empty.

## Solution
Ensure that this field is filled during the process of adding theme suggestions by the "Social Follow Taxonomy Term" module.

## Issue tracker
- https://www.drupal.org/project/social/issues/3346744
- https://getopensocial.atlassian.net/browse/PROD-24498

## How to test
- [ ] It's a tricky case which can be reproduced only sometimes when cron is running. More details can be found in [PROD-24498](https://getopensocial.atlassian.net/browse/PROD-24498).

[PROD-24498]: https://getopensocial.atlassian.net/browse/PROD-24498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Review by ribel — APPROVED** [review]
Changes looks good to me. 
Also it was tested and seems to sole WSOD with cron.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3332-ug6sczlz9lthjnngcfs9rcckliooi9vr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6408aea29a0990c2c099dca0

**Review by nkoporec — APPROVED** [review]

**Comment by nkoporec** [comment]
Test is also failing in the main, so its not related to these changes.

**Comment by nkoporec** [comment]
🍒 picked to 11.7.x, 11.8.x

**Pull request merged**
