### PR TITLE
DS-5881 by serhiy-chornobay: Update package.json for Social base theme

### PR DESCRIPTION
**Pull request by Crazylord**
## Problem
Update package.json library

## Issue tracker
- https://jira.goalgorilla.com/browse/DS-5881

## HTT
- [ ] Check out the code changes
- [ ] Checkout to this branch

## Release notes
Need remove node_modules fosder and run npm install

### CODE REVIEW

**Comment by Kingdutch** [comment]
Hi @Crazylord,

Although this PR updates the `package.json` file it does not contain a `yarn.lock` file. When updating dependencies this file should be updated as well : )

Could you also add some text explaining the changes you've made to Gulp (explain why)? I see that some of the changes change the paths of files which makes them relative to the working directory of the script instead of the location of the gulpfile (which is a constant).

~ Alexander

**Comment by Crazylord** [comment]
Hi @Kingdutch .
I made **npm audit** for **package.json** and check, what need update. Then updated all node modules, what recomended this audit. 
About the paths - after update, the **watch** task doesn't work with old formats of path, so I changed it.

Updated yarn.lock file

**Comment by jaapjan** [comment]
@Crazylord could you fix the conflicts?

**Comment by jaapjan** [comment]
Closing this one as there are all kind of issues with merging and cherry-picking. Must not be that hard to solve, but created follow-up issue for that:
https://www.drupal.org/project/social/issues/3015059

Please create new PR when working on that.

**Pull request closed without merging**
