### PR TITLE
Issue #3226318 by tBKoT: Update possibly translated field group labels

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
We noticed incorrect translation for form labels when switching languages. It happens because some of `hook_entity_form_display_alter` have the save process for form displays and it saves translated string to the default configuration.

## Solution
- Fix `hook_entity_form_display_alter` in all modules. Override language for configurations before saving. 
- Update all possibly broken displays.

## Issue tracker
https://www.drupal.org/project/social/issues/3226318
https://getopensocial.atlassian.net/browse/YANG-6094

## How to test
- [ ] Enable `social_tagging` and `social_content_translation` modules
- [ ] Add additional language for site
- [ ] Add translation for any field group label
- [ ] Go to any add/edit content form where used translated field group label
- [ ] Switch to added language
- [ ] Switch back to the default language

## Screenshots
image

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2450-f2m93blnexzj7swphq71idysyl84j4qq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61080d06378c5f93d37528f8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2450-f2m93blnexzj7swphq71idysyl84j4qq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61080d06378c5f93d37528f8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2450-f2m93blnexzj7swphq71idysyl84j4qq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61080d06378c5f93d37528f8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2450-f2m93blnexzj7swphq71idysyl84j4qq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61080d06378c5f93d37528f8

**Review by ribel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2450-f2m93blnexzj7swphq71idysyl84j4qq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61080d06378c5f93d37528f8

**Pull request merged**
