### PR TITLE
Internal: Ensure upgrade path is tested

### PR DESCRIPTION
**Pull request by Kingdutch**
This PR depends on #3285 and #3282, merge those first

## Problem
While moving over the behat tests from our `@stability-*` set-up to running all test folders on separate GitHub Workflow Jobs we lost the test that would upgrade Open Social from one major version to another.

## Solution

In this commit we add a new parameter to our matrix which will perform an installation of the previous major version, update all the code and then run the database updates. This will ensure all our tests run against an updated site with and without all optional modules so that we know our update hooks don't break anything.

## Issue tracker
Internal no ticket

## Follow-ups
Some tests showed possible issues in our upgrade path. However, this PR is more valuable merged than waiting to fix the issues it discovered so a follow-up meta ticket with children has been created:

[[meta] Check upgrade path for failing tests](https://www.drupal.org/project/social/issues/3334767)
- ["Send Email" action is not installed properly in update to Open Social 11](https://www.drupal.org/project/social/issues/3334769)
- [Data policy update test fails if module is already installed](https://www.drupal.org/project/social/issues/3334770)
- [groups-create-closed.feature fails for updates](https://www.drupal.org/project/social/issues/3334773)
- [check-revoke-or-grant-administrador-roles.feature fails for update](https://www.drupal.org/project/social/issues/3335828)
- [check-export-users-to-CSV.feature fails for update](https://www.drupal.org/project/social/issues/3335829)
- [user-consent.feature fails for update](https://www.drupal.org/project/social/issues/3335830)
- [groups-mute-notify.feature fails for update](https://www.drupal.org/project/social/issues/3335831)
- [groups-create-secret.feature fails for update](https://www.drupal.org/project/social/issues/3335832)

## How to test
- [ ] Behat should pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by Kingdutch** [comment]
This is blocked by missing tags in goalgorilla/open_social_dev which prevents composer in the workflow from installing Open Social 10 before upgrading to Open Social 11.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3138-p9pxcb3ssi0uclznmjeopfughz4enjdi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932f2332d30df7ac38db98

**Pull request merged**
