### PR TITLE
DS-5914: Post comment size

### PR DESCRIPTION
**Pull request by jaapjan**
## Problem
Post comment field is made too tall (potentially due to big pipe)

## Solution
Update script autosize for comment fields

## Issue tracker
- https://jira.goalgorilla.com/browse/DS-5914

## HTT
- [x] Check out the code changes
- [x] Enable big_pipe
- [x] Check the homepage in the base branch, notice the comment post field height is not correct
- [x] Checkout to this branch
- [x] Check post comment field height and notice the height changes when you click on it.

## Documentation
- [ ] This item is documented on LGOS
- [ ] This item has been added to the feature overview

## Release notes
The post comment form was shown in double the size as usual. We fixed this.

### CODE REVIEW

**Comment by ribel** [comment]
Hi @jaapjan,
@Crazylord is no longer work on Open Social, so I think he will not have time to work on it. 
But since as you mentioned there is some issue only with BigPipe and on SaaS, I think any other developer can also take a look to it.

**Comment by jaapjan** [comment]
I did a `gulp scripts` and the diff is a bit bigger, but now it seems to work.

**Comment by jaapjan** [comment]
Ah, it only works after a refresh on the page or when resizing the window. I think it still needs a bit of work though, but an extra pair of eyes is welcome :-)

**Comment by ronaldtebrake** [comment]
Cherry picked to 4 and 5 🥇

**Pull request merged**
