### PR TITLE
Issue #3245767 by rolki: As a SM I can configure different homepages for different roles

### PR DESCRIPTION
**Pull request by rollki**
## Problem
Currently we have the possibility to configure an homepage for AN users and one for LU users. As part of this story we want to extend this feature and allow SM to configure different homepages per role.

## Solution
Remove hardcode and extend functionality to other roles.

## Issue tracker
- https://www.drupal.org/project/social/issues/3245767
- https://getopensocial.atlassian.net/browse/YANG-6192

## How to test
- [ ] Enable the `alternative_frontpage` module
- [ ] Go to the settings `/admin/config/alternative_frontpage`
- [ ] Set some custom path for some role
- [ ] Go to the home page under that role

## Screenshots
image

## Release notes
It will be possible to configure front page for each role.

## Change Record
Configuration structure will be changed for `alternative_frontpage.settings.yml`.

## Translations
No.

### CODE REVIEW

**Comment by navneet0693** [comment]
@rollki You are right! Is it possible to borrow the idea from that PR and work on incorporating them here?

**Comment by rollki** [comment]
### Note:
Previously, it was possible to add custom pages only for anonymous and authenticated users, and for content and site managers it was given the ability to view pages that were redirected and a corresponding message was displayed.

Currently, this functionality is simplified, content and site managers can in any case edit and view pages intended for other roles, and now separate home pages can also exist for content and site managers, so the previous functionality looks unnecessary and outdated.

> You are right! Is it possible to borrow the idea from that PR and work on incorporating them here?
Let me think.

**Comment by rollki** [comment]
@navneet0693 I agree that would be good to combine these two PR's, I'll try to allocate some time to do it.

**Comment by rollki** [comment]
We decided to combine this PR with https://github.com/goalgorilla/open_social/pull/1718, so some additional work needed here.

**Comment by rollki** [comment]
Closed because of https://github.com/goalgorilla/open_social/pull/2590

**Pull request closed without merging**
