### PR TITLE
Issue #3366231 by zanvidmar: Profile organization tag with special characters not displayed correctly

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
Profile organization tag with special characters not displayed correctly in profile stream.

## Solution
Remove double-escaping.

## Issue tracker
[3366231](https://www.drupal.org/project/social/issues/3366231)

## Theme issue tracker
N/A

## How to test
- [ ] Clean installation of Open Social
- [ ] Enable social_profile_organization_tag module
- [ ] Go to /admin/structure/taxonomy/manage/profile_organization_tag/overview and create new tag "A&B's"
- [ ] Go to /user/1/profile and add newly created tag to the "Organization tag" field
- [ ] Create a topic: /node/add/topic and comment on it (/node/1)
- [ ] Go to profile stream /user/1/stream and you will see double-escaped string "admin from A&B's commented on admin's topic" instead of "admin from A&B's commented on admin's topic"
- [ ] The expected result "admin from A&B's commented on admin's topic" is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Review by nkoporec — APPROVED** [review]
LGTM

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by BiaInacio** [comment]
Change working as expected!
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3422-sswuosgah5xk7hooxnlpjycgo7qgsag5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6487382f4c72b346f26c6275

**Comment by tbsiqueira** [comment]
Chert-picked to 11.8.x and 11.9.x

**Pull request merged**
