### PR TITLE
Bug/remove user login from group mails

### PR DESCRIPTION
**Pull request by NickDaelemans**
## Problem
When sending group invitation mails, we include the accept url for the invite. We are sending the user to /user/login page with the accept url as a destination. However, this interferes with the app.

When you are invited to a private group, you get a mail, which contains a link to the new group. If you click on the link, you accept the invite. The link is going to /user/login with the accept url as a destination (https://example.com/user/login?destination=/social-group-invite/{group_id}/accept).

This doesn't work on the app, because all user/login url's are forced to open in the browser. From the moment you log in, you are redirected to the app, but it doesn't show you the accept url anymore, because it has lost that context. If you we send the user directly to the app (by not using /user/login, but the accept url directly, it will open the app (and if necessary) redirect the user to the browser to login. If the user is already logged in, it will show in the app.

## Solution
Change the url, so it doesn't contain the destination part anymore. Use the accept url as url for the email. Drupal will handle the login logic.

## Issue tracker
* https://www.drupal.org/project/social/issues/3305677
* https://getopensocial.atlassian.net/browse/APP-364

## How to test
- [ ] Log in to the app
- [ ] Receive an invitation to any private group
- [ ] Open mail manager logged with the appropriate email
- [ ] Open the email with an invitation
- [ ] Tap the button

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3076-8jv1dpflgdh4nyfb0ned0t3ahlx88czf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6305e217a982dc5767a62d83

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3076-8jv1dpflgdh4nyfb0ned0t3ahlx88czf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6305e217a982dc5767a62d83

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3076-8jv1dpflgdh4nyfb0ned0t3ahlx88czf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6305e217a982dc5767a62d83

**Comment by NickDaelemans** [comment]
Reopening because of some failures.

**Pull request closed without merging**
