### PR TITLE
Issue #3420170: Move metatag configuration into the individual modules rather than `social_metatag`

### PR DESCRIPTION
**Pull request by Kingdutch**
⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). Do not use the rebase button, but instead rebase the branch of the last PR in the series [using git rebase --update-refs](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️

Should be merged after https://github.com/goalgorilla/open_social/pull/3754

## Problem
We currently have the social_metatag module which contains metatag configuration for a lot of distribution features. However, this makes it easy to forget to update this for new features and also creates a silent dependency of the metatag module on all of our features (which is not actually set in the .info.yml module).

## Solution
We can add metatag and metatag_open_graph to our social.installer_options_list.yml file so that they can be installed as optional features that are enabled by default.

We can split the current config/modify file into a file per feature so that we can co-locate the metatag configuration within the features itself rather than requiring a centralized module.

These changes make it so we can almost remove the social_metatag entirely except some more work needed for social_metatag_metatag_route_entity.

## Issue tracker

https://www.drupal.org/project/social/issues/3420170

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes

Metatag configuration is now stored in the modules that provide the features for which the metatag configuration exists rather than in the social_metatag module.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3756-85eeria2cenatvrhsq8is9v3ajr2vhsz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4ff904d84dbee027b7d67

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3756-85eeria2cenatvrhsq8is9v3ajr2vhsz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4ff904d84dbee027b7d67

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3756-85eeria2cenatvrhsq8is9v3ajr2vhsz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4ff904d84dbee027b7d67

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3756-85eeria2cenatvrhsq8is9v3ajr2vhsz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4ff904d84dbee027b7d67

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3756-85eeria2cenatvrhsq8is9v3ajr2vhsz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4ff904d84dbee027b7d67

**Review by nechai — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to the 12.2.x

**Pull request merged**
