### PR TITLE
Issue #3371231 by nkoporec: Make Tugboat testing environment compatible with PHP 8.1

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
As PHP 8.0 is reaching EOL, we need to make the Tugboat environment compatible with PHP 8.1

## Solution
Update Tugboat docker image to use PHP 8.1

## Issue tracker
https://www.drupal.org/project/social/issues/3371231

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ]  Full regression test in Tugboat

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3444-xjjkse7vkx8lvlyrma0eevlnmdfo4ff2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d261ec74483291e905a69

**Comment by tbsiqueira** [comment]
Duplicated from https://github.com/goalgorilla/open_social/pull/3460

**Pull request closed without merging**
