### PR TITLE
Issue #3210717 - As a LU, I want my group membership count to show only active & correct group memberships

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
Right now in the Profile statistics block we count a users group memberships according to

```$variables['profile_groups'] = count(\Drupal::service('social_group.helper_service')->getAllGroupsForUser($user->id()));```

This however doesn't take in to account what kind of groups / memberships there are.

For example a Group type could be filtered which makes sure the membership count isn't correctly reflected compared to the Groups overview.
For example a user could get an invite or request to join a Group, there aren't full memberships untill accepted so they shouldn't be part of the count.

## Solution
The current count isn't flexible enough, it counts all occurrences of group plugins but that doesn't allow us to filter out group types, or plugins easily without breaking BC or cache.

So instead we:
1. Created a separate helper function to count a users group membership
2. Add a query tag so people can alter the query
3. Add an alter hook, so people can filter out certain group types

## Issue tracker
https://www.drupal.org/node/3210717

## How to test
- [x] Enable SKY as a theme so the Profile statistics block is shown
- [x] As a sitemanager, invite user Chris Hall to a new group
- [x] Go to the profile -> Groups overview of Chris Hall
- [x] See that invites are removed from the Group count and the group count is the same as the joined groups in the groups overview

## Release notes
We ensured the count of groups in the profile statistics block show the correct count and allows for better altering if certain groups should not be reflected there.

### CODE REVIEW

**Review by navneet0693 — APPROVED** [review]
**Before**
image

**After**
image

**Comment by ronaldtebrake** [comment]
Merged 10.2 back in here, test fails seem related to the gin_toolbar issue. I think you can merge/backport it after it's green @navneet0693

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2306-hor7bklkcknwtyr5sje8ledth4iql1rl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9ebf0c8256036963eb2e7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2306-hor7bklkcknwtyr5sje8ledth4iql1rl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9ebf0c8256036963eb2e7

**Comment by navneet0693** [comment]
Travis is failing due to curl_exec() errors which is unrelated to this PR and a known error, so merging this.

**Comment by navneet0693** [comment]
🍒 - picked to 10.2.x and 10.1.x

**Pull request merged**
