### PR TITLE
Issue #3355356 by SV: Prevent duplicated logo images on the Files page

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem
Looks like when a logo is not uploaded in the socialblue_footer_powered block it could generate duplicates:

Screenshot 2023-04-20 at 16 28 46

## Solution
Add a check if the default logo exists then it should prevent the creation a new files.

## Issue tracker
- https://www.drupal.org/project/social/issues/3355356
- https://getopensocial.atlassian.net/browse/PROD-25135

## Theme issue tracker
N/A

## How to test
- [ ] Using the latest version of Open Social with the social_footer, file modules enabled
- [ ] Try to open the front page and clear caches two times 
- [ ] Then go the admin/content/files page and I shouldn't see "open_social_logo.png" duplicated files
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Fixed an issue with "open_social_logo.png" duplicated records on the files page

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3380-tsxtjum7x3w83pwznf2phfzpfjxbbndo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/644144d389fc7aabe63bd1a6

**Review by ribel — APPROVED** [review]
Changes was tested and looks good to me.

**Comment by ribel** [comment]
🍒 picked to 11.8.x and 11.9.x

**Pull request merged**
