### PR TITLE
Updates: Bump Group module to 2.3.0

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem (for internal)
The Group module has a new version to be compatible with D11.

## Solution (for internal)
Update Group module to 2.3.0 and reworked patch from GNode.

## Release notes (to customers)
Group module release note: https://www.drupal.org/project/group/releases/2.3.0

## Issue tracker
[PROD-31110](https://getopensocial.atlassian.net/browse/PROD-31110)

## Theme issue tracker
N/A

## How to test
- [ ] Make regression test at Social Group feature

## Change Record
N/A

## Translations
N/A

[PROD-31110]: https://getopensocial.atlassian.net/browse/PROD-31110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4164-wk4oj1cdemsudajcahotug9dvjc0laoj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672a89d221db79eb232181dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4164-wk4oj1cdemsudajcahotug9dvjc0laoj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672a89d221db79eb232181dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4164-wk4oj1cdemsudajcahotug9dvjc0laoj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672a89d221db79eb232181dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4164-wk4oj1cdemsudajcahotug9dvjc0laoj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672a89d221db79eb232181dc

**Comment by BiaInacio** [comment]
I did a regression on groups, checking its workflow, visibility settings, content creation, user invitation and group posts; All good!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4164-wk4oj1cdemsudajcahotug9dvjc0laoj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672a89d221db79eb232181dc

**Review by denis-getopensocial — APPROVED** [review]
🚀

**Pull request merged**
