### PR TITLE
Issue #3119338 by agami4: Add margin to the region content if sidebar is not display

### PR DESCRIPTION
**Pull request by agami4**
## Problem
There are no margins from the sides of the content block.

## Solution
Add margin to the content block.

## Issue tracker
https://www.drupal.org/project/social/issues/3119338

## How to test
- [ ] Go to the group page
- [ ] Go to the manage members tab
- [ ] Activate mobile/tablet mode
 
## Screenshots
before:
Image_00116481583331108

after:
Screenshot at Mar 12 13-06-33

## Release notes
User overview pages in groups and events needed a bit more breathing room on screens bigger than a phone but smaller than a desktop. This room has been provided.

### CODE REVIEW

**Comment by agami4** [comment]
@Kingdutch, I've checked and I've not found this bug. You can see the screenshot. I think to makes sense to close this PR? What do you think?
no_bug

**Comment by Kingdutch** [comment]
Hey @agami4 , is this then also fixed in your original screenshot that clearly shows the bug?

If it's no longer an issue we can close this as "Cannot Reproduce"

**Comment by agami4** [comment]
@Kingdutch, yes, I can not reproduce this bug.I'll write some message about this bug to Andrii(QA) for testing

**Comment by andho7** [comment]
@agami4 the issue can be reproduced on eci-demo [tablet view]
image

**Comment by agami4** [comment]
@ribel, @Kingdutch, I've updated the changes. The region content changes were reverted and added new changes for view_group_member. I found this view only on the group pages.

**Comment by Kingdutch** [comment]
Cherry-picked to 8.x in 1828fe53b

**Pull request merged**
