### PR TITLE
Issue #3356508 - Deleting users with a lot of activities crashing with memory limit

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
When deleting a user it will trigger the activity_creator delete hook, this will in turn delete all the activities for the user.
These activities are currently being deleted with a multiple_load inside the activity_creator, when doing this for 4k items or more the memory will time out.

## Solution
Altering this to a batch we make sure we don't make the request too heavy and divide it per batch. Also it will improve the interface when deleting a user, because now it will seem stuck on status 'initializing'. With this change you will see the process of deleting the activities which is the most heavy process of deleting users.

## Issue tracker
https://www.drupal.org/project/social/issues/3356508

## How to test
- [ ] Create a user with a lot of activities, this can be creating topics or posting stuff in the stream that will trigger the message_template.
- [ ] Go edit the user and cancel account
- [ ] See that it will time out with memory issues
- [ ] Check out to this branch and try again 
- [ ] Note that you see the amount of activities being deleted but also not timing out anymore.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We fixed an issue where old users with a lot of activities couldn't be deleted because the action would time out with an error message.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3387-yfzsrpcugk6ma7ft7t3m2y13kxir8ql6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6448e9fe92a6d1e96d1c5418

**Review by nkoporec — APPROVED** [review]
The code changes are good, also the new tests.

**Comment by nkoporec** [comment]
:cherries:  picked to 11.8.x,11.9.x

**Pull request merged**
