### PR TITLE
PROD-30978: Implement EDA event for when a user profile is updated

### PR DESCRIPTION
**Pull request by tregismoreira**
> [!CAUTION]
> This PR depends on #4111

## Description
This pull request introduces the new EDA event "profile updated" which is dispatches to the Kafka topic `com.getopensocial.cms.profile.update`.

The event is triggered when a user profile is updated (only if any data changes).

Here's an example of the generated payload:

```
{
	"specversion": "1.0",
	"id": "ccb6623d-4516-41b3-b2fa-5f1af46e1621",
	"source": "/user/4/profile",
	"type": "com.getopensocial.cms.profile.update",
	"datacontenttype": "application/json",
	"time": "2024-10-24T12:17:27Z",
	"data": {
		"user": {
			"id": "44fc2f3a-da2f-11e5-b5d2-0a1d41d68578",
			"created": "2024-10-24T12:17:27",
			"updated": "2024-10-24T12:17:27",
			"status": "active",
			"displayName": "Michelle Clark",
			"firstName": "Michelle",
			"lastName": "Clark",
			"email": "drupal_social+michelleclark@goalgorilla.com",
			"roles": [
				"authenticated",
				"verified"
			],
			"timezone": "Europe/Amsterdam",
			"language": "en",
			"address": {
				"label": "",
				"countryCode": "",
				"administrativeArea": "",
				"locality": "",
				"dependentLocality": "",
				"postalCode": "",
				"sortingCode": "",
				"addressLine1": "",
				"addressLine2": ""
			},
			"phone": "+1-202-555-0112",
			"function": "diverse",
			"organization": "freelance advisor",
			"href": {
				"canonical": "http://cablecar.localhost/user/4/home"
			}
		},
		"actor": {
			"application": null,
			"user": {
				"id": "3cd53a66-b86a-41b4-8225-66eed5bb5fe3",
				"displayName": "admin",
				"href": {
					"canonical": "http://cablecar.localhost/user/1/home"
				}
			}
		}
	}
}
```

## Release notes (to customers)
N/A

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-30978

## Theme issue tracker
N/A

## How to test
- [x] Checkout branch `issue/PROD-30978-eda-event-profile-update`
- [x] Enable modules `social_eda` and `social_eda_dispatcher`
- [ ] Update an user profile

The message should be dispatched to Kafka. If you are running locally using the Docker containers, you should be able to see the message on the Kafka UI at http://localhost:8080/.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4143-pntrzivppcvlaatrxxbmd2m5ahe0416s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6721605b3e2dd2b98c318ae1

**Review by ribel — APPROVED** [review]

**Pull request merged**
