### PR TITLE
Issue #3400861: User module is too old after update 11 > 12

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
After updating from 11.9 to version 12, updating the database returns the error
`
[error] The installed version of the /User/ module is too old to be updated day. Update to a version earlier than 10.0.0 first time (missing updates: user_post_update_update_roles).
if we still update the database, the site crashes with the following error:
 Plugin (group_invitation) instance class "Drupal\ginvite\Plugin\GroupContentEnabler\GroupInvitation" does not exist.
and
The service "group.relation_handler.operation_provider.group_invitation" has a dependency on a non-existent service "group.relation_handler.operation_provider".
`

## Solution
Trick Drupal in to thinking our post update hook has ran, by adding a update hook that adds this to the db and lets drupal know.

## Issue tracker
[PROD-27727](https://getopensocial.atlassian.net/browse/PROD-27727)
[#3400861](https://www.drupal.org/project/social/issues/3400861)

## Theme issue tracker
N/A

## How to test
- [ ] Restore the database from Share Square at local environment;
- [ ] Go to console and try to run an drush command, example: drush updb;
- [ ] Check if an error with same message from issue isn't showing;

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-27727]: https://getopensocial.atlassian.net/browse/PROD-27727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3646-k6woj2hjdtnuyfvgxdzfmbkxpjpspvmw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657b415eecba8e8697c14084

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3646-k6woj2hjdtnuyfvgxdzfmbkxpjpspvmw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/657b415eecba8e8697c14084

**Review by ronaldtebrake — APPROVED** [review]
Screenshot 2023-12-15 at 11 02 38

Works great, awesome :D !

**Comment by ronaldtebrake** [comment]
Also in 12.0.x 🍒

**Pull request merged**
