### PR TITLE
Issue #3277125 by agami4: Add improvements to the follow and message buttons

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The `follow/message` buttons have different styles than the default buttons

## Solution
Remove and add general improvements to the `follow/message` buttons.

## Issue tracker
https://www.drupal.org/project/social/issues/3277125
https://getopensocial.atlassian.net/browse/YANG-7639

## Theme issue tracker
- https://www.drupal.org/project/socialbase/issues/3277127 ([MR](https://git.drupalcode.org/project/socialbase/-/merge_requests/121))
- https://www.drupal.org/project/socialblue/issues/3277195 ([MR](https://git.drupalcode.org/project/socialblue/-/merge_requests/79))

## How to test
*[Required] For example*
- [ ] Go to `/admin/config/opensocial/follow-user` page.
- [ ] Enable the checkbox button.
- [ ] Login as a member
- [ ] Go to the `/all-members` page.

## Screenshots
before:
image-20220420-124714

after:
Screenshot 2022-05-03 at 10 27 56

## Release notes
The `follow/message` buttons have general styles.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by Ressinel** [comment]
@agami4 Buttons are cut when we have a larger description:

fd61caa612b6a7079069b9fd8bcb83c3

**Comment by ribel** [comment]
Hi @Ressinel

I see you removed `needs work` label, but didn't approve it yet, so wondering what is the status here? :)
cc @agami4

**Review by Ressinel — APPROVED** [review]
LGTM

**Comment by Ressinel** [comment]
@agami4 Could you remove redundant commits? And we will be ready to merge. Thanks!

**Comment by agami4** [comment]
@Ressinel, I've fixed merge conflict

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2905-h5woo4skv9inlridlrvo9m3vcn3symhm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6268ee0cef17c6f5690bdf8b

**Comment by Ressinel** [comment]
🍒-picked to `11.3.x`

**Pull request merged**
