### PR TITLE
Issue #3365270 by agami4: Add improvements to the `Unfollow` button on the stream teasers

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The `Unfollow` button is displayed on the stream teaser.

## Solution
Change styles to the `Unfollow` button on the stream teasers.

## Issue tracker

- https://www.drupal.org/project/social/issues/3365270
- https://getopensocial.atlassian.net/browse/PROD-25576

## Theme issue tracker
N/A

## How to test
- [ ] Go to the Stream
- [ ] Find the teaser with the `Unfollow` button.
- [ ] They should looks correct (without button style)

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
before:
image-20230602-114132

## Release notes
The `Unfollow` button is hidden on the stream teasers.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3416-zewjpjuz9kpq69u5cevyz7wghsjozul1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64804bbfa18a5084bb603c8e

**Review by ribel — APPROVED** [review]
Changes were tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3416-zewjpjuz9kpq69u5cevyz7wghsjozul1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64804bbfa18a5084bb603c8e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3416-zewjpjuz9kpq69u5cevyz7wghsjozul1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64804bbfa18a5084bb603c8e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3416-zewjpjuz9kpq69u5cevyz7wghsjozul1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64804bbfa18a5084bb603c8e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3416-zewjpjuz9kpq69u5cevyz7wghsjozul1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64804bbfa18a5084bb603c8e

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.9.x

**Pull request merged**
