### PR TITLE
Issue #3217389 by robertragas: add administrative area as an option f…

### PR DESCRIPTION
**Pull request by robertragas**
…or the address field to hide

## Problem
Currently we are able to hide subfields of an address (admin/config/opensocial/profile-fields) namely,
- city
- address
- postal code

But for some countries it can be the also have an administrative area, for example the united state. I would be nice to also give the ability to hide this.

## Solution
Add administrative area as an option to disable

## Issue tracker
https://www.drupal.org/project/social/issues/3217389

## How to test
- [ ] Go to admin/config/opensocial/profile-fields and disable all address fields
- [ ] Try to edit your profile and set the country to united states.
- [ ] See the state also appearing
- [ ] Check out to this branch, go to the settings from the first step and disable administrative area
- [ ] Edit your profile again and see the state also be hidden
- [ ] Also try to export users and see administrative area is added

## Release notes
We have added the possibility to hide the administrative area for the address field. This has been made for countries that work with states such as the United States.

### CODE REVIEW

**Review by nkoporec — APPROVED** [review]
I approve after all checks are green.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2374-uihkbc0cpjcdhtvkynrxhaxf5emkxf74.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc918cc17bbef5057c586a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2374-uihkbc0cpjcdhtvkynrxhaxf5emkxf74.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc918cc17bbef5057c586a

**Review by nachosalvador — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2374-uihkbc0cpjcdhtvkynrxhaxf5emkxf74.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60cc918cc17bbef5057c586a

**Pull request merged**
