### PR TITLE
Issue #3365299 by vnech: Allow for guest event enrollers add event to iCal calendar

### PR DESCRIPTION
**Pull request by nechai**
## Problem
As guest event enroller I can't add event to iCal calendar because when I click on link "iCal calendar" I am prompted to log in.

## Solution
Allow for Guest event enrollers add event to iCal calendar

## Issue tracker
- https://www.drupal.org/project/social/issues/3365299
- https://getopensocial.atlassian.net/browse/PROD-25586

## Theme issue tracker
n/a

## How to test
- [ ] Login as admin
- [ ] Enable `social_event_addtocal` and `social_event_an_enroll` modules
- [ ] Create a public event with enabled option "Allow users to enroll to this event without an account"
- [ ] As anonymous enroll to event and try to add the event to "iCal" calendar

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
Allow for guest event enrollers to add event to iCal calendar

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3417-2xymnbusy3cvnfrt2ilnncmimd6tkpmf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/648070b84c72b346f2def499

**Review by ribel — APPROVED** [review]
Since we don't have test for Add to calendar feature at all, but it's important to have this bug-fix in next release we agreed to add Behat test in follow up PR.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3417-2xymnbusy3cvnfrt2ilnncmimd6tkpmf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/648070b84c72b346f2def499

**Comment by ribel** [comment]
🍒 picked to 11.8.x and 11.9.x

**Pull request merged**
