### PR TITLE
Internal: Update the solr version 9 to 9.2 as config for SOLR 9 was missing in image

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
We have added ci test for solr:9 but this version is not defined and using the image from 8 months ago. This is still using the drupal 8 config.

## Solution
Use the 9.2 version

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Review by Kingdutch — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-zjftts7biqupll1kwgnyka2oj7w3hdzl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d32aebe946a8470ddc54ca

**Comment by Kingdutch** [comment]
We're reverting in https://github.com/goalgorilla/open_social/pull/3787 instead

We can't figure out why SOLR 9 seems to quit on us during site install. This is not reproducable locally, so something in GitHub works differently from local set-up.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3782-g3qj8bfddcbxpthldr1h1xp5h4vofuec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d5cb913a26bc1dce9a1540

**Comment by robertragas** [comment]
Closing this one again as it was an experimental branch.

**Pull request closed without merging**
