### PR TITLE
Issue #3004864 by truls1502: Update flag 4.0.0-alpha2 to 4.0.0-alpha3

### PR DESCRIPTION
**Pull request by truls1502**
## Problem &  Solution
[Full Changelog](https://cgit.drupalcode.org/flag/diff/?h=8.x-4.x&id=0b3501e5d0399c1dd5bd8a5478aed2bb2c7c381f&id2=fa68edef64d741bd15106818e232ae01c99f6f07)
- https://www.drupal.org/project/flag/releases/8.x-4.0-alpha3

## Issue tracker
- https://www.drupal.org/project/social/issues/3004864

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
The flag module has been updated to the latest version. If you have a custom theme please check if you have overridden flag.html.twig and add the correct classes.

### CODE REVIEW

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by jaapjan** [comment]
@truls1502 

FYI the test `topic-follow-content.feature` is still failing, see Travis results at https://travis-ci.org/goalgorilla/open_social/jobs/455193071 

That feature is using the Flag module which indicates that this update is causing an issue. 

In addition the feature status is not default, see:
https://travis-ci.org/goalgorilla/open_social/jobs/455193068

Could you work on those issues to finish the PR?

**Comment by truls1502** [comment]
Sure, I can have a look at it. And I have put it **Needs work** to fix the feature tests. I have struggled with testing on `drupal_social`. Referring to #1042 - that is why I have not solved the other PRs yet.

**Comment by truls1502** [comment]
Now I will try to fix it. 🤓 

However, do you @jaapjan, @ronaldtebrake, @Kingdutch, @bramtenhove or any of @goalgorilla/open-social mind to help me to point narrowly where and how to correct the Behat/feature tests in `topic-follow-content.feature`-file and any file(s) inside in `/modules/social_features/social_follow_content`-folder?

Since it is the first time I am correcting a Behat/feature tests. So I hope I can learn how to fix it then I can fix easier for the other PRs.

Thank you in advance! 🙏

**Comment by robertragas** [comment]
The test itself is not faulty, when clicking the follow button it does not change the text. 
The flag update added a new file called js/flag-action_link.flash.js which tries to append a class to a paragraph (p) child that does not get's created. Could be related to the following issue.

https://www.drupal.org/node/2764709

**Comment by robertragas** [comment]
flag.html.twig seems to have been changed and added some different classes, we need to update our template in socialbase.

**Comment by robertragas** [comment]
I also updated the PR description with release notes. Also included in here that people with their own custom themes might need to add these classes to flag.html.twig if they overridden it for their custom theme.

**Comment by truls1502** [comment]
:white_check_mark: Finally, our friend Travis has accepted it when it has passed all the five tests - https://travis-ci.org/goalgorilla/open_social/builds/456982046

Thank you for great help, @robertragas! 🙇👍

**Pull request merged**
