### PR TITLE
Issue #3431288 by vnech: Prevent wrong sorting option set on "Custom content list" block

### PR DESCRIPTION
**Pull request by nechai**
## Problem
When you creating a **Custom content list** block you get an error if switch options in **Sorting** field:

Screenshot 2024-03-18 at 12 19 40

**Steps to reproduce**:
- Login as admin
- Go to _/block/add/custom_content_list_ page
- Chose "Event" in **Type of content** field
- Chose "Oldest -> Newest" in **Sorting** field
- Chose "Topic" in **Type of content** field
- AB: you will see error in **Sorting** field

## Solution
Add` #process` callback function to `field_sorting` field to reassign values

## Issue tracker
- https://www.drupal.org/project/social/issues/3431288
- https://getopensocial.atlassian.net/browse/PROD-28328

## How to test
- [ ] Login as admin
- [ ] Go to _/block/add/custom_content_list_ page
- [ ] Chose "Event" in **Type of content** field
- [ ] Chose "Oldest -> Newest" in **Sorting** field
- [ ] Chose "Topic" in **Type of content** field
- [ ] EB: you should not see error in **Sorting** field

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Prevent wrong sorting option set on "Custom content list" block.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3820-mhpx3xwsaru8zserhgpxwu7rvaciufze.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f82951f80481d8f0b23391

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3820-mhpx3xwsaru8zserhgpxwu7rvaciufze.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f82951f80481d8f0b23391

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3820-mhpx3xwsaru8zserhgpxwu7rvaciufze.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f82951f80481d8f0b23391

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3820-mhpx3xwsaru8zserhgpxwu7rvaciufze.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f82951f80481d8f0b23391

**Review by ribel — APPROVED** [review]
Changes were tested and looks good to me.

image

**Comment by ribel** [comment]
🍒 picked to 12.3.x, 12.2.x and 12.1.x

**Pull request merged**
