### PR TITLE
Bypass group access permissions doesn't show post stream on group page

### PR DESCRIPTION
**Pull request by NickDaelemans**
## Problem
When viewing a group while having the 'Bypass group access' permission doesn't show the activity stream

## Solution
Alter the Activity post visibility access view filter to allow users with the right permission to view the posts in the group.

## Issue tracker
[*Paste a link to the drupal.org issue queue item. If any other issue trackers were used, include links to those too.*
](https://www.drupal.org/project/social/issues/3252758)

## How to test
*For example*
- [ ] Add a user that has the 'bypass group access' permission
- [ ] Go to a group that has posts and where you are **not** a member of.
- [ ] You should see the posts inside the group.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2635-duvdtkb1bg71ev0j599qs3fzh1jtkp1r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addebdb5f1e20f721a21d4

**Review by nachosalvador — APPROVED** [review]
Looks good to me

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2635-duvdtkb1bg71ev0j599qs3fzh1jtkp1r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addebdb5f1e20f721a21d4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2635-duvdtkb1bg71ev0j599qs3fzh1jtkp1r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addebdb5f1e20f721a21d4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2635-duvdtkb1bg71ev0j599qs3fzh1jtkp1r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addebdb5f1e20f721a21d4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2635-duvdtkb1bg71ev0j599qs3fzh1jtkp1r.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addebdb5f1e20f721a21d4

**Pull request merged**
