### PR TITLE
Issue #3388559: Apply patch at Private Message module to be compatible with D10

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The current private message version isn't be compatible with Drupal 10

## Solution
Apply the patch from [#3297888: Automated Drupal 10 compatibility fixes](https://www.drupal.org/project/private_message/issues/3297888) to private message 3.0.0-beta2 version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3388559
- https://www.drupal.org/project/private_message/issues/3297888

## Theme issue tracker
N/A

## How to test
- [ ] Enable Social Private Message
- [ ] Smoke test at Private Message feature

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by BiaInacio** [comment]
Private messages are working as expected!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Review by nkoporec — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3535-y25ocwyexauoqeageajyy3li1y1mumql.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/650aeff5a72d0957edec8139

**Pull request merged**
