### PR TITLE
Issue #3274539 by alex.ksis: Generate URL instead of using plain text URL.

### PR DESCRIPTION
**Pull request by ksis**
## Problem
If the website is in a subdirectory and we are trying to approve a membership request, we get a 404 error.

## Solution
Generate a URL for the approve/reject links using API instead of using a plain text URL.

## Issue tracker
- https://www.drupal.org/project/social/issues/3274539
- https://getopensocial.atlassian.net/browse/YANG-7484

## How to test

- [ ] Setup the Open Social in a subdirectory
- [ ] Create a group with "Request to join"
- [ ] As a regular user, send a request to join
- [ ] Go to the requests page (/group/%/members-pending) and try to approve/reject the request.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2871-pbhgtvjzxc9posbpc1lwboyklwfnga45.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253ee3adb46ec195962808a

**Comment by Ressinel** [comment]
Hi @ksis 

I see that d.org [issue](https://www.drupal.org/project/social/issues/3274539) has the status **Needs review** but PR is not ready to review. Could you prepare PR to be ready to review?

Thanks!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2871-pbhgtvjzxc9posbpc1lwboyklwfnga45.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253ee3adb46ec195962808a

**Comment by Ressinel** [comment]
Hi, @ksis Is this PR ready to review? If so, could you make it not draft?

**Comment by ribel** [comment]
Closing in favour  of https://github.com/goalgorilla/open_social/pull/2998

**Pull request closed without merging**
