### PR TITLE
Issue #3473556: Disable the placeholder for Embed URL when adding or editing content

### PR DESCRIPTION
**Pull request by rochek03**
## Problem
When the user enables the "_Enforce consent for all embedded content settings_", they will see a consent button on the embedded media preview. However, when the Site Manager creates or edits content with embedded media, they also see this consent button, even on the create or edit page, which they shouldn't.

## Solution
Add route checking in the process method of SocialEmbedUrlEmbedFilter to avoid adding the placeholder on the `embed.preview` route (this route is used to apply the filter when adding or editing a new embed URL).

## Issue tracker

- https://www.drupal.org/project/social/issues/3473556
- https://getopensocial.atlassian.net/browse/PROD-30643

## How to test
- [ ] Enable module "social_embed"
- [ ] Login as admin, go to page “/admin/config/opensocial/embed-consent”, enable all checkboxes
- [ ] Log in as a user with the _"Site manager"_ role
- [ ] Go to _"User Edit"_ page `user/{id}/edit`
- [ ] Enable the checkbox _"Enforce consent for all embedded content settings"_
- [ ] Create any CT with text long field, for instance, _"Topic"_
- [ ] Fill in Embed URL of Vimeo video _**"https://vimeo.com/1006140147"**_
- [ ] **You shouldn't see** see the placeholder with the consent button
- [ ] Save node and go to node view
- [ ] And now **you should see** the placeholder with the consent button

## Screenshots
image
image

## Release Notes
Disabled placeholder of Embed URL during creation or editing content.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4070-lg9v7ndlnbpidavvigidp6ioq6vfzits.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e18760e06d1f5785fba933

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4070-lg9v7ndlnbpidavvigidp6ioq6vfzits.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e18760e06d1f5785fba933

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4070-lg9v7ndlnbpidavvigidp6ioq6vfzits.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e18760e06d1f5785fba933

**Review by ribel — APPROVED** [review]
Changes were tested and work as expected now.

**Pull request merged**
