### PR TITLE
Issue #3346966 by ronaldtebrake: Social Content Translation Config Override runs in unnecessary circumstances.

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
As we're adding this to social_core, so we can easily and always extend this (without creating dependencies) we need to make sure we worry about performance as well. The config override is added on runtime for every request now; but it should only kick in when:

- Social content translation is enabled.
- The module, extending, is configured to be true in the content translation settings
- The config name matches the overridden translations from the extending plugin

## Solution
If its not enabled, lets return early, saves a hell of a lot of checks. 
If it is enabled, lets make sure we statically cache the settings from config, 
otherwise we need to load that over and over.
Otherwise continue as normal, as we are already only overriding things when the config name is in the array of the plugin extending.

## Issue tracker
https://www.drupal.org/project/social/issues/3346966

## How to test
- [x] Reinstall (without social_content_translation) on main
- [x] Put a breakpoint in ContentTranslationConfigOverrideBase
- [x] See that the settings are loaded over and over again 
- [x] Checkout this branch
- [x] See that it exits early
- [x] Enable `social_content_translation`
- [x] See that the settings are cached statically, so it doesn't have to grab that every single time
- [x] See that we only override for given config as determined by the plugin extending the base class.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

## Screenshots
Here you can see on a prod environment using blackfire what difference it makes:
Screenshot 2023-03-10 at 14 12 29

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
TBD

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by Kingdutch** [comment]
@ronaldtebrake I have an alternative proposal implementation:

If we tag all our content translation config overrides with a unique tag, then in our social_core we can filter out those override services in [a service provider's `alter` hook](https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/altering-existing-services-providing-dynamic-services). Drupal already hard caches the container, so then we can avoid the if-statement altogether.

We can take that a step further by tagging our content translation overrides with the entities they affect so we can then look at the settings of the module to only enable those overrides that the user has enabled. This also prevents of from needing to load settings at all since we've seen previously that loading settings in a config override can cause its own set of problems.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by ronaldtebrake** [comment]
Thanks @Kingdutch I'll create a separate story for that connected to this issue; I think in it's current shape it's already creating a great impact and we would like to get the benefits of that reward asap.

Do agree the approach of moving it higher up the ladder in a services provider alter hook is even more favorable.

**Review by zanvidmar — APPROVED** [review]
Tested with config based approach; test a scenario on comparing configuration on main and on PR branch via `drush cget social_content_translation.settings --include-overridden`

Also did functional testing and I can confirm that for example events can be translated as before.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3335-fnlprh9x8ipbve76oiirmumpbxmgdcvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b214f9a0990c2c09d7b20

**Pull request merged**
