### PR TITLE
Issue #3438071: Remove patch with update to Drupal 10.2.5

### PR DESCRIPTION
**Pull request by VBaldych**
## Problem
Patch for issue https://www.drupal.org/project/drupal/issues/1149078 couldn't be applied after update to Drupal Core 10.2.5

## Solution
- Remove patch for 1149078 since the fix is already added to 10.2.5 immediately since it's a blocker for merging other PR's
- Change the required Drupal version to ~10.2.5

## Issue tracker
- https://www.drupal.org/project/social/issues/3438071
- https://getopensocial.atlassian.net/browse/PROD-28717

## Theme issue tracker
n/a

## How to test
- [ ] Install distro with Drupal 10.2.5 or update Drupal to 10.2.5
- [ ] You shouldn't see any fails on applying patches

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3844-afgsro5g9lvdvzyco062ta1pj8vihltd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e6c2baa2dcd62df1da180

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3844-afgsro5g9lvdvzyco062ta1pj8vihltd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e6c2baa2dcd62df1da180

**Review by bramtenhove — APPROVED** [review]

**Review by vcsvinicius — APPROVED** [review]
I approved

**Comment by vcsvinicius** [comment]
I cherry-picked to 12.3.x and 12.4.x

**Pull request merged**
