### PR TITLE
Issue 3139151 by tBKoT: Fix AcitivityFactory service usage

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
When I worked on the anonymous comments for discussion I can not get the correct related entity of my comment for activity. The method `getActivityRelatedEntity` of the `ActtivityFactory` service has a specific condition to check the comment's message template. Overriding of service didn't have an effect because this method is used statically without dependency injections.

## Solution
Change static usage of `getActivityRelatedEntity` to dependency injection

## Issue tracker
https://www.drupal.org/project/social/issues/3139151
https://getopensocial.atlassian.net/browse/YANG-3762

## How to test
N/A

## Screenshots
N/A

## Release notes
N/A

## Translations
N/A

##

##

### CODE REVIEW

**Comment by ribel** [comment]
@dmytriikaiun please update this PR, merge 10.0.x here and fix behat tests.

**Comment by ribel** [comment]
@dmytriikaiun All looks good to me, just please update PR template and don't forget to mention that we introduce new alter hook now.

 @ronaldtebrake could you check it and tell if you a fine to have this merged? This alter hook is needed for Anonymous comments feature in Social Discussion module, see implementation here: https://bitbucket.org/goalgorilla/social_discussion/pull-requests/57

**Comment by ronaldtebrake** [comment]
@ribel I'd be happy to see this get merged, good idea :)

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 9.x

**Pull request merged**
