### PR TITLE
Issue #3248897 by agami4: Improve alignment comment block on the album popup for RTL layout

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The comment block does not have a correct alignment on the album popup if we use RTL

## Solution
Add correct alignment to the comment block on the album popup if we use RTL

## Issue tracker
https://www.drupal.org/project/social/issues/3248897
https://getopensocial.atlassian.net/browse/YANG-6617

## How to test
*For example*
- [ ] Enable Arabic language or change the `dir` attribute from LTR to RTL in the HTML tag.
- [ ] Go to the use page
- [ ] Go to/Create an album and add album post
- [ ] Click on the image
- [ ] You can see album popup

## Screenshots
before:
image-2021-11-09-17-14-48-960

after:
Screenshot 2021-11-11 at 14 29 39

## Release notes
The comment block has a correct alignment on the album popup on the RTL mode.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2600-wf6opv4eq8t7i5pntcvdhnbkumjhqfks.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618d0d24908ae100a257996d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2600-wf6opv4eq8t7i5pntcvdhnbkumjhqfks.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618d0d24908ae100a257996d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2600-wf6opv4eq8t7i5pntcvdhnbkumjhqfks.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618d0d24908ae100a257996d

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 10.3.x

**Pull request merged**
