### PR TITLE
YANG-1860: Update styles for marker clusters

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The marker clusters have new styles

## Solution
Update styles of marker clusters

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-1860

## How to test
- [ ] Enable social_geolocation module and add a map to all event page

## Screenshots
- Before: Screenshot at Jan 31 16-59-12
- After: Screenshot at Jan 31 16-43-33

## Release notes
<describe the release notes>

## Change Record
If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.

### CODE REVIEW

**Comment by Kingdutch** [comment]
Hey @agami4 ,

Could you include a screenshot of the before and after here? That makes it easier to see what has changed :D

**Comment by Kingdutch** [comment]
Hey @agami4 ,

Did you test changing the color configuration on a platform when making this? It looks like the problem in this issue is not "The markers have a new style" but that they don't follow the platform styling. That's why it's being added to the brand.scss file.

However, the `color` module replacement only works on hexadecimal values. So this breaks when you add the opacity using the `rgba` function.

**Comment by agami4** [comment]
Hey @Kingdutch, thank you for your testing. When I worked on this issue, background-color woks well. I have some questions:

1. Should add those updates to the `SocialBlue` theme or `socila_geolocation` module?
2. If I add those updates, can I add the general template for the geolocation map and add the library with those styles? or add this library in the `social_geolocation.module` file?

**Comment by agami4** [comment]
@Kingdutch, I've updated this PR and added some updates to this PR https://github.com/goalgorilla/social_geolocation/pull/7. :)

**Comment by ribel** [comment]
Merged and cherry-picked to 8.x and 7.x.

**Pull request merged**
