### PR TITLE
PROD-29890: Update Github workflows to use the new Docker image with `rdkafka`

### PR DESCRIPTION
**Pull request by tregismoreira**
## Description
Now that we have new Docker images with `rdkafka` extension (https://github.com/goalgorilla/open_social_docker/pull/39), we want all of our workflows to use it.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-29890

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3938-julwju7jj1tocp8nymkkamhrabwoyd0n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6671dd49bc7eaf1d398d8f14

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3938-julwju7jj1tocp8nymkkamhrabwoyd0n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6671dd49bc7eaf1d398d8f14

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3938-julwju7jj1tocp8nymkkamhrabwoyd0n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6671dd49bc7eaf1d398d8f14

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3938-julwju7jj1tocp8nymkkamhrabwoyd0n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6671dd49bc7eaf1d398d8f14

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3938-julwju7jj1tocp8nymkkamhrabwoyd0n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6671dd49bc7eaf1d398d8f14

**Review by ribel — APPROVED** [review]
Based on comments in https://github.com/goalgorilla/open_social_docker/pull/39 and fact that all checks passed it looks good to me.

See also: https://github.com/goalgorilla/drupal_social/pull/395

**Review by bramtenhove — APPROVED** [review]

**Pull request merged**
