### PR TITLE
Issue #3332354: Move "Allow members to follow me" setting from profile to user entity

### PR DESCRIPTION
**Pull request by Kingdutch**
<h3 id="summary-problem-motivation">Problem/Motivation</h3>
The profile entity should be used for fields that provide information about the user visible to other users. Meanwhile settings for the user themselves should be stored on the user entity.

In the profile refactoring of [#3230125] this distinction becomes more strictly enforced because by default profile fields will show up for site managers and users for management of visibility.

It doesn't make sense to manage the visibility of the field "Allow members to follow me" since it's a settings field and not something to be shown on the profile.

<h3 id="summary-proposed-resolution">Proposed resolution</h3>
The value of the field should not be updated programmatically but is managed by the experimental <code>social_follow_user</code> module. Similarly the <code>SocialFollowUserHelper</code> service should be used to read the current setting for a user.

These two things combined means we can transfer the create a field with storage on the <code>user</code> entity with the same settings as the currently existing field on the <code>profile</code> entity. After migrating existing user preferences from the profile to the user we can then delete the field on the profile. The code in the <code>social_follow_user</code> module is adjusted to read and store the value from the new field, calling could should not have to make any changes when correctly using <code>SocialFollowUserHelper</code>.

## Issue tracker
https://www.drupal.org/project/social/issues/3332354

## How to test
- [ ] Covered by `follow-users/follow-users.feature`
- [ ] Covered by `follow-users/move-to-user-entity.feature`

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

This introduces a `Privacy` field group in `social_user` that is then used by the `social_follow_user` module to add its field. We can not re-use the existing `Privacy settings` field because it's not a true field group field but is instead inserted by one of the `social_profile` modules using a form alter.

This creates some duplication until 12.0.0 when this will be fixed by the profile refactor which will move the profile fields to a dedicated `Profile` subsection. 

## Release notes
Changed how the user's follow user preference is stored: the field "field_profile_allow_following" on the profile entity is deleted and replaced by the field "field_allow_following" on the user entity, data has been migrated.

## Change Record
None, not a change to a public API.

## Translations
The string "Privacy" should be extracted as a field group label when this PR is merged.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3280-rzypcdcr7arkdoaxb0uu4mruyinelguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bd8df4e6bc62df9ceb7bf1

**Review by tbsiqueira — APPROVED** [review]

**Comment by Kingdutch** [comment]
@tbsiqueira Cherry-picked into 46d944c63 but had to omit tests because `DatabaseContext` does not exist on `11.7.x`

**Pull request merged**
