### PR TITLE
PROD-30684: Reorganize the Social EDA modules to make all components compatible with Distro

### PR DESCRIPTION
**Pull request by tregismoreira**
## Problem
While working on [PROD-30133](https://getopensocial.atlassian.net/browse/PROD-30133): Implement test coverage for "event create" story we came across the following issue: The event-related components are in `open_social`, but their dependencies (e.g. data types) are in `cablecar`. It made it impossible to successfully run the tests in the Distro, and would possibly bring new issues in the future.

## Solution
To address this issue, we decided to:
- Move `social_eda` module into `open_social`
- Keep `social_eda_dispatcher` in `cablecar` as a stand-alone module

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-30684

## Theme issue tracker
N/A

## How to test
N/A

## Screenshots
N/A

## Release notes
Internal.

## Change Record
N/A

## Translations
N/A

[PROD-30133]: https://getopensocial.atlassian.net/browse/PROD-30133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4083-yn3flqqu9y4pwvmn8bct1izipuy6choy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb2b97a170e9e830fcf95a

**Review by ribel — APPROVED** [review]
Changes look good to me, also I can [see](https://github.com/goalgorilla/open_social/actions/runs/10961309342/job/30438229970?pr=4083) that new test added in https://github.com/goalgorilla/open_social/pull/4045 was run successfully.

**Pull request merged**
