### PR TITLE
PROD-30481: Add patch to metatag to fix non-execution of the batch for single entity deletion

### PR DESCRIPTION
**Pull request by denis-getopensocial**
## Problem

Metatag branch 2.x introduced `$renderer->executeInRenderContext()` which breaks the standard propagation and avoid the batch to run when we try to delete a single post.

## Solution

Patching metatag to process a standard rendering/propagation if a batch is set.
https://www.drupal.org/project/metatag/issues/3476944

## Issue tracker

https://getopensocial.atlassian.net/browse/PROD-30481

## How to test

- Create a post from a group
- Delete that post - you will see the batch page
- Go to home page -> the post is deleted.

## Release notes

Fix a bug introduced by metatag 2.x thats prevent batch to run on hook_entity_delete

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4093-0yvetncegmbagnkn5mgqgfvhp5oe93aw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f531686f1e8632c5dab83e

**Review by robertragas — APPROVED** [review]

**Pull request merged**
