### PR TITLE
Issue #3373172 by tbsiqueira: Update our tugboat docker image with one supporting PHP 8.1

### PR DESCRIPTION
**Pull request by tbsiqueira**
## :rocket: :fire: Related PRs :fire: :rocket:

This is a PR from a series of 4 PRs that should be merged in the following order: 

1. https://github.com/goalgorilla/open_social_dev/pull/70 
2. https://github.com/goalgorilla/open_social/pull/3460 ( this PR )
3. https://github.com/goalgorilla/open_social/pull/3457
4. https://github.com/goalgorilla/drupal_social/pull/392 ( this is just a private repository that we use for development, this will not be available for public users )

They are ALL BC and should not cause any breaking change for our local development 

## Problem
Since we are moving to PHP 8.1, we should update our tugboat docker image

## Solution
Use the new available image from here https://github.com/goalgorilla/ci_images/pkgs/container/ci-tugboat-php

## Issue tracker
https://www.drupal.org/project/social/issues/3373172

## Theme issue tracker
N/A

## How to test
- [ ] Open Social is running on tugboat and PHP 8.1

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3460-f4fvs0mjesspdbjme7ydsl8wjaaffwaf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64a7f7bddc23a4c553978c7f

**Review by zanvidmar — APPROVED** [review]
Note: check tugboat again after alpha release

**Pull request merged**
