### PR TITLE
Issue #3271644 by nkoporec: Don't allow deleting menu links that ships with Open Social

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Currently, SM/CM has the permission _Administer menus and menu links_, this means that they are able to delete any links even the one that ships with Open Social (such as /all-groups, /explore).

Since these are links that are used across Open Social distribution, we should prevent non-admin users to have the ability to delete them.

## Solution
We should only allow admins users to alter these links.

## Issue tracker
https://www.drupal.org/project/social/issues/3271644

## How to test
1. Install the distribution.
2. As SM/CM go to admin/structure/menu/manage/main
3. Delete the 'Explore' or 'All groups' menu link

### Before merge
- [x] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [x] All automated tests are green
- [x] Functional/manual tests of the acceptance criteria are approved
- [x] All acceptance criteria were met
- [x] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [x] This pull request has all required labels (team/type/priority)
- [x] This pull request has a milestone
- [x] This pull request has an assignee (if applicable)
- [x] Any front end changes are tested on all major browsers
- [x] New UI elements, or changes on UI elements are approved by the design team
- [x] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before:

After:

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by Ressinel** [comment]
@nkoporec Could you add type and priority labels to this PR, please?

**Comment by robertragas** [comment]
Merged main back in the feature because there was a fix done for travis.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2831-oasu6hbgpdi0ky2vhjrx8cclumydjfem.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62456201d128c6acc8663a55

**Review by NickDaelemans — APPROVED** [review]

**Comment by Ressinel** [comment]
🍒-picked to `11.1.x` and `11.2.x`

**Pull request merged**
