### PR TITLE
Internal: Ensure there are no install errors

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution
Drush doesn't actually exit if there's an error during installation which is really annoying. We found out because our CI was passing even though the installer threw errors.

To fix this we apply a similar fix which we previously applied in the update steps which captures and checks the output text to check if there's any errors.

## Issue tracker
Internal CI fix no change

## How to test
- [ ] Our CI is currently failing and thus behat.yml should fail. 
- [ ] Fixes are made in separate PRs against this branch.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Comment by robertragas** [comment]
With add the merged changed from the sub PRs this one should go green now before we can merge it.

**Review by robertragas — APPROVED** [review]
green!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3778-otfv4hbvrfvqiksmjh6nlfg0l0invfnw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d1ff079c487cae277560f3

**Pull request merged**
