### PR TITLE
Issue #3408235 by nkoporec: Fix behat CKEditor context for writing inside the editor

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
In some cases the context for @When /^I fill in the "([^"]*)" WYSIWYG editor with "([^"]*)"$/ is not working correctly, especially when the form is loaded via AJAX or nested (like in IEF module). In that case the div gets appended a unique identifier so when the JS script gets evaluated in cannot find the CKEditor instance.

## Solution
Fix the context so that it works in all cases.

## Issue tracker
https://www.drupal.org/project/social/issues/3408235

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Write a test that uses the above context and wants to write to CKEditor 5 instance that is rendered via IEF module.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3641-ysxownmo12zd4i0ypzfh7frwxns7nkdp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6578862aecba8e86978f4ae2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3641-ysxownmo12zd4i0ypzfh7frwxns7nkdp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6578862aecba8e86978f4ae2

**Comment by ronaldtebrake** [comment]
Awesome work @nkoporec!

**Comment by ronaldtebrake** [comment]
Also cherry-picked in 12.0.x so it will land in 12.0.1

**Pull request merged**
