### PR TITLE
Issue #3390638: Update the copy of the Data Policy module

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
A new version of the Data Policy module was released.

## Solution
Update to the latest Data Policy module 2.0.0-beta8.

## Issue tracker
- https://www.drupal.org/project/social/issues/3390638
- https://getopensocial.atlassian.net/browse/PROD-26831
- - https://www.drupal.org/project/data_policy/releases/2.0.0-beta7
- https://getopensocial.atlassian.net/browse/PROD-26275
- - https://www.drupal.org/project/data_policy/releases/2.0.0-beta8

## Theme issue tracker
N/a

## How to test
- [ ] Automated tests pass
- [ ] Test some of the textual changes.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Instead of "**data policy**" the copy changed to "**data protection statement**". Additionally the default text "**I agree with the <data policy here>**" changed to "**I read and consent to the <data protection statement here>**".
Fixed error with the Data Policy Agreement detail page if there are no data policies created.

## Change Record
N/a

## Translations
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Review by ribel — APPROVED** [review]
Hi @bramtenhove,
I've tested changes locally on the existing project and all looks good to me.
image

Maybe @BiaInacio can check it once more on clean installation on Tugboat env?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3542-7gaa2ogqgnk34qgr6qsir4colycznhiv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6516bb61bd668bc63def58de

**Comment by ronaldtebrake** [comment]
Ah oopsie, I didn't notice your message and it was still in main when we branched off 11.11.x, so that means its likely in that release now. Would that be a big problem @ribel ? I think considering its a new minor feature we can still clearly explain the couple of textual changes. Also the data policy will be part of 11.11.x.

**Pull request merged**
