### PR TITLE
Hotfix: Decode filepath for cached secret file requests

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
Path processors don't run on cached route matches and attributes aren't part of the cached value. This means that our `filepath` attribute isn't available for second requests to our secret file path controller. 

We fixed this issue by reprocessing the URL. However, contrary to the URL in our path processor, the value for our controller on a cached route match has no preprocessing done on it since `PathProcessorDecode` hasn't run in that case.

This means that for image with a space in their name we were unable to find the file on disk and unable to locate the source file since we were looking for files with `%20` in their name. 

See https://www.drupal.org/project/drupal/issues/3085360#comment-15614838 for the full story.

## Solution
We decode the `$target` which should ensure that we start looking for the correct file name on disk.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Review by ronaldtebrake — APPROVED** [review]
Can confirm this fixed it 👍

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3911-89rfqwuwzpgjwivos808rfm5yequl7d1.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66562da4e19edc56662bf62c

**Pull request merged**
