### PR TITLE
Issue #3431340: Apply patch to fix SocialBlue theme bug

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The custom color isn't be applied to logged user on Search page, a patch with fix was created at [#3427426](https://www.drupal.org/project/socialblue/issues/3427426)

## Solution
Apply patch to fix SocialBlue theme bug

## Issue tracker
[PROD-28354](https://getopensocial.atlassian.net/browse/PROD-28354)
[#3431340](https://www.drupal.org/project/social/issues/3431340)

## Theme issue tracker
[#3427426](https://www.drupal.org/project/socialblue/issues/3427426)

## How to test
- [ ] Disable cache for CSS file;
- [ ] Change default color on Social Blue settings;
- [ ] Access the Search Page with Logged and Anonymous User

**This errors isn't happen to all installation.**

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
The bug about custom-color on Search Page will be fixed.

## Change Record
N/A

## Translations
N/A

[PROD-28354]: https://getopensocial.atlassian.net/browse/PROD-28354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3822-96d4rwedi749gq5o9jettwt0rfknuz3j.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f855a7c426b4c60b270a91

**Comment by BiaInacio** [comment]
Site color is changed even when the CSS cache is disabled!
image

image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3822-96d4rwedi749gq5o9jettwt0rfknuz3j.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f855a7c426b4c60b270a91

**Review by ribel — APPROVED** [review]
Hi @ronaldtebrake,
I see [theme PR](https://git.drupalcode.org/project/socialblue/-/merge_requests/133/diffs#note_283430) was approved by @agami4, so I assume it's good enough to be merged?

**Pull request merged**
