### PR TITLE
Issue #3473010: Add throbber back to event enrollment.

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
https://www.drupal.org/project/socialblue/issues/3472973

We have added a throbber in the socialblue theme that is causing issue when a button is just disabled without needing to progress it to another state.

## Solution
- Remove the throbber and replace it in the Distro with a progress throbber.

## Issue tracker
https://www.drupal.org/project/social/issues/3473010

## Theme issue tracker
https://www.drupal.org/project/socialblue/issues/3472973

## How to test
As it's theoretically you need to also alter some code in inspector.
- [ ] Create a new event
- [ ] Go to the event and add "disabled" to the enroll button
- [ ] Notice the throbber will show while it should not

## Release notes
We replaced the event enrollment throbber with a default one from Drupal. This should result in no visual change.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by BiaInacio** [comment]
Disable style looks fine!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Review by vcsvinicius — APPROVED** [review]
I approved

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4066-fwiesrnlys9qe2mapghhubberxlxarh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ded3ec8f47bfb2d0f92abb

**Pull request merged**
