### PR TITLE
Issue #3184207 by tBKoT: Update morris.js library from version 0.5 to 0.6

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
6 years was passed since the last release of the morris library so I suggest using another version on this library. Also, it needs to provide a new horizontal bar chart for KPI (screenshot).

## Solution
Use the new library https://www.npmjs.com/package/morris.js06

## Issue tracker
https://www.drupal.org/project/social/issues/3184207
https://getopensocial.atlassian.net/browse/YANG-3983

## How to test
N/A

## Screenshots
image

## Release notes
A new version of Morris library.

## Change Record
The process of using morris is not changed. The new library support all features from old, just add something new.

## Translations
N/A

### CODE REVIEW

**Comment by robertragas** [comment]
Just to note, this worked for Nacho. He tried to get OS running locally, had problems with Morris and said to try out this PR.

I don't know if the kpi analytics are still functionally working, didn't test that.

**Comment by dmytriikaiun** [comment]
> Just to note, this worked for Nacho. He tried to get OS running locally, had problems with Morris and said to try out this PR.
> 
> I don't know if the kpi analytics are still functionally working, didn't test that.

@robertragas It's working. This is the same Morris library but with some new features. I've used it to implement horizontal bars.

**Review by ribel — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
I'm happy to get it in in that case seeing all the input from everybody :)

**Comment by ribel** [comment]
@ronaldtebrake great! 
Just wondering if it is fine to include this in 9.5 milestone, or should it be different?

**Comment by ronaldtebrake** [comment]
Good question @ribel 
In this case considering the amount of features come with this increase in versioning i'd say 9.5 is the correct milestone.

**Comment by ribel** [comment]
🍒 picked to 9.x

**Pull request merged**
