### PR TITLE
Issue #3423273: Past events isn't be showing at Community Events page

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
Events that started and ended in the same day are not displayed in community events page

## Solution
The custom-filter view isn't built correctly, fix it to return past events.

## Issue tracker
[PROD-28258](https://getopensocial.atlassian.net/browse/PROD-28258)
[#3423273](https://www.drupal.org/project/social/issues/3423273)

## Theme issue tracker
N/A

## How to test
- [ ] Create an event that started and ended today
- [ ] Use 01:00 AM as start time and 02:00 AM as end time
- [ ] Go to /community-events
- [ ] Filter the page to show past events
- [ ] You’d expect this to be a past event

**I advice to create a couple of past events with different dates and using all day as well and check Community Events page.**

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
We fixed an issue where the past events would not show up in the event overview if the end and start date would be the previous day in combination with different timezones.

## Change Record
N/A

## Translations
N/A

[PROD-28258]: https://getopensocial.atlassian.net/browse/PROD-28258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by ronaldtebrake** [comment]
Lets make sure we add test coverage for this scenario 🙏

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Review by robertragas — APPROVED** [review]

**Comment by BiaInacio** [comment]
Test done, events that started and ended today are being displayed as past events!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3792-b5qiz0mekvuwwut4emtbmuduotl6grcz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d78f403a26bc1dcebdd847

**Pull request merged**
