### PR TITLE
Issue 3035308 by jcmartinez: Fix fatal error when editing custom content

### PR DESCRIPTION
**Pull request by jcmartinez**
Fix fatal error when editing content with a custom content type

## Problem

Using the "Social Flexible Group" and I've created a new content type for which I have activated the group content plugin in the group types.

When I edit a node of my new content type, I get the fatal error:

```
The website encountered an unexpected error. Please try again later.
TypeError: Argument 4 passed to Drupal\social_group\SetGroupsForNodeService::setGroupsForNode() must be of the type array, null given, called in /app/html/profiles/contrib/social/modules/social_features/social_group/social_group.module on line 1542 in Drupal\social_group\SetGroupsForNodeService->setGroupsForNode() (line 52 of profiles/contrib/social/modules/social_features/social_group/src/SetGroupsForNodeService.php).
```

## Solution
I have added a line of code to evaluate whether the value exists before it's used.

## Issue tracker
https://www.drupal.org/project/social/issues/3035308

## How to test
- Enable the "Social Flexible Group" module
- Add a new content type
- Activate the content type for this group
- Create a new node for the new content type
- Edit the node

Without this fix, there will be a fatal error. With this fix there won't be a fatal error. 

## Release notes
Fix a fatal error when editing a node from a custom content type that is attached to a group.

## Change Record
N/A

### CODE REVIEW

**Comment by Kingdutch** [comment]
It looks like you accidentally indented the entire function with a space. This breaks all the coding standards checks and makes it more difficult to review your patch.

If you can make sure the indenting is correct so that the diff only shows your change then we can easily review it :)

**Comment by jcmartinez** [comment]
Hi Kingdutch, I created another PR https://github.com/goalgorilla/open_social/pull/1726 but it fails. Not sure wether the test needs to be updated or my code is wrong.

**Comment by Kingdutch** [comment]
Hi @jcmartinez ,

The code in this PR failed on coding standards. The other PR you created failed due to the security-advisory package and the security release for the Profile module yesterday. That should resolve itself later today.

I'll close the other PR and we can work on fixing this one here.

~ Alexander

**Comment by ronaldtebrake** [comment]
Due to inactivity i have rebased this in #1816 ensuring tests will pass now.. will close this one, use the other one and review merge once it's done. Thanks for the contribution! :)

**Pull request closed without merging**
