### PR TITLE
Issue #3439974: Activity creator breaking down when the referenced entity does not exist

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
Open Social uses so called "activities" when creating content. For example when creating a topic it will also create an activity to show this on the activity stream.

These activities have referenced objects, but in some cases it can be that a user create a topic, but later on deleted it again. Depending on the run-time of the cron it can happen that there is still a queue item, but not reference item anymore. The cron will then fail as it cannot retrieve this piece of content.
Screenshot 2024-04-10 at 15 14 23

## Solution
Add some defensive checks to make sure the related object exist before creating the activity

## Issue tracker
https://www.drupal.org/project/social/issues/3439974

## How to test
- [ ] Create a topic
- [ ] See with drush queue-list there is a activity_logger_message item waiting to be processed.
- [ ] Run drush queue-run activity_logger_message and see it creates an item for activity_creator_logger
- [ ] Delete the topic and run drush core-cron
- [ ] Depending on what kind of content you create, the cron can either get stuck, or the activity is
- [ ] Checkout to this branch and try the flow again, or just run the cron again if the queue item is still there.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Internal: We have added extra validation in the activity creator to make sure referenced entities exist before processing them, avoiding crashes with the cron, or empty activities.

### CODE REVIEW

**Review by vcsvinicius — APPROVED** [review]
I approved

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by BiaInacio** [comment]
Test done, created and delete a file and the Cron run with no fails!
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3856-ri0gem1vmhiskqfexow32gtu0jzlskiu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66169f4538470ec560534f20

**Comment by ronaldtebrake** [comment]
Considering all the approvals and tests I'll merge and backport this to make sure it ends up in the Distro release

**Comment by ronaldtebrake** [comment]
Cherry pick to 12.3.x and 12.4.x

**Pull request merged**
