### PR TITLE
Issue #3393846: Update `drupal/profile` requirement from 1.4.0 to 1.7.0

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
Even though it's declared to be D10 compatible in the latest releases there are some fixes so we want to upgrade already.
but it is also required for the profile refactor in #3480

## Solution
We decided to cherry-pick the commit already for our 11.11.x branches coming from the profile refactor.
https://github.com/goalgorilla/open_social/pull/3480/commits/57842329d8a3727df6bab0b059dec272f4dd32a2

Additionally patches were needed for regression:
https://github.com/goalgorilla/open_social/pull/3480/commits/0865f7a71482b548c52424d12232254bf5601738

Update includes:

https://www.drupal.org/project/profile/releases/8.x-1.5
https://www.drupal.org/project/profile/releases/8.x-1.6
https://www.drupal.org/project/profile/releases/8.x-1.7

## Issue tracker
https://www.drupal.org/project/social/issues/3393846
https://getopensocial.atlassian.net/browse/PROD-26049

## How to test
- [ ] Test profile functionality

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Update the Profile module from 1.4.0 to 1.7.0

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by BiaInacio** [comment]
Profile fields and display is working as expected! 😄 
image

**Review by vcsvinicius — APPROVED** [review]
I approved this PR

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3556-fisbvfr3mb1axk2enuiatqrzt1sxyflo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6528f6cef19c2a14e38f68a8

**Comment by ronaldtebrake** [comment]
Cherry picked to 11.11.x and 12.0.x 🍒

**Pull request merged**
