### PR TITLE
Issue #3427372 by SV: Add flexible_permissions module

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

For the group upgrade, there is a new [dependency](https://www.drupal.org/node/3281065), and in the [release notes](https://www.drupal.org/project/group/releases/2.0.0) we have the following note:
> flexible_permissions module should be enabled before group upgrade

## Solution

Add and enable **flexible_permissions** module as a dependency of **social_group**.

## Issue tracker

- https://www.drupal.org/project/social/issues/3427372
- https://getopensocial.atlassian.net/browse/PROD-26913
- https://www.drupal.org/node/3281065

## Theme issue tracker

N/A

## How to test
This module provides only helper services, so passing automated tests and checks should be enough. 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes

Add a new flexible_permissions module that will be required for the upcoming group upgrade to version 2.

## Change Record

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3811-jvkgtroumijezv6vxonexbyel2dybdvs.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f071eff38372342bd0b71b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3811-jvkgtroumijezv6vxonexbyel2dybdvs.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f071eff38372342bd0b71b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3811-jvkgtroumijezv6vxonexbyel2dybdvs.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f071eff38372342bd0b71b

**Review by ribel — APPROVED** [review]
Changes looks good to me and all works without regressions.

**Comment by ribel** [comment]
🍒 picked to the 12.3.x

**Pull request merged**
