### PR TITLE
Internal: Move template explanations into HTML comments

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
The PR template requires a lot of removal when trying to fill it in.

## Solution
Move template explanations into HTML comments

This allows them to be more easily ignored and allows someone to just start writing in the template rather than having to replace or remove text.

## Issue tracker
Internal no issue

## How to test
- [ ] We merge it
- [ ] We create a new PR
- [ ] ???
- [ ] Profit

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3406-ujc4zz1fr37las72pgj4ndmtecriniqj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646caff3d58e09b19c832886

**Review by tbsiqueira — APPROVED** [review]

**Pull request merged**
