### PR TITLE
Issue #3015568 by serhiy-chornobay, ribel: As a LU I want the teasers to look complete even if no image is uploaded

### PR DESCRIPTION
**Pull request by ribel**
## Problem
If no image is uploaded now we see just empty grey area with a small icon in a corner.

## Solution
If no image is uploaded the icon should be shown in the image field of the teaser.
See screenshots on drupal.org

## Issue tracker
- https://www.drupal.org/project/social/issues/3015568
- https://jira.goalgorilla.com/browse/FOR-181

## HTT
- [ ] Check out the code changes
- [ ] Check teasers and featured topics and events with images and no images
- [ ] Teasers without images should look better than before :)

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by jaapjan** [comment]
@ribel I think because the base branch is changed afterwards Moss can't really build this correctly. Perhaps a new PR will produce better results?

**Comment by ribel** [comment]
@jaapjan, ok, I can do it. But since it was added to 3.7 release what should be the base branch? 3.x or 4.x?

**Comment by jaapjan** [comment]
@ribel you changed the base branch to 4.x so I think that might be best? unless @ronaldtebrake thinks otherwise.

**Comment by jaapjan** [comment]
@ribel which PR should we now use? https://github.com/goalgorilla/open_social/pull/1136 this one?

**Comment by ribel** [comment]
@jaapjan Probably new one - #1136.
I am closing this.

**Pull request closed without merging**
