### PR TITLE
Issue #3247898 by rolki: Alternative frontpage not multilingual and do not support custom roles

### PR DESCRIPTION
**Pull request by rollki**
## Note:
This PR combines two other PRs, and those PRs is deprecated now. We are decided to created another PR that will combine changes to have proper history.

## Problem
There are two problems:
- Alternative frontpage is not multilangual (see https://github.com/goalgorilla/open_social/pull/1718)
- Currently we have the possibility to configure an homepage for AN users and one for LU users. As part of this story we want to extend this feature and allow SM to configure different homepages per role (see https://github.com/goalgorilla/open_social/pull/2564)

## Solution
- Create a translatable config entity
- Remove hardcode and extend functionality to other roles.

## Issue tracker
- https://www.drupal.org/project/social/issues/3247898
- https://getopensocial.atlassian.net/browse/YANG-6192

## How to test

*Translatable config entity*
- [x] drush cr
- [x] drush updb
- [x] enable a second language and make sure the language switcher is on
- [x] go to the alternative frontpage settings and insert the path to a node for anonymous and authenticated
- [x] Translate them, and let them go to another node page
- [x] Now test them as anonymous and logged in, and use the language switcher.

*Custom roles*
- [x]  Enable the `alternative_frontpage` module
- [x]  Go to the settings `/admin/config/alternative_frontpage`
- [x]  Set some custom path for some role (create a new entity - click on the `+Add Frontpage Settings`)
- [x]  Go to the home page under that role

## Screenshots
image
image

## Release notes
- It's possible to use configuration entity for each role instead of using normal configuration and it means that now we support multilingual.
- It's possible to configure front page for each role.

## Change Record
- We are support multilingual
- Configuration structure changed from one page configuration, to configuration entity with list of entities and ability to add a new entity for role where you will be able to select the role and set the path to Front Page.

## Translations
No.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by rollki** [comment]
If you wanna know more details, please follow PR's that we are combined via this PR (#2564 & #1718).

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by Ressinel** [comment]
Hi @rollki 

Nice improvements🚀
All work as expected but I noticed one thing (not sure that it is a bug).

I have created two Alternative Frontpages:
- For Anonymous user
- For Authenticated user

For all roles, alternative frontpages load properly except the Administrator role. When I logged in as an Administrator I see the front page for Anonymous users.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by rollki** [comment]
@Ressinel @ribel 
I have fixed all issues, please check it out :) 
We still have one failed test but seems it's not related to this changes, I saw that test failed in a lot of PR's, so I'll re-run it but we can ignore it during review.

**Review by ribel — APPROVED** [review]
Changes were tested and look good to me.

**Comment by Ressinel** [comment]
@rollki Rebase the PR branch, please.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by Ressinel** [comment]
@rollki Fix **PHPStan** errors, please.

**Review by Ressinel — APPROVED** [review]
@rollki Improvements look good to me. Just need to ensure that all checks are green.

**Comment by rollki** [comment]
Hi @tbsiqueira 
I see that you reassigned this PR, so I wanna clarify if you manna add something or improve?

**Comment by navneet0693** [comment]
@rollki For fixing PHPStan errors in this branch (please don't merge 'main' back), you have re-generate phpstan-baseline.

The following command will help you:

`../../../../vendor/bin/phpstan analyse -c phpstan.neon --generate-baseline=phpstan-baseline.neon`

The above command assumes that you are running it from "social" folder.

**Comment by navneet0693** [comment]
@rollki Please merge 'main' once https://github.com/goalgorilla/open_social/pull/2702 is merged, or I will update the PR.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2590-ukucunydt1v400idb3y8j0cuhv2b6doc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854729908ae16a7753158e

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
@navneet0693, @tbsiqueira @rollki can we merge this PR now?

**Comment by navneet0693** [comment]
@ribel Yes, just one more test to go 💪🏾

**Pull request merged**
