### PR TITLE
Issue #3276049 by tBKoT: Disallow AN users inviting to the event

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
In Open Social 11 was released a new feature that allows users to invite other users to the event or share it. However, if an anonymous user will enroll in the event all other anonymous users will automatically be able to invite. 

## Solution
Disable access for the AN users to the event invite route

## Issue tracker
- https://www.drupal.org/project/social/issues/3276049
- https://getopensocial.atlassian.net/browse/YANG-7623

## Theme issue tracker
N/A

## How to test
- [x] Using version 11.1+ of Open Social with the `social_event_an_enroll` and `social_event_invite` modules enabled
- [x] As SM got to the `Event invite settings` (`admin/config/opensocial/event-invite`)
- [x] Enable the `Event managers are able to allow users send invites`
- [x] As a CM+
- [x] Create a public event with `Allow users to share the event with others` enabled
- [x] Allow enrollment for AN users
- [ ] As AN user enroll in this event
- [ ] As AN user you are able to invite other users o this event

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Anonymous users should not have the possibility to invite other users to the event.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Review by Ressinel — APPROVED** [review]

**Comment by Ressinel** [comment]
Hi @dmytriikaiun 

Since this https://github.com/goalgorilla/open_social/pull/2525 was added to `11.1.0` I have changed the milestone for this PR to `11.1.4`.

**Comment by Ressinel** [comment]
Hi @ribel Yes=)

**Comment by dmytriikaiun** [comment]
@rollki this PR is ready to be merged

**Comment by Ressinel** [comment]
🍒-picked to `11.1.x`, `11.2.x`, and `11.3.x`

**Pull request merged**
