### PR TITLE
Issue #3212188 by agami4: Improve logos on the gin toolbar

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The admin pages do not have the correct favicon.
Should change logos on the top/bottom of the gin toolbar.

## Solution
Improve favicon on the gin theme settings.
Improve logos on the top/bottom of the gin toolbar.

## Issue tracker
https://getopensocial.atlassian.net/browse/DS-7597
https://www.drupal.org/project/social/issues/3213188

## How to test
- [ ] Logged like SM and go to the admin page.
- [ ] Check the favicon and logo on the top of the gin toolbar.

## Screenshots
before:
image (3)
Structure | ECI Demo 2021-05-10 17-54-54

after:
Site Admin  ECI Demo 2021-05-12 15-58-30

## Release notes
The admin pages have an Open Social favicon.
The logos were changes on the top/bottom of the gin toolbar

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
I've cherry-picked the gin settings update to 10.1.x as well

**Comment by ronaldtebrake** [comment]
The milestone is kept to 10.2.0 because these CSS fixes only apply to Gin toolbar beta 15.

**Comment by ronaldtebrake** [comment]
I'll add a new bug to the socialbase theme to ensure we fix the alignment with both menu's.
Screenshot 2021-05-14 at 10 19 53

**Comment by ronaldtebrake** [comment]
https://www.drupal.org/project/socialbase/issues/3213976#comment-14102933

**Comment by agami4** [comment]
@ronaldtebrake, I have another issue with this bug and I've fixed, but not merge it yet, because I have some issues after update the profile and gin theme/toolbar
https://getopensocial.atlassian.net/browse/YANG-5620

**Comment by ronaldtebrake** [comment]
Ah check! That's exactly what I created haha thanks @agami4 at least I've created a drupal ticket for you now :P

**Pull request merged**
