### PR TITLE
[Internal] - Fix PHPCS errors.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
New PHPStan errors appeared after `mglaman/phpstan-drupal` new release:
- https://github.com/mglaman/phpstan-drupal/releases/tag/1.1.2

## Solution
Update `phpstan-baseline.neon` or fix errors directly.

## Issue tracker
N/A

## How to test
- [ ] PHPStan should be green.

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2661-n1avnbjxdvtarimgba1j4kzhwbtxeu7j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bc76135f46ed13d81dc751

**Comment by ribel** [comment]
@Ressinel Thanks for fixing PHPStan!
But I see Behat tests are still failing on steps related to user login 🤔

**Review by tbsiqueira — CHANGES_REQUESTED** [review]
Hi Andrii, thank you for your work, but we should not add new lines unless necessary, please find below my thoughts.

**About `@internal`**

https://www.drupal.org/project/drupal/issues/3196168#comment-13985754
Comment #6 has a good argument about the usage of @internal for classes that has the comment: “Provides a generic base class for a content entity deletion form”.

That is the case of most of the new warning, but not for `Drupal\social_user\Form\SocialUserLoginForm` and `Drupal\social_user\Form\SocialUserPasswordForm`.

For those two classes we are overriding the methods, and that makes me think if that is the right way to achieve what we want. Maybe we could use events ?

We have other classes that are extending `@internal` forms, but are empty, Thinking on release cycle and possible other community installations that might override those classes, we could add the “deprecated” tag on those classes and mark them to be removed on OS 12 ( for the empty ones ) and the others we could leave add exceptions to the baseline.

For the error on “Plugin definitions cannot be altered” firing from `modules/social_features/social_post/modules/social_post_album/src/Service/SocialPostAlbumElementInfoManager.php` I believe that we should make use of the “`hook_element_plugin`” present at line 68 from the parent class.

**Comment by tbsiqueira** [comment]
As per comment, let's add this to the baseline for now, and add a ticket to investigate and fix as many baseline issues as possible.

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2661-n1avnbjxdvtarimgba1j4kzhwbtxeu7j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bc76135f46ed13d81dc751

**Pull request merged**
