### PR TITLE
Issue #3347315 by bramtenhove: Move execution of expensive invitation data to when it is needed for sending notifications 

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
We execute `$this->inviteService->getInviteData();` on every page load (also file loads from the private file system).

## Solution
Move execution inside of the existing `if` statement controlling the actual notification.

## Issue tracker
- https://www.drupal.org/project/social/issues/3347315

## Theme issue tracker
N/a

## How to test
- [ ] Prepare an invite
- [ ] Load the front page and see that you get a notification about a pending invite

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/a

## Release notes
Slightly improve performance by removing unnecessary load of pending invite data.

## Change Record
N/a

## Translations
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3336-ijhctztrc6dbf1qip4cnsysziqvwo0oy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b972cd9a0d85046c3a59c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3336-ijhctztrc6dbf1qip4cnsysziqvwo0oy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b972cd9a0d85046c3a59c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3336-ijhctztrc6dbf1qip4cnsysziqvwo0oy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b972cd9a0d85046c3a59c

**Comment by Kingdutch** [comment]
@bramtenhove There's another easy fix we can make in the `InviteService` for the routes where the `getInviteData` is actually called.

Instead of loading _all_ event enrollments on https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_core/src/InviteService.php#L84 we can make a `hasAnyInvites` which just uses an entity query to create a boolean value (`LIMIT 1`).

Instead of loading _all_ group enrollments on https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_core/src/InviteService.php#L96 we can simimlarly make a `hasAnyInvites` that has a `LIMIT 1` and returns a boolean value.

**Review by Kingdutch — APPROVED** [review]
Current change is fine, though there's room for improvement on the routes that are still affected by the `getInviteData` call which itself just loads way too much data for what it needs.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3336-ijhctztrc6dbf1qip4cnsysziqvwo0oy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b972cd9a0d85046c3a59c

**Review by zanvidmar — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3336-ijhctztrc6dbf1qip4cnsysziqvwo0oy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640b972cd9a0d85046c3a59c

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.8.x here d7095e3771333cdad9f521c267a033f3939c72fb

**Pull request merged**
