### PR TITLE
[WIP] Internal: Add a functional test to check if the Distribution can be installed through the browser

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
There have been some scenarios where the community encountered issues with installing Open Social through the browser (e.g. /core/install.php). We should be able to test that at least it is installable.

## Solution
This is my attempt to start testing this through a functional test.

## Issue tracker
It is an internal ticket. 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2970-zv3rvkdcnljosvi7wnqsan4nhkut5yan.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62977555c1600d72c5c0171b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2970-zv3rvkdcnljosvi7wnqsan4nhkut5yan.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62977555c1600d72c5c0171b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2970-zv3rvkdcnljosvi7wnqsan4nhkut5yan.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62977555c1600d72c5c0171b

**Comment by ronaldtebrake** [comment]
Closing this for now, the test will run from #2953 and don't have time to finish this anytime soon. The closed PR still remains so we can always re-verify once necessary. Especially considering we need to add some fixes in core to make our custom step testable it's not ideal.

**Pull request closed without merging**
