### PR TITLE
3254530 | Removing deprecated calls on hook_file_download()

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
There are three hook_file_download() calls that uses the deprecated `uriScheme()` and `getTarget()` function calls in the following modules/hooks:

- social_event_enrolments / social_event_enrolments_export_file_download()
- social_group_members / social_group_members_export_file_download()
- social_user_export / social_user_export_file_download()

## Solution
Change the deprecated calls from:

```
  $scheme = \Drupal::service('file_system')->uriScheme($uri);
  $target = \Drupal::service('stream_wrapper_manager')->getTarget($uri);
```

to

```
  $scheme = StreamWrapperManager::getScheme($uri);
  $target = StreamWrapperManager::getTarget($uri);
```

Recommendation:
https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/lib/Drupal/Core/File/FileSystem.php#L294

## Issue tracker
https://www.drupal.org/project/social/issues/3254530

## How to test
- [ ] Go to node/add/book
- [ ] Add a new image
- [ ] Thumbnail should be visible
- [ ] Go to admin/people
- [ ] Select all users
- [ ] At the bottom, on the bulk actions, select "Export the selected users to CSV"

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Review by navneet0693 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2654-pagxoxuz92z1xoi1elpbycuu9h5hzyiy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9eb6f7499db6522a7cd5e

**Pull request merged**
