### PR TITLE
Update README.md for 4.x with two more badges

### PR DESCRIPTION
**Pull request by truls1502**
Added Packagist version and Follow their Twitter account

### CODE REVIEW

**Comment by jaapjan** [comment]
Let's not make unneccesary changes to older 4.x :-) Focus on 6.x and 5.x instead

**Comment by truls1502** [comment]
Ok, @jaapjan! I was thinking have it in 4.x and let the people know there is a newer version than 4.x available

**Comment by jaapjan** [comment]
People won't see the 4.x readme anymore. Default branch is now 6.x

**Comment by truls1502** [comment]
Aha, okay! That makes sense. 👍

**Pull request closed without merging**
