### PR TITLE
Update PHPStan to 1.7.1

### PR DESCRIPTION
**Pull request by Kingdutch**
# Change
Includes the following relevant major releases

https://github.com/phpstan/phpstan/releases/tag/1.6.0
https://github.com/phpstan/phpstan/releases/tag/1.7.0

As well as some 1.6.x minor releases.

The baseline was manually verified. No new errors are muted but the
wording of some errors has changed. Most notably missing methods are now
reported on the interface rather than the final class. Additionally the
variables for some PHP built-ins have changed.

### 1.6.0
Article about the release here: https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

*Conditional return types* which can be used to type some of Drupal's internal methods which use `$return_as_object` or the like
*Reduced memory usage* which allowed me to drop the `--memory-limit=-1` when invoking PHPStan

### 1.7.0
Release notes: https://github.com/phpstan/phpstan/releases/tag/1.7.0

*Full static analysis* - No more fatal errors because of typoes in our code 🥳
*`@phpstan-consistent-constructor`* which provides a new way to deal with errors we had around `static()` usage in Drupal: https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static

## Issue tracker
Internal tooling change, issue omitted

## How to test
- [ ] PHPStan should pass

### Before merge
- [ ] Code/peer review is completed
- [x] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [x] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [x] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [x] This pull request has an assignee (if applicable)
- [x] Any front end changes are tested on all major browsers
- [x] New UI elements, or changes on UI elements are approved by the design team
- [x] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
[Omitted internal change]

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by navneet0693** [comment]
@Kingdutch Our PHPStan check requires more efforts to make it happy :-D https://github.com/goalgorilla/open_social/runs/6567608312?check_suite_focus=true#step:5:11

**Comment by Kingdutch** [comment]
@navneet0693 I was confused by the fact that our CI uses `/tests/composer.json` but PHPStan is also listed in `require-dev` for `/composer.json`. So the new baseline was being tried against an old version.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by Kingdutch** [comment]
This now also updates phpstan-drupal to 1.1.17 which contains some
compatibility fixes with PHPStan 1.7.0. We add existing missing entity
query access checks to our baseline because disabling the rule would
also cause new PRs to miss the check.

That was also because changes I made against #2948 were accidentally against 1.1.12 which messed up the baseline, so I figured I'd do it all.

@navneet0693 i fixed the merge conflict that was caused by merging #2944 while this was open 🙃

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2945-qfdipswjfbsvmblyjfebfsixaxhua0mt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628c7066ee0732728f517af6

**Pull request merged**
