### PR TITLE
Issue #3206166/#3206167 by agami4: Improve album popup behaviour

### PR DESCRIPTION
**Pull request by agami4**
## Problem
Drupal.behavior does not use `context`.

## Solution
Add improvements to the js code and add `context`.
Add style improvements to the post comment block inside the album popup.

## Issue tracker
https://www.drupal.org/project/social/issues/3206166
https://getopensocial.atlassian.net/browse/DS-7590

https://www.drupal.org/project/social/issues/3206167
https://getopensocial.atlassian.net/browse/DS-7591

## How to test
*For example*
- [x] Create album.
- [x] Add post with images to the album.
- [x] Check how album popup works.
- [ ] Check improvements on `social-post-album--popup-slider.js` and `social-post-album--post-loading.js` files.

## Screenshots
N/A

## Release notes
Improve album popup behavior.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2660-qylvb9xbk1feckzrsns7izlecydmkgwm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb5016dc579fc65d22a2a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2660-qylvb9xbk1feckzrsns7izlecydmkgwm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb5016dc579fc65d22a2a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2660-eitd0jhbrfklth9bof2qk324bxfq31ix.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61fce2b9046a4b8d29917cf2

**Review by Ressinel — APPROVED** [review]
Looks good to me.
Create album works properly.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627e4ec30f15004d8e05d015

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by Ressinel** [comment]
Hi, @Kingdutch 

Could you review this PR, please? 

Thanks!

**Review by Ressinel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2660-v8hw4mubtly4oog5ihcvrie37354bgnd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627e4ec30f15004d8e05d015

**Comment by Ressinel** [comment]
🍒-picked to `11.1.x`, `11.2.x`, `11.3.x`, and `11.4.x`

**Pull request merged**
