### PR TITLE
DS-5542 by chmez: update features 3.5 => 3.7.

### PR DESCRIPTION
**Pull request by ghost**
## Description
Update Features to 3.7.

## HTT
- [x] Check out the code changes
- [ ] Test the functionality, observe it is still working the same

## Documentation
- [x] This item is added to the release notes

### CODE REVIEW

**Comment by bramtenhove** [comment]
@OH17L this is still marked as `dont-merge`, is it correct?

**Comment by OH17L** [comment]
@bramtenhove, you can merge it.

**Comment by bramtenhove** [comment]
@OH17L did you check `drush` commands as well? I'm not getting any output when running them (I cleared Drush cache).

**Comment by OH17L** [comment]
@bramtenhove, yes, I checked it but did not have this bug. I will check it again

**Comment by OH17L** [comment]
@bramtenhove, I could not reproduce your bug:

**Comment by bramtenhove** [comment]
@OH17L I mean can you try to use like `drush fl`? For me `drush cr` was also working but `drush` commands for the Features module did not give any output.

**Comment by OH17L** [comment]
@bramtenhove, we use **drush fl** only [here]( https://github.com/goalgorilla/open_social_scripts/blob/master/check-feature-state.sh#L19). This command with **bundle** argument working correct in updated version of module. I found partical solution [here](https://www.drupal.org/project/features/issues/2949343) for this command without arguments but this patch allow to see only features with **default** bundle so we can not use any patches.

**Pull request merged**
