### PR TITLE
Issue #3415923: Add new Behat test steps for validating download urls

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
As a developer I want to test if certain download url can be accessed by checking response code (200, 404, 403,..) and response headers.

## Solution
Provide 3 new Behat test steps:

@When I try to download :url
@then I should see response status code :statusCode
@Then I should see in the response header :header with :value

Example:
Given I am logged in as "user"
When I try to download "/download-url"
Then I should see response status code 200
And I should see in the response header "Content-Type" with "application/pdf"

## Issue tracker
[3415923](https://www.drupal.org/project/social/issues/3415923)

## Theme issue tracker
N/A

## How to test
- [ ] Create new Behat test using new steps and confirm they works as designed

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
We added 3 new Behat test steps:
- @When I try to download :url
- @Then I should see response status code :statusCode
- @Then I should see in the response header :header with :value

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3711-y81tjxkkpekbxewoercoqvfg9n6mdrpp.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab1b69cfb585b14ca7c5f

**Comment by zanvidmar** [comment]
🍒 Cherry-picked to 12.x here: [9317e48a3](https://github.com/goalgorilla/open_social/commit/9317e48a3f95b552159f2bdc8cb183cc265601e5)

**Comment by zanvidmar** [comment]
We need to check why tests failed [here](https://github.com/goalgorilla/open_social/actions/runs/7640714360/job/20819341498), but on the first look this should not be related with the commit changes.

**Pull request merged**
