### PR TITLE
Issue #3248421 by SV: As LU+ I can not like any content

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
Since the last update of the like module, only Administrators can like the content.

## Solution
Looks like there is an issue in the like_and_dislike module and we should include a patch to fix the current issue for all projects

## Issue tracker
- https://www.drupal.org/project/social/issues/3248421
- https://www.drupal.org/project/like_and_dislike/issues/3247929
- https://getopensocial.atlassian.net/browse/YANG-6530

## How to test
- [ ] Using the latest version of Open Social with the social_likes module enabled
- [ ] As a sitemanager
- [ ] Go to any node where is an available likes widget
- [ ] When clicking "like" I expect that counter was increased but instead there are no actions
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Screenshots
Financial-update (1)

## Release notes
- Fixes the issue with "liking/disliking" a content

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2595-bviqkwc6qo0b9eq0umzgtl9ynydd7eal.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618a6e81de497051d0db41ab

**Review by ribel — CHANGES_REQUESTED** [review]
@volodymyr-sydor-lemberg The fix itself looks good.
But I am not sure if it is safe to include a patch to the merge request, since it can be changed.
Could you generate a fixed static patch and upload it to the issue and replace it here?

Also please update the title of the PR.

**Comment by volodymyr-sydor-lemberg** [comment]
@ribel done!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2595-bviqkwc6qo0b9eq0umzgtl9ynydd7eal.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618a6e81de497051d0db41ab

**Review by ribel — APPROVED** [review]
Thanks, @volodymyr-sydor-lemberg!
I also see maintainer merged your PR in the like_and_dislike module, so I think we can merge this once behat test passes.

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
🍒 - picked to 10.3.x

**Pull request merged**
