### PR TITLE
Issue #3010027 by truls1502: Update image_widget_crop 2.1 to 2.2

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
Updated _image_effects_ 1.0 to 2.1. 
_Bugs are listed below or a full list on the link of the Drupal issue._
- https://www.drupal.org/project/image_widget_crop/releases/8.x-2.2

## Issue tracker
- https://www.drupal.org/project/social/issues/3010027

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by truls1502** [comment]
We have three options:
1. Stay like what we have now with 2.1 with the patch as we are using now. (Also update later when we feel ready for it)
2. Still update `image_widget_crop` to 2.2, but [the patch](https://www.drupal.org/files/issues/2018-07-05/2865396-36-apply-default-crop.diff) needs to be rerolled.
3. Disable [image_widget_crop](https://www.drupal.org/project/image_widget_crop) and use [crop](https://www.drupal.org/project/crop) instead of `image_widget_crop`.

What do you prefer or what do you have in roadmap regarding this module @jaapjan, @Kingdutch, @bramtenhove, @ronaldtebrake, and @robertragas? 

.

**Comment by ronaldtebrake** [comment]
Hi @truls1502, 

For now I'd say reroll the patch on 2.2 would be the best option. We are still planning to fix some items with regards to cropping, but those issues wouldn't be blocked by updating this module.

**Comment by ronaldtebrake** [comment]
Moved to 3.8 as it will require some more work to get this done. This is also going to be part of a bigger update for the Cropping issues we encounter therefore feel more confident to get this correct in 3.8 instead of rushing it in 3.7 tomorrow.

**Comment by ronaldtebrake** [comment]
https://github.com/goalgorilla/open_social/pull/1203
This is merged in the above PR, closing this one. Made sure you got the commit credits.

**Pull request closed without merging**
