### PR TITLE
Update styles for the container and hero banner on the sky theme

### PR DESCRIPTION
**Pull request by agami4**
## Problem
There is an issue with the region--secondary-navigation block. This block has the same padding as the container block so that when the region--secondary-navigation block is the child element of the container block it has additional 1rem paddings from its sides. This can be visible on the resource library page, event page, search page, home page

## Solution
Update styles for the container and hero banner on the sky theme

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-3471

## How to test
*For example*
- [x] Go to event/topic pages

## Screenshots
before:
YANG-3471  UI issue - content block does not have indents from both sides on screen with width size 1200px - Jira 2020-08-14 12-52-29

after:
Search | SparkBlue 2020-08-14 12-53-27

## Release notes
Update styles for container elements and update position for the hero banner on the sky theme

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
@ribel yes!!! :D if it goes green lets get this in :) thanks for the headsup!

**Comment by ronaldtebrake** [comment]
Hi there @agami4 @ribel 

I'm seeing this on non-sky, did you check that as well?

Screenshot 2020-08-14 at 14 06 29

**Comment by agami4** [comment]
@ronaldtebrake , I've fixed it, please check

**Comment by bramtenhove** [comment]
I was trying this with the event branch fixes as well and than I noticed this as a SM.

Screenshot 2020-08-14 at 16 31 17

After that PR is merged in this one we need to check it again and fix it.

**Comment by ribel** [comment]
@agami4 I also see that issue still exists, you can check it here: https://x-bitbucket-pr-87-qpz6hni-vncdokyquw6mc.eu.platform.sh/search/groups

**Comment by ribel** [comment]
@bramtenhove, @ronaldtebrake, I am not able to reproduce those issues on the newest build anymore.
So I am going to merge this PR.

**Comment by ribel** [comment]
🍒 picked to 9.x

**Pull request merged**
