### PR TITLE
Internal: Refactor activity stream test to use flexible group

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution
The activity-stream test is a pretty old test that was still using the UI to create all the scaffold content needed. It also used the group add menu for creating a group but that breaks with the removal of the old group types so we create a flexible group directly instead.

While building that test we found that because test coverage was lacking the functionality for showing comments in activity streams for flexible groups was also not implemented. In this PR we change the tests around to at least test what is currently working and leave what is missing to a follow-up.

The follow-up that's also referenced in `activity-stream/activity-stream-group-comments.feature` is: https://www.drupal.org/project/social/issues/3422859

## Issue tracker
Internal test change, no issue

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3775-wtuwrsof43uubkx4edb0gruub8ilnsop.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d088150be493272e917b70

**Review by ronaldtebrake — APPROVED** [review]
If we could still add a reference to the follow up that would be great, so we can easily find it if we ever look back at this PR

**Pull request merged**
