### PR TITLE
Issue #3258167 by agami4: Add route condition, add class and library

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The remove/delete membership group page does not have a correct display.

## Solution
Add class to the membership group page and attach library.

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-6904
https://www.drupal.org/project/social/issues/3258167

## How to test
*For example*
- [ ] Create/Go to group/challenge page.
- [ ] Go to the `Manage participants`/`Manage members` page.
- [ ] Click on the `Actions` dropdown button on the user-item.
- [ ] Click on Edit/Delete button.

## Screenshots
before:
Screenshot 2022-01-12 at 12 05 59
Screenshot 2022-01-12 at 12 06 11

after:
Screenshot 2022-01-12 at 13 02 23
Screenshot 2022-01-12 at 13 02 30

## Release notes
The edit/delete group membership page has a correct layout.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by rollki** [comment]
Hi @agami4 
Please fix `PHPStan` and `PHPCS`.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2688-imw8sylk4iojy5mp4ynovhgq27ftuin8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e04c475f46ed13d84008d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2688-imw8sylk4iojy5mp4ynovhgq27ftuin8.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e04c475f46ed13d84008d0

**Comment by agami4** [comment]
I close this PR because the current PR has extra commits. New PR: https://github.com/goalgorilla/open_social/pull/2698

**Pull request closed without merging**
