### PR TITLE
Issue #3341238: Upgrade Drupal version to Drupal 9.5

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Currently, Open Social is using Drupal 9.4 ( https://github.com/goalgorilla/open_social/blob/11.7.1/composer.json#L127 )

Drupal 9.4's security support is going to end on June 21, 2023 as per documentation in https://www.drupal.org/about/core/policies/core-release-cycles/schedule#current

The current minor version upgrade of Drupal is https://www.drupal.org/project/drupal/releases/9.5.3.

So, we are upgrading Open Social to Drupal 9.5.3

Release notes of Drupal 9.5: https://www.drupal.org/project/drupal/releases/9.5.0

## Solution
1. Upgrade Drupal core dependencies to latest version of Drupal 9.5
2. Deprecation of modules and themes which are mentioned Drupal 9.5 release notes will be dealt when Open Social will move to Drupal 10.

### Drupal 10 preparation 

( taking notes for future Drupal 10 preparation )

Make sure that our PHP support is 8.1

Make sure drupal_social is adjusted for Rector, ECS, and dependencies to use Drupal 10 and PHP 8.1.  [GitHub - goalgorilla/drupal_social: Open Social Development repository.](https://github.com/goalgorilla/drupal_social) 

Make sure the dev dependencies are updated in [GitHub - goalgorilla/open_social_dev: require-dev dependencies for goalgorilla/open_social required to run tests and coding standard checks.](https://github.com/goalgorilla/open_social_dev)

Adopt the change records from https://www.drupal.org/list-changes/drupal/published?keywords_description=&to_branch=10.0.x&version=&created_op=%3E%3D&created%5Bvalue%5D=&created%5Bmin%5D=&created%5Bmax%5D= 

Make sure our PHPStan baseline is at a minimum.

Make sure the contributed modules and Open Social code are ready for Drupal 10.

Use Rector and ECS check tools to upgrade the code compatibility.

Make sure our PHPStan, PHPCS, and PHPUnit settings files are updated as well.

Make sure to take of following deprecations:

https://www.drupal.org/node/3223395

https://www.drupal.org/node/3276601

https://www.drupal.org/node/3306232

https://www.drupal.org/node/3272679

https://www.drupal.org/node/3276601

https://www.drupal.org/node/3304314

https://www.drupal.org/node/3259831

https://www.drupal.org/node/3304899

https://www.drupal.org/node/3304481

https://www.drupal.org/node/3310028

https://www.drupal.org/node/3310025

https://www.drupal.org/node/3313997

https://www.drupal.org/node/3319135

Double check https://www.drupal.org/project/drupal/releases/9.5.0 for removals, deprecations and contributed project information.

Use at least following versions:

https://www.drupal.org/project/bootstrap/releases/8.x-3.26 

https://www.drupal.org/project/gin/releases/8.x-3.0-rc1

[gin_toolbar 8.x-1.0-rc1](https://www.drupal.org/project/gin_toolbar/releases/8.x-1.0-rc1) 

Review our Social Base and Social Blue for removal of libraries and core themes.

## Issue tracker
https://www.drupal.org/project/social/issues/3341238

## Theme issue tracker
N.A

## How to test
- [ ] All checks should pass.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N.A

## Release notes
As Drupal 9.4 was reaching end of security in June 21, 2023. We have upgraded Open Social to Drupal 9.5

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by tbsiqueira** [comment]
Other dependent PRs are already merged, we can merge this as soon as we have all green checks!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3312-hon3keiwppcgkof0kicvzapliegedmgq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e9fa757ec9327275c41936

**Comment by tbsiqueira** [comment]
We reverted this PR and we are going to recreate it with the latest updated code from main 

https://github.com/goalgorilla/open_social/pull/3368

**Pull request merged**
