### PR TITLE
Issue #3354659 by zanvidmar: Update Gin version to 8.x-3.0-rc2

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
We updated Open Social to Drupal 9.5.3 ([PR](https://github.com/goalgorilla/open_social/pull/3369))
We need to upgrade Gin to at least 8.x-3.0-rc1 as stated in PR.

Check the Gin issue for more info: https://www.drupal.org/project/gin/issues/3309113

## Solution
Update Gin version to 8.x-3.0-rc2

## Issue tracker
[3354659](https://www.drupal.org/project/social/issues/3354659)

## Theme issue tracker
[3309113](https://www.drupal.org/project/gin/issues/3309113)

## How to test
- [ ] Update Gin to 3.0-rc2
- [ ] Check if Gin theme is not broken 
- [ ] Use the system, specially the admin area and common content and check for visual issues

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Gin has been updated to 3.0-rc2

## Change Record
Gin has been updated to 3.0-rc2. RC1 deprecated the CamelCase CSS3 classes in favor of kebab case classnames. They will be removed in the stable release. See [#3309113: Change CSS3 variables from camelCase to kebab-case](https://www.drupal.org/project/gin/issues/3309113)

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3375-ylwhsyxbnzxqfi1znvziudg65od9torm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/643d63eb92a6d1e96da5cb73

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.9.x

**Pull request merged**
