### PR TITLE
Issue #3282058 by chmez: Support visibility for any entity type

### PR DESCRIPTION
**Pull request by ghost**
## Problem
Entity edit page display wrong active options and default option in the visibility field for entity type except for nodes.

## Solution
Extend functionality which manages the visibility field to cover all entity types.

## Issue tracker
- https://www.drupal.org/project/social/issues/3282058
- https://getopensocial.atlassian.net/browse/YANG-7863

## How to test
- [x] Enable [Group Media](https://www.drupal.org/project/groupmedia) module and create the "File" bundle with the "Visibility" field (the "field_media_visibility" machine name) of the "Media" entity type.
- [x] Navigate to the "/admin/group/types/manage/flexible_group/content" page and install the "Group media (File)" plugin.
- [x] Create a new flexible group and navigate to the "/group/<GROUP_ID>/content/create/group_media:file" page.
- [x] Fill in the required fields (don't change the "Group members" default value in the "Visibility" field).
- [x] When you press "Save" then you should be redirected to the edit page and you should see that the selected option in the "Visibility" field is still the "Group members" option.

## Release notes
Support visibility for any entity type.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2947-m32w6z02myf4xx56pnmiew60lens8zvb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628cca0c6eb9e7df1ae57188

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2947-m32w6z02myf4xx56pnmiew60lens8zvb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628cca0c6eb9e7df1ae57188

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2947-m32w6z02myf4xx56pnmiew60lens8zvb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628cca0c6eb9e7df1ae57188

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2947-m32w6z02myf4xx56pnmiew60lens8zvb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/628cca0c6eb9e7df1ae57188

**Review by ribel — APPROVED** [review]
I have tested changes and checked the code and I don't see any regressions in old functionality.
Also now visibility field can be added to any entity, like Media for example, so good change, @OH17L!

**Comment by ribel** [comment]
@Ressinel, @tbsiqueira Hi guys! This PR is finished from our side.
Could you please check it and let us know if we can merge it?

**Review by Ressinel — APPROVED** [review]
I can confirm that it works properly for me as well.

**Comment by ribel** [comment]
@Ressinel It was cherry-picked to branch 11.4.x

**Pull request merged**
