### PR TITLE
Issue #3385634 by nkoporec: Inline images are not displaying in social footer block

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When inserting an inline image in social footer block via the admin/config/opensocial/footer-block settings page, the image is not rendered after hitting the save button. The DOM element is there but the URL to the image is broken for other users (it works for the one that saved the form and uploaded the image).

The reason for this is that by default CKEditor will save inline images in the private directory, this ties the image to be only viewed/accessed by users who created this private image or have access to the entity that this image is attached to, since this form is not tied to any entity but rather its a custom implementation it means that only user who uploaded the inline image will have access to it.

## Solution
Implement a hook_file_download() in social_footer module that allows access to private images used within the text field of the social footer block settings.

## Issue tracker
https://www.drupal.org/project/social/issues/3385634

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Log in as user 1.
2. Go to admin/config/opensocial/footer-block and upload an image via the CKEditor.
3. Save the form
4. Log in as different user and check the footer block if the image is displaying correctly.

### Before merge
- [x] Code/peer review is completed
- [x] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [x] All automated tests are green
- [x] Functional/manual tests of the acceptance criteria are approved
- [x] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [x] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [x] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [x] This pull request has all required labels (team/type/priority)
- [x] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [x] Any front end changes are tested on all major browsers
- [x] New UI elements, or changes on UI elements are approved by the design team
- [x] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before:
image

After:
image

## Release notes
Fixed an issue where inline images would not render correctly in social footer block.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by BiaInacio** [comment]
Image is being displayed on the footer as expected!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by tbsiqueira** [comment]
@nkoporec, please add tests to this feature, this is a quick test win

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by nkoporec** [comment]
@tbsiqueira as discussed, I created a follow up for the test, as currently the` I attach the file "/files/opensocial.jpg" to "Image" ` is broken and all tests that are using it are tagged as  `disabled`

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3509-jsnlwvw0b04acsuh9kpyw17zlwfi0tra.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f88c4cf3643e9c2113c31c

**Pull request merged**
