### PR TITLE
Issue #3414795: Upgrade the Drupal to 10.2 version

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Drupal was upgraded to 10.0 version and keeping forward with keep Drupal in major version, we need to upgrade the Drupal to 10.2, it's minor version for Drupal 10.x.

## Solution
1. Upgrade Drupal to 10.2 version;
2. Check all patches to remove or upgrade if it's necessary;
3. Check the releases notes and the impact in our modules;

## Issue tracker
[PROD-27925](https://getopensocial.atlassian.net/browse/PROD-27925)
[#3414795](https://www.drupal.org/project/social/issues/3414795)

## Theme issue tracker
N/A

## How to test
- [ ] Regression test

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Drupal release notes:
- https://www.drupal.org/project/drupal/releases/10.1.0-beta1
- https://www.drupal.org/project/drupal/releases/10.1.0-rc1
- https://www.drupal.org/project/drupal/releases/10.1.0
- https://www.drupal.org/project/drupal/releases/10.1.1
- https://www.drupal.org/project/drupal/releases/10.1.2
- https://www.drupal.org/project/drupal/releases/10.1.3
- https://www.drupal.org/project/drupal/releases/10.1.4
- https://www.drupal.org/project/drupal/releases/10.1.5
- https://www.drupal.org/project/drupal/releases/10.1.6
- https://www.drupal.org/project/drupal/releases/10.1.7
- https://www.drupal.org/project/drupal/releases/10.2.x-dev
- https://www.drupal.org/project/drupal/releases/10.2.0-alpha1
- https://www.drupal.org/project/drupal/releases/10.2.0-beta1
- https://www.drupal.org/project/drupal/releases/10.2.0-rc1
- https://www.drupal.org/project/drupal/releases/10.2.0
- https://www.drupal.org/project/drupal/releases/10.2.1

## Change Record
N/A

## Translations
N/A

[PROD-27925]: https://getopensocial.atlassian.net/browse/PROD-27925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3703-ruzixb7lj0kz4upf1hpxuwiyzv2one3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a6b5487633b712e716fdd7

**Comment by ronaldtebrake** [comment]
#3717

**Pull request closed without merging**
