### PR TITLE
Issue #3355958: Improve the stream block on the landing page

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The stream block has an extra wrapper and styles on the landing page.

## Solution
Reset `card` styles for the stream block.

## Issue tracker

- https://www.drupal.org/project/social/issues/3355958
- https://getopensocial.atlassian.net/browse/PROD-24770

## Theme issue tracker
N/A

## How to test
- [ ] Create the Landing page
- [ ] Add Block(stream block)
- [ ] Save and check how the stream block looks.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before:
Screenshot 2023-03-27 at 10 07 48

After:
Screenshot 2023-04-24 at 12 52 00

## Release notes
The stream block has a correct view on the landing page.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3383-vgsrpke5tcxanrshe9fpe4xbuyvr2jjx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64465234572317307c1822b4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3383-vgsrpke5tcxanrshe9fpe4xbuyvr2jjx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64465234572317307c1822b4

**Review by ribel — APPROVED** [review]
Changes was tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3383-vgsrpke5tcxanrshe9fpe4xbuyvr2jjx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64465234572317307c1822b4

**Pull request merged**
