### PR TITLE
Issue #3455400: Move group_admin to group_manager group role only for SM/CM creators

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

Migration group_admin to group_manager role should be applied for users that have assigned SM/CM roles and they are already creators of the group

## Solution

Add additional checks on sitemanager, contentmanager roles and group owner in migration

## Issue tracker

- https://www.drupal.org/project/social/issues/3455400
- https://getopensocial.atlassian.net/browse/PROD-29829
## Theme issue tracker

N/A
## How to test
This update can be checked only for existing sites during group upgrade when Group Admin is replaced with Group Manager   role only for SM/CM group creators

## Screenshots

N/A
## Release notes

Fixes an issue with replacing group_admin with group_manager roles for members.
## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Review by robertragas — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3936-hxhqvarfufe9l6ghsvfz2gtqriuyzy2q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66717a476939b442cabd6c75

**Review by ribel — APPROVED** [review]

**Pull request merged**
