### PR TITLE
Issue #3239841 by SV: Impossible to add new users when unique nicknames are enabled

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
I have tried to register a new user and received an error message: `The website encountered an unexpected error. Please try again later`

In the report log there is the following:
`Drupal\Core\Database\InvalidQueryException: Query condition 'profile__field_profile_nick_name.field_profile_nick_name_value IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 105 of /var/www/html/core/lib/Drupal/Core/Database/Query/Condition.php).`

So, looks like enabled `"Unique nicknames"` option on the `"/admin/config/opensocial/profile-fields"` page caused a current issue

## Solution
Add additional check for new users on validation step

## Issue tracker
- https://www.drupal.org/project/social/issues/3239841
- https://getopensocial.atlassian.net/browse/YANG-6314

## How to test
- [ ] Using version 10.25 of Open Social with the `social_profile_fields` module enabled
- [ ] As a admisistrator/sitemanager
- [ ] Try to enable the `Unique nicknames` option on `/admin/config/opensocial/profile-fields` page (screen a)
- [ ] Also, note that the nickname field is disabled on the user register page (screen b)
- [ ] Then open `/admin/people/create` page and try to create a new user
- [ ] When saving I expect that I've created a new user but instead see `The website encountered an unexpected error. Please try again later`.
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Screenshots
a:
Social-profile-fields-Workspace

b:
Social-registration-fields-settings-United-Nations-Trust-Fund-to-End-Violence-Against-Women

## Release notes
Fixes the `Unique nicknames` issue on the add/register user pages.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2531-esasewzckm1jkzlmp3xeaa4mgsh7g9gq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61546553cc9cc419485966e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2531-esasewzckm1jkzlmp3xeaa4mgsh7g9gq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61546553cc9cc419485966e4

**Review by rollki — APPROVED** [review]
I'm was able to reproduce this issue, changes look good to me 👍

**Comment by rollki** [comment]
Hey @ronaldtebrake 
What do you think about this fix ?)

**Comment by ribel** [comment]
Hi @Kingdutch,
Could you check the last comment from @volodymyr-sydor-lemberg?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2531-dptrwqm8iprzygpq4snqtnaf4qbvvdgk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9ad3d5f46ed13d80676d7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2531-dptrwqm8iprzygpq4snqtnaf4qbvvdgk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b9ad3d5f46ed13d80676d7

**Comment by Ressinel** [comment]
Hi, @volodymyr-sydor-lemberg @ribel

For now, PR has milestone `11.0.1` Is this issue reproduced on OS 11 since I can do that?

And is this change critical to have a new release of **OS** `10.3.x` version for your customer? Check this [message](https://opensocial.slack.com/archives/C0RQ56PFX/p1643799951068579).

**Comment by volodymyr-sydor-lemberg** [comment]
> Hi, @volodymyr-sydor-lemberg @ribel
> 
> For now, PR has milestone `11.0.1` Is this issue reproduced on OS 11 since I can do that?
> 
> And is this change critical to have a new release of **OS** `10.3.x` version for your customer? Check this [message](https://opensocial.slack.com/archives/C0RQ56PFX/p1643799951068579).

Hi @Ressinel, I just checked and looks like for the current moment this issue is not actual for OS 11

Also, we already use it as a patch and I don't think that is critical to have a new release of **OS** `10.3.x`.

**Comment by ribel** [comment]
@volodymyr-sydor-lemberg, @Ressinel In this case, if we can't reproduce the issue anymore on Social 11 - I think we can close this PR at all?

**Comment by volodymyr-sydor-lemberg** [comment]
@ribel Yes, seems we can close it

**Comment by zanvidmar** [comment]
Note: this issue can be reproduced on OS 13.0.0-alpha5 when you try to create new profile programatically via API (and current_profile does not exit).

Error: Call to a member function get() on null in Drupal\social_profile_fields\Plugin\Validation\Constraint\UniqueNicknameValidator->isUnique() (line 76 of profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_fields/src/Plugin/Validation/Constraint/UniqueNicknameValidator.php).

**Pull request closed without merging**
