### PR TITLE
Issue #3162948 by ribel: Provide a method to alter message templates where duplicates are allowed

### PR DESCRIPTION
**Pull request by ribel**
## Problem
The current architecture of Activity Notifications doesn't allow to have two messages about the same entity for the same user.
There is only a hardcoded exception for `moved_content_between_groups` in `\Drupal\activity_logger\Service\ActivityLoggerFactory::checkIfMessageExist()`. But there might be other use cases.

## Solution
Provide a method to alter message templates where duplicates are allowed.

## Issue tracker

- https://www.drupal.org/project/social/issues/3162948
- https://getopensocial.atlassian.net/browse/YANG-1403
- https://getopensocial.atlassian.net/browse/YANG-1411

## How to test
*For example*
- [ ] Using version 8.x of Open Social with the Social Challenge module enabled
- [ ] Check if the module version has implemented `social_challenge_phase_activity_allowed_duplicates_alter()`
- [ ] As a site manager
- [ ] Create a new challenge phase that will end soon with automatic advancing ideas enabled
- [ ] When phase ends coauthors and follower should receive notifications about that.
- [ ] Create another phase that will end soon with automatic advancing ideas enabled
- [ ] When phase ends coauthors and follower should receive notifications about that again.

## Release notes
New alter hook was added: `hook_activity_allowed_duplicates_alter()` in `activity_logger` module.

### CODE REVIEW

**Comment by denysyukm** [comment]
As for me - all looks good!

**Comment by ribel** [comment]
Hi, @ronaldtebrake could you check it and merge if it's ok with you? Don't want to merge my own PR :)

**Comment by ronaldtebrake** [comment]
Thanks guys, looks good to me will make it part of 9.2 :)

**Comment by ronaldtebrake** [comment]
Cherry-picked 🍒  to 8.x-9.x

**Pull request merged**
