### PR TITLE
PROD-31232: Implement "group create" event for the EDA

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem (for internal)
Currently we don't have an EDA event that fires when a group is created.

## Solution (for internal)
Add the new event

Payload:

```
{
	"specversion": "1.0",
	"id": "70e9f519-a3d0-421f-bf42-659a08c4191f",
	"source": "/group/add/flexible_group",
	"type": "com.getopensocial.cms.group.create",
	"datacontenttype": "application/json",
	"time": "2024-11-21T15:11:46Z",
	"data": {
		"group": {
			"id": "1bd53650-0316-4713-a8da-bdffd14c539f",
			"created": "2024-11-21T15:11:46",
			"updated": "2024-11-21T15:11:46",
			"status": "published",
			"label": "Test",
			"visibility": {
				"type": "community",
				"roles": []
			},
			"contentVisibility": {
				"type": "community"
			},
			"membership": {
				"method": "request"
			},
			"type": "27aaa381-4322-4096-9cfa-63d4df67d538",
			"author": {
				"id": "53bb767a-cdc0-4872-81eb-9a4db10374bf",
				"displayName": "admin",
				"href": {
					"canonical": "https://opensocial.ddev.site/user/1/home"
				}
			},
			"address": {
				"label": "",
				"countryCode": "",
				"administrativeArea": "",
				"locality": "",
				"dependentLocality": "",
				"postalCode": "",
				"sortingCode": "",
				"addressLine1": "",
				"addressLine2": ""
			},
			"href": {
				"canonical": "https://opensocial.ddev.site/group/23/stream"
			}
		},
		"actor": {
			"application": null,
			"user": {
				"id": "53bb767a-cdc0-4872-81eb-9a4db10374bf",
				"displayName": "admin",
				"href": {
					"canonical": "https://opensocial.ddev.site/user/1/home"
				}
			}
		}
	}
}
```

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-31232

## How to test
1. Enable social_eda
2. Enable and set up the social_eda_dispatcher
3. Create a new group.
4. An event should be dispatched with the payload similar to above

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by ribel** [comment]
@nkoporec I have rebased with main (which is fixed now), but I still see that PHPStan and PHPCS still failing.
Could you check it, please?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4178-an1m5hhf97kxhuynzilfnmzn41nw6x5o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67322b5c8e2485d4414244ff

**Review by ribel — APPROVED** [review]
Changes have been tested and works as expected.

image

**Pull request merged**
