### PR TITLE
Internal: Move flexible group specific field from search to flexible group module

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution

In the migration from old group types to flexible groups we added a field to the group search. However that field doesn't exist if flexible groups isn't enabled and the search will be installed before flexible groups. So to make sure the search config is valid we need to make sure that the flexible group module adds the field rather than it being in the social_search module.

We don't yet move the entire index and view for two reasons:

1) There's plans to merge the group index into `all` at which point we'll also have to move the field indexing, but that's out of current scope and already in motion elsewhere (profile refactor).

2) We want to have the `group` view in `flexible_group` because the view should only show flexible groups. However, currently it's also still used to show group-like things such as `courses`. Before limiting the group view to Flexible Groups we must make sure courses has its own way of being found in search by creating a separate view. That's too much work for the amount of time we have at the moment.

## Issue tracker
Internal: no issue

## How to test
- [ ] Group search should work as expected

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3781-hcuod33iunxemyhvmxmdfcmyh7vt6340.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d321b5e946a8470ddbac7b

**Comment by robertragas** [comment]
Sounds logical indeed, and the behaviour is still the same with the group search after testing.

**Review by robertragas — APPROVED** [review]

**Pull request merged**
