### PR TITLE
Issue #3380714: Demo groups can be created with visibility fields

### PR DESCRIPTION
**Pull request by nechai**
## Problem
Follow up for https://github.com/goalgorilla/open_social/pull/3691#discussion_r1465960151

## Solution
Demo groups can be created with visibility fields.

## Issue tracker
n/a

## Theme issue tracker
n/a

## How to test
n/a

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
n/a

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Review by ribel — CHANGES_REQUESTED** [review]
@nechai I've checked on a test env I still see all groups visibilities are set as Public during editing. But in configs default visibility is set to Community.

image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by ribel** [comment]
@nechai I've checked it again, but it still needs work.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3721-aub5egbaljqiwauhoil2he0xub7u5cci.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b273a682e119e53e2e2eb1

**Comment by nechai** [comment]
@ribel When you try to install locally a profile, then run these commands
```
drush en social_demo -y &&
drush sda file user group topic event event_enrollment post comment like
```
everything works fine...
Could be there the issue that db is not installing from scratch or something? 
There are no any fixed we can add, so I thing the problem is with some CI rules during profile install that are ignoring PR's changes.

**Review by ribel — APPROVED** [review]

**Pull request merged**
