### PR TITLE
Issue #3423203: Uninstall admin_toolbar_tools module

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Admin Toolbar Tools module would be uninstalled from [#3385341](https://www.drupal.org/project/social/issues/3385341), but it ins't uninstalled from all because the required-by skip couple installation.

## Solution
Create a hook-update to uninstall Admin Toolbar Tools if it isn't be required by an enabled module.

## Issue tracker
[PROD-28317](https://getopensocial.atlassian.net/browse/PROD-28317)
[#3423203](https://www.drupal.org/project/social/issues/3423203)

## Theme issue tracker
N/A

## How to test
N/A

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-28317]: https://getopensocial.atlassian.net/browse/PROD-28317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3791-c1pl4qfjoeqphkcpaed3ffqbfmolhfrd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d74feba79d441241431a81

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3791-c1pl4qfjoeqphkcpaed3ffqbfmolhfrd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d74feba79d441241431a81

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3791-c1pl4qfjoeqphkcpaed3ffqbfmolhfrd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65d74feba79d441241431a81

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
Approved, 

I also did some small changes to make sure we use the “ and ' consistent as some parts had single quotes and others double quotes.

Waiting for the test to go green now.

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
Merged and cherry-picked to 12.3.x

**Pull request merged**
