### PR TITLE
Issue #2984283 by agami4: Add loader indicator when loading image

### PR DESCRIPTION
**Pull request by agami4**
## Problem
When loading image from any input form (stream, topic etc.) there's no loader indicating to wait.

## Solution
Show loading indicator when loading image

## Issue tracker
https://www.drupal.org/project/social/issues/2984283

## How to test
- [x] Should create new topic or other Content Type and it should be clear there is a loader indicating to wait.
- [x] Should create new comment with attachment and it should be clear there is a loader indicating to wait.
- [x] Should create new post with image and it should be clear there is a loader indicating to wait.

## Release notes
When uploading an image in any file attachment form (post, comment and topic for example) there is now a loader which indicate that the user should wait for the image to upload.

### CODE REVIEW

**Comment by jaapjan** [comment]
It works for topics (and I assume other file types) but does not work for post and comment yet. I think that also needs to be done as part of this story. See attached movies for example.

[loader-movies.zip](https://github.com/goalgorilla/open_social/files/3178591/loader-movies.zip)

**Comment by jaapjan** [comment]
@agami4 time to process my feedback still? :-)

**Comment by agami4** [comment]
Hey @jaapjan,
I have started to update this issue

**Comment by jaapjan** [comment]
It works really well, thanks @agami4 this is a great improvement for 6.x!

**Comment by jaapjan** [comment]
I propose to keep this only in 6.x for now.

**Pull request merged**
