### PR TITLE
Issue #3281698 by colan: "Social: Event sorting (passed and upcoming)" views filter only sorts in descending order

### PR DESCRIPTION
**Pull request by colans**
See https://www.drupal.org/project/social/issues/3281698 for details.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by Ressinel** [comment]
Hi @colans

Thanks for your fixes!

I have try to test it but changes don't do any affect for view sorting.
Could you provide HTT steps for existing view in Open Social?

Thanks!

**Comment by navneet0693** [comment]
@Ressinel As per @colans comment on D.O issue, let's see we can reproduce the problem reported.

**Comment by Ressinel** [comment]
@navneet0693 I don't see any comments on D.org that can help me to reproduce the issue after my last attempt.

**Comment by tbsiqueira** [comment]
Closing PR due to inactivity, please feel free to open if still relevant

**Pull request closed without merging**
