### PR TITLE
Issue #3418675 by nkoporec : Remove drupal/ctools as dependency from our composer.json

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Ctools is no longer a required dependency, as it was remove from https://www.drupal.org/project/pathauto/releases/8.x-1.11

## Solution
Remove the dependency.

## Issue tracker
https://www.drupal.org/project/social/issues/3418675

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Removed ctools from our dependency, as it is no longer needed.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3737-zkfy91c8gr62ttqsfpxc5wyfsvlj9l62.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb6dd4d84dbee02edc73d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3737-zkfy91c8gr62ttqsfpxc5wyfsvlj9l62.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb6dd4d84dbee02edc73d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3737-zkfy91c8gr62ttqsfpxc5wyfsvlj9l62.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb6dd4d84dbee02edc73d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3737-zkfy91c8gr62ttqsfpxc5wyfsvlj9l62.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb6dd4d84dbee02edc73d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3737-zkfy91c8gr62ttqsfpxc5wyfsvlj9l62.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb6dd4d84dbee02edc73d

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
Approved and merged only in main as the milestone is 13.0.0

**Pull request merged**
