### PR TITLE
Issue #3348399 by Kingdutch: Move search to SOLR and drop support for searching against the database

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
pen Social provides a complex community product. Search is a powerful way for users to find content within their community and ensuring that search results are accurate and provided in a performant manner is important to a successful community.

The search_api module provides a way to easily abstract over different search back-ends. However to support those different back-ends Open Social is limited to only using functionality that's within the least common denominator. This can have an adverse effect on the user experience.

In our community building experience we've seen first-hand that using the database as a search back-end can have a profoundly negative impact on platform performance. Additionally we've been unable to build some desired features which would've been supported by SOLR but were not possible with a database.

It's with this in mind that for all of our SaaS customers we've already configured a SOLR back-end and do not use the database for search anymore. Unfortunately with the work being done for [improved profile configuration and privacy options](https://www.drupal.org/project/social/issues/3230125) we're finding that the maintenance cost for making things work with the database back-end is becoming too high.

## Solution
This pulls in the changes that were originally made for the profile refactor from https://github.com/goalgorilla/open_social/pull/3443/. It's different in that it migrates all of our search indices rather than only the single `social_all` index so that it's independent of the work to merge our different indices into one which will be done in a future PR for 13.0.0.

This installs the search_api_solr module and uses our existing internal SOLR configuration to configure a SOLR search back-end. After this we switch our current search-indices to use the SOLR back-end.

Finally we uninstall the database back-end to complete the migration.

This commit also adds the SOLR service to the Behat testing and to Tugboat so that we can verify that search still works.

We can't use update helper because the steps need to be taken in a specific order.

## Issue tracker
https://www.drupal.org/project/social/issues/3348399
https://getopensocial.atlassian.net/browse/PROD-25036

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Behat tests for search should pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Open Social now requires SOLR to power its search operations and no longer supports searching against a database back-end.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3660-iffjdmgqafp9hheusanwea8l4jxseosl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6582b80c9c5de267a43b2776

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Can confirm it works as expected functionally too:
Screenshot 2024-01-02 at 13 44 30
Screenshot 2024-01-02 at 13 44 22
Screenshot 2024-01-02 at 13 44 45

**Pull request merged**
