### PR TITLE
Issue #3385398 by Kingdutch: Optimize menu link loading for module installs

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
A pattern that was seen to add the "All x" links was that we'd load all the menu links (which can be 100s) and then looped through them all.

## Solution

This commit instead uses filters in the database query to more efficiently find the correct link and then more efficently creates the new child menu link. While making this change we move things back into hook_install, which is generally small enough not to need splitting up (especially since we usually don't re-use any of the other install code, since installing is a pretty specific action).

## Issue tracker
https://www.drupal.org/project/social/issues/3385398

## How to test
- [ ] All affected menu items should exist post install

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
[Not sure if release notes is needed for performance optimization on install]

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by BiaInacio** [comment]
Change did not affect the "All-X" pages, test ok!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3507-91thmvaz40grw4uf6mpcvwnhtls2wda8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f74a14f3643e9c21f734c8

**Review by tbsiqueira — APPROVED** [review]

**Comment by Kingdutch** [comment]
Cherry picked to 11.10.x as aca95501b7

**Pull request merged**
