### PR TITLE
Updates: socialbase and socialblue themes to the 2.6.0

### PR DESCRIPTION
**Pull request by Agamich-FE**
## Problem
The Social Blue theme has a new Major version and some patch are outdated.

## Solution

- Update socialbase to 2.6.0
- Update socialblue to 2.6.0

## Issue tracker

- https://www.drupal.org/project/socialbase/releases/2.6.0
- https://www.drupal.org/project/socialblue/releases/2.6.0
- [PROD-29969](https://getopensocial.atlassian.net/browse/PROD-29969)

## Theme issue tracker
N/A

## Release notes
**SocialBase:**
- [#3417761: Replace non-existing classes according to group module upgrade to 2.x](https://www.drupal.org/project/socialbase/issues/3417761)
- [#3407006: Remove legacy group types](https://www.drupal.org/project/socialbase/issues/3407006)
- [#3455930: [UI] Remove extra `z-index` form the region content/content top](https://www.drupal.org/project/socialbase/issues/3455930)
- [#3456257: [UI] Improve position auth buttons](https://www.drupal.org/project/socialbase/issues/3456257)
- [#3444049: [UI] Issue with button alignment on the membership page](https://www.drupal.org/project/socialbase/issues/3444049)
- [#3439342: [UI]Add height to the comment avatar](https://www.drupal.org/project/socialbase/issues/3439342)
- [#3425768: [UI] Re-design Custom Content Block List](https://www.drupal.org/project/socialbase/issues/3425768)

**SocialBlue:**

- [#3407010: Remove legacy group types](https://www.drupal.org/project/socialblue/issues/3407010)
- [#3440435: [UI] Add dropdown behavior to the edit button on the event page(hero section)](https://www.drupal.org/project/socialblue/issues/3440435)
- [#3425773: [UI] Remove extra styles](https://www.drupal.org/project/socialblue/issues/3425773)

## Translations

[PROD-29969]: https://getopensocial.atlassian.net/browse/PROD-29969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3949-fuhbogqxvkqnhf3cdi6yubyboabyfyax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667c08ad81747e9dde506913

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3949-fuhbogqxvkqnhf3cdi6yubyboabyfyax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667c08ad81747e9dde506913

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3949-fuhbogqxvkqnhf3cdi6yubyboabyfyax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667c08ad81747e9dde506913

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3949-fuhbogqxvkqnhf3cdi6yubyboabyfyax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667c08ad81747e9dde506913

**Review by ribel — APPROVED** [review]
Changes were tested and all looks as expected.

**Pull request merged**
