### PR TITLE
Internal: Remove Definition of Done from Pull Request Template

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
We have a big bunch of text in the PR that we're seemingly never using.

## Solution
Remove the Definition of Done from the PR template.

## Issue tracker
N/a

## Theme issue tracker
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3843-pdeo6ygoedb0xnxyjuznejxt4gxv5bhl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660e4a1deaff44936160b5d2

**Comment by Kingdutch** [comment]
We've discussed this a few times and should just do it. it's very very low effort to revert if anyone can make a case that they miss it :D

**Pull request merged**
