### PR TITLE
Issue #3247624 by nkoporec: Alternative frontpage is redirecting to AN page for user 1

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem

In https://www.drupal.org/project/social/issues/3214317 , we introduced the ability to preview the anonymous page but introduced a small bug, when user 1 visits the root domain (eq. https://my-site.local/) it will not redirect him to the LU page defined in the settings but instead it will defer the redirect and show the AN page.

## Solution

We should not defer the redirect if the url request is / .

## Issue tracker

https://www.drupal.org/project/social/issues/3247624

## How to test
1. Enable alternative_frontpage module
2. Set two different frontpages for AN and LU users
3. Visit the root url (apex domain) as admin (user 1)

## Release notes
Fixed an issue with alternative frontpage module and the redirect defer when the administrator visits the root domain.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2583-mxaaksfeqaxbapdhifiqah75bzmziyqa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6183b4a3908ae17ecb51fb47

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2583-mxaaksfeqaxbapdhifiqah75bzmziyqa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6183b4a3908ae17ecb51fb47

**Review by nachosalvador — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2583-mxaaksfeqaxbapdhifiqah75bzmziyqa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6183b4a3908ae17ecb51fb47

**Comment by navneet0693** [comment]
The method will be changed in https://github.com/goalgorilla/open_social/pull/2590.

**Comment by robertragas** [comment]
Then this PR can be closed right? @navneet0693

**Comment by navneet0693** [comment]
@robertragas May be review that PR if that has the required changes :-)

**Comment by navneet0693** [comment]
@nkoporec Would it be possible for you to take a look at changes in #2590 and see that PR fixes your problem statement here?

**Comment by navneet0693** [comment]
@nkoporec @robertragas Please resolve the conflict.

**Pull request closed without merging**
