### PR TITLE
Issue #3132783 by chmez: Fix issue with showing few fields with the same name on the Custom content list block

### PR DESCRIPTION
**Pull request by ghost**
## Problem
When open the Layout Builder sidebar for editing the **Custom content list block** inline-block then some fields which not related to option selected in the **Type of content** field can be visible.

## Solution
Re-use the processing method for creation form.

## Issue tracker
- https://www.drupal.org/project/social/issues/3132783
- https://getopensocial.atlassian.net/browse/YANG-2536
- https://getopensocial.atlassian.net/browse/ECI-1059

## How to test
- [ ] Enable all available modules with the **ContentBlock** plugins
- [ ] Log in as **SM**
- [ ] Create a node of the **Dashboard** content type and add the **Custom content list block** inline-block
- [ ] When you open sidebar for editing the inline-block then you can see fields with the same names

## Release notes
Fix issue with showing few fields with the same name on the Layout Builder sidebar for editing the **Custom content list block** inline-block.

### CODE REVIEW

**Review by ribel — APPROVED** [review]
Looks good to me.

**Review by ribel — APPROVED** [review]
@OH17L All looks good to me, but fix title of the PR, to make it more clear :)
You may copy part of Release notes, which is more clear.

**Comment by OH17L** [comment]
@ribel the PR title and the drupal.org issue title have been updated

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
Merged and cherry-picked to the 8.x-8.x

**Pull request merged**
