### PR TITLE
Issue #3395384 - Fix error to delete a comment with notification

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
When a comment is deleted and it has a notification created the pop-up confirmation never close, an error happen at browser-console and the comment is deleted.

This problem happen because a batch is started by activity module to keep the notification updated with the main entity and when the Ajax Comments is be using the batch can't redirect to batch page, it should be keep to be return at th request, but it is be ignoring by batch validation.

## Solution
Applied a patch from Drupal Community to avoid the batch validation to redirect ajax **request.**

## Issue tracker
[#3395384](https://www.drupal.org/project/social/issues/3395384)
[#3395358](https://www.drupal.org/project/drupal/issues/3395358)

## Theme issue tracker
N/A

## How to test
- [ ] Enable the Social Ajax Comments
- [ ] Create an event content and add a comment
- [ ] Access the new event as simple user and reply the comment added from before step 
- [ ] Come back to origin user and check if the notifications was created
- [ ] If the notifications isn't be created, run the crons
- [ ] After notification is created, try to delete a comment by simple user with the simple user
- [ ] Check comment was deleted and their notification

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-26816]: https://getopensocial.atlassian.net/browse/PROD-26816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by BiaInacio** [comment]
The comment was deleted as expected!
image

PS: I found a bug, the notification related to the deleted content is breaking after the deletion. I believe this will be fixed on another PR.
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by BiaInacio** [comment]
Tested again and the notification about the comment were deleted as well!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3562-jl9kghoe2utdkbwktrhj40zsqa15xega.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6531706acbeeaba7d0d58795

**Comment by robertragas** [comment]
Merged and cherry-picked to 12.0.x

**Pull request merged**
