### PR TITLE
Issue #3261704 by agami4: Improve expand icon position in RTL mode

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The expand icon overlaps the text on the card block

## Solution
Change the position of the expand icon from right to left.

## Issue tracker
https://www.drupal.org/project/social/issues/3261704
https://getopensocial.atlassian.net/browse/YANG-7029

## How to test
*For example*
- [x] Enable `Arabic` interface language.
- [x] Go to the `user/{user_id}/edit` page.

## Screenshots
before:
image-20220126-122928

after:
Screenshot 2022-02-01 at 16 26 32

## Release notes
The expand icon has the right position if we use the `Arabic` language as an interface language(RTL Mode).

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2732-m6b7wfv0ctzk6jsyqyveam3zuh9bfhis.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f944def8ba3c5cfa11edbf

**Comment by agami4** [comment]
@Ressinel, I've changed the position of the expand icon from right to left I did not work on behavior.

**Comment by Ressinel** [comment]
@agami4 I see that these changes are not affected arrow behavior since I see that issue on other envs as well.

**Review by Ressinel — APPROVED** [review]
Looks good to me.

**Review by ribel — APPROVED** [review]
Thanks for the review @Ressinel!
LGTM as well.
I will merge it then.

**Comment by ribel** [comment]
🍒 picked to 11.0.x

**Pull request merged**
