### PR TITLE
Issue #3403980: Add default media teaser view mode

### PR DESCRIPTION
**Pull request by zanvidmar**
Add default media teaser view mode to Social Media System module

At the moment, uninstall hook is missing, and this will be fixed by FUP: [3404301](https://www.drupal.org/project/social/issues/3404301) 

## Problem
We need a default media teaser view mode in Social Media System so it can be reused.

## Solution
Add default media teaser view mode to Social Media System module

## Issue tracker
[3403980](https://www.drupal.org/project/social/issues/3403980)

## Theme issue tracker
N/A

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Add default media teaser view mode

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3620-rvi7eacaimxncw7jvr7y8ynphhkg5jwd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656088e75d2bde9a88856297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3620-rvi7eacaimxncw7jvr7y8ynphhkg5jwd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656088e75d2bde9a88856297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3620-rvi7eacaimxncw7jvr7y8ynphhkg5jwd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656088e75d2bde9a88856297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3620-rvi7eacaimxncw7jvr7y8ynphhkg5jwd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656088e75d2bde9a88856297

**Review by tbsiqueira — APPROVED** [review]

**Comment by tbsiqueira** [comment]
Please make sure to add follow-ups to create the proper hook uninstalls. Besides that, approved.

**Comment by zanvidmar** [comment]
🍒  Cherry-picked to 12.x here: [8a2c7feb7](https://github.com/goalgorilla/open_social/commit/8a2c7feb74e7d7cd4fe9734373efc4461170f398)

**Pull request merged**
