### PR TITLE
Issue #3418595: Replace post entity collection with views and show newest posts first

### PR DESCRIPTION
**Pull request by VBaldych**
## Problem
The post overview `/admin/content/post` is ordered by oldest first.
This is inconsistent with our other overviews and it is not very handy for site managers.

- As a SM I want to see the latest post first
- Column name “Operations”is renamed “Actions”
- Status options are capital “published” → “Published” , “unpublished” → “Unpublished”

## Solution
The `/admin/content/post` page is an entity collection. So, we need to create a view and use it instead to add any customization.

## Issue tracker
 - https://getopensocial.atlassian.net/browse/PROD-27190
 - https://www.drupal.org/project/social/issues/3418595
 - https://github.com/goalgorilla/cablecar/pull/1065

## Theme issue tracker
n/a

## How to test
- [ ] Login as SM
- [ ] Create a few posts (**/post/add**) (already exist on ECI Demo test env)
- [ ] Go to **/admin/content/post** page
- [ ] The column “Operations” should have the name “Actions”
- [ ] Status options should start with capital: “published” → “Published” , “unpublished” → “Unpublished”

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
Change default order in the post overview to show the newest first.
Also added ability to sort by other columns.

### CODE REVIEW

**Comment by VBaldych** [comment]
Tugboat can't create test env because there is an error:
image

**Comment by VBaldych** [comment]
I changed the code in hook_update, but we still have issue with Tugboat

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3735-uzlwcvt4blqiw7kuyfnqy8czl6fhijzy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c37e2b98b7dc1049b243a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3735-uzlwcvt4blqiw7kuyfnqy8czl6fhijzy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c37e2b98b7dc1049b243a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3735-uzlwcvt4blqiw7kuyfnqy8czl6fhijzy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c37e2b98b7dc1049b243a4

**Review by ribel — APPROVED** [review]
Changes were tested both on new installation and existing env and works as expected.
image

**Comment by ribel** [comment]
🍒 picked to the 12.2.x

**Pull request merged**
