### PR TITLE
Issue #3214317 by nkoporec: As a site manager I want to preview the alternative frontpage for anonymous users

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem

I have set /welcome as the alternative frontpage for anonymous users. I named this page "Public Homepage." When I go to content overview as the site manager and click on "Public Homepage," it takes me to /home instead of /welcome. As a site manager, I should be able to see that page, even though it is not the homepage for users who are signed in.

## Solution

If the user is a site manager, then don't perform the redirect to authenticated page, but instead show the anonymous page with a message that this page redirects.

## Issue tracker
https://www.drupal.org/project/social/issues/3214317

## How to test

1. Install alternative_frontpage
2. Go to /admin/config/alternative_frontpage
3. Set different front page for anonymous and authenticated users and save.
4. When logged in, try to go to the anonymous front page

## Screenshots
Screenshot from 2021-05-17 12-46-16

## Translations

1. `This page is redirected to @url_link, but we deferred the redirect to give you an opportunity to edit the content.`

### CODE REVIEW

**Review by nachosalvador — APPROVED** [review]

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2337-vdn2bygctylbr9veaezflo0z519lhmti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d0f1c17bbe0bab79d4f8

**Comment by navneet0693** [comment]
@robertragas Is it a good idea of keeping this in mind: https://github.com/goalgorilla/open_social/pull/1718 and developing either both together or at least build a base of making both features compatible?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2337-vdn2bygctylbr9veaezflo0z519lhmti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d0f1c17bbe0bab79d4f8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2337-crfeiuhb4v5upk5jk7kdggrtji4dyv2m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611a386b331d46209e6134b8

**Review by nachosalvador — APPROVED** [review]

**Comment by bramtenhove** [comment]
I noticed this one did not have a milestone. I believe 10.3.0 is the correct one.

**Pull request merged**
