### PR TITLE
Issue #3276434 by v.koval: Add condition if all day is activated and current date is equal to the end date

### PR DESCRIPTION
**Pull request by Kovalskiy266**
## Problem
Currently, when all day checkbox is activated and the start date and end date are the same for example today, then the event is passed.

## Solution
Add condition in SocialEventTrait.php - if the all-day checkbox is activated and the end date is equal to the current date then the event is ongoing.

## Issue tracker
https://www.drupal.org/project/social/issues/3276434

## Theme issue tracker
N/A

## How to test
- [ ] As a site manager
- [ ] Go to `node/add/event`
- [ ] Fill in the title field
- [ ] Fill in the description field
- [ ] Activate all day field
- [ ] Set today's date in start date field
- [ ] Set today's date in end date field
- [ ] Fill Address field
- [ ] Save the node
- [ ] Go to event page
- [ ] Take a look on the right side of page
- [ ]  Expect the active button "Enroll" instead of "Event has passed" text

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Comment by BiaInacio** [comment]
Change looks good!
image

PS: Great and detailed "How to test" steps, well done! 😄

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3463-czi7cpitnsbhq444xcetno8ic2s2lmum.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64b0163265d7012a0be1047d

**Review by tbsiqueira — APPROVED** [review]

**Review by ribel — APPROVED** [review]

**Pull request merged**
