### PR TITLE
Issue #3413392: Replace md5 hash with random_bytes

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
Automated security scanning tools report on md5 usage. In these cases it's a false positive, but there's some small room for improvement.

## Solution
Replace the md5 hashes with an alternative, PHP's built-in `random_bytes()` which we use in combination with bin2hex to generate a unique 16 character string.

## Issue tracker
https://www.drupal.org/project/social/issues/3413392

## Theme issue tracker
N/a

## How to test
- [ ] Run a user export
- [ ] Run an event enrolments export
- [ ] Run an group member export
- [ ] See that you can download the CSV export files
- [ ] Observe that the filenames contain unique IDs

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/a

## Release notes
Minor code improvement replacing MD5 usage to reduce false positives for automated security scanning tools.

## Change Record
N/a

## Translations
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Review by Kingdutch — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3688-uw2kisbjicmb2nkg4tsyf9b41g9zgxak.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659d19e474571787f7e622f3

**Comment by ronaldtebrake** [comment]
Cherry picked to 12.0.x and 12.1.x

**Pull request merged**
