### PR TITLE
Issue #3340197: Replace default profile image config override with settings

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
In https://github.com/goalgorilla/open_social/pull/394 we originally made the private file system opt-in. However, we recommend that everyone installs this and from a security perspective it's an important part of how Open Social works. Additionally the config overrides were causing some problems because changing the uri_schema for an image field has side-effects when done through the entity, but those side-effects are not properly applied when done through a config override.

When these side-effects are not applied we see hard to debug bugs like a missing default profile image. The suspicion is that the field config save is triggered with config that doesn't match the override, which causes the underlying image to be moved and the default image URI to be updated, however we've only been able to manually reproduce this by saving the FieldConfig item in code and then resetting the database (breaking the field image link).

## Solution
This commit removes the config override services and instead just updates the configuration directly. We do this in an update hook so that the config is applied for everyone that has the module enabled.

Additionally we apply the private uri_schema in all of our default shipped config so that new installations will use the private file system by default without enabling the social_file_private module. With this in mind we remove the social_file_private as an optional module for new installations since it doesn't do anything anymore.

However, we do still include a `hook_install` implementation for any sites who update from an earlier version and want to opt-in the private files but did not yet enable the `social_file_private` module.

 
 We also make a change in the `social_profile` module in how we add
 the default image to our profile picture in the first place. Here too we
 start using the FieldConfig rather than the config directly. We also
 set the UUID to what is in the configuration rather than hardcoding it
 so that if we ever change the config it'll still work.

Finally we ensure the Open Social can not be installed without the
private file system enabled as this would cause errors during the
installation. We prevent installation with a more helpful error message
that points users to a way of fixing the problem.

Install will now fail with an error if the private file system is not configured
image
> Private File System:Not configured
>
> The private file system must be configured for Open Social to install. You may opt-out of the private file system for individual fields after installation. See https://www.drupal.org/documentation/modules/file for how to set the file_private_path in your settings.php. 

## Issue tracker
https://www.drupal.org/project/social/issues/3340197

This also fixes https://www.drupal.org/project/social/issues/2978581 by adding the core patch, test coverage is added to #2478 which has proved the patch works, but the effects are already noticeable in this PR.

## How to test
**Installation requirement**
- [ ] Install Open Social from scratch without configuring the private file system
- [ ] See installation is blocked

**File system is configured causes successful install**
- [ ] Configure the private file system
- [ ] Install Open Social as normal
- [ ] See that the default profile image is correctly served from the private file system

**Private file system as optional module**
- [ ] The private file system should no longer be available as optional module during installation

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
The private file system is now opt-out for new installations and is required to install Open Social. The `social_file_private` no longer uses config overrides but instead applies the updates to the configuration directly. The `social_file_private` module is deprecated and will automatically uninstall in 12.0.0 and be removed in 13.0.0.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-ohgckc1alzenvq7b5seplj1st8oxslqh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e37378e39b3d510ec24cb2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3306-leoythyy22pkafnhcxnul1x6pswodmln.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63eb4b777ec932727590e71c

**Review by tbsiqueira — APPROVED** [review]

**Comment by bramtenhove** [comment]
@tbsiqueira @Kingdutch what does this change do for modules developed outside of Open Social? They will have to opt-in themselves to the private filesystem I assume?

**Comment by Kingdutch** [comment]
@bramtenhove That never changed. The config override we replaced already had a list of field names and didn't do anything dynamically. So we literally just moved config from an override into the install config files (and active config using a hook update), which allows others to change it if they so desire.

**Pull request merged**
