### PR TITLE
Issue #3408496 - Make sure our flagging has the correct arguments otherwise it will break profile teasers for AN.

### PR DESCRIPTION
**Pull request by robertragas**
This is a follow-up as we did not fix this on all places yet.
Original issue: https://www.drupal.org/node/3355315

## Problem
Our socialFollowUser checks all flags for the current user, however, for AN the flag service requires a session id as per:
[https://git.drupalcode.org/project/flag/-/commit/497e170c267780dc314e0f0...](https://git.drupalcode.org/project/flag/-/commit/497e170c267780dc314e0f0ed5962ad5d89dfee7#b6b1c3c70255325ebedd7af4aceb1639bd19829b_129_180)

If not provided, it will trigger the Exception.

## Solution
In our case we can use the same $this->flagService->getAnonymousSessionId to make sure it returns NULL if the user is logged in or provide a/the session ID for AN.

## Issue tracker
https://www.drupal.org/project/social/issues/3408496

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Enable social_follow_user
- [ ] Create a flexible group with public permissions, add at least 1 member to it
- [ ] As anonymous go to the group page and navigate to the members tab
- [ ] See it crashes
- [ ] Go to this branch and try again

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We have fixed an issue where going to the members tab in public groups would result in a page crash.

### CODE REVIEW

**Review by vcsvinicius — APPROVED** [review]
@robertragas I approved this PR

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3644-mgwcltqliuvu6ccxbngmf85wqvbwrbax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579cfc0ecba8e86979d3b3a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3644-mgwcltqliuvu6ccxbngmf85wqvbwrbax.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579cfc0ecba8e86979d3b3a

**Comment by ronaldtebrake** [comment]
Considering a pair review and test has happened I think we can merge this, will also cherry pick to 12.0.x

**Pull request merged**
