### PR TITLE
Issue #3345541 by chmez: Group reference field support only nodes

### PR DESCRIPTION
**Pull request by ghost**
## Problem
A field which is used for creating a relation between groups and other content entity types does not check the entity type of the processed entity and always expects that it will be a node.

## Solution
Define a content plugin based on the entity type.

## Issue tracker
- https://www.drupal.org/project/social/issues/3345541
- https://getopensocial.atlassian.net/browse/PROD-24199

## How to test
- [ ] Repeat the first 4 steps from [here](https://www.drupal.org/project/social/issues/3315177).
- [ ] Create a media entity in the group.
- [ ] When you open created entity edit page, you should see the same group in the "Group" field selected while creating this media entity.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Review by ribel — APPROVED** [review]
LGTM.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3329-sql80x5kqtfyltvwhowsvz9xabez6yad.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6400d64ca151c3649c741a8c

**Review by nkoporec — APPROVED** [review]
LGTM

**Comment by nkoporec** [comment]
:cherries:  picked to 11.8.x

**Pull request merged**
