### PR TITLE
Issue #3326796 by chmez: Home stream filter for any entity type

### PR DESCRIPTION
**Pull request by ghost**
## Problem
The "activity_filter_personalised_homepage" Views filter which is used for the home stream supports only the following entity types: node, post, and comment.

## Solution
Add a new method (the "alter" method) to a class of this filter where new conditions can be added to conditions set based on entity types.

## Issue tracker
- https://www.drupal.org/project/social/issues/3326796
- https://getopensocial.atlassian.net/browse/PROD-22434

## How to test
- [ ] Create group content based on the media entity type.
- [ ] Create a filter plugin instance based on someone who is changed here and use a new method for adding support of group content in the query.
- [ ] Replace the changed filter with the created filter for Views view of the stream.
- [ ] When you create a message template for created group content then you should see notifications related to media type on the changed stream.

## Release notes
Support any entity type by home stream filter.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Review by ribel — APPROVED** [review]
Idea and change looks good to me, it also was tested and works well.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3260-iybfs8ejarrmoudvrvxnetmzx6vs2auc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/639866e4a72d59081875f3ac

**Pull request merged**
