### PR TITLE
Issue #3225497 by Ressinel: Update the Lazy-load module from 2.0 to 3.10

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Lazy-load module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
https://www.drupal.org/project/social/issues/3225497

## How to test
Before test need to ensure that we exactly don't need patches that were added by this [PR](https://github.com/goalgorilla/open_social/pull/1466). 
Necessary @ronaldtebrake consultation 😀
- [ ] Enable modules `social_lazy_loading` and `social_lazy_loading_images`
- [ ] Make additional settings if need on this page `/admin/config/content/lazy`
- [ ] Lazy loading functionality must work properly

## Screenshots
N/A

## Release notes
The Lazy-load module has been updated to 3.10. Please view the release notes from [3.x-dev](https://www.drupal.org/project/lazy/releases/8.x-3.x-dev), [3.0-beta1](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta1), [3.0-beta2](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta2), [3.0-beta3](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta3), [3.0-beta4](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta4), [3.0-beta5](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta5), [3.0-beta6](https://www.drupal.org/project/lazy/releases/8.x-3.0-beta6), [3.0](https://www.drupal.org/project/lazy/releases/8.x-3.0), [3.1](https://www.drupal.org/project/lazy/releases/8.x-3.1), [3.2](https://www.drupal.org/project/lazy/releases/8.x-3.2), [3.3](https://www.drupal.org/project/lazy/releases/8.x-3.3), [3.4](https://www.drupal.org/project/lazy/releases/8.x-3.4), [3.5](https://www.drupal.org/project/lazy/releases/8.x-3.5), [3.6](https://www.drupal.org/project/lazy/releases/8.x-3.6), [3.7](https://www.drupal.org/project/lazy/releases/8.x-3.7), [3.8](https://www.drupal.org/project/lazy/releases/8.x-3.8), [3.9](https://www.drupal.org/project/lazy/releases/8.x-3.9), and [3.10](https://www.drupal.org/project/lazy/releases/8.x-3.10) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2444-fkapxsnvlkcbnxpqujq4df7fn35lqacq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/610016ad742468364a68b327

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2444-fkapxsnvlkcbnxpqujq4df7fn35lqacq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/610016ad742468364a68b327

**Review by navneet0693 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2444-fkapxsnvlkcbnxpqujq4df7fn35lqacq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/610016ad742468364a68b327

**Comment by ronaldtebrake** [comment]
Did we check - https://www.drupal.org/node/3173719 ? 
Maybe the dependency to lazy is redundant and we can benefit from the Core update here :D

**Comment by navneet0693** [comment]
Oh yes, you are right! @ronaldtebrake, shall we open a follow-up or simply remove the module?

**Comment by ronaldtebrake** [comment]
A follow up would be nice @navneet0693, if we then still have time we can phase it out before 11.0.0, if we don't we can do it for 12.0.0! :)

**Comment by Kingdutch** [comment]
Hey @Ressinel @navneet0693, and @ronaldtebrake ,

Just a reminder that Bower is unreliable in its availability of packages which causes issues for developers and CI. In https://github.com/goalgorilla/open_social/pull/2082 we switched everything over to NPM.

In https://github.com/goalgorilla/open_social/commit/60e3d6b8d00ae0d72640c5f38399abeb853ae89e I've done the same for the package introduced in this PR. 

In the future when adding front-end packages, please use `npm-asset` and do not use `bower-asset` (prefer a different package altogether if one is only available on bower, since then it's probably too old to use).

Cheers!

**Pull request merged**
