### PR TITLE
Issue #3224631 by navneet0693: Removed config override from social_group_welcome_message module.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Remove configuration override class from Social Group Welcome Message module.

## Solution
1. Delete the class and service file
2. Add the changes to form alter

## Issue tracker
https://www.drupal.org/project/social/issues/3224631

## How to test
*On OpenSocial 10.3.x with this module enabled*
- [ ] Create few groups of type closed, open, public, secret, and flexible with welcome message enabled.
- [ ] Checkout to this branch.
- [ ] Clear cache
- [ ] Check if already existing functionality is still working.
- [ ] Repeat the steps and see everything works.

*On OpenSocial 10.3.x with this module not enabled*
- [ ] Checkout to this branch.
- [ ] Enabled this module.
- [ ] Create few groups of type closed, open, public, secret, and flexible with welcome message enabled.
- [ ] Check if already existing functionality is still working.

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2427-og8qpuwlso16bjuqhnsoiqboskect3rb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f7e17f00f236802d114024

**Review by Ressinel — APPROVED** [review]
I have tested with all groups types: closed, open, public, secret, and flexible. And for me, functionality works properly.

**Comment by Ressinel** [comment]
@navneet0693 

The first case in the "How to test" section:
I receive this error after the cache clear, but only once, after the next cache clear I have no this error:

cache-clear-error
Although functionality works properly.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2427-og8qpuwlso16bjuqhnsoiqboskect3rb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f7e17f00f236802d114024

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2427-og8qpuwlso16bjuqhnsoiqboskect3rb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f7e17f00f236802d114024

**Comment by navneet0693** [comment]
🍒  - picked to 10.2.x, 10.1.x and 10.0.x

**Pull request merged**
