### PR TITLE
Issue #3280070 by ronaldtebrake: remove our custom fork and move to contrib ginvite module

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
In Open Social versions 10.x we still used a patch to add the `ginvite` module to our distribution.
https://github.com/goalgorilla/open_social/blob/10.0.x/composer.json#L66

Whilst working on D9 compatibility we noticed how hard it is to maintain that patch.
Any work done in making it D9 compatible resulted in us having to update patches making it harder to do our automated code checks. That is when we decided to fork the patch in to a custom module within our Open Social repository as you can see in the 11.x versions
https://github.com/goalgorilla/open_social/tree/main/modules/custom/ginvite

Luckily, there has been an effort in to making this a contrib module as you can see here: https://www.drupal.org/project/ginvite

This task is there for us to move to the contrib module, so we can help our efforts in making the ecosystem better rather than having to update our fork.

## Solution
1. Remove `custom/ginvite` fork
2. Add `drupal/ginvite` to our composer.json

We are using `drupal/ginvite` 1.1 as this closely matches the state of the fork. This should ensure we are backwards compatible. After this is merged, we can decide to upgrade `drupal/ginvite` as well, but that might break BC so lets leave the impact as low as possible.

You can see a diff between the Drupal module and the custom fork in our distribution attached, that should hopefully indicate how small the actual step is.

Screenshot 2022-05-12 at 13 38 58

## Issue tracker
https://www.drupal.org/project/social/issues/3280070

## How to test
- [x] Before checking out, add some invites to a group, with different status (pending / accepted etc.)
- [x] Update to this branch
- [x] See that it still works as expected

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We are now using the Drupal based ginvite module instead of our own, so we can help the Drupal & Group ecosystem with any additional efforts in maintenance.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2929-haylubzdflza5qfqudkn37zuzwlvw3zz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/627cecbd0f15004d8efcf664

**Review by Ressinel — APPROVED** [review]
I have tried steps from HTT sections and it works properly for me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2929-haylubzdflza5qfqudkn37zuzwlvw3zz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627cecbd0f15004d8efcf664

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2929-haylubzdflza5qfqudkn37zuzwlvw3zz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/627cecbd0f15004d8efcf664

**Pull request merged**
