### PR TITLE
Issue #3157094 and #3232246 by Kingdutch: Fix Message entity handling in activity system

### PR DESCRIPTION
**Pull request by Kingdutch**
## Review Guideline
This PR contains 14 commits but only two are actually unique which is 50c615dc0ae96d95354e9e2a73e6e5faad1c66f7 and f7a8a06b496b1fa1de3948e235e08e58bb0b036e (the first and last commit). All commits in between are updates to configuration which should be checked as follow:

Check that the commit for the message template(s) it modifies contains 
- `field_message_context`
- `field_message_destination`
- `field_message_related_object`

For each of those three fields check that the following properties are updated to contain the template's id:
- `dependencies.config`
- `id`
- `bundle`

## Problem
It was discovered while working on #3282 that message fields were being created at runtime, that solution was added in #150. However, there were also code paths that tried to access fields before this code had run.

This code is brittle and we should really be creating the necessary fields at install time.

## Solution
This PR solves two issues:

1. It prevents treating all message inserts as being part of the activity system by checking the fields we need exist on the message entity in the _insert hook. This allows the message entity to be used for non-activity purposes.
2. It no longer automatically creates config fields during content creation but instead asserts that they're present. This also ensures we catch the problem but forces developers to deal with it by flagging it in tests and development.

## Issue tracker
https://www.drupal.org/project/social/issues/3157094
https://www.drupal.org/project/social/issues/3232246

## How to test
- [ ] Create a site-install without demo content
- [ ] Create content that triggers notifications, this should now work for all notifications

I've assumed that all notifications that we have were covered by test coverage.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Open Social no longer errors when a Message entity is created outside of the activity system. Message entities are no longer modified when incompatible with the activity system, an error will be thrown instead and the developer should provide the necessary fields.

## Change Record
[Notification message templates should now also create the `field_message_context`, `field_message_destination` and `field_message_related_object` fields](https://www.drupal.org/node/3333024)

## Milestone
I believe we can put this in a minor version. The config for a new install has been added based on our test coverage. Additionally we add an update hook to create the fields for any message templates that currently exist (even if no notification has been sent yet). The service method has been deprecated for major version removal but is still available.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by Kingdutch** [comment]
Tugboat has tested that this update hook runs without error
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3285-62d5q5gxuuuwj9g6wz655xn7i0w7xw7q.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c029a25804da46dbaa5107

**Review by tbsiqueira — APPROVED** [review]

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.7.x with `git cherry-pick 547339e4432b5a1f9d188708340757ab3c213a9b^..11c4e1342729d6602a7bcace0c0e2846df24b34e`

**Pull request merged**
