### PR TITLE
Issue #3092272 by Kingdutch, ronaldtebrake, sjoerdvandervis, navneet0693, albertoalaejos: [Meta] Moving away from features

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
Features causes many issues for us (see ticket)

## Solution
Remove features

## Issue tracker
https://www.drupal.org/project/social/issues/3092272

## How to test
- [ ] Updates from 7.1 should succeed
- [ ] Fresh install on 8.0 should succeed

## Release notes
<describe the release notes>

## Change Record
https://www.drupal.org/node/3109459

### CODE REVIEW

**Comment by Kingdutch** [comment]
Here is the diff for the changes that were made in the installation process for optional modules.

https://github.com/goalgorilla/open_social/compare/d794c3d4312198f16aafd9425aa662505c2cf2cc...07ece1ead49006b114b143b8f85f88fb5dd22d3d

**Comment by Kingdutch** [comment]
The next batch of changes that you can review contains fixes for the configuration that will be installed as well as some install hooks: https://github.com/goalgorilla/open_social/compare/333e77fe6e90d7e22c01abe338ae844132676ab5...35d0eda98494316a7632b678b97622f338de38c7

The first commit in the series also makes some path/namespace changes to the install form to streamline that addition.

**Comment by Kingdutch** [comment]
Looks like we're all green and good to go! Just need to test locally whether the installation still works with all optional modules enabled. This is the diff of the last few commits: https://github.com/goalgorilla/open_social/compare/0077bc0...ebaf215

**Comment by ronaldtebrake** [comment]
Nice work @Kingdutch 
I have reviewed all the diffs as well now and seems good to go. 
Will try to do some more testing on my local install before merging but the code is approved already :D

**Comment by Kingdutch** [comment]
@ronaldtebrake I think the last 4 commits should just be reviewed individually.

The last commit (votingapi patch) can be reviewed in: https://www.drupal.org/project/votingapi/issues/3110353

**Comment by Kingdutch** [comment]
And another patch we can review: https://www.drupal.org/project/entity_reference_revisions/issues/3110377 :D

**Pull request merged**
