### PR TITLE
Issue #3227356 by Ressinel: Remove the unnecessary langcode filter from events enrollments views.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
If the event has langcode `und` not all users can see who enrolled in a certain event on the event details and the /all-enrollments page. For accounts with different languages, it looks as if no one had enrolled in the event, even if that is not the case.

This is a significant issue for us, since seeing other event participants is important information for our users.

- This even persists if the user signs up for the event. It still looks to that user as if no one had signed up, they can not even see their own signup.
- In the "overview card" of an event (in search results, etc.) the number of enrollees is correctly displayed next to the icon.

## Solution
Remove the unnecessary langcode filter from events enrollments views.

## Issue tracker
- https://www.drupal.org/project/social/issues/3227356
- https://getopensocial.atlassian.net/browse/TB-6023

## How to test
- [ ] Ensure that you have at least two languages on a site
- [ ] Create an event
- [ ] Add enrollments with different languages to created event
- [ ] All enrollments who were added have to see a list of enrollments on the event details and the /all-enrollments page

## Screenshots
N/A

## Release notes
Fixes issue when only LU with default site language can see who enrolled in a certain event.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by ronaldtebrake** [comment]
Seems to work like a charm @Ressinel, nice work :) 

Would be grateful if you could still do the following:
1. Write this story looking at it from a Distro perspective, so instead of saying German/French, what is the problem & what are we fixing for multilingual users?
2. Could you maybe see if you can lock it in a test? We already have something for the multi language test, maybe we can add a scenario to it, we don't want to have this in the future anymore.
3. Update the PR information.

Thanks 🚀

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Review by navneet0693 — CHANGES_REQUESTED** [review]
Please also include the original configuration files.

**Comment by Ressinel** [comment]
> Please also include the original configuration files.

@navneet0693 Thanks for reminding me of it. I've done it.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
@nechai Just for your information, that this PR is reverting some of the work done in https://github.com/goalgorilla/open_social/pull/2379. Please check this PR and let @Ressinel know if you see some issues/concerns.

**Comment by nechai** [comment]
@navneet0693 Thanks for the update. Yes, I had a conversation with @Ressinel before and we agreed that some changes from #2379 should be reverted.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2458-tuvf3q5v5x1r5sk0bp7j5h8zirtzteyr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61113947378c5f598c7ab111

**Comment by navneet0693** [comment]
🍒 -pick to 10.3.x

**Pull request merged**
