### PR TITLE
Issue #3340698 - Follow user still in menu even when not active

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
In Open Social there is an option to follow users with the social_follow_user module. When enabled it also has the option to be disabled on admin/config/opensocial/follow-user.
Follow user setting
Screenshot 2023-02-09 at 22 33 04

But when disabled it will still show the options on the user profile menu (user/x/stream).
User profile menu
Screenshot 2023-02-09 at 22 31 37

## Solution
Remove the permissions that control the view behind the links so the menu links will also disappear.

## Issue tracker
https://www.drupal.org/project/social/issues/3340698

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Enable social_follow_user
- [ ] Disable the follow user on the admin page admin/config/opensocial/follow-user.
- [ ]  Go to a user profile (user/x/stream)
- [ ]  See in the menu it still has the links following and followers
- [ ] Check out to this branch and try again to see it's fixed.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
An issue is fixed where the user profile menu link would show followers information even when the feature is disabled. 

Screenshot 2023-02-09 at 22 31 37

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3311-vvt0thcxaicvqluhaj3o4x7pyrd0qi2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e576c0d9bec500529dd1e6

**Comment by robertragas** [comment]
Kept it on 11.7 to avoid issues with update hook.

**Pull request merged**
