### PR TITLE
Issue #3224268 by Ressinel: Update the Block field module from 1.0-alpha8 to 1.0-rc1

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Block field module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3224268

## How to test
N/A

## Screenshots
N/A

## Release notes
The Block field module has been updated to 1.0-rc1. Please view the release notes for [1.0-rc1](https://www.drupal.org/project/block_field/releases/8.x-1.0-rc1) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2421-0eei9vcotzq80nueu78ogtrqfhid2fzd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f589c700f236fa310f9337

**Comment by ronaldtebrake** [comment]
Looks good to me! I've checked landing pages mainly.

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Once travis is green we can merge away :D 🚀

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2421-0eei9vcotzq80nueu78ogtrqfhid2fzd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f589c700f236fa310f9337

**Comment by ronaldtebrake** [comment]
Tests indicate there is something we need to update in our plugins, so maybe it's not backwards compatible and might need to move to 11.0.0 for that

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2421-0eei9vcotzq80nueu78ogtrqfhid2fzd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f589c700f236fa310f9337

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2421-0eei9vcotzq80nueu78ogtrqfhid2fzd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f589c700f236fa310f9337

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2421-0eei9vcotzq80nueu78ogtrqfhid2fzd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f589c700f236fa310f9337

**Review by navneet0693 — APPROVED** [review]

**Pull request merged**
