### PR TITLE
Issue #3208582 by ronaldtebrake: As a LU when editing a flexible group I want my chosen join method settings to be respected 

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When I create a flexible group and choose group visibility, content visibility and join methods all works well.
Whenever I edit that group, the join method automatically jumps to the "request to enroll" without the user selecting it, it seems the Drupal states are all wrong.

## Solution
Remove the states logic and redo everything with javascript.

## Issue tracker
https://www.drupal.org/project/social/issues/3208582
https://www.drupal.org/project/social/issues/3204470

## How to test
1. Create a flexible group with everything set to Public
2. Edit that group and see it switches the join method to "request to enroll"

### CODE REVIEW

**Review by nachosalvador — APPROVED** [review]

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by robertragas** [comment]
Still needs a bit of work as we can see a test failing. Since we removed the states, it doesn't automatically set a join method value.

Screen Shot 2021-09-30 at 9 48 00 AM

**Comment by nkoporec** [comment]
@robertragas This is ready for another review.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-ef6lve4xc8rcaippfboejmxmgoalpojf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d118f3ee30814ff0c692

**Comment by nachosalvador** [comment]
Hey @nkoporec I just reviewed it again with the last 10.3.x version and I see the same behavior as @robertragas [commented](https://github.com/goalgorilla/open_social/pull/2310#issuecomment-930960233)
Screenshot at 2021-11-24 11-03-55
:

**Review by nachosalvador — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2310-odptqycubmfbdyc8x8lf5h968sy4yx2o.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b76e377499db652291e216

**Comment by navneet0693** [comment]
🍒 -picked to 11.0.x, 10.3.x, 10.2.x, 10.1.x

**Pull request merged**
