### PR TITLE
Compressed social_demo images 

### PR DESCRIPTION
**Pull request by truls1502**

### CODE REVIEW

**Comment by jaapjan** [comment]
@truls1502  Just wondering what should we do with this PR? I see Travis is failing as well.

**Comment by truls1502** [comment]
@jaapjan I have restarted the Travis tests. Maybe it is a false negative?

Error result was:
```
--- Failed scenarios:
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/contentmanagement/node-visibility.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/event/all-day-timezone.feature:8
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/event/event-create.feature:8
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/group/group-access-roles.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/group/group-create-closed.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/group/group-create-open.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/group/group-create-public.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/post/post-create.feature:7
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/profile/edit-profile.feature:8
    /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/profile/hide-profile-fields.feature:7
```

**Comment by truls1502** [comment]
Hi again, @jaapjan! It looks Travis test passed now 😊

**Comment by Kingdutch** [comment]
Hi @truls1502 ,

Given that binary images don't compress too well, could you give some info about the steps you took to get to the compressed images? 🙂

**Comment by truls1502** [comment]
@Kingdutch: I used https://compressor.io to compress the image size. For our Drupal sites, it has saved a lot of storage and performance time.

**Comment by jaapjan** [comment]
Good idea @truls1502 ! I'll merge it 🚀

**Comment by jaapjan** [comment]
Also cherry-picked to 5.x branch.

**Comment by truls1502** [comment]
No problem @jaapjan - Let me know if there are more images that I can compress too?

**Pull request merged**
