### PR TITLE
Issue #3262831: Remove deprecated Group hero setttings.

### PR DESCRIPTION
**Pull request by NickDaelemans**
## Problem
Since the Group hero size is not supported anymore we have to remove the setting entirely.

## Solution
* Remove the setting from the Group settings form at /admin/config/opensocial/social-group and all of it's references in code.
* Remove the Small hero crop type for group hero images.

## Issue tracker
https://www.drupal.org/project/social/issues/3262831
https://getopensocial.atlassian.net/browse/DE-665

## How to test
- [ ] Go to the /admin/config/opensocial/social-group settings page
- [ ] Notice that the hero size select option is gone.
- [ ] Go to a group that has a hero image
- [ ] See the hero image in the large format.
- [ ] Edit the group and see that the Small hero crop type is gone.

## Release notes
The deprecated functionality of the small hero image size is now unable to select. We deleted the settings and the crop types for hero images.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2743-e8fjvekspyppilafpcgljxgg1kpf71au.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6200e96800c7e8a758437317

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2743-e8fjvekspyppilafpcgljxgg1kpf71au.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6200e96800c7e8a758437317

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2743-e8fjvekspyppilafpcgljxgg1kpf71au.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6200e96800c7e8a758437317

**Review by nkoporec — APPROVED** [review]
Looks good 👍  Can you create a separate PR for the 11.x branch ?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2743-e8fjvekspyppilafpcgljxgg1kpf71au.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6200e96800c7e8a758437317

**Pull request merged**
