### PR TITLE
Issue #3415933: Improve Behat test step for groups

### PR DESCRIPTION
**Pull request by zanvidmar**
Improve Behat test step in a way that group with multiple "Group content visibility options" can be created

## Problem
At the moment it is only possible to set singe value for "Group content visibility options" with "@Given groups:"
```
Given groups:
  | author | title    | description     | author   | type        | language | field_group_allowed_visibility
  | user-1 | My title | My description  | username | open_group  | en       | public
  | ...    | ...      | ...             | ...      | ...         | ...      | ...
```
 
[Screenshot](https://www.drupal.org/files/issues/2024-01-19/Screenshot%202024-01-19%20at%2018.45.01.png)

## Solution
Improve Behat test step in a way that group with multiple "Group content visibility options" can be created

Example:

```
Given groups:
  | author | title    | description     | author   | type        | language | field_group_allowed_visibility
  | user-1 | My title | My description  | username | open_group  | en       | public,community,group
  | ...    | ...      | ...             | ...      | ...         | ...      | ...
```

## Issue tracker
[3415933](https://www.drupal.org/project/social/issues/3415933)

## Theme issue tracker
N/A

## How to test
- [ ] Create new Behat test using "@Given groups:" step and confirm they works as designed

Example:
```
    Given groups:
      | author | label   | type           | field_flexible_group_visibility | field_group_allowed_visibility | field_group_allowed_join_method |
      | admin  | Group A | flexible_group | public                          | public,community,group         | added                           |
```

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Behat test step has been improved in a way that group with multiple "Group content visibility options" can be created

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3712-b4hb65pyjijo09o1ohp6rofkrapazuxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65aab86d82e119e53ead2297

**Comment by zanvidmar** [comment]
🍒 Cherry-picked to 12.x here: [2b82b677b](https://github.com/goalgorilla/open_social/commit/2b82b677b61bee4a94d1b1831b543049100dd031)

**Comment by zanvidmar** [comment]
It seems like that new bug was introduced and we did not spotted it before it was merged:
https://github.com/goalgorilla/open_social/actions/runs/7640714360/job/20819341498#step:4:265

**Comment by ronaldtebrake** [comment]
Also in 12.1.x 🍒

**Pull request merged**
