### PR TITLE
Issue #3305919 by nkoporec: User does not receive email notification when added directly to a event

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When a person is directly added to a event, they do not receive a notification via email.

## Solution
 There is a message template ` member_added_by_event_organiser` that should be sent to the user, but this never happens. The issue is that in `ActivitySendEmailJobType.php `we always check if the recipient has access to the entity, before sending out an email. This is not the case, when adding users directly to the event, since the owner of the event enrollment is not the recipient but the event manager, so the condition evaluates to false

We need to allow view access to event enrollment entity if the user is a recipient, since it make sense that the user has access to its own event enrollment.

## Issue tracker
https://www.drupal.org/project/social/issues/3305919

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Make sure you have emails sending working
2. Create an event
3. Go to the event and click the Manage enrollments tab
4. Open the Add enrollees menu and click the Add directly option
5. Select a random authenticated user to add
7. Run cron 
8. Check if the user received an email that it has been added to the event.

### Before merge
- [x] Code/peer review is completed
- [x] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
Fixed an issue with email sending when adding users directly to the event.

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3078-txfxfnbtvytegodx9rnbbc1gxgdlqdpu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63073161f08423f9ad0f048c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3078-txfxfnbtvytegodx9rnbbc1gxgdlqdpu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63073161f08423f9ad0f048c

**Comment by NickDaelemans** [comment]
@nkoporec I tested this locally, but did not receive any mail when adding the user to an event. I do get other e-mails.

**Comment by NickDaelemans** [comment]
Update; it does work. You have to run cron first to receive the emails.

**Review by NickDaelemans — APPROVED** [review]

**Comment by NickDaelemans** [comment]
This PR was reverted in PR 3079, because of lack of documentation and other remarks. More information on that PR.

**Pull request merged**
