### PR TITLE
Issue #3329802 by navneet0693: Organization tags display doesn't respect current language

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
On multilingual website the organization tags on the profile stream page are displayed in the default language instead of current language. The yellow marker contains the tag name in language which doesn't matches the current language or user's preferred language.

**Steps to reproduce**
1. Install Open Social
2. Enable social content language module and configure more than one languages.
3. Enable social profile organization tags module
4. Add profile tags and also add translations for them
5. Edit a profile and add the organization tag to it
6. Visit the profile.
7. Regardless of the current language selected, the yellow marker tooltip will show the organization tag in default language only.

## Solution
Add conditions to check if the website is multilingual and then fetch the correct translation of term here https://github.com/goalgorilla/open_social/blob/11.1.16/modules/social_features/social_profile/modules/social_profile_organization_tag/social_profile_organization_tag.module#L103

## Issue tracker
https://www.drupal.org/project/social/issues/3329802

## Theme issue tracker
N.A

## How to test
- [ ] Using latest version of Open Social with the social content translations and social profile organization tag module enabled
- [ ] Enable more than one language on the website
- [ ] As a sitemanager
- [ ] Add terms in profile organization tag vocab and translate them
- [ ] Edit a profile or add a profile with one of the organization tag
- [ ] Visit the profile in all the languages configured
- [ ] You should be able to see correct language in yellow marker tooltip.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
**Before**
Screenshot 2022-12-27 at 5 01 07 PM

**After**
Screenshot 2022-12-27 at 5 02 10 PM

## Release notes
The organization tags on the profile were not appearing in correct language on a multilingual website. We did some magic to display them in correct language.

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3271-wngri2qogvmnewrvr94uyfnzyfb8iguf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63aadc2a0645501a1ec746f0

**Review by nkoporec — APPROVED** [review]
Ignore the above message, I was looking at profile tags instead of the organization tags. For organization tags, it works correctly.

**Comment by nkoporec** [comment]
🍒 picked to 11.5.x and 11.6.x

**Pull request merged**
