### PR TITLE
Issue #3397809: Enter key does not work to send a private message

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The "Enter" key does not work after first message was sent in Private Message

## Solution
This error already be fixed before and it should be used the solution before.

## Issue tracker
[#3397809](https://www.drupal.org/project/social/issues/3397809)

Private Message:
[#3397794](https://www.drupal.org/project/private_message/issues/3397794)

## Theme issue tracker
N/A

## How to test
- [ ] Enable the Social Private Message
- [ ] Send a Private Message to any user
- [ ] Go to the Private Message sent before and try to write a message adding break-line with "Enter" key

### Before merge
- [ ] Code/peer review is completed
- [ ] Strings that should be translated are also translatable ( double check Drupal interface translation for the added strings, and they are "[en-ud](https://www.oxfordinternationalenglish.com/differences-in-british-and-american-spelling/)" based ones )
- [ ] The translation server, Weblate, contains the new strings
- [ ] How-to-test is provided (acceptance criteria), modified if needed, and passing
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Hook update numbers should follow `YYxxx` pattern, where `YY` are the last two numbers of the release year
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] Any front-end changes are tested on all major browsers ( Desktop and mobile )
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner
- [ ] On ticket close, fill the RCA ( Root Cause Analysis )
- [ ] All your composer related changes need to be reflected in the [root as well as in the individual](https://open-social.slite.com/app/docs/evp_AlVzdK0dje) extension
- [ ] Jira has all necessary information on comments, if a bug, what was the cause, etc.
- [ ] If applicable please fill the "Drupal.org ticket" field on Jira Ticket

### After merge
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status
- [ ] Add the fix version

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3584-1qvsvvj6f3cnaz780fsx2b24hfwcafu3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65400543c5102c7756a9186a

**Comment by ronaldtebrake** [comment]
Screenshot 2023-11-21 at 18 13 55
[Private Message.webm](https://github.com/goalgorilla/open_social/assets/16667281/09315d0b-e435-433c-b3be-c263fbe006d0)

**Comment by ronaldtebrake** [comment]
nice work! cherry-picked to 12.0.x 🍒

**Pull request merged**
