### PR TITLE
Issue #3253268 by robertragas: change the personalised activity stream query to make sure we filter with the correct group content data

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
When showing the personalized stream block on a page it should show all the content relevant to a person. There are some checks to see if the user has access to nodes but does not work for the usecase when content is not in a group and posted to the community or public.

It will try to make some joins with the group_content_field_data but doesn't take into account that entity_ids are not unique. For example a membership can be entity_id 5 but a topic content can also be entity_id 5. Therefore it can think the content is within a group and remove it from the list and thus missing from the activity stream.

## Solution
Change the query to only contain the content nodes as we don't show invitations or membership in our stream activity.

## Issue tracker
https://www.drupal.org/project/social/issues/3253268

## How to test
It can be hard to reproduce but you would need to have a membership in group_content_field_data with the same entity_id as the content_topic.
- [ ]  Create page with the personalized activity stream block
- [ ] Join a group so it will create a membership entry.
- [ ]  Create a topic without a group and on community
- [ ]  Check the group_content_field_data table that they have the same entity id, otherwise you might to create some extra content to match it up.
- [ ]  Run the cron so it will create the activity items
- [ ]  Log in as admin (who has an exception) and see the content preview
- [ ]  Log in as a LU and see the content preview is missing

## Release notes
We fixed an issue where activity items that were posted outside of a group wouldn't not show up on your personalized activity stream.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2642-4dues1o0o0ylxdla94eszrqzhgiuxaas.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b0a514821ec832cf0bf269

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2642-4dues1o0o0ylxdla94eszrqzhgiuxaas.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b0a514821ec832cf0bf269

**Review by nkoporec — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2642-qaes1uxzawwhljl9so0thfxodptz5x4b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e6bb72f8a118577f337547

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2642-mluzb81fby78ufjnmes4ivlu8ztuuope.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d6798856d5d4cc0723d23f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2642-mluzb81fby78ufjnmes4ivlu8ztuuope.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d6798856d5d4cc0723d23f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2642-mluzb81fby78ufjnmes4ivlu8ztuuope.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d6798856d5d4cc0723d23f

**Review by Ressinel — APPROVED** [review]

**Comment by Ressinel** [comment]
🍒-picked to `11.1.x`, `11.2.x`, `11.3.x`, and `11.4.x`

**Pull request merged**
