### PR TITLE
Issue #3458763: Add custom filter for table responsive behavior

### PR DESCRIPTION
**Pull request by Agamich-FE**
## Problem
The table does not have a `table-responsive` wrapper for the correct behavior if we have a big table.

## Solution
Add a custom filter to the text format.

## Issue tracker
https://www.drupal.org/project/social/issues/3458763
https://getopensocial.atlassian.net/browse/PROD-29818

## How to test
- [ ] Go to the Create Topic page.
- [ ] Go to the Ckeditor
- [ ] Add the table with a lot of rows and cells
- [ ] Add content to the cells.
- [ ] Save and check the page.

## Screenshots
before:
Screenshot 2024-07-01 at 16 11 11

after:
Screenshot 2024-07-03 at 16 59 20

## Release notes
Add a custom filter to the text format for table responsive.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3962-jeiaewnfugp1v8psbsdz7dzd3dwqcr5f.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/668550e21bd6ecfe43301079

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3962-jeiaewnfugp1v8psbsdz7dzd3dwqcr5f.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/668550e21bd6ecfe43301079

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3962-jeiaewnfugp1v8psbsdz7dzd3dwqcr5f.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/668550e21bd6ecfe43301079

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3962-jeiaewnfugp1v8psbsdz7dzd3dwqcr5f.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/668550e21bd6ecfe43301079

**Comment by Agamich-FE** [comment]
This PR will be closed because we will use the contrib module instead of the custom solution.

**Pull request closed without merging**
