### PR TITLE
Issue #3455025: Fix type error when users directly goes to `social_group_request.anonymous_request_membership`

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem & Solution
The intention of this route is that it's a callback for the join button, which works well. 
We never figured out what would happen if the user directly goes to the route. In this case, we will ensure that the flow gets started through the join button by
- Ensuring that we will redirect them to the group page if they go to the route directly.
- Write a fall back for the error, if the referer isn't there.

## Issue tracker
https://www.drupal.org/project/social/issues/3455025

## How to test
- [ ] Create a group with public settings and the request to join as join method
- [ ] As an visit `/group/{group}/anonymous-request-membership`
- [ ] See that it breaks
- [ ] Checkout this branch and do the same
- [ ] See that it now redirects to the group page, so the AN user can click the Request to join button
- [ ] See that you are being redirected to user register / join accordingly
- [ ] See that when you login with, lets see chris hall, you get directed to the Group page and the request flow starts (by popping up the request to join message)

## Release notes
We ensured the AN Group Request membership flow is fixed for the scenario that the modal frame URL is opened directly.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Review by vcsvinicius — APPROVED** [review]
I approve

**Comment by BiaInacio** [comment]
The request to join a group of an anonymous user flow is working as expected!
group

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3935-vadocvzjx3asokt1tblxihdotmy1il2n.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/667011c7bc7eaf1d39761d1e

**Comment by robertragas** [comment]
Merged and cherry-picked to 12.4.x and 12.3.x

**Pull request merged**
