### PR TITLE
Issue #3294681 by tBKoT: Allows to filter users by the Profile tag

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
CM+ users should be able to filter people by the `Profile tag(s)` on the users' overview page.

## Solution
Add a new filter to the views.

## Issue tracker
- https://www.drupal.org/project/social/issues/3294681
- https://getopensocial.atlassian.net/browse/YANG-8117

## Theme issue tracker
N/A

## How to test
- [x] Using the latest version of Open Social
- [x] As a CM+
- [ ] Go to the users' overview page (`/admin/people`).
- [ ] You should be able to filter by `Profile tag(s)`

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
No, CM+ users can filter people on the users' overview page by `Profile tag(s)`.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Review by rollki — APPROVED** [review]
LGTM. 
cc @Ressinel

**Comment by navneet0693** [comment]
Hi @dmytriikaiun ,

I see that the Behat tests didn't work on this one. Would it be possible for you to rebase the PR? I will create a PR for Open Social 11.3.x and below for this.

Regards,
Navneet

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3027-ewtike91aiqd5myybhqhqumcpue61x1w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d5376b56d5d4cc07169957

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3027-ewtike91aiqd5myybhqhqumcpue61x1w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62d5376b56d5d4cc07169957

**Comment by rollki** [comment]
@navneet0693 
Seems tests are green now, so can we merge this one?

**Review by Ressinel — APPROVED** [review]

**Comment by Ressinel** [comment]
🍒-picked to `11.4.x`

**Comment by ribel** [comment]
@Ressinel I think it should be in the beta-2 milestone, since it was not released yet, right?

**Comment by Ressinel** [comment]
@ribel You're right.

**Pull request merged**
