### PR TITLE
Issue #3316206 by ronaldtebrake: Enabling AN enrolments export install removes actions for managing enrollees

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
On `hook_install()` of `social_event_an_enroll_enrolments_export` the module tries to replace the Action provided by `social_event_enrolments_export` because this module only takes care of users with actual Drupal accounts. 
The one provided by `social_event_an_enroll_enrolments_export` also takes care of AN enrollees.

However, in doing to, it incorrectly removed other actions because the logic of detecting which action should be replaced.

Screenshot 2022-10-19 at 11 08 49

You can see it in this screenshot above.
Because of it's multidemensional indexed array, instead of removing the array with index 2, it removes the one with key 2, which is exactly what we dont need.

You can see an example here of what is going wrong in an associative/indexed array when trying to remove the "green" value from the array. This is exactly what happened.

Screenshot 2022-10-19 at 11 38 01

## Solution
Two things:
- First we ensure it's now indexed before we remove it. This way we can be sure the position of the pointer is grabbed correctly.
- Additionally I've added the enabling of this module in to an existing test, it actually happens on install and thats all, that removes the Email selected attendeed action. You can see this fail when I run it in main:

Screenshot 2022-10-22 at 11 07 21
 
## Issue tracker
https://www.drupal.org/project/social/issues/3316206

## How to test
* In main branch*
- [x] Enable `social_event_an_enroll_enrolments_export`
- [x] As a sitemanager / Event Manager / Admin
- [x] Login, go to an event and visit the manage enrollments
- [x] See that the Actions incorrectly show two Exports and Email seems to be removed
* In this branch*
- [x] Reinstall Open Social and perform the exact same steps
- [x] See that now the correct actions are shown (Email / Export / Remove) users

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Enabling of the `social_event_an_enroll_enrolments_export` module, disabled / removed certain actions on "Event's -> Manage Enrollment" page. 

For existing websites, the options will have to be added manually by "administrators" by editing the view at `/admin/structure/views/view/event_manage_enrollments`. We didn't want to "add back" those actions by code as that might be un-required for many users. Also, it might have overridden their customizations.

For new installations, this won't be able a problem anymore.

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
The PHPStan issue is coming from #3129 
Can confirm it's all clear in my branch when that is solved

Screenshot 2022-10-22 at 11 25 53

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
@ronaldtebrake It works great.

**Before**

Screenshot 2022-10-24 at 8 16 57 AM


**After**

Screenshot 2022-10-24 at 8 20 48 AM

But I am wonder that our existing installations after https://github.com/goalgorilla/open_social/pull/3071 which landed in Open Social 11.3.9 will not be having this issue, but any new install will have this problem as you mentioned.

Is there anything we can do about our existing installations after Open Social 11.3.9 ?

**Comment by ronaldtebrake** [comment]
Thats a good question @navneet0693 

With this code performed I can't be sure what update hook to write.
Imagine an additional action is added to the same array, it means instead of the export enrollees item maybe the email item got removed and I don't know what to put back. 

I'll have a think about what to do, if you have any ideas let me know!

**Comment by navneet0693** [comment]
Certainly, that's a problem. Is it possible to add it back manually into views? If so, we can write release notes to do so via Views UI for 'admin' ? This will be safer option.

We also did the same for #3071 

Screenshot 2022-10-24 at 11 43 48 AM

**Comment by ronaldtebrake** [comment]
That's a nice idea :) 

The alternative is that we would re-run update hooks in all modules that have these actions to ensure the action is put back, but even then it needs to be checked for all extensions as well indeed.

So i'll update the release notes section with that 👍

**Comment by navneet0693** [comment]
🍒 - picked to 11.5.x, 11.4.x and 11.3.x

**Pull request merged**
