### PR TITLE
Issue #3233475 by chmez: Embed button doesn't appear in the CKEditor toolbar

### PR DESCRIPTION
**Pull request by ghost**
## Problem
In some cases when the config override service of the "Social Embed" module executing many times then the module handler injected service can not found any implementations of the "social_embed_formats" alter hook.

## Solution
Ensure that the current call of the config override service contains configuration which will be processed before executing the alter hook.

## Issue tracker

- https://www.drupal.org/project/social/issues/3233475
- https://getopensocial.atlassian.net/browse/YANG-6259

## How to test
- [x] Enable the "Social Embed" module and log in as a regular user.
- [x] When you navigate to the topic creation page then the "Media" button can be absent on the CKEditor toolbar.

## Release notes
Get rid of unnecessary calls of the "social_embed_formats" alter hook.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2504-na3rtpuc21cgem4a1yti7fniczv9w1ed.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614316fe2c43837371abf51c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2504-na3rtpuc21cgem4a1yti7fniczv9w1ed.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614316fe2c43837371abf51c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2504-na3rtpuc21cgem4a1yti7fniczv9w1ed.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614316fe2c43837371abf51c

**Review by ribel — APPROVED** [review]
I have tested and it works the same as before - Embed button appears also for LU, with and on CKEditor 4 and 5.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2504-na3rtpuc21cgem4a1yti7fniczv9w1ed.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614316fe2c43837371abf51c

**Pull request merged**
