### PR TITLE
by robertragas: for the search overlay add the white color to the pla…

### PR DESCRIPTION
**Pull request by robertragas**
…ceholder text for accessibility improvement

## Problem
The search overlay in the SKY theme has light grey placeholder text which makes it hard to read.

## Solution
Set the placeholder text for this form control to white.

## Issue tracker
https://www.drupal.org/project/social/issues/3181807

## How to test
- [x] Go to the homepage and click on the search icon in the navigation bar
- [x] Notice that the placeholder text is gray and hard to read
- [x] Check out to this branch
- [x] See it's white now

## Screenshots
Before
Screen Shot 2020-11-10 at 11 55 46 PM

After
Screen Shot 2020-11-10 at 11 55 53 PM

## Release notes
We have change the placeholder text color in the search overlay to match the brand colors configured to avoid it becoming unreadable.

### CODE REVIEW

**Review by jochemvn — CHANGES_REQUESTED** [review]
By setting a 'hard' color, the result of making the search bar white is that the text is not readably anymore... see attached screenshot:

Screenshot 2020-11-24 at 10 23 44

**Comment by robertragas** [comment]
@jochemvn can be reviewed again, I moved the logic to the brand styling so it gets updated based on the theme settings.

**Review by jochemvn — APPROVED** [review]

**Comment by jochemvn** [comment]
@robertragas ok all good... it says it needs a backport... but everything? and to where?

**Comment by robertragas** [comment]
Uhmm this PR needs to be cherry-picked this 9.x, as the base branch is 10.x now

**Pull request merged**
