### PR TITLE
Issue #3212327 by nkoporec: Implement AND condition when filtering with multiple terms

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Currently the terms filtering works as an OR condition, this means that if you have a topic that is tagged to Term 1 and Term 2 and multiple topics that are tagged to Term 1 filtering by Term 1 and Term 2 produces multiple results, which is confusing.

## Solution
 Implement a settings that will enabled to use AND condition in the query for terms filtering. This way a user could decide what kind of tags filtering he wants on his page.

## Issue tracker
https://www.drupal.org/project/social/issues/3212327

## How to test
1. Install social_tagging
2. Create multiple root tags with children
3. Tag multiple topics with these new tags
4. Try to search for a specific topic that is tagged to multiple terms.

## Screenshots

_Learn more about the EAA_ is tagged to Term 1 and Term A

_Welcome to the EAA community_ is tagged to Term 1

Before:
Screenshot from 2021-05-05 13-04-12

When the setting is enabled:
Screenshot from 2021-05-05 13-04-40

### CODE REVIEW

**Review by nachosalvador — APPROVED** [review]

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2313-0wlxgoopsy34fzarknsecgtgsplj79ra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d1b7c825606ea73ea3ad

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2313-0wlxgoopsy34fzarknsecgtgsplj79ra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d1b7c825606ea73ea3ad

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2313-0wlxgoopsy34fzarknsecgtgsplj79ra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d1b7c825606ea73ea3ad

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2313-0wlxgoopsy34fzarknsecgtgsplj79ra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d1b7c825606ea73ea3ad

**Comment by navneet0693** [comment]
🍒 - picked to 10.2.x, 10.1.x and 10.0.x

**Pull request merged**
