### PR TITLE
Issue #3419202: Hide event enrollments count if enrollment is disabled

### PR DESCRIPTION
**Pull request by VBaldych**
## Problem
Even when 'event enrollment' has been disabled, the platform shows '0 attendees,' visible from a site manager and verified user account.

## Solution
Hide the enrollments counter if "Enable event enrollment" for the event is disabled.

## Issue tracker
- https://www.drupal.org/project/social/issues/3419202
- https://getopensocial.atlassian.net/browse/PROD-26090

## Theme issue tracker
n/a

## How to test
- [ ] Create an event
- [ ] Be sure that "Enable event enrollment" is checked
- [ ] Save
- [ ] Go to /community-events page. You should see the enrollment counter on the event teaser
- [ ] [Optional] add the event in "Featured content" block in Dashboard and check if counter is hidden

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
**Before**
image

**After**
image

## Release notes
Hide the enrollments counter if "Enable event enrollment" for the event is disabled.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3746-tdve4wgb7advacnyaqkmytcrqxpersxx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c0c6440be493272e8000c5

**Review by ribel — APPROVED** [review]
Changes were tested and looks good to me.

**Pull request merged**
