### PR TITLE
Issue #3246751 by milos.kroulik, Ressinel: Add extra check for Message entity.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
When updating from `10.2.5` to `10.3.0` or `10.3.1` (on two populated installations) - I had errors updating the database.

The issue turned out to be this:
`"Call to a member function getFieldValue() on null in /var/www/social/html/profiles/contrib/social/modules/social_features/social_event/modules/social_event_invite/social_event_invite.tokens.inc on line 88"`

## Solution
Add extra check for **Message** entity in `social_event_invite.tokens.inc`.

## Issue tracker
- https://www.drupal.org/project/social/issues/3246751

## How to test
- [ ] Updating from social `10.2.5` to `10.3.0` or `10.3.1`.

## Screenshots
N/A

## Release notes
Fixed errors related to `social_event_invite.tokens.inc` during updating Open Social minor version.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by navneet0693** [comment]
@Ressinel Would it be possible to find out the actual reason behind this? Also, please add the defensive check in other files (*. token.inc)

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by miloskroulik** [comment]
Will this become part of 11.0.0? This looks like a possible blocker to me.

**Comment by ronaldtebrake** [comment]
Hi @miloskroulik, this isn't necessarily a blocker for the 11.0.0 release (as it's something that is already present in early releases, so that means we should be able to add it to any patch release) but hopefully we can make it part of one of the release candidates. Thanks for your work on this 👍

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2633-t55xvfzw3nqekf0wu8f1vadnoippuxrv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a9f7c7b880b22aa3112dee

**Comment by ronaldtebrake** [comment]
cherry-picked to 11.0.x & 10.3.x 🍒

**Pull request merged**
