### PR TITLE
Issue #2845325: Incorrect display of mention when editing comment/post

### PR DESCRIPTION
**Pull request by bojanbogdanovic**
## Problem
When you create a post or comment with a mention and then edit this content the mention is displayed as [~123].

## Solution
Add mentions initialisation logic when editing comment/post.

## Issue tracker
https://www.drupal.org/node/2845325

## Theme issue tracker
N/A

## How to test
- [ ] Create a post or comment and add mentions in the text by using @username
- [ ] Save comment/post
- [ ] Edit the comment/post
- [ ] Instead of seeing tokens you see now users first and last name.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
On comment/post edit; the mentions now properly displays the user name.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-xywjgec2aqeoy3hkpfqsofvhedxo6fiw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b087e114d98b2defdacc5c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3001-wb6i5fn1toylpeqon9ay1v5hx2by7ojt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62fb3ef4fe6282831389973d

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.4.x

**Pull request merged**
