### PR TITLE
Issue #3300210 by tBKoT: Fix broken post update with search re-index

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
In this PR #2872, we added the post update to clear search indexes and reindex items again, but it fails when we have a lot of content that should be reindexed.

## Solution
Do not reindex items and let cron do this job.

## Issue tracker
https://www.drupal.org/project/social/issues/3300210

## Theme issue tracker
N/A

## How to test
- [ ] Using version 11.1.13 of Open Social
- [ ] You should have a lot of content (>10k)
- [ ] Update to the 11.1.14
- [ ] Run updates
- [ ] Search server could be broken

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Re-indexing is necessary due to updates in search index.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3054-sloyduuue9y9z4npcg8ile0usdxqf672.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e12a9ffe628283131cc01c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3054-sloyduuue9y9z4npcg8ile0usdxqf672.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e12a9ffe628283131cc01c

**Review by ribel — APPROVED** [review]
I have tested this fix instead of previous update and it works good to me.
Before update took more than 30 minutes and was out of memory.
So I think this approach is more reliable.

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
🍒-picked to 11.1.x, 11.2.x, 11.3.x and 11.4.x

**Pull request merged**
