### PR TITLE
Issue #3224512 by Ressinel: Update the Dynamic Entity Reference module from 1.7 to 1.12

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Dynamic Entity Reference module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3224512
- https://www.drupal.org/project/social/issues/2886907

## How to test
- [ ] Enable `social_landing_page` module
- [ ] Go to `/node/add/landing_page`, add the section **Featured Items** and press button **Create landing page**
- [ ] Landing page should be created without any errors

## Screenshots
N/A

## Release notes
The Dynamic Entity Reference module has been updated to 1.12. Please view the release notes from [1.8-alpha1](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.8-alpha1), [1.8](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.8), [1.9](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.9), [1.10](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.10), [1.11](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.11), and [1.12](https://www.drupal.org/project/dynamic_entity_reference/releases/8.x-1.12) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2425-o6mmx4yox7cm3raa4dgwvurn1hocroj7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f713c57424684ad0635208

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2425-o6mmx4yox7cm3raa4dgwvurn1hocroj7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f713c57424684ad0635208

**Comment by ronaldtebrake** [comment]
Something seems not right here:

HTT.

On tugboat environment, create landing page, try to add featured content, see that when you select Group or Profile only content entities are shown.

Screenshot 2021-08-10 at 13 43 06

On distro nightly, create landing page, try to add featured content, see that when you select Group or Profile you can actually add those entities

Screenshot 2021-08-10 at 13 43 00

**Comment by ronaldtebrake** [comment]
Could you take a look @Ressinel, thanks

**Comment by Ressinel** [comment]
@ronaldtebrake I have done some investigation and faced with strange behaviours on envs where we have an old version of the module `Dynamic Entity Reference`. I think we have to check it deeply.

For example, we don't need to see profiles in autocomplete where is selected entity type Group.

Screenshot 2021-08-10 at 17 33 04

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2425-o6mmx4yox7cm3raa4dgwvurn1hocroj7.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f713c57424684ad0635208

**Comment by ronaldtebrake** [comment]
Thanks for the fix @Ressinel that seems to work ✅  
Screenshot 2021-09-02 at 10 35 34

**Pull request merged**
