### PR TITLE
Issue #3412327 by nkoporec: Uncaught PHP Exception Error: "Call to a member function access() on null"

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
We have encountered a WSOD page when visiting a regular members profile as a SM. The error was

```
Uncaught PHP Exception Error: "Call to a member function access() on null" at /app/html/profiles/contrib/social/modules/custom/activity_creator/src/ActivityAccessControlHandler.php line 116
```
## Solution
Currently activity_creator/src/ActivityAccessControlHandler.php we not gracefully handling if the related entity does not exist. We always assume that it is there, so we should add a check that verifies that the related entity indeed exists before calling a method.

## Issue tracker
https://www.drupal.org/project/social/issues/3412327

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
I don't have an exact steps to reproduce, but the issue should occur if a certain reference activity is deleted and thus the access check throws an errror.

Test that there is no WSOD when visiting users profiles.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Change Record
Fixed an issue when visiting a members profile would throw a WSOD.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3680-ubhp2cndrwvpsknm2ae8jxgsd8kr4ln9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596bf8bbd1320f6a9ea4749

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3680-ubhp2cndrwvpsknm2ae8jxgsd8kr4ln9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596bf8bbd1320f6a9ea4749

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3680-ubhp2cndrwvpsknm2ae8jxgsd8kr4ln9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596bf8bbd1320f6a9ea4749

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3680-ubhp2cndrwvpsknm2ae8jxgsd8kr4ln9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596bf8bbd1320f6a9ea4749

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3680-ubhp2cndrwvpsknm2ae8jxgsd8kr4ln9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6596bf8bbd1320f6a9ea4749

**Review by ronaldtebrake — APPROVED** [review]

**Comment by BiaInacio** [comment]
Delete a post, post creator profile page loaded fine as expected:
image

**Comment by ronaldtebrake** [comment]
cherrypicking to 12.1 and 12.0.x

**Pull request merged**
