### PR TITLE
Issue #3062452 by truls1502: Update drupal/group from 1.0-rc2 to 1.0-rc4

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](https://git.drupalcode.org/project/group/compare/8.x-1.0-rc2...8.x-1.0-rc4)
- https://www.drupal.org/project/group/releases/8.x-1.0-rc3
- https://www.drupal.org/project/group/releases/8.x-1.0-rc4

## Issue tracker
https://www.drupal.org/project/social/issues/3062452

## Release notes
Update drupal/group from 1.0-rc2 to 1.0-rc4

### CODE REVIEW

**Comment by jaapjan** [comment]
Marking as needs work as the feature status is not default, see:
https://travis-ci.org/goalgorilla/open_social/jobs/547136876

**Comment by jaapjan** [comment]
Marking for 5.7 since there seems to be still some work needed for which our team does not have time this week.

**Comment by truls1502** [comment]
It has removed a patch that is committed in rc4. I will try to solve the other things that needed work.

**Comment by jaapjan** [comment]
We also need to update cache contexts, see:
https://github.com/goalgorilla/open_social/commit/566b168618a54be9ef5532e43a600c68e8fbaf64 and maybe more commits in that PR needs to move to this one...

**Comment by jaapjan** [comment]
I'll open a new PR based on 7.x for this and link it later.

**Pull request closed without merging**
