### PR TITLE
Issue #3239372 by agami4: Add new colours to the colour theme settings

### PR DESCRIPTION
**Pull request by agami4**
## Problem
For the EC project, we need to implement a two-row header, so we need additional colour settings for a new row.

## Solution
Add new colour settings on the theme setting page.

## Issue tracker

- https://www.drupal.org/project/social/issues/3239372
- https://getopensocial.atlassian.net/browse/ECI-1261
- https://www.drupal.org/project/socialblue/issues/3229069

## How to test
- [ ] Make socialblue theme has two-row [changes](https://www.drupal.org/project/socialblue/issues/3229069).
- [ ] Go to the socialblue theme settings page.
- [ ] Enable `Two rows` header setting.
- [ ] Scroll to color settings.
- [ ] You can see new colors on the bottom of the color settings list

## Screenshots
Change colors and styling | ECI Demo 2021-10-25 14-49-05

## Release notes
The socialblue theme has new settings:
1. Header - one/two rows
2. New color settings according to a new header layout

## Translations

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by agami4** [comment]
@Kingdutch, I've added a fix to the color scheme, and new color settings use for the elements of the bottom header and old color settings use for the top header

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by Ressinel** [comment]
@agami4 Looks like there is [failed test](https://app.travis-ci.com/github/goalgorilla/open_social/jobs/546834411#L3687) which you need to look at.

**Comment by ribel** [comment]
@Ressinel From the code changes and fact that this behat is also often failing in other PR's it looks like false positive.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Review by Ressinel — APPROVED** [review]

**Comment by ribel** [comment]
Merge Requests 30 was already merged in socialblue, so the patch here needs to be replaced with socialblue version 2.0.x once it will be released.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2523-poxnf7osfneawzuzrhlmgfmtkwlnqz7m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61518bba4807c036753c1768

**Comment by ronaldtebrake** [comment]
Coding standards will be fixed in #2675 so once reviews are completed we can merge it like this :)

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
cherry-picked to 11.0.x

**Pull request merged**
