### PR TITLE
Issue #3218415 by chmez: ActivitySend plugin doesn't support injected services

### PR DESCRIPTION
**Pull request by OH17L**
## Problem
The plugin main method and a method for injecting services have the same name.

## Solution
Rename the plugin main method.

## Issue tracker
- https://www.drupal.org/project/social/issues/3218415
- https://www.drupal.org/project/social_pwa/issues/3218432
- https://getopensocial.atlassian.net/browse/ECI-1174

## Release notes
Allow using injected services in the activity send plugins.

## Change Record
https://www.drupal.org/node/3238220

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by Kingdutch** [comment]
This is a backwards incompatible change so this will need a major version release cc @ronaldtebrake

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2378-rhgwe6xxbfhoizzcy33mkggd4wwj1fzf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c33a1dcde720762c7ccf28

**Comment by navneet0693** [comment]
@OH17L Are we still targetting this to be in 11.0.0!

**Comment by ribel** [comment]
@navneet0693 This PR was needed for fixing coding standards in our [social_app](https://bitbucket.org/goalgorilla/social_app/pull-requests/12) extension.
I think it still would be good to get this merged. But I think we also need to create a change request record and check if we need to create PR with relevant change for other extensions. For example, I see we also need this for the [social_admin](https://bitbucket.org/goalgorilla/social_admin/src/master/modules/social_admin_notifications/src/Plugin/ActivitySend/PlatformEmailActivitySend.php) notification.

cc @OH17L @Kingdutch

**Review by ribel — APPROVED** [review]

**Comment by OH17L** [comment]
@ribel, the "Social Admin" module already has [PR for this](https://bitbucket.org/goalgorilla/social_admin/pull-requests/17) (see Jira task).

cc @navneet0693 @Kingdutch

**Comment by navneet0693** [comment]
@ribel Yes, let's do it :-D

**Review by navneet0693 — APPROVED** [review]

**Pull request merged**
