### PR TITLE
Issue #3397762: Define entity_access_by_field permissions for all entity types

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
The PR [#3109](https://github.com/goalgorilla/open_social/pull/3109) extended functionality of EntityAccessHelper to cover all entity types and rename method to entityAccessCheck(). However, permission definitions in the PR were not updated to apply to this logic.

Starting with Drupal 9.3.0, all permissions in a user role must be defined in a module.permissions.yml file or a permissions callback. Source: https://www.drupal.org/node/3193348

## Solution
Resolve the issue by defining permissions for entity_access_field for all entity types (at the moment, permissions are defined only for node entity type).

## Issue tracker
[3397762](https://www.drupal.org/project/social/issues/3397762)

## Theme issue tracker
N/A

### Test case 1 (show permissions on list)

- [x] Install clean open social installation
- [x] Enable Field UI module
- [x] Add an Entity access field to an entity that is not node (example in following steps)
- [x] Go to admin/structure/taxonomy/manage/topic_types/overview/fields and create Entity access field called “Example” 
- [x] Under “Allowed values list” add for example
```
public|public
community|community
group|group
test|test
```
and save it.
- [x] Go to admin/people/permissions/module/entity_access_by_field and you will see only node related fields here
Screenshot 2023-11-02 at 16 20 08
- [x] The expected result is that nodes permissions remains as they are and we can see additional permissions from other entities as well when the fix is applied
Screenshot 2023-11-02 at 16 37 12

### Test case 2 (Make sure that getRealmWithPermission() method was updated correctly and working as it was designed before)

Related to this method: https://github.com/goalgorilla/open_social/blob/1b8ba9974543a5e2b869b1a1460e23f2f07432b2/modules/custom/entity_access_by_field/src/EntityAccessByFieldPermissions.php#L110

- [x] Follow all steps from test case 1 
- [x] Create basic page (node/add/page)
- [x] Set Access permissions field as public
- [x] Anonymous user should see the basic page
- [x] Set Access permissions field as Community
- [x] Anonymous user should not see the basic page
- [x] Feel free to test any other un/happy flow related to this.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Support entity access checker permissions for any entity type.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by kashandarash** [comment]
Test case 1 works as expected
Screenshot 2023-11-03 at 17 01 40
Test case 2 also work as expected

**Review by kashandarash — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3583-abithekoook5xbncq0b9peekdivwqusq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653fe095c5102c7756a6f0c1

**Comment by zanvidmar** [comment]
🍒  Cherry-picked to 12.0.x here: [81dfb980b0](https://github.com/goalgorilla/open_social/commit/81dfb980b009625ff76670e22ab63c855fde4414)

**Pull request merged**
