### PR TITLE
Issue #3119193 by agami4: Add styles to the icon in the title on the custom content block

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The icon has not styles in the title in the custom content block.

## Solution
Add styles to the icon.

## Issue tracker
https://www.drupal.org/project/social/issues/3119193

## How to test
- [ ] Create a custom content list block.

## Screenshots
before:
Screenshot at Mar 11 16-23-59

after:
Screenshot at Mar 11 16-28-35

## Release notes
The icon has styles in the title on the custom content block.

### CODE REVIEW

**Comment by ribel** [comment]
@Kingdutch Could you check if this PR is still relevant? Because I think you made similar changes in PR #1778

**Comment by Kingdutch** [comment]
I think it's still needed, I made changes in the Dashbaord module only.

https://bitbucket.org/goalgorilla/social_dashboard/src/33fb88add01bb7270b78829ba2f725a8e46869a7/assets/css/page-node-type-dashboard.css#lines-195

Please make sure that changes made here don't break the styling when displayed on the dashboard.

Perhaps moving the styling from the dashboard module to the socialbase theme can fix it in both places.

**Comment by agami4** [comment]
@Kingdutch, I've moved styles for the icon to socialbase theme and removed form social_dasboard module

**Comment by ribel** [comment]
@agami4,
Even if it fix the issue with SVG icon, I think subtitle still needs to be fixed.
I think font-weight and position for the custom content list should be the same as for example for Upcoming events block.

image

**Comment by ribel** [comment]
Merged and cherry-picked to 8.x-8.x

**Pull request merged**
