### PR TITLE
Issue #3225521 by Ressinel: Update the Update helper module from 1.3 to 2.0.0

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Update helper module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3225521

## How to test
- [ ] Drush version has to be greater than 10.2.
- [ ] Run `drush generate configuration-update`

## Screenshots
N/A

## Release notes
The Update helper module has been updated to 2.0.0. Please view the release notes from [2.x-dev](https://www.drupal.org/project/update_helper/releases/2.x-dev), and [2.0.0](https://www.drupal.org/project/update_helper/releases/2.0.0) of that module for the changes.

## Change Record
This release uses **drush** generate instead of **drupal console**. **Drush** version has to be greater than `10.2`.

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2446-bvnhnrv78figxw9tsm9yy4bxutwvsgvm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6100340480afb095c84b518b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2446-bvnhnrv78figxw9tsm9yy4bxutwvsgvm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6100340480afb095c84b518b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2446-bvnhnrv78figxw9tsm9yy4bxutwvsgvm.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6100340480afb095c84b518b

**Comment by navneet0693** [comment]
As the new version of the update helper module requires Drush 10 as given here: https://git.drupalcode.org/project/update_helper/-/blob/2.x/composer.json#L31

We will have to update our existing Drush commands to be Drush 10 compatible.

**Comment by navneet0693** [comment]
Drush 10 compatibility is being covered in https://github.com/goalgorilla/open_social/pull/2487

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
Other two related PRs:

https://github.com/goalgorilla/open_social_scripts/pull/40/files
https://github.com/goalgorilla/drupal_social/pull/361

**Comment by Kingdutch** [comment]
@navneet0693 @Ressinel Since this already breaks anyone's workflow who is working on the development branch, can you share some internal documentation/notice on Slack that a new command is now required (and when you should start using that).

**Pull request merged**
