### PR TITLE
Issue #3183704 by agami4: The hyperlinks have not the correct styles on the body/description block.

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The hyperlinks have not the correct styles on the body/description block.

## Solution
Add primary color for all links

## Issue tracker
https://www.drupal.org/project/social/issues/3183704

## How to test
- [x] Go to/create any page and add a link to the body/description block

## Release notes
All links have a primary color on the description of the paragraphs on the landing page

## Related PR
https://github.com/goalgorilla/open_social/pull/1610

### CODE REVIEW

**Review by ribel — APPROVED** [review]

**Comment by Kingdutch** [comment]
The linked Drupal.org ticket was marked as fixed 10 months ago, so this probably needs a new ticket specific to the remaining problem.

**Comment by ribel** [comment]
@agami4 please create different issue on drupal.org for this PR.

**Comment by agami4** [comment]
@ribel, @Kingdutch, I've added a separate ticket. Please check

**Comment by ribel** [comment]
🍒 picked to 8.x and 9.x

**Pull request merged**
