### PR TITLE
Issue #3197794 by tBKoT: Fix regression on activity stream

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
Regression after merging the #2229 PR.
Check comment from @ronaldtebrake https://github.com/goalgorilla/open_social/pull/2229#issuecomment-801199399

## Solution
Change conditions for comments activity.

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-5208

## How to test
N/A

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by dmytriikaiun** [comment]
@ronaldtebrake please check if it works for you and let me know if need some more work on it.

**Comment by ronaldtebrake** [comment]
FYI - @robertragas this might solve the problem for us :) (didnt test yet just forwarding the message)

**Review by ribel — APPROVED** [review]
Our QA has tested changes after this fix and approved them.
Code changes also look ok to me.

**Comment by ronaldtebrake** [comment]
Thanks guys, that seems to do the trick! :) Happy to see this merged

**Pull request merged**
