### PR TITLE
Issue #3420069: [13.0.0] Remove the ability to change a group bundle type

### PR DESCRIPTION
**Pull request by Kingdutch**
⚠️ This PR is part of [a set of stacked-PRs](https://newsletter.pragmaticengineer.com/p/stacked-diffs). Do not use the rebase button, but instead rebase the branch of the last PR in the series [using git rebase --update-refs](https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/) ⚠️

Should be merged after #3753

## Problem
For our old group types we have a bunch of functionality that relates to changing the bundle of the group to move between the public, open, closed, and secret group types. For Flexible Groups this is no longer required as you can change the visibility of the group itself.

## Solution
Remove the code related to this functionality
-     Drupal\social_group\GroupContentVisibilityUpdate
-     social_group_form_alter contains group type editing logic and references SocialGroupAddForm
-     _social_group_inform_group_type_selection
-     _social_group_type_edit_submit

## Issue tracker

https://www.drupal.org/project/social/issues/3420069

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes

It's no longer possible for users to change the bundle of a group entity.

## Change Record

https://www.drupal.org/node/3420118

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3754-xp9rxgiee6tqfqbw4y8sc47tfje0nxdb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4e9860be493272ebec276

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3754-xp9rxgiee6tqfqbw4y8sc47tfje0nxdb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4e9860be493272ebec276

**Review by nechai — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3754-xp9rxgiee6tqfqbw4y8sc47tfje0nxdb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4e9860be493272ebec276

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3754-xp9rxgiee6tqfqbw4y8sc47tfje0nxdb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4e9860be493272ebec276

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3754-xp9rxgiee6tqfqbw4y8sc47tfje0nxdb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c4e9860be493272ebec276

**Pull request merged**
