### PR TITLE
Issue #3268943 by SV: As a LU I want to be able to see the list of the followers & following users

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Note
- Depend on [related PR](https://github.com/goalgorilla/open_social/pull/2778) and should be reviewed after merging that PR

## Problem
- LU should be able to see the list of the users another user follows
- LU should be able to see the list of users following another user

## Solution

-  On the user’s profile it should be possible to see the list of people that user follow 
   - there should be a CTA leading to the list
   - there should be the number of users on the list specified
- On the user’s profile it should be possible to see the list of followers
   - there should be a CTA leading to the list
   - there should be the number of followers on the list specified

## Issue tracker
- https://www.drupal.org/project/social/issues/3268943
- https://getopensocial.atlassian.net/browse/YANG-6957
- https://getopensocial.atlassian.net/browse/YANG-6958

## How to test
- [ ] Using  the latest version of Open Social with the social_follow_user module enabled
- [ ] As a LU (first users)
- [ ] Try to open /all-member page
- [ ] And click follow button for a few users
- [ ] Next, got to your profile page 
- [ ] And you should see the increased number of "following" users
- [ ] After click on the "following" link  you will be redirected to the "following" users page
- [ ] And you should see the list of "following" users 
- [ ] Login as another user (second user)
- [ ] And find "first" LU and click on the follow button 
- [ ] Switch back to the "first" LU and number of "followers" users should be increased
- [ ] After click on the "followers" link  you will be redirected to the "followers" users page
- [ ] And you should see the list of "followers 

## Screenshots

Screenshot 2022-03-09 at 12 33 28
Screenshot 2022-03-09 at 18 44 52

## Release notes
 - Provides a list of following users & followers

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2812-nbwbmtviviosyyntmn74pizhh21jlo5j.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622b83158884bf8cd4ad38a3

**Comment by OH17L** [comment]
Replaced by PR #2850.

**Pull request closed without merging**
