### PR TITLE
Updates: (deps): Update drupal/views_bulk_operations requirement from 4.1.4 to 4.2.4 - follow up

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
We need to update VBO module to latest version so that we are compatible with Drupal 10.

This is a breaking change because VBO added type-hint to their functions, making them BC breaking changes, so it should land in major version of OS. We also need to check cablecar extensions compatibility, since any custom VBO action will break.

## Solution
Upgrade VBO module and fix all the custom code compatibility.

## Issue tracker
Follow up from https://github.com/goalgorilla/open_social/pull/3281

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Create a new event
- [ ] Create a new user and enroll in this event
- [ ] As admin go to the event and click the manage enrollments
- [ ] Select all enrollments
- [ ] Send email to enrolees
- [ ] Complete the form for sending the email
- [ ] Verify that the email is being sent out correctly 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Upgrade views_bulk_operation module to the latest version.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3528-ip0zrtvi4ufdmgwxxqeah2svebo8pour.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65032c19a586415e1a34a01b

**Comment by nkoporec** [comment]
:cherries: picked to 12.0.x

**Pull request merged**
