### PR TITLE
Issue #3353190 by ribel: Add Header top region to the Landing page template

### PR DESCRIPTION
**Pull request by ribel**
## Problem
Header top region is missing from overridden Landing Page template: `page--node--landing-page.html.twig`.

## Solution
Add rendering of Header top region the same as in base template of socialblue theme: page--sky.html.twig:

```
{% if page.header_top and multi_line %}
  {{ page.header_top }}
{% endif %}
```

## Issue tracker
- https://www.drupal.org/project/social/issues/3353190
- [PROD-24944](https://getopensocial.atlassian.net/browse/PROD-24944)

## Theme issue tracker
N/A

## How to test
- [ ] Enable module Social Landing Page
- [ ] Go to theme settings
- [ ] Enable two-row header style
- [ ] Add some blocks to the Header top region
- [ ] Go to Landing page
- [ ] You should see block in the Header top region

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before:
image
After:
image

## Release notes
Header top region is now displayed on Landing Pages.

## Change Record
N/A

## Translations
N/A

[PROD-24944]: https://getopensocial.atlassian.net/browse/PROD-24944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3371-dwwz8ejlffshaeb3wlyr7ptvmptrstfd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6433e0334ea53954e47b7207

**Comment by agami4** [comment]
@ribel, I've checked if we have the header(header with two rows) on the landing page and everything looks good.

**Review by agami4 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3371-dwwz8ejlffshaeb3wlyr7ptvmptrstfd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6433e0334ea53954e47b7207

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3371-dwwz8ejlffshaeb3wlyr7ptvmptrstfd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6433e0334ea53954e47b7207

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3371-dwwz8ejlffshaeb3wlyr7ptvmptrstfd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6433e0334ea53954e47b7207

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3371-dwwz8ejlffshaeb3wlyr7ptvmptrstfd.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6433e0334ea53954e47b7207

**Comment by ribel** [comment]
🍒 picked to 11.9.x and 11.8.x

**Pull request merged**
