### PR TITLE
YANG-1689: Fix theming for social birthday block

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The birthday small block has the wrong styles

## Solution
Update styles and layout for the birthday small block

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-1689

## How to test
- [ ] Display the birthday small block on the sidebar
- [ ] You can see the birthday small block on the home page

## Release notes
Updated layout and display the birthday small block on the sidebar

### CODE REVIEW

**Comment by bramtenhove** [comment]
Just wondering, the Birthday module is not in Open Social core right?

In that case I'm not sure if we should just add this to the code. I think it would be nicer if we change it maybe to, for example, an alter hook and let the Birthday module implement that.

_Also, if you don't have a change record you can remove the default text._

**Comment by ribel** [comment]
@bramtenhove You are correct, but in this case, as we know there are plans to add Birthday module to the distro, is that correct @ronaldtebrake?
So we just fixed the issue here that Xinyu noticed as in advance.

**Comment by ronaldtebrake** [comment]
> @bramtenhove You are correct, but in this case, as we know there are plans to add Birthday module to the distro, is that correct @ronaldtebrake?
> So we just fixed the issue here that Xinyu noticed as in advance.

@ribel //cc @bramtenhove 
It's not going to be in the Distro but will still be used as an extension.
The alter option would definitely be very interesting (also for other use cases we will have with extensions in the future) is that something you can still take a look at?

**Comment by ribel** [comment]
@ronaldtebrake Got it now.
Unfortunately, I can not guarantee that we will have time to work on it in ECI team, also since this is not the highest priority for us at the moment.
So If distro team can take this over I would appreciate it.

**Comment by Kingdutch** [comment]
Hey @ribel @ronaldtebrake ,

This PR is adding an implementation for `social_core_preprocess_block`. This can easily be copied to the `social_birthday` module without any changes in Open Social right? This is an alter hook that's already supported by Drupal core.

That means we can just close this PR and any associated Drupal.org ticket as not needed.

**Comment by Kingdutch** [comment]
@ronaldtebrake I removed this from the 8.0 milestone

**Pull request closed without merging**
