### PR TITLE
DS-1981 by ribel: Remove geocoder and geolocation modules from distro 

### PR DESCRIPTION
**Pull request by ribel**
# HTT
- [x] Reinstall your site first on 8.x-1.x branch, then checkout this branch and do a `drush updb -y; drush fra -y; drush cr` (to make sure it works for update path)
- [x] Login as normal user
- [x] Check that Search functionality works like before and nothing is broken (especially for groups).
- [x] Reinstall site in this branch and check that nothing is broken.
- [x] Check the code

# Changes
- Removed `geocoder` and `geolocation` modules from distro.
- Remove group proximity search functionality
- Removed deprecated bloks and views from Social Search module.
- Moved `navbar-search` script from `social_search` to `social_core` (in order to use this library with `social_geolocation` module in enterprise versions.

### CODE REVIEW

**Comment by NielsGG** [comment]
@ribel There are some merge conflicts could you take a look?

**Comment by ribel** [comment]
Hi @NielsGG,
I have fixed this conflict.

**Comment by NielsGG** [comment]
Hi @ribel,

During the updatedb on step 1. I get the error:
The following reasons prevent the modules from being uninstalled: The <em class="placeholder">Geolocation</em> field type is used in the following field: group.field_group_geolocation

**Comment by ribel** [comment]
@NielsGG sorry, this was caused by typo in field name. Fixed.

**Comment by NielsGG** [comment]
Hi @ribel,

I get this notice quite often in this branch:
Notice: Undefined index: group in Drupal\Core\Asset\AssetResolver::sort() (line 375 of core/lib/Drupal/Core/Asset/AssetResolver.php).

Could it be related to your changes?

**Comment by ribel** [comment]
Hi @NielsGG,
I didn't see this notice before, but i will check it.

**Comment by ribel** [comment]
@NielsGG i checked that issue is also on other branches, so not sure it's related to this PR, but definetly need to be fixed as part of maintenance story.

I have add them to description of DS-2168

**Pull request merged**
