### PR TITLE
Issue #2968935 It should be clear that posts or entities are unpublished

### PR DESCRIPTION
**Pull request by Crazylord**
## Problem
Currently when a node or a post is marked as unpublished this is not very nicely displayed in the front-end in most places, except for the node full display.

## Solution
Update styles for unpublished teasers

## Issue tracker
- https://www.drupal.org/project/social/issues/2968935

## HTT
- [ ] Check out the code changes
- [ ] Checkout to this branch
- [ ] Try change status for event/topic to unpublish and check how looks teasers for it.

## Documentation
- [ ] This item is added to the release notes

### CODE REVIEW

**Comment by jaapjan** [comment]
Ok, it seems to work for topic (nodes) - although i think it should not be capitalised letters

topic-unpublished-teaser

But I can't get it to work for Posts. Did you test it by merging in 8.x-2.x into this branch locally? (See: https://github.com/goalgorilla/open_social/pull/715 ) I think you need to change the templates of the posts as well..

So the TODO is:

- [ ] Make it work for Posts in stream 
- [ ] Make it work for Posts in full display: /post/1 as well
- [ ] Change UNPUBLISHED in teaser to small letters

**Comment by Crazylord** [comment]
Hi @jaapjan . Look like for now unpublished Post aren't in stream.

**Comment by jaapjan** [comment]
@Crazylord yes you are right. You can temporary change filter for post.status from 1 to 0 in: `ActivityPostVisibilityAccess.php` and `ActivityFilterPersonalisedHomepage.php` as changed in: https://github.com/goalgorilla/open_social/pull/715/files

**Comment by Crazylord** [comment]
@jaapjan 
Add unpublished label for posts in activity stream.

**Comment by jaapjan** [comment]
Hey @Crazylord for Posts it looks good now, but I think we need to implement it for node teasers the same way. The solution is now not very consistent. 

Can we also move the "unpublished" label to the top right for node teasers (just like you did for posts?)

- [ ] Move "unpublished" label to the top right of the node teaser

**Comment by Crazylord** [comment]
Update status label for node teaserю

**Comment by bramtenhove** [comment]
@Crazylord, @jaapjan I noticed this yesterday evening on the /explore page. Can you confirm you have this issue as well?

screen shot 2018-05-18 at 09 23 46

**Comment by jaapjan** [comment]
@bramtenhove @Crazylord when did you notice this yesterday, was it after the latest commit of Sergey? I couldn't reproduce it with LU and SM in both Firefox and Chrome. Actually it does look good for me now.

**Comment by Crazylord** [comment]
@bramtenhove @jaapjan . I tested it againg and for me this also looks good.

**Comment by bramtenhove** [comment]
@jaapjan @Crazylord ok, nvm me then. Was late at night, maybe I made a mistake. Sorry for the confusion!

**Comment by jochemvn** [comment]
@bramtenhove I guess the label 'need work' can go?

**Pull request merged**
