### PR TITLE
Issue #3415514 by ronaldtebrake: Prefer native lazy loading

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
In https://www.drupal.org/node/3173719 we already switched to native lazy loading for images.
It's now time to also move to that for iframes, which we use in our `social_embed` using the same native functionality as images use https://web.dev/articles/iframe-lazy-loading

This has added benefit we can remove javascript in the future, as well as have it work better in a webview on a native app.

## Solution
Currently we use the https://www.drupal.org/project/lazy module for iframes, this uses a text filter and adds either javascript and classes to lazy load images or lets us use the native browser behavior.

Currently we prefer the native solution, so this is something we want to install by default. 

In the future we will deprecate our `social_lazy_loading` and use this by default.

## Issue tracker
https://www.drupal.org/project/social/issues/3415514 - this is just part one.

## How to test
- [ ] Enable `social_lazy_loading` and `social_embed
- [ ] Embed a youtube video in a post
- [ ] see that the iframe now has `loading="lazy"` when you inspect the element

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Screenshot 2024-01-18 at 12 32 50
Screenshot 2024-01-18 at 12 56 08

## Release notes
We prefer using native lazy loading for iframes, which we allow when you use our social_embed module.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Review by robertragas — APPROVED** [review]
Codewise approved

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3709-jojtioyjscptsgoanmd1zyqp18mmvabq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a913c87633b712e74383fa

**Comment by BiaInacio** [comment]
Lazy loading tag is displayed on video's ifreame, as expected!
image

**Comment by ronaldtebrake** [comment]
Cherry picked to 12.1.x 🍒

**Pull request merged**
