### PR TITLE
Issue #3004857 by truls1502: Update block_field 1.0.0-alpha5 to 1.0.0-alpha8

### PR DESCRIPTION
**Pull request by truls1502**
## Problem& Solution
[Full Changelog](http://cgit.drupalcode.org/block_field/diff/?h=8.x-1.x&id=f453c2d44af202300161b2d65753bbbfbff12212&id2=7d89db375c115758910504a016fc4a76bd7543e7)
- https://www.drupal.org/project/block_field/releases/8.x-1.0-alpha6
- https://www.drupal.org/project/block_field/releases/8.x-1.0-alpha7
- https://www.drupal.org/project/block_field/releases/8.x-1.0-alpha8

## Issue tracker
- https://www.drupal.org/project/social/issues/3004857

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by truls1502** [comment]
Done ✅ 👍

**Comment by jaapjan** [comment]
Reviewed and couldn't find anything wrong with this update. Let's wait for project Moss to finish testing it.

**Comment by bramtenhove** [comment]
@robertragas, @Kingdutch, can anyone of you look at RT to see if the patch applied to block_field can be removed?
Currently patch from https://www.drupal.org/project/block_field/issues/2876014 is applied, but it looks like it is solved in https://www.drupal.org/project/block_field/releases/8.x-1.0-alpha8 via a different issue. Thanks!

**Pull request merged**
