### PR TITLE
Give possibility to add additional header and footer to emails

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
Currently the notification emails can be quite plain without any additional general information a sitemanager might want to add.
We might want to add the possibility for a sitemanager to add a header or footer to the email notifications.

## Solution
Add a field under the swiftmailer configuration to add a general header or footer with a basic text format to allow 'a', 'em', 'strong', 'u', 'br'. 

## Issue tracker
https://www.drupal.org/project/social/issues/3019458

## How to test
- [x] Go to admin/config/opensocial/swiftmail through the url bar of interface
- [x] First save without filling the fields in.
- [x] Trigger email notification and see fields are not included
- [x] Fill in the fields with some basic formatting provided by the text format
- [x] Trigger email notification again and see fields are included
- [x] Try to add Xss to the fields and see that they are not included

## Additional note
Apart from the restricted text format that I created, it was possible to use the source editor or chrome inspector to add <script> and save without it being properly stripped. This is why I also sanitized it on a deeper level, also making sure that should people switch text format to full basic they cannot include any additional markup.

## Release notes
We have added the possibility to add an additional header or footer to the email notifications, giving you the possibility to give a personal touch to the notifications.

### CODE REVIEW

**Comment by robertragas** [comment]
Travis is green and Saas is green.

**Comment by ribel** [comment]
@robertragas FYI, I've also made some changes in email templates in PR #1304

**Comment by Kingdutch** [comment]
The target branch of this PR has been changed to 6.x which will be the next major version. Our policy is to merge any bugfixes in the newest branch first and cherry-pick/backport any required changes. This ensures that the newest major version is the longest/least diverged branch.

**Comment by ribel** [comment]
@robertragas will you be able to proceed on the last comment from Jochem?

**Comment by ronaldtebrake** [comment]
All green + reviewed, so merging this we can tackle the rest as part of bugfixing day. Want to see this feature tested on multiple platforms.
For what its worth, already created an issue in the 6.0 testing day list for the known comments made by Jochem.

**Pull request merged**
