### PR TITLE
Issue #3062448 by truls1502: Update drupal/profile from 1.0-rc4 to 1.0-rc5

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](https://git.drupalcode.org/project/profile/compare/8.x-1.0-rc4...8.x-1.0-rc5)
- https://www.drupal.org/project/profile/releases/8.x-1.0-rc5

## Issue tracker
https://www.drupal.org/project/social/issues/3062448

## Release notes
Update drupal/profile from 1.0-rc4 to 1.0-rc5

### CODE REVIEW

**Comment by albertoalaejos** [comment]
@ronaldtebrake PR to be accepted. I created a new profile, added it to a group and interact to make sure that there is no conflict.

**Comment by jaapjan** [comment]
Marking as needs work as feature status is not default. See:
https://travis-ci.org/goalgorilla/open_social/jobs/547131706

Should be easy fix :-)

**Comment by jaapjan** [comment]
Just updated the configurations so feature state will be default. 🤞

**Comment by jaapjan** [comment]
Failing test seems to be false-negative, will merge :-)

**Pull request merged**
