### PR TITLE
Issue #3437440: Block with enrollments from Event page is showing wrong count

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The enrollments count from Event page is showing all enrollments without check the status for invite or pending request.

## Solution
Removed parameters to ignore status from events

## Theme issue tracker
[PROD-28692](https://getopensocial.atlassian.net/browse/PROD-28692)
[#3437440](https://www.drupal.org/project/social/issues/3437440)

## How to test
- [ ] Create an event
- [ ] Add an enrollee to the event
- [ ] Invite another user to the event
- [ ] Check the event page
- [ ] The Enrollees block states that the event has two enrollees on the event when there is only one displayed

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Fixed the enrollments count from event page.

## Change Record
N/A

## Translations
N/A

[PROD-28692]: https://getopensocial.atlassian.net/browse/PROD-28692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by BiaInacio** [comment]
Enrollees count is right even when there are pending invites!
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Review by robertragas — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3841-biraivb76ehy0ot4eux3y0jbbcdytuar.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/660b0670bb60c231751e0e7c

**Comment by robertragas** [comment]
Approved/merged and cherry-picked to 12.4.x and 12.3.x

**Pull request merged**
