### PR TITLE
Issue #3225340 by Ressinel: Update the Views Infinite Scroll module from 1.6 to 1.8

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Views Infinite Scroll module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3225340

## How to test
Before testing recommended decrease `Items per page` in view. To do it enable `views_ui` module, go to `/admin/structure/views/view/who_liked_this_entity` and change `Items per page` value.
- [ ] Find comment with plural likes count
- [ ] Press **[count] likes** link to open a popup with a list of members who liked this Comment
- [ ] Press `show some more` to load more members
- [ ] Loading should work properly without any errors

## Screenshots
N/A

## Release notes
The Views Infinite Scroll module has been updated to 1.8. Please view the release notes from [1.7](https://www.drupal.org/project/views_infinite_scroll/releases/8.x-1.7), and [1.8](https://www.drupal.org/project/views_infinite_scroll/releases/8.x-1.8) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2442-t4w5griw2t51cwvxte1j1sisladtfu79.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60febfd500f236a4ee1577d8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2442-t4w5griw2t51cwvxte1j1sisladtfu79.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60febfd500f236a4ee1577d8

**Comment by ronaldtebrake** [comment]
Thanks for this @Ressinel 

All manual tests pass :) once Travis is happy with it we can merge this.

Screenshot 2021-08-09 at 09 38 13
Screenshot 2021-08-09 at 09 38 18
Screenshot 2021-08-09 at 09 38 25

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
@Ressinel Sorry, i found one more thing. 
Maybe you could still have a look at:

I see this notice, could that be related to the update of the patch? It seems to happen when the modal opens and related to:
https://www.drupal.org/project/drupal/issues/2663316

Screenshot 2021-08-09 at 10 08 02

https://pr2442-t4w5griw2t51cwvxte1j1sisladtfu79.tugboat.qa/admin/reports/dblog/event/37

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2442-t4w5griw2t51cwvxte1j1sisladtfu79.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60febfd500f236a4ee1577d8

**Comment by Ressinel** [comment]
@ronaldtebrake I have received this notice even without the Views Infinite Scroll module update. But I've found the patch. Check if you still receive that notice, please.

**Comment by ronaldtebrake** [comment]
Nice @Ressinel that works :D once tests are green we can merge 🚀

**Pull request merged**
