### PR TITLE
Issue #3318303 by rolki: Add support for allowed_values_function in entity_access_by_field

### PR DESCRIPTION
**Pull request by rollki**
## Problem
So, the problem is that user realms are not described for all types of fields. Previously, we had only one type of field `(field_content_visibility)` for processing accesses, but not so long ago another appeared `(role_visibility),` and for it, the `allowed_values` are not obtained correctly, as a result of which a user who has direct access to an entity cannot always see it in other places (for example, search ). Accordingly, content can be created with visibility for the role, the user under that role will have direct access to the entity, but will not be able to see it, for example, in the resource library.

## Solution
Correctly describe `getSetting('allowed_values')` for `role_visibility` field, accordingly add support for `allowed_values_function`.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-22952
- https://www.drupal.org/project/social/issues/3318303

## Theme issue tracker
NONE.

## How to test (OS 10.3.x and 11.5.x)
- [ ] You have to install and enable the `social_role_visibility` and `social_resource_library` extensions
- [ ] Create a topic with a custom role visibility option
- [ ] Login under the user with that role
- [ ] You can access that entity directly
- [ ] You should see that entity on the resource library

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Знімок екрана 2022-10-31 о 15 14 58

Знімок екрана 2022-10-31 о 15 17 08

## Release notes
Now we support `allowed_values_function` for adding grants in the `entity_access_by_field_node_grants` hook. This means that previously we could process only allowed_values and based on this data decide whether to give the user access to view the content or not (`hook_node_grants`), but in some cases, this is not enough, that is why you should process all possible variants of the field value (including allowed_values_function).

## Change Record
Now we support `allowed_values_function` for adding grants in entity_access_by_field_node_grants hook.

## Translations
NONE.

### CODE REVIEW

**Review by ribel — APPROVED** [review]
Hi @rollki,

I see that indeed method `getRealmWithPermission()` was not changed almost from the beginning (2016), so it definitely could be that it doesn't support extensions that was added later.

Code changes looks good to me, and I see all tests pass including EntityAccessTest.php, so it means we shouldn't have any regressions. 

I just not sure about Change Record - if we didn't bring API change, we don't really need this.

@navneet0693 and @tbsiqueira, could you please review this PR as well and let us know if we can merge it?

**Review by nkoporec — CHANGES_REQUESTED** [review]
@rollki I manually tested and it does work, the changes also look good to me. I do have one minor nitpick, could you update the release notes, so they are more meaningful to non-developers? Not everybody understands what grants mean etc...

**Comment by rollki** [comment]
Hi @nkoporec 
I have updated the release notes. They will not be completely understandable for a non-technical person, since only a technical person can understand what grants and access records are.

**Comment by navneet0693** [comment]
@rollki I request you to please add a change record here: https://www.drupal.org/node/add/changenotice?field_project=2125649&field_issue_links=https%3A//www.drupal.org/node/3318303

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3191-jgvorqfxufeld5n8r23nva9bhna4gdgl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63be6f145804da46db5b2c75

**Review by nkoporec — APPROVED** [review]

**Pull request merged**
