### PR TITLE
Issue #2867675 by alex.ksis, ribel: Set privacy for profile information fields

### PR DESCRIPTION
**Pull request by ribel**
Related Issue: https://www.drupal.org/node/2867675

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
@jochemvn if xinyu agrees you can merge this in the distro :)!

**Comment by NielsGG** [comment]
Hi @jochemvn, 

Just wondering why this is not merged in the distro yet. I know Xinyu saw some usability issues but isnt it better to have something in which is not perfect but still usable?

**Comment by jochemvn** [comment]
Hi @NielsGG ,
Xinyu had a very strong opinion on why he did not want to release this yet. Please contact him on slack for some more information about this. I know that we initially had the improvement story in the current sprint, but due to a lack of development hours, it was taken out again unfortunately.
Jochem

**Comment by jaapjan** [comment]
@bramtenhove  This one is ready to be reviewed. See the Behat test for the desired workflow :-)

HTT:

- [ ] Check the code and notice that it is an optional (and Expiremental) module.
- [ ] Check the code changes since it was last pushed by ECI. Most notable is: textual changes, support for User forms, rewrite to some common functions which can be re-used and made sure the module is optional.
- [ ] Install the module social_profile_privacy.
- [ ] Visit the social profile privacy admin configuration. Notice the default configuration should be that its only enabled for contact information on the user settings form and not for profile forms. Also notice the nice disclaimer 💯 
- [ ] Login as user X and make sure to fill in your profile information and go to your settings page (in the toolbar on top) and set your privacy so that other people will not be able to view your Phone number and address information.
- [ ] Login as user Y and go to the Information tab and verify that you can not see the phone number and address.
- [ ] Now login as administrator again and enable privacy settings for all the field groups.
- [ ] Login as User X and make sure all your fields are set to private.
- [ ] Login as User Y and see a nice message on the Information tab of user X "Username/name has not shared profile information."

@robertragas 

Changes for existing sites already using this module should be minimal. Just change your configuration file and reimport.  I've build the module flexible enough that you can enable the privacy switches on user form, profile form or both if you want to. Each it's own configuration. By default we will enable it on user forms only for just "Phone number and address" field group.

Let me know if you have any questions on how to handle this on existing sites.

**Pull request merged**
