### PR TITLE
Issue #3399224: Use composer lenient plugin to allow a patch for ensuring D10 coverage for color module in contrib.

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
`drupal/color` currently doesn't have a D10 compatible release yet, but is removed from Drupal 10 Core. 
So we need a patch to ensure it's D10 readiness, mainly for the `info.yml` file.

Because the `composer.json` of the contributed color module already correctly shows it's compatibility with both D9 and D10.

## Solution
At first we thought we might need the [lenient plugin](https://www.drupal.org/docs/develop/using-composer/using-drupals-lenient-composer-endpoint) to ensure we can use a patch within composer to have D10 coverage. 
It shouldn't be necessary and likely the patch should be enough. 

According to the precedence you see here: 
https://www.drupal.org/project/project_composer/issues/3084063#comment-13414884

## Issue tracker
https://www.drupal.org/project/social/issues/3399224

## How to test
See the color module installs on D10 and can be enabled correctly without any warnings on the Update status either.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
None.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3597-ybjcmxmipqz2hefuzbi0ykxxfiqjcyrn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654685f7f9aa9a0cfd134442

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3597-ybjcmxmipqz2hefuzbi0ykxxfiqjcyrn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654685f7f9aa9a0cfd134442

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3597-ybjcmxmipqz2hefuzbi0ykxxfiqjcyrn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654685f7f9aa9a0cfd134442

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3597-ybjcmxmipqz2hefuzbi0ykxxfiqjcyrn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654685f7f9aa9a0cfd134442

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3597-ybjcmxmipqz2hefuzbi0ykxxfiqjcyrn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654685f7f9aa9a0cfd134442

**Comment by Kingdutch** [comment]
> drupal/color currently doesn't have a D10 compatible release yet, but is removed from Drupal 10 Core.
So we need a patch to ensure it's D10 readiness, mainly for the info.yml file.
>
> Because the composer.json of the contributed color module already correctly shows it's compatibility with both D9 and D10.

I think this is false?

Composer allows 9 and 10: `"drupal/core": "^9.4 || ^10"`

The module's package info also allows 9.4, 10 (and 11) through: [`core_version_requirement: '>=9.4'`](https://git.drupalcode.org/project/color/-/blob/1.0.3/color.info.yml?ref_type=tags#L5)

**Comment by ronaldtebrake** [comment]
Doesn't seem to be needed, waiting for some more information.

**Pull request closed without merging**
