### PR TITLE
Issue #3442690: Rename "Basic Page" content type label into "Page"

### PR DESCRIPTION
**Pull request by tregismoreira**
## Problem/Motivation
Customers have indicated that the basic page label gets in the way. An underlying assumption is that they use these pages for generic website content and thus the type of content is less important. 

## Solution
Rename "Basic Page" content type label into "Page". 
We must make sure the existing tests will pass.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-24397
- https://www.drupal.org/project/social/issues/3442690

## Theme issue tracker
N/A

## How to test
- [ ] Create a basic page (`/node/add/page`)
- [ ] Note that on top of the page title, there is a "Page” label

image

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Rename "Basic Page" content type label into "Page".

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Review by ribel — COMMENTED** [review]
Changes were tested and all look good.
image

**Comment by ribel** [comment]
@ronaldtebrake I just want to check with you two things:
1. Since it is a low prio improvement is it fine to have it only in 13.0.0-alpha2?
2. Should we  add "Basic page" string to the [translations.php](https://github.com/goalgorilla/open_social/blob/main/translations.php) ?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Review by ribel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3875-qdcte4ywqosxryfc8kx4gzvstvhjw2ga.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6626bb690183f8d6e2ecf42c

**Pull request merged**
