### PR TITLE
Issue #3366365 by nkoporec: Tag text is cut when using social_follow_tag module and layout builder

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When using the social_follow_tag module together with layout builder and with 2 column layout then the tag text is cut and not displayed correctly.

## Solution
 Adjust the CSS so that the tag text is not cut off.

## Issue tracker
https://www.drupal.org/project/social/issues/3366365

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Enable social_follow_tag module and create a really long tag name.
2. Enable layout builder
3. Create a new page with layout builder and set a 2 column display
4. In one of the columns add the Social follow tag block and put something in the other (like content block)
5. Check the tag display.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Before:

After:

## Release notes
Fixed a styling issue where tag text in social follow tag block would be cut off when using it with layout builder and 2 column layouts.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Review by zanvidmar — APPROVED** [review]
LGTM

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3424-e8yg22jcb2qbce4wkgmhv9swedrmei4o.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64880ba04c72b346f2975ac4

**Comment by zanvidmar** [comment]
🍒 

Cherry-picked to 11.8.x here: [451b0862e](https://github.com/goalgorilla/open_social/commit/451b0862e46a0cba3b63482e128af796dfc595c4)
Cherry-picked to 11.9.x here: [237dccfee](https://github.com/goalgorilla/open_social/commit/237dccfeeabd159ab7bf03c98ed84162f82c67a2)

**Pull request merged**
