### PR TITLE
Issue #3326223 by vnech: Hide "Enroll" button on events with "Invite-only" joining

### PR DESCRIPTION
**Pull request by nechai**
## Problem
Extra **"Enroll"** button is visible on events with **"Invite-only"** joining method.

## Solution
Hide **"Enroll"** button on events with **"Invite-only"** joining method.

## Issue tracker
- https://www.drupal.org/project/social/issues/3326223
- https://getopensocial.atlassian.net/browse/PROD-23460

## Theme issue tracker
n/a

## How to test
- [x] Login as SM
- [x] Create an event with "Invite-only" join method
- [x] Invite any LU user to this event
- [x] Login as LU
- [x] Visit event main page

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
**Before:**
Screenshot 2022-12-09 at 14 08 11

**After:**
Screenshot 2022-12-09 at 14 37 28

## Release notes
Hide extra **"Enroll"** button on events with **"Invite-only"** joining method.

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Review by ribel — APPROVED** [review]
Hi @nechai 
Changes looks good to me and I see that they solve an issue.

@tbsiqueira, @navneet0693 It would be good to have this merged before next release.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3253-emgbcrkrhqtzvlqwocut9cny10jjuzlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932ca932d30df7ac38c86f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3253-emgbcrkrhqtzvlqwocut9cny10jjuzlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932ca932d30df7ac38c86f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3253-emgbcrkrhqtzvlqwocut9cny10jjuzlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932ca932d30df7ac38c86f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3253-emgbcrkrhqtzvlqwocut9cny10jjuzlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932ca932d30df7ac38c86f

**Review by robertragas — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3253-emgbcrkrhqtzvlqwocut9cny10jjuzlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932ca932d30df7ac38c86f

**Comment by robertragas** [comment]
Reviewed / approved / merged and cherry-picked to 11.6.x and 11.5.x

**Pull request merged**
