### PR TITLE
Issue #3295901 by robertragas: refactor social core dashboard homepage block

### PR DESCRIPTION
**Pull request by robertragas**
The dashboard core block is a menu link rendered on every page where the toolbar is present. This menulink is rendered dynamicly and because of the different menu context also hard to cache. This causes it to be loaded multiple times over multiple pages causing performance downgrade. This change refactors the homepage block to be set to a static link where we will redirect to the correct page when the link has been clicked. Elimating the need to execute this on every page.

## Problem
The dashboard core block is a menu link rendered on every page where the toolbar is present. This menulink is rendered dynamically and because of the different menu context also hard to cache. This causes it to be loaded multiple times over multiple pages causing performance downgrade.

## Solution
Refactor the homepage block to be set to a static link where we will redirect to the correct page when the link has been clicked. Eliminating the need to execute this on every page.

## Issue tracker
https://www.drupal.org/project/social/issues/3295901

## How to test
- [ ] Load any page with a role that has the side toolbar (cm+) and see how the function getHeroBlockSettings() gets loaded multiple times.
- [ ] Now checkout to this branch and see it only get's loaded once you click on it.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
No visual change but just to show which menu link we are talking about.

## Release notes
We have altered the way the "customize home page" link is rendered by doing the calculating once someone presses on the link. Avoiding unnecessary load on every page.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3037-vf3iq1ydideivrlmgaudtd7dhiwrlnvk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62cfbf089f9e1fc1eb6272a1

**Comment by navneet0693** [comment]
@robertragas Please rebase your PR branch, so that behat tests can kick in.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3037-vf3iq1ydideivrlmgaudtd7dhiwrlnvk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62cfbf089f9e1fc1eb6272a1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3037-vf3iq1ydideivrlmgaudtd7dhiwrlnvk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62cfbf089f9e1fc1eb6272a1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3037-vf3iq1ydideivrlmgaudtd7dhiwrlnvk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62cfbf089f9e1fc1eb6272a1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3037-vf3iq1ydideivrlmgaudtd7dhiwrlnvk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62cfbf089f9e1fc1eb6272a1

**Comment by tbsiqueira** [comment]
Cherry picked to 11.1.x, 11.2.x 11.3.x and 11.4.x

**Pull request merged**
