### PR TITLE
Issue #3398146: CKEditor 5 isn't respecting width limit

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Social Base is customize the CKEditor 5 layout and currently it will impacting the width limit from entity create page.

## Solution
Apply a patch to fix the width layout bug.

## Issue tracker
Social issue: [#3398146](https://www.drupal.org/project/social/issues/3398146)
Social Base issue: [#3398140](https://www.drupal.org/project/socialbase/issues/3398140)

## Theme issue tracker
N/A

## How to test
- [ ] Try to create any content and check CKEditor 5 width is respecting the page limit.
 
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by vcsvinicius** [comment]
This PR only can be merged after Drupal 10 upgrade.

**Comment by robertragas** [comment]
I checked it out while testing https://github.com/goalgorilla/open_social/pull/3578/files (d10) and its working for me. 

But what do you mean with that it can only be merged after d10? will this css break other stuff if we are not on d10 yet? because it's just a simple css specific to certain classes. As it's also specific in the ckeditor5 stylesheet already.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Review by robertragas — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3585-dyfcrtdvl1luww5escihwayjrwqzuxex.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654145d7cbeeaba7d08942dd

**Comment by robertragas** [comment]
Merged and cherry-picked to 12.0.x

**Pull request merged**
