### PR TITLE
Issue #3404422 by SV: Is not possible to translate a title on the "Add event" page

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

Screenshot 2023-11-27 at 17 59 40 v2

## Solution

The title should be fully translated on the create event page - so, the article should be wrapped with t() and then it will be properly displayed in:
 >     return $this->t('Create @article @name', [
 >      '@article' => $titles[$entity_type_id]['bundles'][$entity_type->id()] ?? 'a',
 >      '@name' => mb_strtolower($label),
 >    ])->render(); 

## Issue tracker

- https://www.drupal.org/project/social/issues/3404422
- https://getopensocial.atlassian.net/browse/PROD-27093

## Theme issue tracker

N/A

## How to test
- [ ] Using the latest version of Open Social with more then 1 languages on the site
- [ ] As LU with different language then default one
- [ ] Try to create a new event
- [ ] When i opened the page the title should be fully translated but instead see it only partly.
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

N/A

## Release notes

Fixes the issue with translation of title on the create event page

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3624-3wdjk6ugrraa9gwwmiy444hxccwuzgoy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6564c4a80ccea0f75fd56361

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3624-3wdjk6ugrraa9gwwmiy444hxccwuzgoy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6564c4a80ccea0f75fd56361

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3624-3wdjk6ugrraa9gwwmiy444hxccwuzgoy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6564c4a80ccea0f75fd56361

**Review by ribel — APPROVED** [review]
Since we already have `a/an` articles wrapped in `t()` functuon in the `social_follow_taxonomy_tokens()` changes here looks good to me as well.

**Comment by ribel** [comment]
🍒 picked to the 12.0.x

**Pull request merged**
