### PR TITLE
Issue 3216000 by nkoporec: Remove body field from Outlook add to calendar link

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
The problem is that Outlook.com is only allowing up to 2056 characters URL length. Since we are passing title + body text this limit can easily be hit. Moreover when the user is not logged in, the Outlook.com will upon log in add additional characters to the URL (due to some encoding/security measures), which means that if the user is not logged in it will be more likely to hit that limit/

I have test it by creating an event with only title and no body and the link work for me in both cases(logged in and logged out from Outlook.com), then tested with a longer body and it did not work.

There are some open issues regarding this:
https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/issues/19

## Solution
Since this is an issue on the Outlook side, we can't do much except limiting the number of characters sent to Outlook, so that the URL
will never hit the limit. The most straightforward way to do it is to remove the body field as it is not so important.

## Issue tracker
https://www.drupal.org/project/social/issues/3216000

## How to test
1. Enable Social Event Add To Calendar module
2. Enable add to calendar links (Outlook) at /admin/config/opensocial/event-addtocal
3. Create a new event with title and a longer body (400+ characters)
4. Click add to calendar -> Outlook

## Screenshots
Before:
Screenshot from 2021-05-27 10-57-51

After:
Screenshot from 2021-05-27 10-59-09

## Release notes
- Fixed issue with Outlook.com add to calendar link

### CODE REVIEW

**Review by nachosalvador — APPROVED** [review]

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2356-uunucvsi8nn4ornyeqqemcho8w1vibnb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9c4cfc82560d1e63e936b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2356-uunucvsi8nn4ornyeqqemcho8w1vibnb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9c4cfc82560d1e63e936b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2356-0r7kqj876jbtz74xp7vldiemfu1aoy1b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d0ec7331d467caf637a0b

**Comment by navneet0693** [comment]
🍒 - picked to 10.2.x and 10.1.x

**Pull request merged**
