### PR TITLE
Issue #3144794: Hero block display based on path is too fragile

### PR DESCRIPTION
**Pull request by Ressinel**
Related PR https://github.com/goalgorilla/open_social/pull/1960

## Problem
There is an issue of duplicate Hero Blocks when the URL has one of the words `add`, `edit`, or `delete`.

## Solution
Correct visibility settings for socialblue_pagetitleblock_content block.

## Issue tracker
- https://www.drupal.org/project/social/issues/3144794

## Theme issue tracker
N/A

## How to test
It is reproducible only in some environments but not on vanilla Open Social.
- [ ] Create a topic with a URL that has one of the words `add`, `edit`, or `delete`. E.g. `/topic/test-added-topic`
- [ ] You will see duplicate Hero Blocks
- [ ] Apply changes from this PR
- [ ] Re-do previous steps
- [ ] You should not see duplicate Hero Blocks

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
175a660e80186c1b149435085a0e7d75

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2968-mjakkqbp24uc7nivdjfue9gymshzmcxf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629648b66eb9e7df1a3cb167

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2968-mjakkqbp24uc7nivdjfue9gymshzmcxf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629648b66eb9e7df1a3cb167

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2968-mjakkqbp24uc7nivdjfue9gymshzmcxf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629648b66eb9e7df1a3cb167

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2968-mjakkqbp24uc7nivdjfue9gymshzmcxf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629648b66eb9e7df1a3cb167

**Comment by navneet0693** [comment]
@Ressinel What is the correct status of this PR? Does it need review or needs work? The PR is still in draft, please close it if it is not relevant anymore.

**Comment by Ressinel** [comment]
@navneet0693 It is relevant and needs additional work.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2968-mjakkqbp24uc7nivdjfue9gymshzmcxf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629648b66eb9e7df1a3cb167

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
🍒 - picked to 11.4.x. The update hook numbers are not compatible with versions below this.

**Comment by navneet0693** [comment]
@Ressinel You may need to backport this manually.

**Pull request merged**
