### PR TITLE
Issue #3173585 - Private content explore

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Follow up on https://github.com/goalgorilla/open_social/pull/1998. This added regressions in /explore page where :

1. As AN, the user could only see the public post, not the public events nor topics.

2. As a LU, the user could see the public posts and events, not the public topics.

## Solution
1. Revert https://github.com/goalgorilla/open_social/pull/1998
2. Add a new filter to be added only on the "/explore" page

## Issue tracker
https://www.drupal.org/project/social/issues/3173585

## How to test
- [ ] As LU 1, Create a public, closed, open, or flexible group.
- [ ] Create a topic and event with different visibility
- [ ] Run cron
- [ ] Go to /explore as LU 2 (different user)
- [ ] You should not see any updates regarding the creation of the contents as per visibility.

## Screenshots
N.A

## Release notes
Activity stream has been modified to make it more personalized and different from /explore page.

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by navneet0693** [comment]
We might also want to backport this https://github.com/goalgorilla/open_social/pull/1942 to as this PR changes views.view.activity_stream.yml at Line 341.

**Review by sjoerdvandervis — APPROVED** [review]
Works perfect for me!

**Comment by ronaldtebrake** [comment]
@navneet0693 the tests arent passing here, could you maybe update them for the 8.9 release of January? :) these tests do seem related.

**Review by ronaldtebrake — APPROVED** [review]

**Comment by navneet0693** [comment]
🍒 picked to 8.x-9.x

**Pull request merged**
