### PR TITLE
update search_api to 8.x-1.15

### PR DESCRIPTION
**Pull request by slowflyer**
## Task
Update search_api to fullfill all dependencies for latest search_api_solr

## Issue tracker
https://www.drupal.org/project/social/issues/3124533

## How to test
- [ ] Wait for Travis to be green it should have test coverage for search

## Release Notes
The Search API module has been updated to version 1.15 which should fix an issue with the latest version of search_api_solr.

### CODE REVIEW

**Comment by Kingdutch** [comment]
Looks like this will need some work due to at least the following note in the 1.16 release notes for Search API.

> Due to #3111635: Duplicate dependencies, new index exports will differ substantially from earlier versions after this release. It is advised to re-export all exported search indexes, stored in any config directory or the like, after updating to this release, to avoid confusion when actual changes are later made.

**Comment by Kingdutch** [comment]
The following issue is of interest to us and should receive an internal follow-up for test improvement and developer education: https://www.drupal.org/node/3115214 (Add Search API support for Behat Drupal Extension)

**Comment by Kingdutch** [comment]
The two above comments are specifically for version 1.16 of the Search API module. If it solves a concrete problem then I do not have an issue with updating to Search API 1.15 without any additional work, based on the release notes for that version :)

**Comment by slowflyer** [comment]
Than 1.15 should be fine for the moment!

**Comment by Kingdutch** [comment]
Force pushed to set back the version number, fix a merge conflict and make backporting to 8.x easier.

A follow-up with the above comments for 1.16 has been made in https://www.drupal.org/project/social/issues/3131799

This can be merged once Travis is green.

**Comment by ronaldtebrake** [comment]
Als in 8.x :) thanks

**Pull request merged**
