### PR TITLE
Issue #3282031 by navneet0693: Email subjects in message templates are not translatable.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Follow up of #2946 

The email subjects are not being detected in weblate and also POTX tool is not able to extract them for translations.

## Solution
Add them to translations.php file for enabling to detect and translate them.

## Issue tracker
https://www.drupal.org/project/social/issues/3282031

## Theme issue tracker
N.A

## How to test
- [ ] Checkout to this branch
- [ ] `drush cr; drush updb -y`
- [ ] Follow the steps on the original PR

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
- [ ] Source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2980-wzywsd6pflmdiaxvwfcgpl51bugwpqoe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629f482bc1600d72c50530a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2980-wzywsd6pflmdiaxvwfcgpl51bugwpqoe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629f482bc1600d72c50530a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2980-wzywsd6pflmdiaxvwfcgpl51bugwpqoe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629f482bc1600d72c50530a0

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr2980-wzywsd6pflmdiaxvwfcgpl51bugwpqoe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/629f482bc1600d72c50530a0

**Pull request merged**
