### PR TITLE
Issue #3102720 by epapaniko, Ressinel: Search form submit redirects to the wrong path when the installation is under a subdirectory.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
When Social is installed under a domain's directory, ex. http://www.example.com/social/, search forms and their exposed filters redirect to the wrong path once submitted.

Specifically, SearchContentForm and SearchHeroForm use Url::fromUserInput() which includes the base path resulting in a url like the following http://www.example.com/social/social/search/content/term.

The exposed filters of the form present the opposite problem; when submitting, they strip the base path from the url, so we end up with something like http://www.example.com/search/content/term?type=event

## Solution
N/A

## Issue tracker
- https://www.drupal.org/project/social/issues/3102720

## How to test
- [ ] Install **OpenSocial** in domain's directory e.g. http://www.example.com/social/
- [ ] Go to installed **OpenSocial** and click on the search icon
- [ ] Input text `I search this text` into the search field and press `Enter`
- [ ] You will be redirected to the page with the status `Page not found` http://www.example.com/social/social/search/all/I%2520search%2520this%2520text
- [ ] Checkout to this PR's branch
- [ ] Go to installed **OpenSocial** and click on the search icon
- [ ] Input text `I search this text` into the search field and press `Enter`
- [ ] You will be redirected to the right page http://www.example.com/social/search/all/I%20search%20this%20text

## Screenshots
N/A

## Release notes
Fix issue where search form submit redirects to the wrong path when the installation is under a subdirectory.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2603-oz7k9otcrd2dh8mjrb5euyvmejoje9mq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618d3fb2908ae1097c57cf06

**Comment by ribel** [comment]
Hi @Ressinel,
We have the same issue with one of our projects. This patch helps, but I still noticed one issue with the search users tab.
I have fixed it in `RedirectSubscriber.php` tested locally and pushed here. Please check if it looks good for you.
Also, since this is actually a bug fix, can we include it in the 10.3.2 milestone?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2603-oz7k9otcrd2dh8mjrb5euyvmejoje9mq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/618d3fb2908ae1097c57cf06

**Comment by Ressinel** [comment]
Hi @ribel 

Yes, you are right. I was able to reproduce the issue with the search users tab as well.
I have checked your changes and they look good to me.
Milestone has been chaneged to `10.3.2` as well.

**Comment by Ressinel** [comment]
@ribel Could you review the changes I added?

**Review by ribel — APPROVED** [review]
Hi @Ressinel,
Changes look good to me and we already use this PR as a patch on a project installed in a subdirectory.
Can I merge it then?

**Comment by Ressinel** [comment]
@ribel yep

**Comment by ribel** [comment]
🍒 picked to 10.3.x

**Pull request merged**
