### PR TITLE
Internal: Add Behat test linting to CI workflow

### PR DESCRIPTION
**Pull request by Kingdutch**
This should be merged after https://github.com/goalgorilla/open_social/pull/3625

## Problem 
Our Behat test writing is somewhat inconsistent and feedback on Behat related PRs is often very similar encouraging best practices outline in our developer handbook.

## Solution
This adds two checks to the quality checks in the CI.

1. Check that all test files are named using lowercase kebab-case
containing only letters and numbers. This ensures consistent filenaming.

2. Run the features themselves through Cucumber Linter which provides
common feedback about how to structure a test file and make it readable.

Logic is implemented to only run this on files that are added or
modified (skipping deleted files) because we have a lot of existing
tests and we don't want to have complaints about all of them for every
PR that doesn't touch them.

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-27812

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] CI should fail for the debug commits
- [ ] CI should pass without debug commits

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

Incorrect filenames properly fails the check and annotates the file :D 

image

Incorrect tags or step choices are flagged and annotated in the file diff.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by Kingdutch** [comment]
Modified a known bad file (which had a correct name) to show that errors are reported properly after the changes to logic made in the previous force pushes

image

**Comment by Kingdutch** [comment]
Force pushed with a removal of the previous debug and modified an incorrectly named file which is also still properly detected.

image

Now force pushing without any debug commits which should be all green.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3626-j2pake4edrpc9jllafmscubeq9qruefv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6567452d5d2bde9a88d908d0

**Comment by Kingdutch** [comment]
All green if no test files are changed in a PR.

image


That satisfies all requirements, merging :D

**Comment by ronaldtebrake** [comment]
Awesome, thanks for that @Kingdutch!

**Review by ronaldtebrake — APPROVED** [review]

**Pull request merged**
