### PR TITLE
Issue #3274467 by tBKoT: Shows content in group on the search page

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
Users cannot see content on the search pages with the `Group members` visibility even if the user is a member of the attached group. The main problem is that search API uses realms to check node access. The `entity_access_by_field` provides node grants for the user, but it works only if that user is an author of created content because the verified does not have permissions like `view node.<node_type>.field_content_visibility:group content`.

## Solution
As a solution, we could add realms provided by the `gnode` module to the search index and alter the grants list to remove groups where the user is not a member.

## Issue tracker
https://www.drupal.org/project/social/issues/3274467

## Theme issue tracker
N/A

## How to test
- [x] Using the latest version of Open Social
- [x] As a CM+
- [x] Create the Flexible group
- [x] Group should be open to joining and visible to users
- [x] The `Group members` in `Group content visibility options` should be selected
- [x] Create a content (topic, event, etc.)
- [x] Attach to the create group
- [x] Set `Group member` visibility
- [x] Index the `Social content` search index
- [x] As a verified
- [x] Join the created group
- [x] You should have access to view newly created content in the group
- [x] Go to the content search page
- [x] You cannot see the content to which you have access

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Fix issue when the user can't see the content to which he has access on the search pages.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2872-cfhuepjp7qrnawypr9clbqxpqke4ux9z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253f7c37a1d628954d6ca47

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2872-cfhuepjp7qrnawypr9clbqxpqke4ux9z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253f7c37a1d628954d6ca47

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2872-cfhuepjp7qrnawypr9clbqxpqke4ux9z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253f7c37a1d628954d6ca47

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2872-cfhuepjp7qrnawypr9clbqxpqke4ux9z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6253f7c37a1d628954d6ca47

**Comment by navneet0693** [comment]
@dmytriikaiun Please see the comments on this PR. Also, I request you rebase this PR.

**Review by Ressinel — APPROVED** [review]
LGTM

**Pull request merged**
