### PR TITLE
PROD-30709: Bump better_exposed_filters to 7.0.1

### PR DESCRIPTION
**Pull request by denis-getopensocial**
## Problem

Update drupal/better_exposed_filters requirement from 6.0.6 to 7.0.1

## Solution

Update drupal/better_exposed_filters requirement from 6.0.6 to 7.0.1

## Issue tracker

https://getopensocial.atlassian.net/browse/PROD-30709

## How to test

- Test if the search still works
- Test if the page /group/X/membership still works.

## Release notes

Update better_exposed_filter to the latest version.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by BiaInacio** [comment]
Search and Group menage members page are working as expected!
image
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Review by vcsvinicius — APPROVED** [review]
I approved

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4100-lh00szjvzanq1v2vr5ttjy2nfc7lr1lj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66faacf01af7a30928d046bb

**Pull request closed without merging**
