### PR TITLE
Issue #3114669: Update Profile to 1.1

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
Profile module needs to be updated to 1.1.

## Solution
Change Profile dependency to 1.1. I also added `^` so we make it easier for other people to update without us releasing a new version.

We came from `1.0-rc6`, there are some more changes we need to look at: https://git.drupalcode.org/project/profile/compare/8.x-1.0-rc6...8.x-1.1.

## Issue tracker
https://www.drupal.org/project/social/issues/3114669

## How to test
- [ ] Ensure social_profile_privacy works still after routes have been updated
- [ ] Try some other profile things

## Release notes
n/a

### CODE REVIEW

**Comment by Kingdutch** [comment]
This also duplicates #1562  - https://www.drupal.org/project/social/issues/3088366

**Comment by ronaldtebrake** [comment]
Screen Shot 2020-02-21 at 10 27 28
Test run fine locally :) rekicking travis though but should be ready for review.

**Comment by ronaldtebrake** [comment]
Cherry-picked to 8.x and 7.x

**Comment by ronaldtebrake** [comment]
Screen Shot 2020-02-25 at 15 33 30

Oh and FYI - Travis was green :) the only failure was on the security dependency check.

**Pull request merged**
