### PR TITLE
Theme a11y Q&A

### PR DESCRIPTION
**Pull request by Kingdutch**
PR for Tugboat

Stages changes for https://www.drupal.org/project/social/issues/3179425#comment-14182969

### CODE REVIEW

**Comment by Kingdutch** [comment]
Looks like Drupal.org doesn't publish dev branches on composer. Will modify the composer.json to use a dynamic patch instead when I get around to testing this, will close this PR when done :)

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2454-jcbja9y9huhrgtydtofrqbrheuww4qe3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611394db378c5f465f7c62b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2454-jcbja9y9huhrgtydtofrqbrheuww4qe3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611394db378c5f465f7c62b1

**Comment by Kingdutch** [comment]
The things that this was testing on Tugboat have since been merged 🎉

**Pull request closed without merging**
