### PR TITLE
Issue #3010020 by truls1502: Update image_effects 1.0 to 2.2

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](http://cgit.drupalcode.org/image_effects/diff/?h=8.x-2.x&id=8.x-2.1=id2=8.x-1.0)
- https://www.drupal.org/project/image_effects/releases/8.x-1.1
- https://www.drupal.org/project/image_effects/releases/8.x-2.0
- https://www.drupal.org/project/image_effects/releases/8.x-2.1
- https://www.drupal.org/project/image_effects/releases/8.x-2.2

## Issue tracker
- https://www.drupal.org/project/social/issues/3010020

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by truls1502** [comment]
I was typo in make-file. It has been corrected :)

**Comment by jaapjan** [comment]
FYI: file_mdm is added as per:
https://www.drupal.org/node/2856573

**Comment by ronaldtebrake** [comment]
Also cherry-picked to 4.x and 5.x!

**Comment by truls1502** [comment]
Great 👍 

I just thought it could post on multiple milestones, but no.

**Pull request merged**
