### PR TITLE
DS-2424 - Event types (optional sub-module)

### PR DESCRIPTION
**Pull request by jochemvn**
## HTT

- [x] Check the code

- [x] Switch to this branch and install social_event_types

- [x] Enable social_demo module

- [x] Add event types demo content: "drush sda eventtype"

- [x] Add an event and see that the event type radio is on top (not mandatory)

- [x] Alternatively as a SM go to "configuration >> opensocial settings >> event type settings and play around with those

- [x] Also as a SM add some taxonomy terms for event_types

- [x] Test the filters on: Explore events / User events / Group events

- [x] Uninstall the module: drush pm-uninstall social_event_type

- [x] Notice the filters are gone

- [x] Notice the field no longer appears in the node add/edit form

**WHEN THEMING IS DONE:**

- [x] See that the event type reflects in the teaser

- [x] See that the event type reflects on full node

- [x] Notice you can click on the event type and it takes you to the all events overview with the event type preselected. Also the correct date type is selected (past or future events)

### CODE REVIEW

**Comment by peterpolman** [comment]
Theming is done in PR https://github.com/goalgorilla/open_social/pull/223

**Comment by jochemvn** [comment]
@ronaldtebrake: Can you check the latest steps form the HTT?
@peterpolman: I've also looked at your todo and fixed it. A quick peek is appreciated.

**Comment by ronaldtebrake** [comment]
@jochemvn , done works well :) restarted the build just to be sure about tests eventhough we know its the false negative again

**Comment by peterpolman** [comment]
@jochemvn All clear, thanks!

**Pull request merged**
