### PR TITLE
Issue #3222539 by tBKoT: Allow users to add profile tags to the profile

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
Regarding the [original AC](https://getopensocial.atlassian.net/browse/YANG-5091) of the PR #2271 LU should be able to add profile tags to his/her profile but now it is possible only for the CM+ users.

## Solution
Add new setting `allow_tagging_for_lu` which allows regular users to add profile tags to their profiles.

## Issue tracker

- https://www.drupal.org/project/social/issues/3222539
- https://getopensocial.atlassian.net/browse/YANG-5924
- https://github.com/goalgorilla/open_social/pull/2271
- https://github.com/goalgorilla/open_social/pull/35

## How to test
- [x] Using version 10.2.x of Open Social
- [x] Login as CM+ and go to profile edit page
- [x] You are able to add profile tags
- [x] Loggin as LU user and go to profile edit page
- [x] You are not able to add profile tags

### LU
зображення
### CM+ 
зображення

## Release notes
Now authenticated users can add profile tags to their profiles.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Review by Ressinel — APPROVED** [review]
Hi @dmytriikaiun 

Good work!
Works as expected.

Thanks!

**Review by ribel — CHANGES_REQUESTED** [review]
@dmytriikaiun With the permission change here we may break backward compatibility and disclose some information that was previously available only for higher roles to regular users. 

We need to keep in mind that the Profile tagging feature was developed [5 years](https://getopensocial.atlassian.net/browse/DS-1874) ago and might be used on multiple sites which we don't know. There it stays:

>  Only CM or higher can edit Profile tags on profile (You can't do it on your own profile)

That's why just changing permission is not enough. I think we need to make `enable_profile_tagging` disabled by default as well as the permission `edit profile tags`

If needed you may also consider other options:

- Add two separate settings (and/or permissions): Allow profile tagging for CM+, Allow Profile tagging for LU
- By default enable Profile tagging only for CM+, and when `enable_profile_tagging` is enabled open it for LU.

@ronaldtebrake I would like to hear your thoughts as well, since you reviewed the previous PR and was involved in the development of the original feature.

**Comment by dmytriikaiun** [comment]
@ribel I've added a new option to allow profile tagging for LU on the profile settings form. For CM+ I've left the old `Allow profiles to be tagged` and reverted previous changes, so now LU will not have the `edit profile tags`

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2405-z3wvpwwgczrx4mwsr0qfpwqpcyftcgfa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ec7ba33989c2b20c3827fc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2405-z3wvpwwgczrx4mwsr0qfpwqpcyftcgfa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ec7ba33989c2b20c3827fc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2405-z3wvpwwgczrx4mwsr0qfpwqpcyftcgfa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ec7ba33989c2b20c3827fc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2405-z3wvpwwgczrx4mwsr0qfpwqpcyftcgfa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ec7ba33989c2b20c3827fc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2405-z3wvpwwgczrx4mwsr0qfpwqpcyftcgfa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ec7ba33989c2b20c3827fc

**Review by ribel — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
> @dmytriikaiun With the permission change here we may break backward compatibility and disclose some information that was previously available only for higher roles to regular users.
> 
> We need to keep in mind that the Profile tagging feature was developed [5 years](https://getopensocial.atlassian.net/browse/DS-1874) ago and might be used on multiple sites which we don't know. There it stays:
> 
> > Only CM or higher can edit Profile tags on profile (You can't do it on your own profile)
> 
> That's why just changing permission is not enough. I think we need to make `enable_profile_tagging` disabled by default as well as the permission `edit profile tags`
> 
> If needed you may also consider other options:
> 
> * Add two separate settings (and/or permissions): Allow profile tagging for CM+, Allow Profile tagging for LU
> * By default enable Profile tagging only for CM+, and when `enable_profile_tagging` is enabled open it for LU.
> 
> @ronaldtebrake I would like to hear your thoughts as well, since you reviewed the previous PR and was involved in the development of the original feature.

Good observations!

I'm happy to have it in 10.3 in the current format. By having the permission set to false, I think we actually have got it covered. The only thing that is different is the actual adding/editting, the viewing part wasn't changed so I don't think there is actually much to worry about now it's set to false by default. 

So for me in the current shape it's good to go for 10.3 :D nice

**Comment by ribel** [comment]
@ronaldtebrake Thanks!
Just wondering, since we released PR #2271 in 10.2, shouldn't we release this one in 10.2.x, since this is more like a regression fix rather than a new feature imo?

**Comment by ronaldtebrake** [comment]
Ah correct @ribel :D

**Pull request merged**
