### PR TITLE
Issue #3360661 - Url Embed - preg_split in _filter_url breaks for long html tags

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
Having a really long HTML tag (e.g. < img > with src:data/image...) makes preg_split fail and return false. On PHP 7.4 this throws a warning ("Warning: count(): Parameter must be an array or an object that implements Countable in _filter_url() (line 535 of core/modules/filter/filter.module).") and makes the field render empty, on PHP 8.0 this throws a fatal error.

## Solution
If $chunks is empty, keep $text.

## Issue tracker
https://www.drupal.org/project/social/issues/3360661

## How to test
- [ ] Have a text format that has Convert URLs into links enabled
- [ ] Using that text format, add a node with content like this: https://gist.github.com/kporras07/618b3bf4cd77ff57fcd5034262220e99
- [ ] Visit the node / or try to re-index search api
- [ ] You will get the warning and empty node or the fatal error depending on your PHP version

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
*[Required if new feature, and if applicable] If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Review by nkoporec — APPROVED** [review]
LGTM, @robertragas can you check the failed tests, it looks like a false positive, after everything is green, I think it safe to merge this.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3399-vjprsl8nxuf0y2xutwzjpfzbhrm7o23i.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64636ad2718fa8418d6e0950

**Pull request merged**
