### PR TITLE
Issue #3262837 by ronaldtebrake: Remove Social Lazy Loading Image and Upgrade Drupal Lazy Load to 3.x

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Drupal core now ships with native lazy loading for images.
This means we can finally phase out our Social Lazy Loading Image module.
See: https://www.drupal.org/node/3173719

## Solution
Deprecate / Uninstall `social_lazy_loading_images`
Remove `blazy` from all the packages (composer / npm) as lazy-load now uses lazysizes library for rich features.
Migrate the Overriddes/Preprocesses to the new lazy-load functionality

## Issue tracker
https://www.drupal.org/project/social/issues/3262837

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Make sure the module social_lazy_loading_images is disabled
- [ ] Create a new topic and upload an image
- [ ] Use developer tools and inspect the image, make sure it contains the attribute `loading='lazy'`
- [ ] Test other images as well.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
Social Lazy Loading Images module is now deprecated, Drupal core now ships with core support for lazy loading images.

## Change Record
Social Lazy Loading module has been marked as deprecated, as we are moving to native browser lazy loading. The core lazy loading works in similar way, so therefore this is not a breaking change and it should not affect anything.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by BiaInacio** [comment]
Topic image as well as user image and stream images are being displayed with the "loading="lazy"" tag!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by robertragas** [comment]
Few questions, could be that i'm not testing it right or missing configuration.

1. Is the milestone correct or should it be 12? because in our social_lazy_loading we have an alter hook to disable the lazy loading if you don't want to. Since we don't have this anymore people have to alter this hook, making it backwards breaking.
2. I also see the lazy tag but when minimising my screen it looks like it's still loading everything straight from the start

Without social lazy loading module and clearing network tab when scrolling this shows up
Screenshot 2023-10-13 at 15 23 47

With social lazy loading module and clearing network tab when scrolling this shows up
Screenshot 2023-10-13 at 15 24 31

**Comment by nkoporec** [comment]
@robertragas 

1. Yes you are correct, did not catch that , I updated the milestone.
2. I tested this and for me the images are lazy loaded, steps I took:

 - Go to Tugboat env and log in as user `benflorez`
 - Go to /stream page and open up the network tab
 - Clear the network tab
 - Start scrolling.
 - The images are loaded as I scroll.
 - The social_lazy_images module is disabled.

Can you maybe show a screen recording as it seems like I can't really reproduce it.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by robertragas** [comment]
As discussed, the core lazy works a bit different than the contrib lazy load as in html behaviour vs javascript injection.
Differences that were spotted are for example the loading on the slow 3g throttle acts a bit differently.

We are going more towards the native implementation so approving this.

But @nkoporec could you update the change record of this PR with the removal of the api hook, and that our core lazy can  behave a bit differently and that therefore it's not BC.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Review by ronaldtebrake — CHANGES_REQUESTED** [review]
I think this also needs to be removed from `social_lazy_loading.install`

```
/**
 * Implements hook_install().
 *
 * Perform actions related to the installation of social_language.
 */
function social_lazy_loading_install() {
  // Enable the submodule, it's standalone so don't depend on it.
  install_lazy_loading_images();
}

/**
 * Function that enables the lazy loading images module.
 */
function install_lazy_loading_images() {
  $module = [
    'social_lazy_loading_images',
  ];

  \Drupal::service('module_installer')->install($module);
}

/**
 * Install social_lazy_loading_images module.
 */
function social_lazy_loading_update_8601() {
  install_lazy_loading_images();
}
```

**Comment by nkoporec** [comment]
@robertragas I updated the change records, not sure what you meant by removing the api hook ? 
@ronaldtebrake  I removed the install hooks.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3555-whlwaghkf67r9uorgzfump9wtqkvjiz8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/652558eef57766838bb06ad5

**Comment by ronaldtebrake** [comment]
I've added a release note draft here: https://www.drupal.org/node/3396600

**Pull request merged**
