### PR TITLE
 Issue #3209986 by nkoporec: The 'Newest members' block is not displaying correctly

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
If you enable social tagging module and set profile tagging then the 'Newest Members' block stops showing users.

## Solution
Only alter the config when on view.newest_users.page_newest_users display.

## Issue tracker
https://www.drupal.org/project/social/issues/3209986

## How to test
1. Enable social_tagging module
2. Set profile tagging
3. Check the 'Newest members' block

## Screenshots
Screen Shot 2021-04-14 at 11 09 44 AM

### CODE REVIEW

**Comment by robertragas** [comment]
@nkoporec we still need to fix the PHP Stan issues here.

**Comment by nkoporec** [comment]
@robertragas I have update the PR with fixes for phpstan.

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-qw6wzmabbwdwfjdbkzby1ioj1tgw5ooj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d12ec8256033bb3ea31f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-qw6wzmabbwdwfjdbkzby1ioj1tgw5ooj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d12ec8256033bb3ea31f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-qw6wzmabbwdwfjdbkzby1ioj1tgw5ooj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d12ec8256033bb3ea31f

**Comment by robertragas** [comment]
Restarted for Travis 1 more time, already ran behat tests locally which did not fail, but want to double check, as the social_ajax_comment error is about the social tagging override and our code does touch this code, so want to make sure there is no relation here.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-qw6wzmabbwdwfjdbkzby1ioj1tgw5ooj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c9d12ec8256033bb3ea31f

**Comment by navneet0693** [comment]
One more time 🙈

**Comment by navneet0693** [comment]
@nkoporec Please rebase/merge the latest main branch.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-5t1x2y2uszy20j80urcmngyplvniikvt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61714d8e8c559d9e8d1b5a64

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-5t1x2y2uszy20j80urcmngyplvniikvt.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61714d8e8c559d9e8d1b5a64

**Comment by nkoporec** [comment]
> @nkoporec Please rebase/merge the latest main branch.

done

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-mcnkqsng8wtublcawpbq696bzywc2q4h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e57911f67b7c778cfcc6b8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-mcnkqsng8wtublcawpbq696bzywc2q4h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e57911f67b7c778cfcc6b8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-mcnkqsng8wtublcawpbq696bzywc2q4h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e57911f67b7c778cfcc6b8

**Comment by navneet0693** [comment]
@nkoporec The failure of Travis seems to be genuine, please take a look.

**Comment by navneet0693** [comment]
@nkoporec Please rebase your PR's branch with main.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-z5hypfw7skwfjtzbfbmyauidnqum8oom.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625e6648dd48a44089f27ec6

**Comment by nkoporec** [comment]
@robertragas @NickDaelemans Can you re-review the PR ?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2299-z5hypfw7skwfjtzbfbmyauidnqum8oom.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625e6648dd48a44089f27ec6

**Comment by Ressinel** [comment]
@nkoporec Rebase/merge the latest main branch, please.

**Comment by Ressinel** [comment]
Hi, @nkoporec 
Rebase/merge the latest main branch, please.

**Review by tbsiqueira — APPROVED** [review]

**Comment by nkoporec** [comment]
This has been fixed by https://github.com/goalgorilla/open_social/commit/751fd93513dc358ca64d1a16e270d223c6b1d28b, so closing the PR.

**Pull request closed without merging**
