### PR TITLE
Issue #3408511 by nkoporec: Replace renderRoot() with renderPlain() when trying to render a notifiication in an email

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
The renderRoot() should be used as a response to a controller. If we use the renderRoot or render() methods incorrectly it can produce warnings such as:

`LogicException: Render context is empty, because render() was called outside of a renderRoot() 
`
We are catching a lot of this kind of logs warnings and its related to when cron processes a queue job.

## Solution
Replace renderRoot with renderPlain

## Issue tracker
https://www.drupal.org/project/social/issues/3408511

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
It's hard to reproduce this one, but you can try by creating a lot of notifications for a certain user that has the frequency set to 'Immediate', then running cron multiple times to process these jobs... the warning should appear in the watchdog.

Also we need to make sure that the rendering of email notification is the same as before the change.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Fixed a warning about invalid render state when rendering the email notifications.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Review by vcsvinicius — APPROVED** [review]
I approved the PR

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by BiaInacio** [comment]
Notification test is done, but I was not able to test the emails
sent 30+ notification and it is working fine.
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3645-sas9wbggdtxbxussksla1mvgnuckjyxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6579d032ecba8e86979d4951

**Comment by ronaldtebrake** [comment]
Cherry picked to 12.1.x and 12.0.x

**Pull request merged**
