### PR TITLE
Issue #3236733 by chmez: Improve copy of Custom content list sorting options

### PR DESCRIPTION
**Pull request by ghost**
## Problem
Improve copy of Custom content list sorting options.

## Solution
We want to change the description below the label when a sorting order has been selected. For the copy and order, I would suggest:

Old label | New label | Description
-- | -- | --
Last created | Most recent | Show the newest posts first.
Most comments and likes | Most popular | Show posts with the highest comments and likes first.
Last interacted | Trending | See the posts people are currently interacting with first.
Most commented | -//- | See posts with the most comments first.
Most liked | -//- | See posts with the most likes first.

## Issue tracker
- https://www.drupal.org/project/social/issues/3236733
- https://getopensocial.atlassian.net/browse/ECI-1264

## How to test
- [ ] When you change the selected sorting option in the "Sorting" field then you should see that description of this field is changed as well.

## Release notes
Change the description of the field for sorting options of custom content list block dynamically.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2511-f869vnaqk6hhyqve3savahmy2a8vdaao.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6148857dd7000ac83645e20d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2511-f869vnaqk6hhyqve3savahmy2a8vdaao.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6148857dd7000ac83645e20d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2511-f869vnaqk6hhyqve3savahmy2a8vdaao.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6148857dd7000ac83645e20d

**Review by ribel — APPROVED** [review]
Changes look good and were tested by QA and approved by the Designer.
The failing test looks false positive so I think we can merge this PR, since this was a follow up of #2474 which is included in 10.3 milestone.

**Comment by ribel** [comment]
🍒 picked to the 10.3.x

**Pull request merged**
