### PR TITLE
Issue #2845325 by bojanbogdanovic, navneet0693: Added mentions init logic on comment/post edit.

### PR DESCRIPTION
**Pull request by bojanbogdanovic**
## Problem
When you create a post or comment with a mention and then edit this content the mention is displayed as [~123].

## Solution
Add mentions initialisation logic when editing comment/post.

## Issue tracker
https://www.drupal.org/node/2845325

## How to test
- [x] Create a post or comment and add mentions in the text by using @username
- [ ] Save comment/post
- [ ] Edit the comment/post
- [ ] Instead of seeing tokens you see now users first and last name.

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Review by navneet0693 — CHANGES_REQUESTED** [review]
Mentions are not working in the comments.

Screenshot 2021-12-31 at 6 28 58 PM

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2673-zuvv5ibvjsnymlv1txlgmxcmeiceab7h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c9e6ac5f46ed13d87d2b62

**Pull request closed without merging**
