### PR TITLE
Issue #3259070 by tBKoT: Fix counter on the Manage members page

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
When we select members on the Manage members page counter of selected members are not changed. It's because of updates in the JS of the new version of the VBO module.

## Solution
- Add an additional class that VBO used in the new JS.
- Update response in custom callback (`SocialCoreController::updateSelection`) to take into account changes in the VBO module.

## Issue tracker
- https://getopensocial.atlassian.net/browse/YANG-6897
- https://www.drupal.org/project/social/issues/3259070

## How to test
- [x] Create any group
- [x] Go to the Manage members page
- [x] Select member
- [x] Counter is not changed

#### Before changes
зображення

#### After changes
зображення

## Release notes
Now counter on the Group Manage members page works correctly.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2700-mzf90r7zk4ijjcooeysr4q4qcqyavtmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e682aaffbe18bf78e78faf

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2700-mzf90r7zk4ijjcooeysr4q4qcqyavtmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e682aaffbe18bf78e78faf

**Review by tbsiqueira — APPROVED** [review]
Looks good!

**Comment by tbsiqueira** [comment]
Cherry picked to 11.0.0

**Pull request merged**
