### PR TITLE
Issue #3004859 by truls1502: Update entity_reference_revisions 1.4 to 1.6

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](http://cgit.drupalcode.org/entity_reference_revisions/diff/?h=8.x-1.x&id=167be1c05fb713e030db9c94365d5ef7f09374b9&id2=70716f2e54bf3a8e290c114b03f40cb13d795f62)
- https://www.drupal.org/project/entity_reference_revisions/releases/8.x-1.5
- https://www.drupal.org/project/entity_reference_revisions/releases/8.x-1.6

## Issue tracker
- https://www.drupal.org/project/social/issues/3004859

## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Release notes
<describe the release notes>

### CODE REVIEW

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by jaapjan** [comment]
@truls1502 
Is the `needs work` status still valid here? Looks like it needs review now?

**Comment by truls1502** [comment]
@jaapjan - let us see what Travis says now because in the previous test - it has failed in Travis which I assumed it needs to fix with the Behat tests. Waiting for the Tavis test.

**Comment by truls1502** [comment]
@jaapjan - The test was passed on Travis now  ✅

**Comment by truls1502** [comment]
Maybe you need to restart the MOSS test?

**Pull request merged**
