### PR TITLE
Issue #3405938: Deprecate 'social_core.layout' service

### PR DESCRIPTION
**Pull request by VBaldych**
## Problem
Deprecate 'social_core.layout' service since we don't use it anymore
Earlier we used it in Socialbase theme, but now we going to remove it there

## Solution
Deprecate 'social_core.layout' service in social_core module

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-27484
- https://www.drupal.org/project/social/issues/3405938

## Theme issue tracker
https://www.drupal.org/project/socialbase/issues/3405919

## How to test
n/a

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by ribel** [comment]
Hi @VBaldych,
If we want to introduce some deprecation or major change, we also need to create Change Record.
You can take a look to some examples here: https://www.drupal.org/list-changes/social
You can create it already, but please keep it Unpublished until this PR is merged.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3629-03kmkiiydid7hhjlblitvwwxcm79hz9t.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656de516ec1e7bc242b8355f

**Pull request closed without merging**
