### PR TITLE
Issue #3251374 by Ressinel: Rename topic type Discussions.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
It interferes with the extensions - Discussions. Needs to manually renamed everytime. Changing this to "Article" would be better.

## Solution
Only change it on install not on update to maintain BC.

## Issue tracker
- https://www.drupal.org/project/social/issues/3251374
- https://getopensocial.atlassian.net/browse/DS-7725

## How to test
- [ ] Install OS from scratch
- [ ] Go to `/node/add/topic`
- [ ] You should see topic type **Dialog** instead of **Discussion** and new topic type **Content**.

## Screenshots
N/A

## Release notes
Topic type **Discussion** was renamed to **Dialog** and added **Content** as a new option for new platforms.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by ronaldtebrake** [comment]
Hi @Ressinel would be great if you could also update the demo content 
Screenshot 2021-12-15 at 09 05 28
Screenshot 2021-12-15 at 09 05 35

Other than that seems like it will work great :D

**Comment by Ressinel** [comment]
@ronaldtebrake I have updated the Demo content and used Dialog instead of Discussion.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Review by navneet0693 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2622-njrnzwgueldxjrr9dtnnq0b6vkt2d3ty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a0e5da908ae15c7163e92b

**Comment by navneet0693** [comment]
🍒 -picked to 11.0.x

**Pull request merged**
