### PR TITLE
Issue #3333919 by vnech: Duplicated messages in "Notification Center"

### PR DESCRIPTION
**Pull request by nechai**
## Problem
I added a new custom message template message.template.example with this data:
[Video screenshot](https://user-images.githubusercontent.com/19921926/212740991-0717b0fa-77a7-4519-9e05-a4752c3a5b00.mov)

Then if I create a topic I will see multiple (duplicated) messages in "Notification Center":
Screenshot 2023-01-16 at 19 34 12

## Solution
The problem coming from views filter plugin - `\Drupal\activity_viewer\Plugin\views\filter\ActivityNotificationVisibilityAccess`, namely query in `query()` method has broken join with `node_access` table which cause duplicated rows in view.

## Issue tracker
- https://www.drupal.org/project/social/issues/3333919
- https://getopensocial.atlassian.net/browse/PROD-23776

## Theme issue tracker
n/a

## How to test
- [ ] Login as admin
- [ ] Disable `social_advanced_queue` and `advancedqueue` modules for testing purposes
- [ ] Import message template same as provided [in this screenshot](https://user-images.githubusercontent.com/19921926/212740991-0717b0fa-77a7-4519-9e05-a4752c3a5b00.mov)
- [ ] Create a topic
- [ ] Run cron jobs `Activity Creator` and `Activity Send Email`
- [ ] Visit "Notification Center" page

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
Fix issue with duplicated messages on "Notification Center"

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Review by ribel — APPROVED** [review]
@nechai I have checked changes and they looks good to me.
As I found this [ActivityNotificationVisibilityAccess.php](https://github.com/goalgorilla/open_social/pull/2201/files#diff-9f4af291e020bd62b0a06df90dd4e6e8c03359606815f5e446f68087e8adf38d) was added as part of performance improvement in PR #2201 

I've also tested it with Follow Tag functionality and it works without regressions:
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3288-vzdqagoc8dao8tc0or99odfauok6ccel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63c593295804da46dba5370d

**Review by nkoporec — APPROVED** [review]
LGTM

**Pull request merged**
