### PR TITLE
Issue #3251540 by tBKoT: Allows anonymous users viewing comments

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
The anonymous user cannot see comments even if it added to the public content(posts, topics, etc.).

## Solution
Needs to add the `access comment` permission for the anonymous user. As a default in the comment access handler, it checks if users have access to the commented entity, so we do not need to add additional checks.

## Issue tracker
https://www.drupal.org/project/social/issues/3251540
https://getopensocial.atlassian.net/browse/YANG-5584

## How to test
- [x] Create any public content(post, topic, etc.)
- [x] Add a comment to this content
- [x] Try to view commented content as an anonymous user

#### As LU
зображення
#### As AN
зображення
#### As AN
зображення

## Release notes
Now anonymous users can view comments if they are allowed to view commented content.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Comment by dmytriikaiun** [comment]
To show post comments we should use a [patch](https://www.drupal.org/files/issues/2021-11-29/3251638-show-comments-for-anonyumous-4.patch) for the socialbase theme.

**Comment by Ressinel** [comment]
@dmytriikaiun I see this by AN👇🏼 

Screenshot 2021-11-29 at 16 47 48

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Review by Ressinel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Review by rollki — APPROVED** [review]
Changes look good to me. Already using as a patch for one of the projects.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2624-dz2p7qahacdsa2eseejjmhrna5iuatsd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a373f4908ae1288b64d1d2

**Review by ribel — APPROVED** [review]
All tests now passed, so I am going to merge this PR.

**Pull request merged**
