### PR TITLE
Issue #2888728 by alex.ksis: Fix links to overview pages in blocks in…

### PR DESCRIPTION
**Pull request by ksis**
Related issue: https://www.drupal.org/node/2888728

# HTT

- [ ] Add language different to English
- [ ] Switch to new language
- [ ] Click link in block in sidebar (for example **All topics** or **All upcoming events**)
- [ ] Make sure that selected language persists

### CODE REVIEW

**Comment by jochemvn** [comment]
@ksis , Could you add some test steps?

**Comment by ksis** [comment]
Hi @jochemvn. I added instruction how to test.

**Comment by jochemvn** [comment]
Hi @ksis ,
Links all look good to me... i have some issues with the translations though:

Why did you change:
`$variables['button_text'] = t('All @label', array('@label' => $variables['label']['#markup']));`
into
`$variables['button_text'] = t('All ') . $variables['label']['#markup'];`

This way the context of the string is gone. For instance in dutch the word 'All' is translated differently depending on the context (the rest of the sentence). Any particular reason why you changed the translations here?

Jochem

**Comment by ksis** [comment]
Hi @jochemvn!
I think that it happened because of merging branches. 
As you can see there are no these changes in my commit.
I have fixed it. Please, check.

**Comment by jochemvn** [comment]
Hi @ksis,
hmm that's weird.. and probably my fault then, so sorry for the hassle. Thanks for fixing it!
Jochem

**Comment by bramtenhove** [comment]
@jochemvn is this something you can take a look at? It’s open for quite sometime and I don’t know what the status is.

**Comment by bramtenhove** [comment]
@jochemvn could you take a quick look at my previous comment?

Also I noticed we are removing the `/my-events` link. Is it possible to redirect this url to the new situation? It would be a shame if we would be breaking possible existing links.

@ksis there are a few merge conflicts currently happening, could you take a look?

**Comment by Kingdutch** [comment]
Prematurely removed the "needs-work" tag. I've resolved the merge conflicts but @bramtenhove's comment about the `/my-events` path still needs to be done.

**Comment by bramtenhove** [comment]
Considering that this still requires work, I will re-add the "needs-work" label.

**Comment by ksis** [comment]
@bramtenhove @Kingdutch I returned the controller for the **/my-events** path.

**Pull request merged**
