### PR TITLE
Internal: Split flexible group content test across multiple GitHub Jobs

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem/Solution
The flexible group content tests are consistently the slowest in our test suite which is causing a backup in our CI. This moves the tests into individual folders so our CI splits them out over several jobs. This won't lessen the amount of work to be done but allows it to be better parallelised, hopefully speeding up our test runs.

We can consider moving these back into a single folder in the future if we're able to speed up the tests in such a way that the extra job set up causes a considerable overhead compared to test runtime.

## Issue tracker
Internal no issue

## How to test

- [ ] Behat should pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3331-g07ahwuytggx1to2lpmtq4ppvh9tndnl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640204027340234e8af256df

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3331-g07ahwuytggx1to2lpmtq4ppvh9tndnl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640204027340234e8af256df

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3331-g07ahwuytggx1to2lpmtq4ppvh9tndnl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640204027340234e8af256df

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3331-g07ahwuytggx1to2lpmtq4ppvh9tndnl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640204027340234e8af256df

**Comment by Kingdutch** [comment]
🍒 d45ae0040 on 11.8.x and 0347c24c9 on 11.7.x

**Pull request merged**
