### PR TITLE
Issue #3351326 by vnech: Skip activities creation during content migration

### PR DESCRIPTION
**Pull request by nechai**
## Problem
When migrate a content activities are created as well. As a result when there are a huge of amount content this can cause a bad users experience because of streams flooding.

## Solution
Create an activity only if entity is not syncing.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-24731
- https://www.drupal.org/project/social/issues/3351326
- https://www.drupal.org/project/drupal/issues/3052115

## Theme issue tracker
n/a

## How to test
This can be faced on content migration.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
Skip activities creation during content migration.

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Review by ribel — APPROVED** [review]
@nechai I see you added patch from closed issue: 
https://www.drupal.org/project/drupal/issues/3052115#comment-14899981

But changes there doesn't looks significant and might be useful for migration or synchronisation.

image

image

Let's see what Orbiters and and Guaridans think :)

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3365-z5vicpd4domcasgazljsrswme4ixywi7.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6425aa5d721f24cdcdfb7b44

**Review by bramtenhove — APPROVED** [review]

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.8.x and 11.9.x

**Pull request merged**
