### PR TITLE
Issue #3361854 - Message template subject translation for multilanguage

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
When sending out email notifications based on the message templates while having multilanguage on. It will only send the base language, not the translation for the subject lines.

This is caused by the function $message->getTemplate which load the override free template, in our case we need the translated version as we later include this in the sendemail as a variable %subject which Drupal does not translate.

## Solution
Replace the function getTemplate by getting it from the entitytypemanager with the override, so it's correctly translated.

## Issue tracker
https://www.drupal.org/project/social/issues/3361854

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Enable social_language
- [ ] Add a second language
- [ ]Translate on 1 the message templates on /admin/structure/message. Make sure to translate the subject line.
- [ ]Change the preferred language for the user you want to trigger it for to a different one (not the base language)
- [ ] Trigger the message template
- [ ] Notice the subject line is not translated
- [ ] Checkout to this branch and try again

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We made a fix where the subject for emails would not get translated. These should now show in the preferred language for the user.

## Change Record
*[Required if applicable] If this Pull Request changes the way that developers should do things or introduces a new API for developers then a change record to document this is needed. Please provide a draft for a change record or a link to an unpublished change record below. Existing change records can be consulted as example. Please provide a draft for a change record or a link to an unpublished change record below. [Existing change records](https://www.drupal.org/list-changes/social) can be consulted as example.*

## Translations
*[Optional]Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by robertragas** [comment]
Changes made, now waiting for the test to go green again.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3404-qduzgjmm4zdne79ezjarucweklct0f5w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/646b719ad58e09b19c71a77c

**Review by tbsiqueira — APPROVED** [review]

**Pull request merged**
