### PR TITLE
PROD-29281: Replace Mergeable with a custom tool for label and title enforcement

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
The message that Mergeable adds is usually not very helpful and it can be difficult to figure out without opening the workflows what needs to be changed. Additionally Mergeable doesn’t really provide us with many ways to extend its capabilities and build on top of it.

## Solution
In  we’ve found that we can use GitHub Scripts to create a tool that can post and update comments on a PR to provide more targetted and helpful feedback.

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-29281

## How to test
- [ ] Create a PR with different combinations of missing labels, a missing milestone and malformed title

The business logic of the PR manager is tested using Jest, (see `*.test.js`) we assume that GitHub's API works as described and don't have tests that talk to the REST API directly.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### When nothing is provided.
The feedback message posted by the PR Manager on a pull request without any labels or milestone.

### Duplicate labels or a title mixing the Drupal and Jira format
image

## Release notes
Pull Requests will no longer be validated by Mergeable and instead use a newly introduced custom built JavaScript solution under the name "PR Manager". It aims to provide more helpful messages in case PRs violate the requirements we set.

One additional change is that PRs for Jira tickets should no longer start with `Issue #` but should start with the Jira ticket directly.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Review by ronaldtebrake — APPROVED** [review]
Nice one!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3862-zvznohuu0ht4v7i8nd2kyhmiqkld1def.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/661b9c7c30b208a05cbfab18

**Pull request merged**
