### PR TITLE
Internal: Add CI check to prevent Config Overrides being added

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution
We've found that config overrides cause a lot of performance issues because they'll be called in a lot of scenarios. We used to need them when we were still using Features, but these days 99.9% of the config overrides can be replaced with a config update in an install hook and uninstall hook instead.

We add a one-liner check to ensure that no new config overrides are being added to our code. In case someone does add one the CI check will fail which can prompt a discussion on the PR for alternative solutions. In case the PR is merged with the override still in then we won't keep complaining on the merged branch.

## Issue tracker
Internal change no issue

## How to test
- [ ] CI should pass
- [ ] CI should fail on the added debug step

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Comment by Kingdutch** [comment]
The workflow correctly identified that a config override was being added to the PR (we do this by checking changes in a `services.yml` file).

image

The workflow is configured to continue-on-error since we don't consider the workflow a failure if it fails a job. The job failure should be input for discussion. Although we will usually err away from the things it detects there may be situations where it's the best option.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3352-jffrzy3kmmrg5vf11covxennjjc7xrk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/641491464d3ab3666767d025

**Pull request merged**
