### PR TITLE
Issue #3386141 by nkoporec: Update drupal/config_update from 1.7 to 2.0.0-alpha3

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Changes:

 https://git.drupalcode.org/project/config_update/-/compare/8.x-1.7...2.0.0-alpha3?from_project_id=55524&straight=false 

## Solution
Update to latest version.

## Issue tracker
https://www.drupal.org/project/social/issues/3386141#comment-15223076

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
 - [ ] Make sure that the config_update module works

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Review by vcsvinicius — APPROVED** [review]
@nkoporec I approved the pull-request

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by BiaInacio** [comment]
Update is working as expected!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3515-g34lkj2hswga9aq1ngxftdwch0wvmmca.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64fb2cb8ed3390cee76d7c6b

**Comment by ronaldtebrake** [comment]
I've moved this to 12.0.0, this included a hidden PHP 8.1 requirement in the `info.yml` file, which isn't used in the composer facade of Drupal https://www.drupal.org/project/project_composer/issues/3352513#comment-15286439 so we didn't notice this until now where our update hooks are not running.

We're going to loosen the dependency for 11.11.x in a new version. `^1.7 || 2.0.0-alpha3` so people can determine which version they want to use.

`1.7` does not need PHP 8.0
`2.0.0-alpha3` needs php 8.1

as some might already use some of the hooks https://www.drupal.org/project/config_update/issues/3136087 already from 2.0.0 as we've release it this would be the only option for people to make a decision themselves, we can't do it for them.

**Pull request merged**
