### PR TITLE
Issue #3171507 by tBKoT: Rename file and hook update

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
The Social Editor module has hoor_update with the incorrect file name for the Update Helper moduleThe Social Editor module has hoor_update with the incorrect file name for the Update Helper module
STR:
- [x] Run database update
- [x] You will get a warning `file_get_contents(profiles/contrib/social/modules/social_features/social_editor/config/update/social_editor_update_8002.yml): failed to open stream: No such file or directory ConfigHandler.php:402`

## Solution
Rename fine name in the hook_update

## Issue tracker
https://www.drupal.org/project/social/issues/3171507

## How to test
- [x] Run database update
- [x] You should get message that `basic_html` and `mail_html` successfully updated

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Review by ribel — APPROVED** [review]
I have tested the latest OS 9.2 with this patch and all updates went well.

**Comment by ribel** [comment]
@ronaldtebrake I think it would be good to merge this, and maybe even do a new release, what do you think?

**Comment by ronaldtebrake** [comment]
Hmm thanks for notifying me, think it's a good idea indeed.

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 9.x

**Pull request merged**
