### PR TITLE
Issue #3251633 by agami4: Improve profile organization tag label behaviour

### PR DESCRIPTION
**Pull request by agami4**
## Problem
When I create a featured content block or a stream in the Dashboard and the content is created by a person with an organization tag, the label of the tag is always visible and breaks the layout.

## Solution
Add improvements to the behaviour of the organization label.

## Issue tracker
https://www.drupal.org/project/social/issues/3251633
https://getopensocial.atlassian.net/browse/YANG-3788

## How to test
- [ ] Add organization tag to the profile.
The first case:
- [ ] Go to the dashboard page.
- [ ] Create scream block.
- [ ] Find teaser with organization label.
The second case:
- [ ] Go to the `user/1/stream` page.
- [ ] Check behaviour on the user statistic block.

## Screenshots
before:
Screenshot 2020-09-25 at 13 52 27

after:
Screenshot 2021-11-29 at 16 18 44

## Release notes
The profile organization label has a correct behaviour.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2687-7621ke1ykoj4kcn5ey4yj4vqtm3zhpkx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dd3eaddc579fc65db6d5d5

**Review by Ressinel — APPROVED** [review]

**Comment by ribel** [comment]
@agami4 please merge the main branch to fix Coding Standards and tests.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2687-7621ke1ykoj4kcn5ey4yj4vqtm3zhpkx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dd3eaddc579fc65db6d5d5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2687-7621ke1ykoj4kcn5ey4yj4vqtm3zhpkx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dd3eaddc579fc65db6d5d5

**Comment by navneet0693** [comment]
🍒 -pick to 11.0.x and 10.3.x

**Pull request merged**
