### PR TITLE
Issue #3397613 - Replace the ckeditor4 core modules with the contrib one

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
Ckeditor4 will be deprecated from core in favor of Ckeditor5. Open Social will be moving to Ckeditor5 in the version 12, but to give the community some time in moving from 11 to 12, we can move to the contrib ckeditor which will be supported until the end of the year.

## Solution
Move to contrib Ckeditor4

## Issue tracker
https://www.drupal.org/project/social/issues/3397613

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Install open_social like your are used to.
- [ ] Create content and see the ckeditor is still functioning like expected
- [ ] Install the social_embed module
- [ ] See there is a url embed (media) icon and use it to include videos, see that this also still works like normal.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We moved the ckeditor4 module from Drupal core to the contrib one. This will be supported until the end of the year and will give people some extra time in moving to Open Social 12.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3581-zpngvlsdwq27foptv7zlnajepp3djjk0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/653f7679cbeeaba7d0706de4

**Comment by socialnicheguru** [comment]
Is there an update hook that helps to switch from core ckeditor to the contrib module?

**Comment by robertragas** [comment]
Hello @socialnicheguru, that should go automatically. See screenshot when I installed a clean version of 11.11.2 and later on went to the 11.11.x-dev branch.

OS - 11.11.2
Screenshot 2023-10-31 at 17 05 18

OS - 11.11.x-dev
Screenshot 2023-10-31 at 17 06 40

**Comment by socialnicheguru** [comment]
My concern is upgrading a current site that has drupal/ckeditor enabled.

I tried it on a test site and I was not quite sure how to switch from core to creditor.

**Pull request merged**
