### PR TITLE
Issue #3176854 by tBKoT: Add iCal option to the 'Add to calendar' feature

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
Need to add the `iCal` option to the `Add to Calendar` feature.

## Solution
Create a plugin with the `iCal` option.
Create a controller to download the ICS file.

## Issue tracker
https://www.drupal.org/project/social/issues/3176854
https://getopensocial.atlassian.net/browse/YANG-3712

## How to test
- [x] Enable the `social_event_addtocal`
- [x] Enable the `Add to Calendar` button in `/admin/config/opensocial/event-addtocal`
- [x] Choose `iCal` option
- [x] Go to any event as LU
- [x] Press the `Add to Calendar` button and click `iCal` if needed
- [x] You should resave the ICS file for event importing to your calendar.

## Screenshots
image

## Release notes
Now SM could choose the `iCal` as one of the options for adding the event to the calendar

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Review by ribel — APPROVED** [review]
I have tested and all works as expected on Mac OS.

**Comment by ribel** [comment]
@dmytriikaiun please fix coding standards.

**Comment by ronaldtebrake** [comment]
Awesome!
Don't have iCal to test, but seems good to me can imagine you guys have tested it functionaly.
Also 9.5 seems fine to me from a milestone!

**Comment by ribel** [comment]
🍒 picked to 9.x

**Pull request merged**
