### PR TITLE
by robertragas, _hannibal_: Update the social_medium image effect to …

### PR DESCRIPTION
**Pull request by robertragas**
…use the teaser crop because our content offers large and small croppings and we don't want to introduce a new cropping

## Problem
When creating content such as topics the user is able to add an image and crop this for the header and teaser. The issue is that this teaser cropping is not being used for the topic overview block which can be found in the sidebar of the /stream.

## Solution
The sidebar uses the image style "social_medium". This image-style uses a cropping profile that is not available for topics. Instead of adding yet another cropping option to the image, make sure we change the cropping profile to "small" which is being used. The downside is that a 22x22 will be upscaled to 44x44 but because it's so small details will hardly be visible anyway.

## Issue tracker
https://www.drupal.org/project/social/issues/3248528

## How to test
- [ ] Create a new topic and add an image.
- [ ] Make the 2 croppings for the the image.
- [ ] Go to /explore or /stream and see the latest topic block in the sidebar does not show the chosen cropping
- [ ] Check out to this branch and run the update
- [ ] Try again and see it now works

## Release notes
We have made a fix where the small teaser images in lists such as topic overview would not pick the image cropping that was chosen in the content creation. It now shows the correct cropping again.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2636-ljtd7qafvsieh2wkzwmw0wr622bpzvkg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61addefe821ec8bd0409e898

**Comment by navneet0693** [comment]
@robertragas Please resolve the conflicts on the PR.

**Comment by ribel** [comment]
@DmytroRovovyi From the diff, I see changes from this PR was already merged in different PR: #2619, so I think we can close this one.

**Pull request closed without merging**
