### PR TITLE
Issue #3231998 by Ressinel: Add tests covering for group activities.

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Group activities have no tests covering.
Closed group member does not see post creation notification in Notifications Center.

## Solution
- Make sure we have tests covering closed group activities
- Check out the filters added to the Activity stream for Groups (likely there is an access check too strict)

## Issue tracker
- https://www.drupal.org/project/social/issues/3231998
- https://www.drupal.org/project/social/issues/3233473
- https://getopensocial.atlassian.net/browse/TB-6072

## How to test
- [ ] Tests added by this PR have to pass successfully.

## Screenshots
N/A

## Release notes
Fixed issues with closed group notifications.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Review by navneet0693 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2490-895q8ibi3oovglu8sw76jsijbvlcxft2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6139101d08cf4761c960668c

**Comment by navneet0693** [comment]
🍒 -picked to 10.3.x

**Pull request merged**
