### PR TITLE
Issue #3348399 by Kingdutch: Move search to SOLR and drop support for searching against the database

### PR DESCRIPTION
**Pull request by Kingdutch**
<h2 id="summary-problem-motivation">Problem/Motivation</h3>
Open Social provides a complex community product. Search is a powerful way for users to find content within their community and ensuring that search results are accurate and provided in a performant manner is important to a successful community.

The <code>search_api</code> module provides a way to easily abstract over different search back-ends. However to support those different back-ends Open Social is limited to only using functionality that's within the least common denominator. This can have an adverse effect on the user experience.

In our community building experience we've seen first-hand that using the database as a search back-end can have a profoundly negative impact on platform performance. Additionally we've been unable to build some desired features which would've been supported by SOLR but were not possible with a database.

It's with this in mind that for all of our SaaS customers we've already configured a SOLR back-end and do not use the database for search anymore. Unfortunately with the work being done for <a href="https://www.drupal.org/project/social/issues/3230125">improved profile configuration and privacy options</a> we're finding that the maintenance cost for making things work with the database back-end is becoming too high.

<h2 id="summary-proposed-resolution">Proposed resolution</h3>
We plan to drop support for the search_api_db back-end 12.0.0. The <code>social_search</code> module's dependency will be changed from <code>search_api_db</code> to <code>search_api_solr</code> and an update hook will be provided to introduce the <code>social_solr</code> server, switch the indices and disable the search_api_db module.

## Issue tracker
https://www.drupal.org/project/social/issues/3348399

## How to test
- [ ] Search tests should pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
TBD

## Change Record
TBD!

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-hdbtrbkyohbwqa4rd00sw8my3m09vzo3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649c2873757563ca3722eb91

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-hdbtrbkyohbwqa4rd00sw8my3m09vzo3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649c2873757563ca3722eb91

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-hdbtrbkyohbwqa4rd00sw8my3m09vzo3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649c2873757563ca3722eb91

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-hdbtrbkyohbwqa4rd00sw8my3m09vzo3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649c2873757563ca3722eb91

**Comment by Kingdutch** [comment]
The only tests failing here are the ones that have been failing throughout this process and that will be fixed in profile (the name check, and the profile tagging). So it looks like search is otherwise migrated to SOLR. 

The Drupal ecosystem seems to be making our live easy :D

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Link (solr):
- https://pr3443-7ryukffxuouwdetpotdelziyuyw554tb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Link (solr):
- https://pr3443-7ryukffxuouwdetpotdelziyuyw554tb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3443-e9ob60t9xc8myk5uxp9plt5kgkmizxtt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/649d9701ee74754fca2eb869

**Comment by Kingdutch** [comment]
The failing tests here are only the ones that will be fixed in #2478 🥳  Merging

**Pull request merged**
