### PR TITLE
Issue #3236705 by tBKoT: As a user I want to invite members to my group

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
It is currently only possible to invite people as a Group managers, but we need to make the invite function accessible to members.

## Solution
- Add additional settings on the group settings page
- Create a new field in the group to allow group managers to decide if members can invite other users to the group
- Update permissions to the group invite page

## Issue tracker

- https://www.drupal.org/project/social/issues/3236705
- https://www.drupal.org/project/socialblue/issues/3238973
- https://getopensocial.atlassian.net/browse/OEC-25
- https://getopensocial.atlassian.net/browse/OEC-26

## How to test
- [x] Enable the `social_group_invite` module
- [x] As an SM+ go to group settings (`admin/config/opensocial/social-group`)
- [x] Enable `Group managers is able to allow members send invites` in `Group invite settings`
- [x] Edit any group and enable `Allow members to share the group with others`
- [x] Go to the group page as a member
- [x] You should see a new `Invite` dropdown

## Screenshots
**Group settings**
зображення
**Group edit**
image
**Group details**
зображення

## Release notes
Now, if it is allowed by SM+ and a group manager, members can share a group link or invite other users to their group.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
@dmytriikaiun I see behat tests are still failing here even after re-run. 
Could you maybe merge the main branch again to solve this issue?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-plnycplztmxwrmnkq7gjqqxa1xy3enmf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614d9ecb2c4383767eb355a0

**Comment by dmytriikaiun** [comment]
To display invite/share buttons we should use this [patch](https://www.drupal.org/files/issues/2021-11-29/3238973-add-invite-button-6.patch) for the `socialblue` theme

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-uxay2mwd2tlmcd2y1ia7uzkwlsuqmhra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3e84383209ffbb818fb0a

**Review by Ressinel — CHANGES_REQUESTED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2519-uxay2mwd2tlmcd2y1ia7uzkwlsuqmhra.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3e84383209ffbb818fb0a

**Review by Ressinel — APPROVED** [review]
Looks good to me.

**Comment by ribel** [comment]
@navneet0693 can we merge it?

**Comment by navneet0693** [comment]
@ribel Yes!!

**Pull request merged**
