### PR TITLE
Issue #3354659 by zanvidmar: Fix status message on "Manage enrollments" actions

### PR DESCRIPTION
**Pull request by zanvidmar**
Fix status message on "Manage enrollments" actions that reports wrong number of operations.

## Problem
Status message on Manage enrollments actions reports wrong number of operations.

## Solution
Fix the issue introduced in [https://github.com/goalgorilla/open_social/commit/cad316d3c661b099945851...](https://github.com/goalgorilla/open_social/commit/cad316d3c661b099945851eefa528b148aa5cf79#diff-276d80a5f825c11ab82d3f38f32d1631e7f4b1dec0a571480012602a5666fa30L451)

## Issue tracker
[3363797](https://www.drupal.org/project/social/issues/3363797)

## Theme issue tracker
N/A

## How to test
- [ ] Create clean install of open social
- [ ] Create an event
- [ ] Enroll any number of users to newly created event
- [ ] As sitemanager, go to "Manage enrollments" tab on newly created event
- [ ] Select X number of enrollees and execute an action (for example: "Remove selected enrollees")
- [ ] Once action is successfully completed, you will see the message "2 selected enrollees have been removed from the event successfully"
- [ ] The expected result (success message) "X selected enrollees have been removed from the event successfully" is attained when repeating the steps with this fix applied. 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Status message on "Manage enrollments" actions now reports correct number of operations.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3411-tsnjxc31n8hlhjw2tiswbqnc2uwrn7bz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64771dcfc2783c67cb025c98

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3411-tsnjxc31n8hlhjw2tiswbqnc2uwrn7bz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64771dcfc2783c67cb025c98

**Comment by zanvidmar** [comment]
Rebased because of https://github.com/goalgorilla/open_social/pull/3414.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3411-tsnjxc31n8hlhjw2tiswbqnc2uwrn7bz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64771dcfc2783c67cb025c98

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3411-tsnjxc31n8hlhjw2tiswbqnc2uwrn7bz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64771dcfc2783c67cb025c98

**Review by nkoporec — APPROVED** [review]
LGTM

**Comment by nkoporec** [comment]
:cherries:  picked to 11.9.x

**Pull request merged**
