### PR TITLE
Issue #2947663 by agami4: Add styles for the link on the body/description blocks

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The links have different styles on the body/description blocks.

## Solution
Update link styles on the body/description blocks.

## Issue tracker
https://www.drupal.org/project/social/issues/2947663

## How to test
*For example*
- [ ] Create all CT and groups and add a link to the description block.

## Screenshots
before:
link-before1
link-before2

after:
link-after

## Release notes
The link has the same styles on the body/description blocks.

## Change Record
-

## Translations
-

### CODE REVIEW

**Comment by Kingdutch** [comment]
@agami4 This would've been a great story to include before and after screenshots so we know what goes where. There are quite a few selectors added so going through these manually for review without any visual guidance is quite a bit of work.

**Comment by agami4** [comment]
@Kingdutch, I've added screenshots. Please check.

**Comment by ribel** [comment]
@ronaldtebrake @Kingdutch As I see this PR comes from WCAG epic, so not directly from ECI team.
That's why I am not sure if we can/should review and merge it - could you maybe check and decide?
From my point of view, it looks like ready to merge, but don't want to merge this by myself.

**Comment by ronaldtebrake** [comment]
Hi @ribel, after talking to @Kingdutch:
It seems this is a good first step for fixing some encountered issues, however as https://www.drupal.org/project/social/issues/2947663#comment-13859739 it seems not everything is covered yet (?)

Also since we are removing a style library, we can't backport this unfortunately. 
Those expecting this library to be there will get an issue. 

So from our point of view we can merge this, update drupal.org with what is fixed in this PR and the fact the library is deleted so people are aware when updating this happens.

**Comment by ribel** [comment]
@agami4 please check comments above, including this one:
 https://www.drupal.org/project/social/issues/2947663#comment-13859739
And also resolve conflicts caused by merge of PR #1999.

**Comment by agami4** [comment]
@ribel, I've fixed the merge conflict

**Comment by agami4** [comment]
@Kingdutch, I've fixed merge conflicts and added updates for the links on the comment block. I checked [this comment](https://www.drupal.org/project/social/issues/2947663#comment-13859739). Do I need to work on issues on that comment?

**Comment by agami4** [comment]
I close this PR because all changes were moved to the socialblue theme. See new MR https://git.drupalcode.org/project/socialblue/-/merge_requests/11

**Pull request closed without merging**
