### PR TITLE
Issue #3402841 by SV: Undefined array key "entity" during export of enrolment user data

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem
There are some  warnings during the export of enrolment user data:
Screenshot 2023-11-20 at 15 15 45

## Solution

Add checks to prevent warnings during the export of anonymous enrolments.

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-26734
- https://www.drupal.org/project/social/issues/3402841

## Theme issue tracker
N/A

## How to test
Need to use drush command to export user data

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes

Add checks to prevent wanrnings during the export of enrolment user data.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3613-auzduvjhftq1phwsthga3ojeofpbnyor.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b5e29009f247c531bb22d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3613-auzduvjhftq1phwsthga3ojeofpbnyor.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b5e29009f247c531bb22d

**Review by ribel — APPROVED** [review]
I've enabled Anonymous Enroll Export module and changes works as expected without regressions and warnings:
image

**Comment by ribel** [comment]
🍒 picked to the 12.0.x

**Pull request merged**
