### PR TITLE
Issue #3254729 by yaroslav-shandra: Featured teasers does not support taxonomy custom icons

### PR DESCRIPTION
**Pull request by YaroslavShandra88**
## Problem
In the resource library page the standard topics, events and groups icon is displayed. Not icon what was selected at topic/group/event type taxonomy term.

## Solution
Fix condition for topic/group/event type icons at templates. 

## Issue tracker
https://www.drupal.org/project/social/issues/3254729
https://getopensocial.atlassian.net/browse/SUP-1960

## How to test
1. Add term to Topic types taxonomy and select icon for term.
2. Create Topic with added term and include in the resource library.
3. Go to Resource library page and check added Topic icon.

## Screenshots
Screenshot from 2021-12-16 14-52-06
Screenshot from 2021-12-16 14-53-34

## Release notes
Fixed Resource library template for showing icon selected from Topic type term.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2659-pl9mbjebppcomphsqicfnqclgbnydsmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb3d375f46ed13d8118513

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2659-pl9mbjebppcomphsqicfnqclgbnydsmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb3d375f46ed13d8118513

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2659-pl9mbjebppcomphsqicfnqclgbnydsmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb3d375f46ed13d8118513

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2659-pl9mbjebppcomphsqicfnqclgbnydsmj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61bb3d375f46ed13d8118513

**Comment by navneet0693** [comment]
@ribel Tests pass, please see if can you review it.

**Review by ribel — APPROVED** [review]
I have tested changed and all looks good to me.

**Comment by ribel** [comment]
🍒 picked to 11.0.x and 10.3.x

**Pull request merged**
