### PR TITLE
Issue #3272028 by tBKoT: Removes the 'View' action on the 'Manage members' page

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
On the `Manage members` page, we have actions like `Edit`, `Delete`, `View`, etc. As we can click on the member's avatar or name, so the `View` action actually not needed. Also, when we click on `View` it does not work and redirects back to the `Manage members` page.

## Solution
Remove the `View` action from the `Manage members` page.

## Issue tracker
 - https://www.drupal.org/project/social/issues/3272028
 - https://getopensocial.atlassian.net/browse/YANG-1680

## Theme issue tracker
N/A

## How to test
- [ ] Using the latest version of Open Social
- [ ] As a group manager
- [ ] Go to the group's `Manage members` page
- [ ] Pres on the `View` action in the table of members.
- [ ] You will be redirected to the same page

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
зображення

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2837-toc1ximwgzj9gcx1y0wz9x6bocxnmd9g.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6241c5719413e8006b1e8f75

**Review by rollki — APPROVED** [review]
LGTM, @ronaldtebrake what do you think about this change?

**Comment by ronaldtebrake** [comment]
@rollki Interesting, it does make sense, the user should have access to the operation so revoking that isn't a good idea. 
Also I think this makes it more consistent with for example Events.

Does this change also make sense from a perspective of things like Courses & Challenges? 
Might be a good idea to double check this with the design team, what do you think? Alternatively we could of course fix the actual "view" link but I'm not sure from a UX perspective if that is something users expect to have or not.

**Comment by dmytriikaiun** [comment]
@ronaldtebrake we have the same list of actions o the `Manage enrollment` page and the `View` action is absent as we can click on the user's name or avatar for view.
зображення

**Comment by ronaldtebrake** [comment]
> @ronaldtebrake we have the same list of actions o the `Manage enrollment` page and the `View` action is absent as we can click on the user's name or avatar for view. зображення

Thanks for the info @dmytriikaiun 

What I think is important is that there are two options here.

1. Fixing the view option and create a follow up issue to add View to all the other overviews to make it consistent
2. Removing the view option which you've done and seems fair from what you've mentioned.

From a UX perspective I'm not sure if the actual "view" action is needed or not, I don't think as developers we should be making that decision.

For now I'm OK with removing it as it makes it at least more consistent as you've showed but would be good to verify these things with UX 😊

**Comment by dmytriikaiun** [comment]
Hi @ronaldtebrake 
I have confirmation from Jessica to remove the view action

> You're absolutely right that the “view” CTA is not needed if we can click on the user profile, so I agree with the solution to remove the “view” CTA and instead rely on clicking the name/picture. However, we must make sure this is consistent on all member lists. So that it is always the same interaction and navigation :)

**Comment by dmytriikaiun** [comment]
@ronaldtebrake can we merge this PR as we already have confirmation from Jessica?

**Review by ronaldtebrake — APPROVED** [review]

**Comment by Ressinel** [comment]
🍒-picked to `11.3.x`

**Pull request merged**
