### PR TITLE
Issue #3204850 by rolki: Handling the visibility of a the about / members tab

### PR DESCRIPTION
**Pull request by rollki**
## Problem
Group visibility options don't work for groups

## Solution
Add some extra checks to the FlexibleGroupContentAccessCheck

## Issue tracker
- https://www.drupal.org/project/social/issues/3204850
- https://getopensocial.atlassian.net/browse/YANG-5116

## How to test
- [ ] Go to the flexible group creation page
- [ ] Select the "Group members only (secret)" option
- [ ] Save the group
- [ ] Go to this group under anonymous
- [ ] You should see "Access denied" instead of a group

## Screenshots
Screenshot (1)
Снимок экрана 2021-03-22 в 10 46 15

### CODE REVIEW

**Comment by rollki** [comment]
Was tested here: https://getopensocial.atlassian.net/browse/YANG-5116

**Review by ribel — APPROVED** [review]
Proposed changes look logical for me, and it was tested by QA.
But wondering if the distro team can give a quick look on if there is no objection to merging it, as it relates to important content access check.
cc @ronaldtebrake @navneet0693

**Comment by ronaldtebrake** [comment]
hi @ribel @rollki 

Thanks a lot, looks good to me, update the PR text a bit to reflect the correct issue, but will merge and backport 👍

**Comment by ronaldtebrake** [comment]
🍒 cherry picked to 10.1.x and 10.0.x

**Pull request merged**
