### PR TITLE
#3020571: Implement config schema for message.template.*.third_party.activity_logger

### PR DESCRIPTION
**Pull request by ideb**
PR for https://www.drupal.org/project/social/issues/3020571

### CODE REVIEW

**Comment by Kingdutch** [comment]
The update hook here should probably be changed to a post_update hook. :) I'll take a look at it this month.

Schema looks good from first glance (and passing CI tests). Nice improvements in the activity_logger.module

Moss still needs a look :)

**Comment by jaapjan** [comment]
@Kingdutch did you manage to look into this last month?

**Comment by Kingdutch** [comment]
I did have some time today. However, moving to a post_update hook doesn't seem to work locally. I'll finish and merge this tomorrow.

**Comment by Kingdutch** [comment]
@jaapjan The new update hook seems to run fine on Travis so I think that was an issue with my local installation. 

The failures in MOSS are not related to this Pull Request so I think we can merge this :)

**Pull request merged**
