### PR TITLE
Bugfix/2980661 gdpr inform brand color

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
Socialbase should provide structure only and should not provide coloring for blocks as that could break the color schemes of extending themes such as socialblue.

The GDPR Inform Block provides a (non variable) color to the card title of the GDPR inform and consent block.

## Solution
Move the color to the socialblue theme and utilise the $brand-primary color variable.

## Issue tracker
- https://www.drupal.org/project/social/issues/2980661

## HTT
- [x] Check that the inform block still looks the same

## Documentation
- [x] This item is added to the release notes

### CODE REVIEW

**Comment by jaapjan** [comment]
@Kingdutch when do you plan to work on this?

**Comment by Kingdutch** [comment]
@jaapjan @bramtenhove Updated :)

**Comment by jaapjan** [comment]
@Kingdutch thanks, could you update the branch `test-distro/dev-bugfix/2980661-gdpr-inform-brand-color` on PAC and remove the patch from composer.json there?

**Comment by Kingdutch** [comment]
@jaapjan Done

**Pull request merged**
