### PR TITLE
Issue #3275150 by agami4: Improve title and subtitle on the mobile screen

### PR DESCRIPTION
**Pull request by agami4**
## Problem
Words of the title and subtitle are hidden in the mobile version.

## Solution
Remove the `max-height` style from the title and subtitle on the mobile screen.

## Issue tracker
https://www.drupal.org/project/social/issues/3275150
https://getopensocial.atlassian.net/browse/SUP-2414

## How to test
- [x] Create the landing page
- [x] Create the hero small banner
- [x] Add a long title and subtitle

## Screenshots

**before:**
image-20220411-110245

**after:**
Screenshot 2022-04-15 at 00 02 44

## Release notes
The title and subtitle display fully on the mobile screen.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2882-bgtg4pehpx1ck4qxajcv0hxjjvkemqse.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62588b209d9568879fdf5100

**Review by ribel — APPROVED** [review]

**Review by Ressinel — COMMENTED** [review]
Hi @agami4 

For mobile, it looks good but for desktop, the title and subtitle are cut.
Shouldn't we fix it for the desktop as well?

### Desktop

c78aaf36aaf3a7498ce51f2c4a9c0a36

### Mobile:

28b2d918a6a8d7e744ec1f484765face

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2882-bgtg4pehpx1ck4qxajcv0hxjjvkemqse.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62588b209d9568879fdf5100

**Comment by Ressinel** [comment]
🍒-picked to `11.0.x`, `11.1.x`, and `11.2.x`

**Pull request merged**
