### PR TITLE
Issue #3386542 by nkoporec: Update drupal/csv_serialization from 2.x to 3.x

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
It is not possible to support both Drupal 9.x and 10.x in a single release of this module due to a breaking change in EncoderInterface::encode() between Symfony 4.4 (D9) and Symfony 6.2 (D10). When preparing for an upgrade to Drupal 10 we need to widen Composer version constraints to allow either 2.x or 3.x: composer require drupal/csv_serialization:^2.0 || ^3.0. This will allow the module to be automatically upgraded when you upgrade Drupal core.

Changelists:

[https://git.drupalcode.org/project/csv_serialization/-/commits/3.x?ref_t...](https://git.drupalcode.org/project/csv_serialization/-/commits/3.x?ref_type=heads)

## Solution
Allow 3.x version in composer.json

## Issue tracker
https://www.drupal.org/project/social/issues/3386542

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Set up Open Social 
- [ ] Enable social_user_export
- [ ] Go to /admin/people and select users
- [ ] Run VBO action 'Export selected users to CSV'
- [ ] Check that the CSV file is correct

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Update drupal/csv_serialization module to latest version.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3518-qsd2bqrocglz76v1olsttkpeiyusk0kt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ff5057a34e83b789b38166

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3518-qsd2bqrocglz76v1olsttkpeiyusk0kt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ff5057a34e83b789b38166

**Review by vcsvinicius — APPROVED** [review]
@nkoporec I approved this pull-request

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3518-qsd2bqrocglz76v1olsttkpeiyusk0kt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ff5057a34e83b789b38166

**Comment by BiaInacio** [comment]
Update works as expected!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3518-qsd2bqrocglz76v1olsttkpeiyusk0kt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ff5057a34e83b789b38166

**Pull request merged**
