### PR TITLE
Issue #3413772 - Render context empty when mentioning users

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
When running the cron the message outputs

LogicException: Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead. in Drupal\\Core\\Render\\Renderer->doRender() (line 251 of /app/html/core/lib/Drupal/Core/Render/Renderer.php). {\"severity_level\":3,\"exception\":\"[object] (LogicException(code: 0): Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead. at /app/html/core/lib/Drupal/Core/Render/Renderer.php:251)\"}

## Solution
Replace the render for renderPlain in the social_profile_organization_tag.module

## Issue tracker
https://www.drupal.org/project/social/issues/3413772

## How to test
- [ ] Enable the social_profile_organization_tag
- [ ] Go to a user profile and in the stream mention his name.
- [ ] Run the cron and see in the advancedqueue the render context empty
- [ ] Checkout to this branch and do it again, notice it will run correctly now
- [ ] Also check that the email is still correctly rendered.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Fixed an issue where mentioning someone would not send out a notification email when the social_organization_tag extension has been enabled.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Review by vcsvinicius — APPROVED** [review]
I approved the PR

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Comment by BiaInacio** [comment]
Cron ran without any problem!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3697-hjfruusy0t6awde0c4kkdjhasbhbakej.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659fc6b90d79d1e4df3a98fa

**Comment by ronaldtebrake** [comment]
Cherry picked to 12.0.x and 12.1.x

**Pull request merged**
