### PR TITLE
Issue #2964693: Update Bootstrap from 3.9 to 3.11

### PR DESCRIPTION
**Pull request by Crazylord**
Updated bootstrap to 3.11
Removed unnecessary patch for Bootstrap

## Issue tracker
- https://www.drupal.org/project/social/issues/2964693
- DS-5350

## HTT
- [ ] Checkout to this branch
- [ ] Check out the code changes

## Documentation
- [ ] This item is added to the release notes

### CODE REVIEW

**Comment by jaapjan** [comment]
I've reviewed, but all the tests are failing. See for example:
https://travis-ci.org/goalgorilla/open_social/jobs/372044373

Check the changelog of 3.10: https://www.drupal.org/project/bootstrap/releases/8.x-3.10

Changes in our themes necessary for:
1. https://www.drupal.org/node/2943973
2. https://www.drupal.org/node/2943327

Could you fix this @Crazylord

**Comment by Crazylord** [comment]
Hi @jaapjan. I checked this errors and looks like this is not related to theming. 
When I try make the same tests manualy - all works good.
I think need help from developer for this.

**Comment by jaapjan** [comment]
@OH17L and @Crazylord could you guys explain why you didn't do anything with these 2 change requests? I expected some code changes related to that. What is the reason why? Don't you think it is applicable for our theme(s)?

https://www.drupal.org/node/2943973
https://www.drupal.org/node/2943327

**Comment by jaapjan** [comment]
After checking and testing thoroughly and the fact that change requests does not break anything (yet) we decided to merge it for now. Would be great if you could still answer those questions though.

**Pull request merged**
