### PR TITLE
Issue #3423900: Set default cache maximum age with 1 hour

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The default `cache.page.max_age` isn't configured and the default value is 0, change it to 1 hour to increase our performance.

## Solution
1. Create a hook-update to set 1 hour for cache maximum age when it's empty and create a configuration modify to new installation being with 1 hour as default cache maximum age.
2. Fix behat tests

Expanding on that a bit more, as you can see it's quite the change.
The biggest issue is that we currently have a lot of places where we now encounter browser cache.

This is because `FinishResponseSubscriber`

```
    if ($is_cacheable && $this->config->get('cache.page.max_age') > 0) {
      if (!$this->isCacheControlCustomized($response)) {
        // Only add the default Cache-Control header if the controller did not
        // specify one on the response.
        $this->setResponseCacheable($response, $request);
      }
    }

.....

  protected function setResponseCacheable(Response $response, Request $request) {
    // HTTP/1.0 proxies do not support the Vary header, so prevent any caching
    // by sending an Expires date in the past. HTTP/1.1 clients ignore the
    // Expires header if a Cache-Control: max-age directive is specified (see
    // RFC 2616, section 14.9.3).
    if (!$response->headers->has('Expires')) {
      $this->setExpiresNoCache($response);
    }

    $max_age = $this->config->get('cache.page.max_age');
    $response->headers->set('Cache-Control', 'public, max-age=' . $max_age);
```

Adds the Cache-Control header, which is used by the browser to base it's cache on (obviously, it has other things like last modified, ETAG and more headers that influence it)

But, because we're not using Scenario's across the board in our behat tests, we will see that browser cache is used incorrectly. In a sense that the caching is correct, but we're not clearing it correctly.

For that we have introduce an additional reset in the existing BeforeScenario, which means the browser cache is cleared between scenario's. I've also left other examples which we've tried but which weren't succesfull in clearing it correctly.

Having a browser cache clear between scenario's allows us to now split up some tasks in different scenario's. Something we want to do anyway considering it's best practice. So we took the time to rewrite the failing scenario's which had issues with browser cache in place fully, to also make behat linting green. Eventhough it wasn't the entire scenario failing, but this way it's easier to trace back and get a lot of value along with it.

But also when you think about it, you can now create scenarios using the arrange / act / assert way, with caches being tested in between your scenario. The whole goal of asserting (and background) is to setup your test in such a way you can act and arrange on it and not have to deal with other scenarios. 

## Issue tracker
[PROD-28382](https://getopensocial.atlassian.net/browse/PROD-28382)
[#3423900](https://www.drupal.org/project/social/issues/3423900)

## Theme issue tracker
N/A

## How to test
N/A

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-28382]: https://getopensocial.atlassian.net/browse/PROD-28382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3794-ykmro0xfjmnyv1cwn2dfedgbdcmosrx0.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65dcd521ba55b82d30ec57b9

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
Change looks good and think this will help with our future behat test, hopefully having to rely less on the step "I clear the cache" as it does not really sounds like a step that should be in a behat test.

**Pull request merged**
