### PR TITLE
Issue #3402882: Deprecated message for Social GraphQL module for PHP8.1

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
To keeping forward with PHP 8.1 compatibility, the Social GraphQL is throwing a deprecated message:
`
Return type of Drupal\social_graphql\GraphQL\Violation::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed
`

## Solution
Add a return type for the function: Drupal\social_graphql\GraphQL\Violation::jsonSerialize()

## Issue tracker
[#3402882](https://www.drupal.org/project/social/issues/3402882)

## Theme issue tracker
N/A

## How to test
Run PHPUnit and check ht deprecated message is resolved.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3615-bfiwwt6jfk62g2byqtw38ahgrvmvwies.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b7ff7382826646cae759f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3615-bfiwwt6jfk62g2byqtw38ahgrvmvwies.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655b7ff7382826646cae759f

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Screenshot 2023-11-21 at 08 18 00
Screenshot 2023-11-21 at 08 18 27

You can clearly see the difference, nice! 👏

**Comment by ronaldtebrake** [comment]
Also cherry-picked to 12.0.x 🍒

**Pull request merged**
