### PR TITLE
Issue #3402176: Add Social Media System module (social_media_system)

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
We need a module for all the default media configuration that can be reused by other modules.

## Solution
Add Social Media System module (social_media_system) to Open Social.

## Issue tracker
[3402176](https://www.drupal.org/project/social/issues/3402176)

## Theme issue tracker
N/A

## How to test
- [ ] Install social_media_system
- [ ] go to admin/structure/media/add
- [ ] Under "Field with source information" you are able to select `media.field_media_file`

Screenshot 2023-11-10 at 15 59 22

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Add Social Media System module to Open Social. This release does not bring any functional changes for Open Social, to the current set of features. The existing functionalities remain unaffected.

## Change Record
Any media related configuration, that can be reused by other modules, should live in social_media_system module from now on.

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3605-p0y5q5pbzloyambh1iibalkyahnpgpwy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/654e45a1f4558a785c9eae66

**Comment by zanvidmar** [comment]
🍒 Cherry-picked to 12.x here: [acb009f99](https://github.com/goalgorilla/open_social/commit/acb009f99f63b026c543e9054bbc704ae0792c10)

**Pull request merged**
