### PR TITLE
Issue #3427607 by slowflyer, Kingdutch: Variables are incorrectly output in strings causing them to be interpolated as different variables

### PR DESCRIPTION
**Pull request by Kingdutch**
<h3 id="summary-problem-motivation">Problem/Motivation</h3>
There's various cases in the codebase where a string is created and a variable is interpolated (e.g. <code>"Something like {$foo}"</code> where this happens incorrectly (i.e. <code>"Something like ${$foo}"</code>) which causes the contents of the variable to be used as name of a different variable that's then interpolated.

After internal investigation we find that none of the 5 occurrences found provide the ability to leak sensitive data and thus we do not consider this a security issue.

Three times in test code.
<ul>
<li>tests/behat/features/bootstrap/TaggingContext.php</li>
<li>tests/behat/features/bootstrap/BookContext.php</li>
<li>tests/behat/features/bootstrap/AlbumContext.php</li>
</ul>

<code>src/Installer/OptionalModuleManager.php</code> which is only run on install and does not use user input.

<code>modules/custom/social_graphql/src/GraphQL/EntityConnection.php</code> which does use user input and was the most likely candidate. However any variables that can be accessed from the particular line of code are deemed to be safe to leak.

<h3 id="summary-proposed-resolution">Proposed resolution</h3>
Fix the string interpolation to use <code>{$variable}</code>

## Issue tracker
https://www.drupal.org/project/social/issues/3427607

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Review by ronaldtebrake — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3813-xqjxnmriuh2d6n4fwyivcgfwr4j3qxbg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65f1afbb41b1ff2ae94c2cff

**Comment by ronaldtebrake** [comment]
Also in 12.3.x,12.2.x & 12.1.x 🍒

**Pull request merged**
