### PR TITLE
Internal: Fix PHPStan errors

### PR DESCRIPTION
**Pull request by tregismoreira**
## Description

This PR fixes the PHPStan errors recently merged into `main`: https://github.com/goalgorilla/open_social/actions/runs/11743894946/job/32717905178?pr=4163

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Review by ribel — APPROVED** [review]
LGTM, can be rebased after this one is merged: https://github.com/goalgorilla/open_social/pull/4180

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4171-b4k43gaxfsy46xwjkw8ljprocsqv0rjb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e326121db79eb236ff311

**Pull request merged**
