### PR TITLE
Update PR 2710 to match restructure of alternative_frontpage module

### PR DESCRIPTION
**Pull request by NickDaelemans**
## Problem
In our alternative frontpage we have the option to set a homepage for logged in users and anonymous. It makes no point to set a page for anonymous that has the visibility set to Logged in users, because that would redirect to an access denied/login page.

## Solution
When going to the alternative frontpage settings and setting a page for anoymous users it must check which visibility that page has and give a validation error if it’s set for logged in users.

## Issue tracker
https://www.drupal.org/project/social/issues/3259724

## How to test

- [ ] Enable alternative_frontpage module
- [ ] Create a basic page with community visibility
- [ ] Go to the alternative frontpage settings form and add the basic page for anonymous
- [ ] Access to the home page as anonymous

## Screenshots
None

## Release notes
We fixed an issue for the alternative frontpage that if you set a community page for anonymous users it could in some cases cause an infinite redirect loop as anonymous users are not allowed to visit community pages. 

## Change Record
None

## Translations
None

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2711-vwhzhwxlrrp6kg8pasndcooekmxuehem.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0193900c7e8a7588efa21

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2711-vwhzhwxlrrp6kg8pasndcooekmxuehem.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0193900c7e8a7588efa21

**Comment by robertragas** [comment]
I'm merging this back in the main issue and will continue reviewing there.

**Comment by robertragas** [comment]
Code looks good, but guess we need to copy the template information from the PR that Nacho made so it's clear here what the goal is, and think we should wait until the other one is merged so we don't get tangled up there.

**Comment by robertragas** [comment]
And off course check out Travis

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2711-vwhzhwxlrrp6kg8pasndcooekmxuehem.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0193900c7e8a7588efa21

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2711-vwhzhwxlrrp6kg8pasndcooekmxuehem.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f0193900c7e8a7588efa21

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
Merged and cherry picked to 11.1.x

**Pull request merged**
