### PR TITLE
Issue #3292189 by agami4: Improve teaser album on the mobile mode

### PR DESCRIPTION
**Pull request by agami4**
## Problem
Teaser body is missed for the album

## Solution
Add `flex-wrap: nowrap` to the parent element.
Improve the height of the teaser body.

## Issue tracker
https://getopensocial.atlassian.net/browse/YANG-8050
https://www.drupal.org/project/social/issues/3292189

## Theme issue tracker
N/A

## How to test
- [x] Go to the album page.
- [x] Open the current page on the mobile mode.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
before:
image-20220621-100137

after:
Screenshot 2022-06-23 at 13 52 32

## Release notes
The teaser body has a correct position on the mobile mode.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3009-4j91esggbbswbx4vsk0oxy5deuz29jtk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62b44755cff9b7f12b98abe5

**Review by ribel — APPROVED** [review]
I have tested changes and they looks good to me. As well as code changes.
@agami4 Just would be good t provide before/after screenshots with the same examples, so it's more clear what exactly was changed ;)

**Comment by ribel** [comment]
@Ressinel could you review it as well when you have a time?

**Review by Ressinel — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 11.1.x, 11.2.x, 11.3.x and 11.4.x

**Pull request merged**
