### PR TITLE
Issue #3251633 by agami4: Improve profile organization tag label behaviour

### PR DESCRIPTION
**Pull request by agami4**
## Problem
When I create a featured content block or a stream in the Dashboard and the content is created by a person with an organization tag, the label of the tag is always visible and breaks the layout.

## Solution
Add improvements to the behaviour of the organization label.

## Issue tracker
https://www.drupal.org/project/social/issues/3251633
https://getopensocial.atlassian.net/browse/YANG-3788

## How to test
- [ ] Add organization tag to the profile.
The first case:
- [ ] Go to the dashboard page.
- [ ] Create scream block.
- [ ] Find teaser with organization label.
The second case:
- [ ] Go to the `user/1/stream` page.
- [ ] Check behaviour on the user statistic block.

## Screenshots
before:
Screenshot 2020-09-25 at 13 52 27

after:
Screenshot 2021-11-29 at 16 18 44

## Release notes
The profile organization label has a correct behaviour.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Comment by Ressinel** [comment]
Hi, @agami4

I have made some testing and saw that profile organization tag shows properly on the profile stream page, content list (posts) but it doesn't show on dashboard streams. I have used the new Social Dashboard `3.0.0`.

### Dashboard:
tag-not-shows

### Profile:
profile-tag

### Topics list:

all-topics

**Comment by agami4** [comment]
@Ressinel, thanks for the comment and it is a good point. I don't know what happened with the profile organization tag label on the dashboard. Maybe you can help me with it? I've checked it and we can not see this label on the HTML structure. Maybe it is a BE issue?
@ribel, what do you think? Perhaps anybody can check it from our team?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Comment by agami4** [comment]
@Ressinel, @YaroslavShandra88 added improvements. Please re-check new changes.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Review by Ressinel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Review by ribel — CHANGES_REQUESTED** [review]
@agami4 I understand that this change it improves label visibility in some cases, but on other hand, it becomes less readable on the User Details page for example, where organization text is now over user name text. Can we fix that? See after screenshot you posted.

**Comment by agami4** [comment]
@ribel, I've changed the background opacity of the tag label on the user page. Please check

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2628-kgxwnlfbnefpurcitfzieu2jynojmfdq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4e19bde49705118eba8f0

**Comment by agami4** [comment]
This PR was closed after not correctly merging the main branch to the current branch. New PR https://github.com/goalgorilla/open_social/pull/2687

**Pull request closed without merging**
