### PR TITLE
Issue #3087026 by mdeny: As a CM+ I want to be able set a icon for new topic and event types

### PR DESCRIPTION
**Pull request by denysyukm**
## Problem
As a CM+ I want to be able set a icon for new topic and event types

## Solution
Implement icons for topic and event types

## Issue tracker
https://www.drupal.org/project/social/issues/3089405
https://getopensocial.atlassian.net/browse/YANG-1465

## How to test
For topics:
- [ ] go to topic types taxonomy page
- [ ] change icon fields in terms
- [ ] go to /all-topics page
- [ ] the icons of topic's teasers should be changed

For events:
- [ ] go to event types taxonomy page
- [ ] change icon fields in terms
- [ ] go to /community-events page
- [ ] the icons of event's teasers should be changed

## Release notes
Implemented icons for topic and event types

### CODE REVIEW

**Comment by ronaldtebrake** [comment]
Hi guys, when trying to review this issue it seems something was missed in the update hook.

Screen Shot 2020-01-21 at 16 59 18

We should be able to first update the database and do a feature revert after (eventhough we are obviously moving to CMI but that's another story :P) 

Could you check it out and ensure we can update from older versions in to this?

**Comment by ribel** [comment]
@agami4 please regenerate svg file after merge conflict.

**Comment by agami4** [comment]
@ribel, Icons were updated

**Comment by ribel** [comment]
@denysyukm please create test env to check if this feature is still working. 
Would be good to merge it t 10.x if all ok.

**Comment by denysyukm** [comment]
@ribel , I created PR on ECI Demo to test functionality. Check: https://bitbucket.org/goalgorilla/eci_demo/pull-requests/138

**Review by ribel — CHANGES_REQUESTED** [review]
@denysyukm 
After creating the topic I see the following error:

```
InvalidArgumentException: Field field_topic_type_icon is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of core/lib/Drupal/Core/Entity/ContentEntityBase.php).
Drupal\Core\Entity\ContentEntityBase->get('field_topic_type_icon') (Line: 61)
social_topic_preprocess_node(Array, 'node', Array) (Line: 287)
```

The reason is that this PR was created when we were using features, but no new fields need to be added with hook update. So please fix that. Make sure that you add check in case field already exists.

**Comment by ronaldtebrake** [comment]
Hi @denysyukm //cc @ribel - Really love this feature, also with the list of available icons.

I've fixed the merge conflict, added update hooks for the new field, storage and the form display so it should now also work for existing installations.

If tests turn green I'll merge it and add a known issue with the icon preview not correctly working.
But thats a minor one, it does work like a charm.
Will also add a feature request to make this work for the new group type field for flexible groups.

**Pull request merged**
