### PR TITLE
Issue #3382576 by nkoporec: Disable revisions for groups

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When doing a clean install of the latest Open Social (from branch dev-main), revisions are enabled for groups and show up as a tab in the group itself.

## Solution
Disable revisions as this was not enabled before.

## Issue tracker
https://www.drupal.org/project/social/issues/3382576

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
1. Install clean OS
2. Go to admin/group/types/manage/closed_group
3. See that Create a new revision when a group is modified checkbox is **disabled**.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

Before:
image

After:
image

## Release notes
Disabled revisions for groups.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by nkoporec** [comment]
@BiaInacio This is correct as per screenshot, the option should be disabled and the "Revisions" tab should not be visible when viewing the group stream pages.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3486-tvfunxdcbi5jabkt6vx2youuyldduogn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64e4b6f6dbfaac75b49bedb5

**Comment by BiaInacio** [comment]
Hi @nkoporec,
Thank you for the explanation, test ok! 😄

**Review by tbsiqueira — APPROVED** [review]

**Comment by nkoporec** [comment]
New PR: https://github.com/goalgorilla/open_social/pull/3517

**Pull request closed without merging**
