### PR TITLE
Issue #3421348: Remove redundant group type filters from group views

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
We have various views that we re-use for things that we build on top of group. For example "Manage members" or "Manage group invites". These views show data that is in the context of a specific group.

Additionally as part of [#3380714] we're moving from the old group types to flexible groups. A sub-goal of that migration is to make <code>social_group_flexible_group</code> an optional feature which contains "Open Social's concept of a group" and to make <code>social_group</code> a module that "Contains tools for building on-top of the group module within an Open Social context". The idea being that Group as a module is very useful for "Collections of things with member based access controls" and we may want to build things that contain a group of users with certain levels of access but are conceptually not "an Open Social Group", for example a "Course".

Because the views mentioned provide re-usable functionality they should live in <code>social_group</code>. However they currently filter based on group type which causes them to have an implicit dependency on the module that provides the group type. This causes the <code>social_group</code> module to depend on modules it shouldn't depend on. Additionally it requires any module that wants to use the view to update the filter to add it's group bundle.

The views don't actually need to filter based on group type. The group itself is already provided as context to the view and the filter on its type thus already exists from that context. 

## Solution
We should remove the bundle specific filtering from the view and instead rely on the group provided through context.

In case something built on top of the group entity doesn't want to use the view for its group-type then access handling should be used to revoke access to the view when that group is passed in as context, rather than editing the view.

### Changes made
For views.view.group_events we remove specific references to group types. To ensure we only show event content we make the relationship to the events required. We can also remove the validation of the group type.

The view is also moved to `config/optional` so that it’s only available if the views module and the social_event module are enabled. This brings us closer to not requiring a dependency on `social_event` from `social_group`. The other changes are relatively small but out of scope for this issue.

For views.view.group_topics we make similar changes, but we add `social_topic` as a dependency for the view since it contains the required node bundle. Again this is moved to `config/optional` in a first step to decouple `social_group` from `social_topic`.

For views.view.group_manage_members we also remove the filters. There might be multiple different relationships between a user and a group. For example “invites”, “membership requests” and actual “memberships”. The `gc__user` relationship ensures that we only show actual memberships. This also provides an option to unify the invites/request/member views by playing with these relationships.

The same goes for views.view.group_members. However, here the relationship doesn’t exist yet so we add it to ensure we only show full-members.

For views.view.group_managers we make use of the naming for group roles being `<group_type>-<role_name>` and the fact that we use `group_manager` as role name consistently across our existing group types. This allows us to match for a role `-group_manager` regardless of which group the role belongs to. While we’re at it we simplify the groupings of this filter.

There are other views that we leave as non-optional for future changes.

SocialGroupAdminPeopleConfigOverride is removed because the modifications it makes to views are no longer needed.

## Issue tracker
https://www.drupal.org/project/social/issues/3421348

## How to test
- [ ] Existing group functionality should work as expected
- [ ] Create a new group type and add the event relationship see that the view works without any changes
- [ ] If no event relationship are added the events view shouldn't do anything
- [ ] The same goes for the other view types

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
The views that are contained in `social_group` have been changed to no longer refer to group types directly. Instead the relationship with a specific content type or a group with a specific role ID (matching on the end; not the group type) is used to make it easier to re-use these views for custom group types without having to change their configuration.

Some of the views have also been moved to the `config/optional` folder in preparation of better decoupling Open Social's individual features (such as groups, events, etc.)

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Review by nechai — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3763-nurjaapu4uv3yrs0meahdsklx9tm4cgk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65cde946c5f017e403e23844

**Review by ribel — APPROVED** [review]

**Pull request merged**
