### PR TITLE
PROD-29813: Security fixes for embeddable links

### PR DESCRIPTION
**Pull request by tregismoreira**
## Problem
We’ve received a couple of vulnerability alerts related to social_embed implementation. The vulnerability is mostly caused by the fact that the [whiteList()](https://github.com/goalgorilla/open_social/blob/main/modules/social_features/social_embed/src/Service/SocialEmbedHelper.php#L101) method is returning TRUE if it finds at least 1 link with the provided pattern, so one could use add a malicious link alongside a white-listed URL.

## Solution
In order to prevent this issue, we should:
- Fix the algorithm for checking white-listed sources;
- Make sure we use oEmbed only for the [official supported providers](https://oembed.com/providers.json) instead of using the discovery mechanism, since it opens several security concerns. I’d keep our list of patterns as is;
- Disallow any provider other than the ones white-listed in code to use oEmbed.

The method `convertUrls` was simplified since the approach is more straight-forward. Some methods were removed because they are not needed anymore. I also took the chance to added `x.com` as an allowed provided.

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-29813

## Theme issue tracker
N/A

## How to test
- [ ] Checkout the branch `issue/PROD-29813-security-social-embed`
- [ ] Create a new post with the following content:
```
<h2>These links should be embedded</h2>

https://x.com/Greenpeace/status/1821894214688633054
https://www.ted.com/talks/ethan_hawke_give_yourself_permission_to_be_creative?vwo=featured&subtitle=en&geo=pt-br

<h2>Even without the <code>https://</code> or <code>www.</code></h2>
x.com/Greenpeace/status/1821803687070855406

<h2>These links are not whitelisted, so won't be embedded</h2>

- https://greenwire.greenpeace.ch/fr/post/341
- https://google.com

<h2>If a whitelisted website is used as a link, it should not be embedded</h2>

<a href="https://x.com/Greenpeace/status/1821894214688633054">Example with link</a>

```

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4016-34uj54amfgjxejbduryg59vzub514dte.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66b776316c7d83449c9c6af2

**Review by nechai — APPROVED** [review]
LGTM

**Pull request closed without merging**
