### PR TITLE
Issue #3328607: Refactor Behat scripts from capabilities > administration

### PR DESCRIPTION
**Pull request by BiaInacio**
## Problem
There was a need due to a poor organization of scripts to refactor and validate old Behat scripts from capabilities > administrator to improve its quality.

## Solution
Organise the behat scrip to improve its quality by:
- Adding comments explaining steps that are not intuitive
- Adding the correct indentation
- Renaming the scripts
- Fixing bugs

## Issue tracker
https://www.drupal.org/project/social/issues/3328607

## Theme issue tracker
N/A

## How to test
Pre condition:
- [ ] Set up the local environment
- [ ] Docker should be running Social local environment

Steps:
- [ ] run the behat scripts from the folder Administration by using the command: `docker exec -it social_web sh /var/www/scripts/social/behatstability.sh administration`

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by nkoporec** [comment]
there are some tests failing, so I'm re-running it to see if it was a false positive

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3269-phzh8ogiine6nesjubcjk18lld9rdrvr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a321fee6bc62df9c335e19

**Comment by nkoporec** [comment]
@BiaInacio can you check why the administration tests are failing ?

**Comment by BiaInacio** [comment]
@nkoporec Please check it now, I have fixed the issue.

**Pull request merged**
