### PR TITLE
Issue #3277621: Update socialblue dependency to 2.1.5

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Socialbase and socialblue have new releases, we need to update the release on our composer.json

## Solution
Update socialblue to 2.1.5 version

## Issue tracker
https://www.drupal.org/project/social/issues/3277621

## Theme issue tracker
N/A

## How to test
- [ ] Install this branch, and smoke test the front-end, make sure everything is working as expected;

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2903-isysgja4l3hlsrswlmfaregpp8rmbcqk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62668b31ef17c6f569d0d67c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2903-isysgja4l3hlsrswlmfaregpp8rmbcqk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62668b31ef17c6f569d0d67c

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2903-isysgja4l3hlsrswlmfaregpp8rmbcqk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62668b31ef17c6f569d0d67c

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2903-isysgja4l3hlsrswlmfaregpp8rmbcqk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62668b31ef17c6f569d0d67c

**Comment by Ressinel** [comment]
🍒-picked to [11.3.x](https://github.com/goalgorilla/open_social/commit/200f395a859c38d84f2546c9f184692720bf772a) and pushed to [11.2.x](https://github.com/goalgorilla/open_social/commit/54aa04fdf2715ab91f650fa2f04d87a56a502ce4) after fixing conflicts

**Pull request merged**
