### PR TITLE
Issue #3247896 by tBKoT: Fix errors with activity tokens when the related object does not exist

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
`Error: Call to a member function getVotedEntityType() on null in social_like_tokens_alter() (line 152 of profiles/contrib/social/modules/social_features/social_like/social_like.tokens.inc). `

Also, I've noticed that we do have a not correct condition to check if the field is empty here #2277 which could provide critical issues on the token replacement process.
`empty($entity->geet('<field_name>'))` will always return FALSE, so better to ALWAYS use already existing method `isEmpty()` for field values.

## Solution
Check if the like exists and we do not use the `NULL` value.

## Issue tracker
https://www.drupal.org/project/social/issues/3247896
https://getopensocial.atlassian.net/browse/YANG-6552

## How to test
- [x] Like some content
- [x] Generate activity (run cron)
- [x] Remove like
- [x] Check the last page of `/admin/content/message`

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2591-garnjzlwhkvrzhhttg3tokosp7c3pxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854734908ae1afb95315c5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2591-garnjzlwhkvrzhhttg3tokosp7c3pxzu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61854734908ae1afb95315c5

**Comment by Ressinel** [comment]
Hi, @dmytriikaiun Could you add the HTT list?

**Comment by dmytriikaiun** [comment]
@Ressinel done

**Review by ribel — APPROVED** [review]

**Review by Ressinel — APPROVED** [review]
Looks good to me.

**Comment by ribel** [comment]
🍒 picked to 10.3.x

**Pull request merged**
