### PR TITLE
Issue #3053687: update to 8.7.1

### PR DESCRIPTION
**Pull request by jaapjan**
## Problem
Updating to 8.7.1.

## Solution
- Updated to 8.7.1 in the make and composer file.
- Removed patch from this issue https://drupal.org/node/2599228 since it was committed to 8.7 branch.
- Updated patch for getting commented entity
- Updated patch for issue 3007424
- Replaced Entity with EntityBase
- Updated unit test for email verification
- Fix feature state to default

## Issue tracker
https://www.drupal.org/project/social/issues/3053687

## How to test
- [ ] Test the code locally and go to through the website and test all the core functions.
- [ ] Check code changes.
- [ ] Check Travis.

## Release notes
Drupal Core has been updated from 8.6 to 8.7.1. This means that the support of drush entup is also removed. You can remove that command from your update scripts safely.

### CODE REVIEW

**Comment by jaapjan** [comment]
Got this error:
```
TypeError: Argument 2 passed to Drupal\activity_creator\ActivityNotifications::markEntityNotificationsAsRead() must be an instance of Drupal\Core\Entity\Entity, instance of Drupal\comment\Entity\Comment given, called in /var/www/html/profiles/contrib/social/modules/custom/activity_creator/activity_creator.module on line 210 in Drupal\activity_creator\ActivityNotifications->markEntityNotificationsAsRead() (line 82 of profiles/contrib/social/modules/custom/activity_creator/src/ActivityNotifications.php).
```

**Comment by jaapjan** [comment]
$ if [ "$TEST_SUITE" = "install_stability_1" ]; then docker exec -i social_ci_web_scripts sh /var/www/scripts/social/unit-tests.sh; fi
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
......EEEEEEEEEEEEEEEEEEEEEEEEEEEE                                34 / 34 (100%)
Time: 274 ms, Memory: 6.00MB
There were 28 errors:
1) Drupal\social_user\Tests\SocialUserNameConstraintTest::testValidate with data set #2 (Mock_FieldItemListInterface_86b36944 Object (...), true, array(), 'prettyandsimple@example.com')
ArgumentCountError: Too few arguments to function Egulias\EmailValidator\EmailValidator::isValid(), 1 passed in /var/www/html/profiles/contrib/social/modules/social_features/social_user/tests/src/Unit/Validation/Constraint/SocialUserNameConstraintTest.php on line 69 and exactly 2 expected
/var/www/vendor/egulias/email-validator/EmailValidator/EmailValidator.php:35

**Comment by jaapjan** [comment]
Fixed feature state in commit 59ddb2034

```
Showing difference for social_core...
Legend: 
Code:    drush features-import will replace the active config with the displayed code.
Active:  drush features-export will update the exported feature with the displayed active config
Config block.block.footer 
  settings
  settings::depth : 0
> settings::expand_all_items : false
  settings::id : 'system_menu_block:footer'
  settings::label : Footer
Config block.block.mainnavigation 
  settings
  settings::depth : 0
> settings::expand_all_items : false
  settings::id : 'system_menu_block:main'
  settings::label : 'Main navigation'
Config block.block.socialbase_account_menu 
  settings
  settings::depth : 1
> settings::expand_all_items : false
  settings::id : 'system_menu_block:account'
  settings::label : 'User account menu'
Config block.block.socialblue_account_menu 
  settings
  settings::depth : 1
> settings::expand_all_items : false
  settings::id : 'system_menu_block:account'
  settings::label : 'User account menu'
Config block.block.socialblue_footer 
  settings
  settings::depth : 0
> settings::expand_all_items : false
  settings::id : 'system_menu_block:footer'
  settings::label : Footer
Config block.block.socialblue_mainnavigation 
  settings
  settings::depth : 0
> settings::expand_all_items : false
  settings::id : 'system_menu_block:main'
  settings::label : 'Main navigation'
Showing difference for social_profile...
Legend: 
Code:    drush features-import will replace the active config with the displayed code.
Active:  drush features-export will update the exported feature with the displayed active config
Config taxonomy.vocabulary.expertise 
  description : 'A users expertises'
< hierarchy : 0
  langcode : en
  name : Expertise
Config taxonomy.vocabulary.interests 
  description : 'A users interests for their profile.'
< hierarchy : 0
  langcode : en
  name : Interests
Config taxonomy.vocabulary.profile_tag 
  description : 'CM can tag a user, giving options on filtering / searching users.'
< hierarchy : 0
  langcode : en
  name : 'Profile tag'
Showing difference for social_topic...
Legend: 
Code:    drush features-import will replace the active config with the displayed code.
Active:  drush features-export will update the exported feature with the displayed active config
Config taxonomy.vocabulary.topic_types 
  description : 'Topic types'
< hierarchy : 0
  langcode : en
  name : 'Topic types'
The feature state is not default!
```

**Comment by frankpanduh** [comment]
social 8.x-6.x-dev fails to update after updating core.

**Comment by truls1502** [comment]
@ronaldtebrake - how about [8.7.2](https://www.drupal.org/project/drupal/releases/8.7.2)?

**Pull request merged**
