### PR TITLE
Issue #3426132: Update the patches with Drupal 10.2.4

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Drupal was upgraded to 10.2.4 version and a couple patches is brokwn to be applied.

## Solution
1. Updated patch about image filesystem [#2786735](https://www.drupal.org/project/drupal/issues/2786735)
2. Removed patch about datetime, they are fixed in this version

## Issue tracker
[PROD-28480](https://getopensocial.atlassian.net/browse/PROD-28480)
[#3426132](https://www.drupal.org/project/social/issues/3426132)

## Theme issue tracker
N/A

## How to test
- [ ] Regression test

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-28480]: https://getopensocial.atlassian.net/browse/PROD-28480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3806-55kjfusdnt8dkoukeu0nog0nvvnaxxqe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65e8a8e6a1fc0bcda45a01a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3806-55kjfusdnt8dkoukeu0nog0nvvnaxxqe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65e8a8e6a1fc0bcda45a01a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3806-55kjfusdnt8dkoukeu0nog0nvvnaxxqe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65e8a8e6a1fc0bcda45a01a4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3806-55kjfusdnt8dkoukeu0nog0nvvnaxxqe.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65e8a8e6a1fc0bcda45a01a4

**Review by ronaldtebrake — APPROVED** [review]

**Pull request merged**
