### PR TITLE
Issue #3406164 - Make sure our email template styling gets converted correctly.

### PR DESCRIPTION
**Pull request by robertragas**
## Problem
We are having an issue where our e-mails lose styling / formatting. 

1. the inline-css plugin does not see any css and will not go through the css-inline plugin and will not add inline css. This causes gmail to not have any styling. 
2. there are emails without text formats, meaning they are escaped, mail_html feels like a safe workaround.

## Solution
As a workaround we are adding our own plugin who basically does the same apart from that it will do this always, not only if there is additional css and additionally adds a fallback if there is no text format.

## Issue tracker
https://www.drupal.org/project/social/issues/3406164

## How to test
- [ ] Configure Symfony mailer so it's able to send out email via admin/config/system/mailer/transport
- [ ] Use the old branch of code first and send out a test email via admin/config/system/mailer/test
- [ ] When receiving the email, right click and inspect element. Notice that the element don't have style attribute on it.
- [ ] Check out to this branch and try again
- [ ] Notice that the elements have a style element on it similar to the screenshot below.
Screenshot 2023-12-06 at 16 12 52

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
We introduced a workaround to fix the inline-css styling not being applying to emails causing the emails to not be styled for some clients like gmail.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by ronaldtebrake** [comment]
Screenshot 2023-12-07 at 12 24 36

Update hook also works great 👍

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3633-fydssxo2ucefxfoq9ydtsjvmk5rhxkno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65708c8cec1e7bc242d621dc

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Cherry-picked to 12.0.x

**Pull request merged**
