### PR TITLE
Internal: Fix random test failure with `groups-edit-content-in-group.feature`

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
Internal: Fix random test failure with `groups-edit-content-in-group.feature`

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3724-1wvtcawe6u9dcyahcg8rre1pvgtjrdaz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b37c0482e119e53e3fb261

**Comment by ronaldtebrake** [comment]
We're going to remove this test, so rewriting it doesn't make much sense. Manually (and locally) running this test works fine, so closing this so we can fix the last issue (the patch not applying) in a separate PR.

**Pull request closed without merging**
