### PR TITLE
Issue #3301508 by ribel: Allow to filter by Flexible groups in custom content list block

### PR DESCRIPTION
**Pull request by ribel**
## Problem
Currently it is not possible to filter Topics by Flexible groups in Custom content list block.
Only Open and Public groups are supported.

## Solution
Add ability to filter by Flexible group type together with Open and Public groups in field settings.

## Issue tracker
- https://www.drupal.org/project/social/issues/3301508
- https://getopensocial.atlassian.net/browse/SUP-2885

## Theme issue tracker
N/A

## How to test
- [ ] Using version 11.5.x of Open Social with the `social_content_block` module enabled
- [ ] As a sitemanager
- [ ] Add some content to Flexible group
- [ ] When create Custom content list block you should be able to filter content by this Flexible group.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
Added ability to filter by Flexible group type together with Open and Public groups in Custom content list block.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-z9g48jp4u9octwkjwtcgfsifvolhpqta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62ea47737e6c3f16da9a62b7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-z9g48jp4u9octwkjwtcgfsifvolhpqta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62ea47737e6c3f16da9a62b7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-z9g48jp4u9octwkjwtcgfsifvolhpqta.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62ea47737e6c3f16da9a62b7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Review by nkoporec — CHANGES_REQUESTED** [review]
@ribel tests are failing, most likely just need a rebase. Could you also update the steps, so its more clear how to test it? Currently is very vague.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by ribel** [comment]
Hi @nkoporec, 
I've fixed issue with failing behat test. It was related to missing dependency.
Now it's ready for the review again.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3063-9cwsijcpjqrsvnjcyfdgoezeerra3kh2.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63932e23a72d590818558033

**Comment by nkoporec** [comment]
:cherries: picked to 11.5.x  and 11.6.x

**Pull request merged**
