### PR TITLE
Issue #3344980 by agami4: Reset extra styles for the Follow tags block

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The organization dashboard displays the additional frame around selected tags.

## Solution
Reset extra styles for the follow tag block.

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-24292
- https://www.drupal.org/project/social/issues/3344980

## Theme issue tracker
N/A

## How to test
- [ ] Enable module `social_follow_landing_page`
- [ ] Create new Landing Page, Dashboard or Organisation
- [ ] Add `Follow tags` block
- [ ] Style of this block should be consistent with other blocks. 

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
**Before:**
image-20230221-202012

**After:**
Screenshot 2023-02-28 at 17 16 49

## Release notes
The `Follow tags` block does not have an extra frame.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Review by ribel — APPROVED** [review]
Changes looks good to me. 
I've also tested them on Landing pages and it looks good.
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3325-ggbnrx24o1zl7j9kxd1bor96rw3utm8y.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63fe1bc7d5af549afd323d12

**Comment by nkoporec** [comment]
:cherries:  picked to 11.7.x and 11.8.x

**Pull request merged**
