### PR TITLE
Add visibility validation for anonymous alternative frontpage.

### PR DESCRIPTION
**Pull request by nachosalvador**
## Problem
In our alternative frontpage we have the option to set a homepage for logged in users and anonymous. It makes no point to set a page for anonymous that has the visibility set to Logged in users, because that would redirect to an access denied/login page.

## Solution
When going to the alternative frontpage settings and setting a page for anoymous users it must check which visibility that page has and give a validation error if it’s set for logged in users.

## Issue tracker
https://www.drupal.org/project/social/issues/3259724

## How to test

- [ ] Enable alternative_frontpage module
- [ ] Create a basic page with community visibility
- [ ] Go to the alternative frontpage settings form and add the basic page for anonymous
- [ ] Access to the home page as anonymous

## Screenshots
None

## Release notes
Add visibility validation for anonymous alternative frontpage on settings form page.

## Change Record
None

## Translations
None

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2710-mbmn3uol4geoy97vo06fbigmgsgqlrob.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ea7ed4f8a118577f686bc0

**Comment by navneet0693** [comment]
I just want to re-iterate that the PR https://github.com/goalgorilla/open_social/pull/2590, will be in soon.

**Comment by navneet0693** [comment]
@nachosalvador Please check the above-mentioned PR and see if you can improve that PR if required.

**Comment by NickDaelemans** [comment]
> Member

Since Nacho left, I will pick this up. We will need to adapt this PR, since the one you mentioned deletes the file Nacho changed 😅

**Comment by NickDaelemans** [comment]
@navneet0693 I created PR https://github.com/goalgorilla/open_social/pull/2711 to match your updates. I opened the PR against your changes. Is that OK for you?

**Comment by navneet0693** [comment]
@NickDaelemans Yes, I have closed this PR.

**Pull request closed without merging**
