### PR TITLE
Issue #3304336 by zanvidmar: Tile teaser's content on resources library page on mobile is not visible

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem
Tile teasers content on resources library page on mobile is not visible

## Solution
Change css

## Issue tracker
[3304336](https://www.drupal.org/project/social/issues/3304336)

## Theme issue tracker
N/A

## How to test
- [ ] Create resources library content and go to /search/resources
- [ ] Set display size to 599px width or lower and you will see that body content of teasers is missing (see attachments).
- [ ] The teaser's content is empty
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3072-3xh3u54tsf2sk2yrdx2neqs9zcgabq5d.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62fd14ee19770b441acca777

**Comment by zanvidmar** [comment]
Can reviewer please check if updated css target any other occurrence beside the one mentioned and check if this does not break anything else. Thank you.

**Comment by nkoporec** [comment]
@zanvidmar The changes looks good, can you add a milestone and also update the PR title and description ? The resource library is a paid extension and we should not mention it in the open source community repository, just  update it and find a way to test this bug without the paid extension enabled.

**Review by nkoporec — CHANGES_REQUESTED** [review]
see comment above

**Comment by zanvidmar** [comment]
Based on further investigation the provided fix might not be correct. Further analysis is required as there are some design inconsistencies in first place.

**Comment by zanvidmar** [comment]
I am closing this issue as it will be handled differently. Here is the new MR: https://git.drupalcode.org/project/socialbase/-/merge_requests/146

**Pull request closed without merging**
