### PR TITLE
Issue #3432522: Remove deprecated modules and functions

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
We are preparing the code for 13.0.0 version and we need to remove all deprecated modules and functions.

## Solution
Remove deprecated modules and functions to be removed from 13.0.0.

## Issue tracker
[PROD-28595](https://getopensocial.atlassian.net/browse/PROD-28595)
[#3432522](https://www.drupal.org/project/social/issues/3432522)

## Theme issue tracker
N/A

### Social Event
- [ ] Create an event
- [ ] Invite an user by email

### Social Max Enrollment
- [ ] Enable module: Social Event Max Enrollment
- [ ] Create an event and set a max enrollment
- [ ] Test Max Enrollment feature

### Social Group
- [ ] Regression test of Social Group feature

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
- Add group isn't have Group Type, should be redirect to Flexible Group automaticly;
- Removed deprecated function, the depreciation was notified in before versions;

## Change Record
N/A

## Translations
N/A

[PROD-28595]: https://getopensocial.atlassian.net/browse/PROD-28595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Review by robertragas — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by BiaInacio** [comment]
Enrollees block count is breaking when an user is invited via email:
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-53k3pevk7tk1ritoskuukpztm34pyerv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65fb65246eeb18edf66f71ec

**Comment by BiaInacio** [comment]
Event scenarios are working as expected!
image
image
Group feature is working as expected too!
image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-cclnxseyjkhjtsepxurrqp8jxmsqvn1e.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66226f57268662900910df7e

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-cclnxseyjkhjtsepxurrqp8jxmsqvn1e.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66226f57268662900910df7e

**Comment by robertragas** [comment]
Rebased with latest changes from main

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3826-cclnxseyjkhjtsepxurrqp8jxmsqvn1e.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66226f57268662900910df7e

**Pull request merged**
