### PR TITLE
Issue #3450286: Fix pewview element on the general and hover states

### PR DESCRIPTION
**Pull request by Agamich-FE**
## Problem
The preview element has a wrong hover behavior on the teaser.

## Solution
Reset general and hover styles for the preview element when we use text.

## Issue tracker

- https://www.drupal.org/project/social/issues/3450286
- https://getopensocial.atlassian.net/browse/PROD-29684

## Theme issue tracker
N/A

## How to test
- [ ] Enable the `social_profile_preview` module.
- [ ] Go to the `/all-discussions`.
- [ ] Check/Hover on the use name on the teaser

## Screenshots
before:
image
Screenshot 2024-05-24 at 15 14 41

after:
Screenshot 2024-05-28 at 11 25 06
Screenshot 2024-05-28 at 11 25 19

## Release notes
The text preview element has the correct styles on the general and hover states.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3909-m5up8og3szhnsppgovujkbq5vg17s9pi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/665596494899741b9b675523

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3909-m5up8og3szhnsppgovujkbq5vg17s9pi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/665596494899741b9b675523

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3909-m5up8og3szhnsppgovujkbq5vg17s9pi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/665596494899741b9b675523

**Review by ribel — APPROVED** [review]
Changes were tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3909-m5up8og3szhnsppgovujkbq5vg17s9pi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/665596494899741b9b675523

**Pull request merged**
