### PR TITLE
Internal: PROD-27796 - Add Behat test steps around profile management

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem / Solution
As part of the profile refactor we added [quite comprehensive test steps around profiles](https://github.com/goalgorilla/open_social/blob/2b640208df7b05c79fc22c1b573e5d2aba7821b8/tests/behat/features/bootstrap/ProfileContext.php). We want to bring those into the distribution ahead of the profile refactor because they can be useful already.

All the steps that are not directly related to the new field management system are included:

-  When I am viewing my profile
-  When I try to view the profile of :user
-  Given user :username has a profile filled with:
-  Given I have a profile filled with:
-  Given have a profile filled with:
-  When I am editing my profile
-  When I try to edit the profile of :user
-  Given unique nickname for users is :state
-  Then unique nicknames for users should be :state

## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-27796

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3656-fvqevd4cjdiserol2mn7y3ffmdaqynvv.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6581c2bc8dd1363848c1155d

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Also in 12.x versions 🍒

**Pull request merged**
