### PR TITLE
Issue #3172477 by agami4: Album theming fixes

### PR DESCRIPTION
**Pull request by agami4**
## Problem
[YANG-4773](https://getopensocial.atlassian.net/browse/YANG-4773) - Error overlay incorrect.
[YANG-4774](https://getopensocial.atlassian.net/browse/YANG-4774) - Scrollwheel doesn't work anymore after zooming in and out
[YANG-4775](https://getopensocial.atlassian.net/browse/YANG-4775) - Album zoom in on safari differently than other browsers
[YANG-4783](https://getopensocial.atlassian.net/browse/YANG-4783) - The `back album` button does not have correct styles.
 
## Solution
[YANG-4773](https://getopensocial.atlassian.net/browse/YANG-4773) - Add extra `position: relative` style for the form album post image wrapper
[YANG-4774](https://getopensocial.atlassian.net/browse/YANG-4774) - Decrease `setTimeout` for the `popupClose` function
[YANG-4775](https://getopensocial.atlassian.net/browse/YANG-4775) - Add extra `setTimeout` for the slider init when 
the popup opened
[YANG-4783](https://getopensocial.atlassian.net/browse/YANG-4783) - Add styles for the `back album` button on the hero banner.

## Issue tracker
https://www.drupal.org/project/social/issues/3172477
https://getopensocial.atlassian.net/browse/YANG-4773
https://getopensocial.atlassian.net/browse/YANG-4774
https://getopensocial.atlassian.net/browse/YANG-4775
https://getopensocial.atlassian.net/browse/YANG-4783

## How to test
[YANG-4773](https://getopensocial.atlassian.net/browse/YANG-4773):
- [ ] Create an album or add the images on the post on the stream
- [ ] You can see the correct position `Add image` button
[YANG-4774](https://getopensocial.atlassian.net/browse/YANG-4774):
- [ ] Go to Album post
- [ ] Click on the image
- [ ] You can see the popup
- [ ] Close popup and open popup again
- [ ] Close popup and the page should have a vertical scroll
[YANG-4775](https://getopensocial.atlassian.net/browse/YANG-4775):
- [ ] Open Album post on the Safari browser
- [ ] Click on the image on the album
- [ ] You can see the popup with the slider where one image displayed and arrows navigation

## Screenshots
[YANG-4773](https://getopensocial.atlassian.net/browse/YANG-4773):
form-post-album-bug
form-post-album

[YANG-4783](https://getopensocial.atlassian.net/browse/YANG-4783):
back-link-button

## Release notes
The `Add image` button has a correct position on the album post form
The album popup has a correct close behavior
The slider on the album popup load correct
The `back-album` button has the correct styles.

## Change Record
-

## Translations
-

### CODE REVIEW

**Comment by navneet0693** [comment]
@agami4 This PR needs a bit of more work for resolving those conflicts. 🙈

**Comment by ronaldtebrake** [comment]
Hi @agami4 
It seems the only thing which doesn't apply is the styles on the back-to-albums within the hero section. The rest of the fixes seem good to me! If you can fix those its good to be merged.

Screenshot 2021-01-30 at 13 19 40

**Comment by agami4** [comment]
@ronaldtebrake, I recompiled styles for the back-album button.

**Comment by ronaldtebrake** [comment]
Thanks for me that was the only thing I saw what didn't work, so if everybody is happy feel free to merge it @agami4 :D

**Pull request merged**
