### PR TITLE
Issue #3241316 by SV: Landing Page template applies to any node type when using it as 404 page

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
The template of Landing Page applies to any node type when using it as 404 page which caused UI issues

## Solution
- Add additional check to apply specific template suggestion **only** for landing_page content type when using it as 404 page

## Issue tracker
- https://www.drupal.org/project/social/issues/3241316
- https://getopensocial.atlassian.net/browse/YANG-6353

## How to test
- [ ] Using the latest version of Open Social with the social_landing_page module enabled
- [ ] As an administrator
- [ ] Go to "/admin/config/system/site-information"(screen a)
- [ ] Set URL in "Default 404 (not found) page" field to any page except landing node type.
- [ ] When opening an unexisting URL I expect that the 404 page uses the right template and displays correctly
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Screenshots
*a:*
Basic-site-settings-ECI-Demo

*before*
Screenshot-from-2021-10-07-15-01-18-png-1866×609-

*after*
Screenshot-from-2021-10-07-15-23-33-png-1855×724-

## Release notes
Fixes issue with overriding a template of the 404 page

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2540-rsurgnrznzbpw3wq7p6m6ljibbymtmpl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615ee7e7cc9cc43ef460a6d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2540-rsurgnrznzbpw3wq7p6m6ljibbymtmpl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615ee7e7cc9cc43ef460a6d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2540-rsurgnrznzbpw3wq7p6m6ljibbymtmpl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/615ee7e7cc9cc43ef460a6d6

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 10.3.x

**Pull request merged**
