### PR TITLE
Issue #3463599: Fix Behat Lint warnings from Social GDPR module

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Social GDPR has couple of warning for Behat Tests.

## Solution
Fix warnings from Behat Tests.

## Issue tracker
[PROD-28087](https://getopensocial.atlassian.net/browse/PROD-28087)
[#3463599](https://www.drupal.org/project/social/issues/3463599)

## Theme issue tracker
N/A

## How to test
Execute Behat Tests for files: create-data-policy.feature, inform-block.feature and user-consent.feature

## Screenshots
N/A

## Release notes
Fixed warnings from Behat Tests (Automated tests).

## Change Record
N/A

## Translations
N/A

[PROD-28087]: https://getopensocial.atlassian.net/browse/PROD-28087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3988-a85clbp698xz6njugvjncsplqcxzmtso.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66a1498093759c7c20204a16

**Review by robertragas — APPROVED** [review]

**Pull request merged**
