### PR TITLE
Issue #3385570 by vnech: Add ability to translate custom settings with UI

### PR DESCRIPTION
**Pull request by nechai**
## Problem
As a SM I want to have an ability to translate custom settings that we have in distro with UI.

## Solution
Add ability to translate custom settings with UI.

## Issue tracker
- https://www.drupal.org/project/social/issues/3385570
- https://getopensocial.atlassian.net/browse/PROD-26513

## Theme issue tracker
n/a

## How to test
- [ ] Login as admin
- [ ] Install at least two languages
- [ ] Enable "Social Event Invite Enrolments" module
- [ ] Enable "Configuration Translation" module
- [ ] Visit the page _/admin/config/opensocial/event-invite/translate_
  - [ ] **EB**: Admin should be able to translate settings with UI

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
_Before:_
Screenshot 2023-09-06 at 13 18 57

_After:_
Screenshot 2023-09-06 at 13 20 38

## Release notes
Add ability to translate distro custom settings with UI

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by ribel** [comment]
Hi @nechai, 
In general changes looks good to me, and it looks good for Event invite and Anonymous event settings:

image

image


But I would suggest removing changes for groups or creating separate PR for it, because it doesn't works correct now.
In normal settings we have ability to change invite text for multiple group types, but in translation I see only one:

image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by nechai** [comment]
@ribel I removed UI for translating group settings.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3508-3erpfau4cpodpbqh4dwnavw9kyy2tvcx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f868f2961ebaf9ece290d2

**Review by tbsiqueira — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked in 11.10.x and 12.0.x

**Pull request merged**
