### PR TITLE
Hotfix: PROD-24054 Add missing notification field configs

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
Some config was forgotten in  in #3285 but this is now needed as per https://www.drupal.org/node/3333024. Additionally some existing install config actually didn't match what the activity factory required but is now being errored on.

## Solution
Add the missing field configs. 

Re-run the update hook added in 3285 to fix any missing config that was not yet added in 11.7.1.
## Issue tracker
https://getopensocial.atlassian.net/browse/PROD-24054

## How to test
- [x] Install Open Social
- [x] Trigger all the notifications

We have the following notifications:
```bash
$ find . -name 'message.template.*' | grep -vE '[0-9]'
./modules/custom/social_queue_storage/config/install/message.template.background_process_finished.yml
./modules/social_features/social_private_message/config/install/message.template.create_private_message.yml
./modules/social_features/social_content_report/config/install/message.template.content_reported.yml
./modules/social_features/social_event/config/optional/message.template.activity_on_events_im_organizing.yml
./modules/social_features/social_event/config/optional/message.template.user_was_enrolled_to_event.yml
./modules/social_features/social_event/modules/social_event_invite/config/install/message.template.invite_event_enrollment.yml
./modules/social_features/social_event/modules/social_event_managers/config/optional/message.template.member_added_by_event_organiser.yml
./modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.create_node_following_tag.yml
./modules/social_features/social_follow_taxonomy/modules/social_follow_tag/config/install/message.template.update_node_following_tag.yml
./modules/social_features/social_like/config/install/message.template.create_like_node_or_post.yml
./modules/social_features/social_mentions/config/install/message.template.create_mention_post_stream.yml
./modules/social_features/social_mentions/config/install/message.template.create_mention_comment.yml
./modules/social_features/social_mentions/config/install/message.template.create_mention_comment_stream.yml
./modules/social_features/social_mentions/config/install/message.template.create_comment_reply_mention.yml
./modules/social_features/social_mentions/config/install/message.template.create_mention_post.yml
./modules/social_features/social_follow_content/config/install/message.template.create_comment_following_node.yml
./modules/social_features/social_activity/config/install/message.template.request_event_enrollment.yml
./modules/social_features/social_activity/config/install/message.template.moved_content_between_groups.yml
./modules/social_features/social_activity/config/install/message.template.create_topic_gc.yml
./modules/social_features/social_activity/config/install/message.template.create_event_gc.yml
./modules/social_features/social_activity/config/install/message.template.create_post_profile.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_community_post.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_post_profile.yml
./modules/social_features/social_activity/config/install/message.template.create_event_group.yml
./modules/social_features/social_activity/config/install/message.template.create_event_community.yml
./modules/social_features/social_activity/config/install/message.template.create_content_in_joined_group.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_group_node.yml
./modules/social_features/social_activity/config/install/message.template.create_topic_community.yml
./modules/social_features/social_activity/config/install/message.template.join_to_group.yml
./modules/social_features/social_activity/config/install/message.template.event_request_approved.yml
./modules/social_features/social_activity/config/install/message.template.create_post_group.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_group_post.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_reply.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_community_node.yml
./modules/social_features/social_activity/config/install/message.template.create_comment_author_node_post.yml
./modules/social_features/social_activity/config/install/message.template.create_topic_group.yml
./modules/social_features/social_activity/config/install/message.template.create_post_profile_stream.yml
./modules/social_features/social_activity/config/install/message.template.create_post_community.yml
./modules/social_features/social_group/modules/social_group_invite/config/optional/message.template.invited_to_join_group.yml
./modules/social_features/social_group/modules/social_group_flexible_group/modules/social_flexible_group_book/config/optional/message.template.create_book_group.yml
./modules/social_features/social_group/modules/social_group_request/config/install/message.template.request_to_join_a_group.yml
./modules/social_features/social_group/modules/social_group_request/config/install/message.template.approve_request_join_group.yml
```

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Fixed an issue where notifications that were never triggered before 11.7.0 caused an error when being triggered.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3308-zg0zr436qin96pzasdfa9mmsvu3mdnve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3e05de1ca2d71c50d02a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3308-zg0zr436qin96pzasdfa9mmsvu3mdnve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3e05de1ca2d71c50d02a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3308-zg0zr436qin96pzasdfa9mmsvu3mdnve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3e05de1ca2d71c50d02a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3308-zg0zr436qin96pzasdfa9mmsvu3mdnve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3e05de1ca2d71c50d02a0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3308-zg0zr436qin96pzasdfa9mmsvu3mdnve.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3e05de1ca2d71c50d02a0

**Review by tbsiqueira — APPROVED** [review]

**Comment by Kingdutch** [comment]
Cherry picked to 1db90acb7 and 72b4fd798

**Pull request merged**
