### PR TITLE
Issue #3406255 by SV: Display translated "commented content type" on the stream/email notification

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

When the user comments on content, "topic"  (or also event, discussion, idea)  displays untranslated on the stream/email notification.

## Solution

Use entity type label in related token to get translated data on the stream/email.

## Issue tracker

- https://www.drupal.org/project/social/issues/3406255
- https://getopensocial.atlassian.net/browse/PROD-27576

## How to test
- [ ] Using the latest version of Open Social with the social_comment module enabled
- [ ] As a sitemanager
- [ ] Try to add comment to any content (topic, event, discussion,idea) of any user with different language then default one
- [ ] After running cron, I expect that the author of commented node received an email with correct translation of commented entity tyoe 
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

Before:
Screenshot 2023-12-05 at 16 35 03-1

After:
Screenshot 2023-12-05 at 16 35 16

## Release notes
Fixes translations of entity type name on the stream/email notification.

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3631-tseq6myftjr5vunda6fq6lelhmkciexz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656f3a150430b6e237e88b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3631-tseq6myftjr5vunda6fq6lelhmkciexz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656f3a150430b6e237e88b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3631-tseq6myftjr5vunda6fq6lelhmkciexz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656f3a150430b6e237e88b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3631-tseq6myftjr5vunda6fq6lelhmkciexz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/656f3a150430b6e237e88b38

**Review by ribel — APPROVED** [review]
Changes were tested and works as expected now.
image

**Pull request merged**
