### PR TITLE
Issue #3350838 by vnech: Error blocked the "Activity Creator" cron job

### PR DESCRIPTION
**Pull request by nechai**
## Problem
If try to execute the function `_social_group_get_current_group($node)` in out-of-page context we get an error:

```bash
WARNING  Undefined array key "node" in profiles/contrib/social/modules/social_features/social_group/src/SocialGroupHelperService.php on line 128
```

This issue can be reproduced in a lot of places related to activity creation (and may block "Activity Creator" cron job).

## Solution
Fix syntax error.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-24769
- https://www.drupal.org/project/social/issues/3350838

## Theme issue tracker
n/a

## How to test
- [ ] Install profile with demo content
- [ ] Execute the command in terminal: `drush php:eval '$node = \Drupal::entityTypeManager()->getStorage("node")->load(10); _social_group_get_current_group($node);'`

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
Fix the error blocked the "Activity Creator" cron job.

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by ribel** [comment]
@nechai changes looks ok to me, but please resolve conflicts after recent merge.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Review by ribel — APPROVED** [review]
LGTM.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3364-bhn3f7fgzaubkmrdi4glwjcdfiwgidoc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6422cdbe5262ae33e9f40857

**Comment by ribel** [comment]
🍒 picked to 11.9.x and 11.8.x

**Pull request merged**
