### PR TITLE
Issue #2992009 by truls1502: Properly namespace Behat test context classes

### PR DESCRIPTION
**Pull request by truls1502**
## Problem
Sometimes the Behat makes challenges if I create a custom project based on Open Social. 

## Solution
Therefore I suggested own names namespaces for OpenSocial

## Issue tracker
- https://www.drupal.org/project/social/issues/2992009

_I am not sure how the below works, so I leave them blank_
## HTT
- [ ] Check out the code changes
- [ ] Login as user X and do this and this and that
- [ ] Notice it doesn't work
- [ ] Checkout to this branch
- [ ] Try this and this and that and see that it works now

## Documentation
- [ ] This item is documented on LGOS
- [ ] This item has been added to the feature overview

## Release notes
It would be great if it is possible to add in milestone 3.0.0

### CODE REVIEW

**Comment by truls1502** [comment]
@bramtenhove - I see you have replied on Drupal-issue. Therefore I am tagging you here to get a bit attention. 

This is just a beginning. 

To be honest, I am not expert in namespaces, so I assume we have to do more than what I did. 
Moreover, also you know the structure, etc. better than me. 

My suggestion or thinking way to use:
- `Behat/` if no modified files _(Use the default file(s) from Behat which is placed inside in open_social-repo)_
- `OpenSocial/` if we have modified the Behat-files for OpenSocial

I need your help. Moreover, I also appreciate if it is possible to include this to milestone 3.0.0.

**Comment by Kingdutch** [comment]
Hi @truls1502,

I only just saw your comment here :) I have posted a reply with the next steps in the [issue](https://www.drupal.org/project/social/issues/2992009).

I've also suggested a change for the namespace to match existing namespaces that we use instead of introducing a new one.

Please let me know if you have any questions either by tagging me here, in the Open Social channel on the Drupal slack or in the issue on Drupal.org.

~ Alexander

**Comment by truls1502** [comment]
Hi @Kingdutch 

It seems that the test works now, and please have a look at https://travis-ci.org/goalgorilla/open_social/builds/421040138

Otherwise, if you feel that need to run the test one more time, it is fine! :)

**Comment by Kingdutch** [comment]
To satisfy MOSS we'll need to change the behat.yml of all our internal projects.

**Comment by truls1502** [comment]
Is there anything I can help you from here? :)

**Pull request merged**
