### PR TITLE
Issue #2977782: My own Private Messages are marked as unread

### PR DESCRIPTION
**Pull request by ghost**
## Problem
When I went to my private message inbox today, a number of old conversations were newly marked as unread. Viewing those messages revealed that I was the last person to communicate in those threads. The viewing process did remove the green indicator dot in the inbox.

Then I created a new message and now it displays as unread in my inbox.

## Solution
My expectation is that only messages I receive would display as unread.

## Issue tracker
https://www.drupal.org/project/social/issues/2977782

### CODE REVIEW

**Review by Kingdutch — APPROVED** [review]
Patch has been reviewed by multiple people in the private_message queue. I've used a slightly newer version of the patch than the one by Oleksandr. I've also tested this in a distro installation and it works as expected.

**Comment by jaapjan** [comment]
Note: this will not solve the issue for people with existing installs who run `composer update goalgorilla/open_social --with-all-dependencies` because the version of private message is not updated the new patch won't be found and applied.

**Comment by jaapjan** [comment]
Doing a `rm -rf html/modules/contrib/private_message` before running composer update works :-) Will merge it anyway because it solves the issue. But for existing installs this extra step is required. I'm not aware of any other work-around :-)

**Comment by jaapjan** [comment]
Also cherry-picked `31390f2` in 8.x-5.x and 8.x-3.x

**Comment by jaapjan** [comment]
@OH17L could you also write release notes next time? Thanks in advance! :-)

**Comment by OH17L** [comment]
Sure.

**Pull request merged**
