### PR TITLE
Internal: Improve test fixture creation for group references

### PR DESCRIPTION
**Pull request by zanvidmar**
## Problem / Solution
This commit allows group reference data to be provided as a comma separated list of IDs or term names (mixing is allowed). This can now be used in tables for e.g. groups, topics and events. By putting this in the validate method we can use this everywhere.

This ensures we deduplicate the group title lookup so that we don't break on a pre-fetched value. Since we now do it by field type we no longer need to do it by field name.

## Example usage

```cucumber
    Given groups:
      | label |
      | Cats  |
      | Birds |
    And groups:
      | label   | field_related_groups |
      | Dogs    | 1,Birds              |
      | Snakes  | 1,2                  |
      | Rabbits | Cats,Birds           |
```

Inspired by: [3394](https://github.com/goalgorilla/open_social/pull/3394)

## Issue tracker
[3436789](https://www.drupal.org/project/social/issues/3436789#)

## Theme issue tracker
N/A

## How to test
- [ ] Tests should pass :)

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Review by tbsiqueira — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3836-yxzhkv4iwhs2uktqw4hpq1ivho9gm6zj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6605913e8b0100d2653822d6

**Comment by zanvidmar** [comment]
Cherry-picked to 12.0.x here: [71a1cf809](https://github.com/goalgorilla/open_social/commit/71a1cf80996630783d2eda89281a8f16890cc28e)

Cherry-picked to 12.4.x here: [8c9acc530](https://github.com/goalgorilla/open_social/commit/8c9acc5307160ce1f32ae49c19840421d4ea7e7e)

**Pull request merged**
