### PR TITLE
Issue #3043555 by truls1502: Update drupal/paragraphs from 1.6 to 1.8

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](https://git.drupalcode.org/project/paragraphs/compare/8.x-1.6...8.x-1.8)
- https://www.drupal.org/project/paragraphs/releases/8.x-1.7
- https://www.drupal.org/project/paragraphs/releases/8.x-1.8

## Issue tracker
https://www.drupal.org/project/social/issues/3043555

## Release notes
Update drupal/paragraphs from 1.6 to 1.8

### CODE REVIEW

**Comment by truls1502** [comment]
Trying retrigger MOSS

**Comment by jaapjan** [comment]
Only thing I noticed is some comma's placed when creating a Block section because of http://drupal.org/node/3012053

paragraphs

I'll fix that

**Comment by truls1502** [comment]
Great @jaapjan - Keep me update or let me know if you want me to test your patch 🤓

**Comment by jaapjan** [comment]
Works great! Merging :-)

**Comment by jaapjan** [comment]
Also cherry-picked for 5.x.

**Pull request merged**
