### PR TITLE
Issue #3275467 by chmez: Profile preview for event organizers

### PR DESCRIPTION
**Pull request by ghost**
## Problem
Profile preview doesn't work for users in the event organizers block.

## Solution
Enable previewer for profile compact teaser.

## Issue tracker
- https://getopensocial.atlassian.net/browse/YANG-7467
- https://www.drupal.org/project/social/issues/3275467

## Theme issue tracker
- https://www.drupal.org/project/socialbase/issues/3275461

## How to test
- [x] Enable the "Social Profile Preview" module.
- [x] Log in as a member and create an event with one or more organiser users.
- [x] When you hover the user in the "Organisers" block then you should see the profile preview modal window.

## Screenshots
Event organiser previewer

## Release notes
Integrate profile previewer with event organisers block.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Review by ribel — CHANGES_REQUESTED** [review]
Hi @OH17L,
I have tested functionality and all works and looks as expected, but could you just resolve a conflict here and rebase if needed?
Then we can merge it.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2886-ycf54nuzdm2dy2upj0nhebpkrpr6vtmp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62597b4f9d9568879f432e4d

**Review by ribel — APPROVED** [review]
Now, all looks good to me.

**Review by Ressinel — APPROVED** [review]

**Comment by ribel** [comment]
@Ressinel I have merged and made cherry-pick to 11.3.x and 11.2.x

**Pull request merged**
