### PR TITLE
Issue #3384825 by Kingdutch: Update metatag settings using config/modify

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
The `social_metatag` module overwrote settings for the metatag module by adding a duplicate config file in `config/install`. This works when all modules are installed during site-install, and it also worked in the era of features. However sites extending Open Social might install the `metatag` module first and then want the Open Social defaults from `social_metatag` which will cause a duplicate config error.

## Solution
Moving the configuration to config/modify will properly update the settings on install without having duplicated config.

## Issue tracker
https://www.drupal.org/project/social/issues/3384825

## How to test
- [ ] Install metatag module
- [ ] Then as separate step install social_metatag

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Installing `social_metatag` module can cause an error if the `metatag` module was already enabled. We've changed how `social_metatag` installs its default metatag config to avoid this.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3504-gt4fmzceyz92rgpshq4mwu5ytrz461gt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64f1f7c5f3643e9c21d47620

**Review by vcsvinicius — APPROVED** [review]
@Kingdutch I approved this pull-request

**Pull request merged**
