### PR TITLE
Issue #3347592 by agami4: Improve layout of the blocks on the landing page

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The Custom list block and Custom multiple list block do not have the container wrapper.

## Solution
Add `container` wrapper to a Custom list block and a Custom multiple list block.

## Issue tracker

- https://www.drupal.org/project/social/issues/3347592
- https://getopensocial.atlassian.net/browse/PROD-23578

## Theme issue tracker
N/A

## How to test
- [ ] Go to/Create the landing page.
- [ ] Create a Custom list block and a Custom multiple list block.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
**Before:**
image-20221215-095750

**After:**
Screenshot 2023-03-13 at 15 05 37

## Release notes
A Custom list and a Custom multiple list blocks now have a correct layout.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Review by ribel — APPROVED** [review]
Changes was tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3338-jfdf9twgjqtmjy9gcoraunbnuriqwk1b.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/640f20076895ab5391384c97

**Review by nkoporec — APPROVED** [review]

**Comment by nkoporec** [comment]
🍒  picked to 11.7.x, 11.8.x

**Pull request merged**
