### PR TITLE
Issue #3484275:  Album feature still visible when disabled in settings

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem (for internal)

When the Album feature is disabled at the backend using /admin/config/opensocial/album, it is still visible on the main site menu and group menu but only disappears on the profile menu.

## Solution (for internal)

Add custom check to validate access and verify that feature is active/disabled

## Release notes (to customers)

Fixes the issue with access to Album feature when it's disabled in settings.

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-26541
- https://www.drupal.org/project/social/issues/3484275

## Theme issue tracker

N/A

## How to test
- [ ] Using the latest version of Open Social with the social_album module enabled
- [ ] As a sitemanager try to disable album feature on /admin/config/opensocial/album page
- [ ] Try to open view/edit, check links
- [ ] And I expect that those pages/links are not available but instead I can still see them.
- [ ] The expected result is attained when repeating the steps with this fix applied.

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr4141-iwc9ofe94somx7w6tctk03vrebqsns37.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6720aebc2737e5f7e518b805

**Review by nechai — APPROVED** [review]
LGTM

**Review by ribel — APPROVED** [review]
Changes were tested and works as expected now.

**Pull request merged**
