### PR TITLE
Issue #3403776 by SV: "Unique nicknames" setting should result in error message instead of "unexpected error" during registration

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem
When a new user tries to register using a "Nickname" that already exists in the system, the registration fails and the user gets shown:
Screenshot 2023-11-23 at 16 47 29

## Solution
- Add check to prevent issue on user register page. 
- Update text of the waring message: “This name is already taken, please try another one”

## Issue tracker

- https://www.drupal.org/project/social/issues/3403776
- https://getopensocial.atlassian.net/browse/PROD-26459

## Theme issue tracker
N/A

## How to test

- [ ] Using the latest version of Open Social with the social_profile_fields module enabled
- [ ] And "Unique nicknames" option enabled
- [ ] As a AN
- [ ] Try to register on the site but use nicknames that already exist
- [ ] When saving I expect to see provided warning message but instead i see WSOD page
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

N/A

## Release notes

Fixes the issue with "Unique nicknames" on the user register page

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3619-neawgszzoyfqhdhrlw93c6j3qtreubec.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/655f6bab0ccea0f75fa8e101

**Review by ribel — APPROVED** [review]
Changes looks good to me.
Also was tested by QA on existing env and by me on clean install and doesn't cause any regressions.
image

**Pull request merged**
