### PR TITLE
Issue #3228099 by vnech: Allow skipping flexible group views query alter for external modules

### PR DESCRIPTION
**Pull request by nechai**
## Problem
In `Social Flexible Group` we have query alter function `social_group_flexible_group_views_query_alter()` that change query for all views (globaly) display group entities.

The issue is that if I have a view displayed `Course` group type on the page I will see other groups as well.

## Solution
Add a hook `hook_social_flexible_group_skip_query_rules` allows external modules to skip flexible group views query alter.

## Issue tracker
- https://www.drupal.org/project/social/issues/3228099
- https://getopensocial.atlassian.net/browse/OEC-33

## How to test
*For example*
- [ ] Login as an admin
- [ ] Add views page to display only one group type (f.e. "Open group")
- [ ] Login as LU
- [ ] Go to the created view page

## Release notes
* Add a hook `hook_social_flexible_group_skip_query_rules` allows external modules to skip flexible group views query alter.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2463-gjhka9uh7hyxcvevez4ijsjl5dg2rdxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61168edfb52cf92ec8bb2a07

**Review by ribel — CHANGES_REQUESTED** [review]
@nechai I understand the issue you described. But I would like to avoid adding one more alter hook if possible.
We didn't have this problem before, so it looks like some regression. Maybe it is related to changes in PR #2432?
// cc @nkoporec @robertragas @navneet0693

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2463-gjhka9uh7hyxcvevez4ijsjl5dg2rdxo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61168edfb52cf92ec8bb2a07

**Comment by navneet0693** [comment]
I agree with @ribel. Let's try to look if this is a regression caused by the PR indicated.

**Comment by nechai** [comment]
@ribel @navneet0693 Seems like I missed updates with this PR #2432 🙈
I tested with it and can't reproduce the issue.

**Comment by nechai** [comment]
Closed (the issue can't be reproduced)

**Pull request closed without merging**
