### PR TITLE
Issue #3439386: Remove extra "to" in enrolees/members form confirmation messages

### PR DESCRIPTION
**Pull request by VBaldych**
## Problem
This bug is actual for events and groups. There are typos on the following confirmation pages:
- _/group/{group}/membership/configure-action_ - "Are you sure you want to send your email to to the following %count members?"
- _/node/{node}/all-enrollments/confirm-action_ - "Are you sure you want to send your email to to the following %count enrollees?"

## Solution
Remove extra "to" in:
- SocialEventManagersViewsBulkOperationsConfirmAction.php
- SocialGroupViewsBulkOperationsConfirmAction.php
- event-bulk.feature

## Issue tracker
- https://www.drupal.org/project/social/issues/3439386
- https://getopensocial.atlassian.net/browse/PROD-28632

## How to test
- [ ] Login as SM
- [ ] Go to any group
- [ ] Go to "Manage members/enrollments" tab
- [ ] Select users
- [ ] Click "Actions" button
- [ ] Click on 'Send email to group members' (for email)/Email selected enrollees
- [ ] Fill the fields
- [ ] On the confirmation page you shouldn't see doubled "to" in message

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image

## Release notes
Fix a typo and remove the extra "to" in enrolees/members form confirmation messages.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3850-unbljszrchqccfrx2msulln3qyjkoq5v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6613dc1daa2dcd62df5e6b38

**Review by ribel — APPROVED** [review]
Changes were tested and looks good.
image

**Pull request merged**
