### PR TITLE
Issue #3302921 by chmez: Support visibility tooltip for any entity type

### PR DESCRIPTION
**Pull request by ghost**
## Problem
The "Visibility" field has a tooltip only for groups and nodes.

## Solution
Extend functionality which manages the visibility field to cover all entity types.

## Issue tracker
- https://www.drupal.org/project/social/issues/3302921
- https://getopensocial.atlassian.net/browse/PROD-19356

## How to test
- [ ] Declare "hook_social_group_content_visibility_field" hook in your module which should return "field_media_visibility".
- [ ] Repeat the first three steps from PR #2947.
- [ ] You should see a question sign after the label of the “Visibility” field.

## Release notes
Support visibility tooltip for any entity type.

## Change Record
https://www.drupal.org/node/3303876

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3069-ez3yw9tc1xublbvln1szysfph6mmtxnn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f3d73219770b441a6e7ba8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3069-ez3yw9tc1xublbvln1szysfph6mmtxnn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f3d73219770b441a6e7ba8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3069-ez3yw9tc1xublbvln1szysfph6mmtxnn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f3d73219770b441a6e7ba8

**Review by ribel — APPROVED** [review]
I have tested changes and don't see any regressions.
Also it now allows us to extend Visibility tooltip by other modules, for example our new Media Directory extension.

**Review by ksis — APPROVED** [review]

**Comment by navneet0693** [comment]
PHPStan checks require your attention.

**Comment by ribel** [comment]
Hi @navneet0693, 
Now it's ready for the review again.

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
🍒 -picked to 11.5.x

**Pull request merged**
