### PR TITLE
Issue #3347940 by vnech: Group "/books" and "/albums" pages are visible for non-allowed users

### PR DESCRIPTION
**Pull request by nechai**
## Problem
These pages are visible for users who don't have view access to the group:
<ul>
  <li><em>/group/{gid}/albums</em></li>
 alt
  <li><em>/group/{gid}/books</em></li>
 alt
</ul>

## Solution
Add fixes to access checkers.

## Issue tracker
- https://www.drupal.org/project/social/issues/3347940
- https://getopensocial.atlassian.net/browse/PROD-24503

## Theme issue tracker
n/a

## How to test
- [ ] Login as admin
- [ ] Create a flexible group with with `community` visibility
- [ ] As anonymous user visit _/group/{gid}/albums_

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
Group pages "/group/{gid}/books" and "/group/{gid}/albums" pages aren't visible for non-allowed users.

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Review by ribel — APPROVED** [review]
Changes was tested and looks good to me.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3342-icrpr9abwmuwytgpds0f7zghvxbi5t1v.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6410abdfd1d6b6f9cab66feb

**Review by nkoporec — APPROVED** [review]
LGTM.

**Pull request merged**
