### PR TITLE
Issue #3247243 by agami4: Add collapse behaviour to the privacy settings block on the profile settings page

### PR DESCRIPTION
**Pull request by agami4**
## Problem
The privacy settings block does not have collapse behaviour on the profile settings page.

## Solution
Add collapse behaviour to the privacy settings block on the profile settings page.

## Issue tracker
https://www.drupal.org/project/social/issues/3247243
https://getopensocial.atlassian.net/browse/YANG-6535

## How to test
*For example*
- [x] Go to the profile settings page.
- [x] Scroll to privacy settings block.

## Screenshots
before:
SUP-1762  Privacy settings collapsed - Jira 2021-11-02 15-56-21

after:
Site Admin | ECI Demo 2021-11-02 23-29-36
Site Admin | ECI Demo 2021-11-02 23-29-50

## Release notes
The privacy settings block has collapse behaviour on the profile settings page.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2579-gitxy6zfviibaeg9j2qlorudyqxjk3hv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6181aee8de4970077ed63378

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2579-gitxy6zfviibaeg9j2qlorudyqxjk3hv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6181aee8de4970077ed63378

**Comment by Ressinel** [comment]
Hi @agami4 

I think that the collapsed privacy settings by default will be more logical. 
What do you think?

cc @ribel

**Comment by agami4** [comment]
@Ressinel, If I do privacy block collapse by default, Behat tests do not pass. Should we change Behat tests for it?

**Comment by Ressinel** [comment]
> @Ressinel, If I do privacy block collapse by default, Behat tests do not pass. Should we change Behat tests for it?

Yes please, I think it would be better with the collapsed privacy settings by default.

**Comment by ribel** [comment]
@Ressinel 
I think it's better to keep them expanded by default. 

1. Since this is the current state and user might be used to it. 
2. Also since it's quite an important setting, users might miss them if they are collapsed (see images).
3. And as @agami4 said in this way we don't need to rewrite behat tests.


**Expanded (currrent state)**
image

**Collapsed**
image

**Comment by Ressinel** [comment]
@ribel Ok, then let's keep it as it is.

**Review by Ressinel — APPROVED** [review]

**Review by ribel — APPROVED** [review]

**Comment by ribel** [comment]
🍒 picked to 10.3.x

**Pull request merged**
