### PR TITLE
Issue #3224278 by Ressinel: Update the Configuration Update Manager module from 1.6 to 1.7

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Configuration Update Manager module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3224278

## How to test
N/A

## Screenshots
N/A

## Release notes
The Configuration Update Manage module has been updated to 1.7. Please view the release notes for [1.7](https://www.drupal.org/project/config_update/releases/8.x-1.7) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2422-kzjliwoqsldktya4qimf3g9olfdmrsud.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f592e77424686d99625f19

**Comment by ronaldtebrake** [comment]
Looks good to me!

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2422-kzjliwoqsldktya4qimf3g9olfdmrsud.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f592e77424686d99625f19

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2422-kzjliwoqsldktya4qimf3g9olfdmrsud.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f592e77424686d99625f19

**Review by ronaldtebrake — APPROVED** [review]
Can be merged once tests passes eventhough it's only a helper module.

**Pull request merged**
