### PR TITLE
Issue #3258139 by CurriedN, hitesh-jain, tbsiqueira: Invalid user name/password on login screen throws website error

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
With PHP 8.0 version when the user tries to submit with Invalid username/password it throws below website encounter error.

## Solution
This error is due to PHP 8.0 version causing TypeError exception with error message passed to form element.

## Issue tracker
https://www.drupal.org/project/social/issues/3258139

## How to test
- [ ] Use php 8.0
- [ ] Log in to the website with an invalid username/password

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2694-4wfpqicw5oehizad98wjelncpce9jrtv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e570e1f8a118577f2b76ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2694-4wfpqicw5oehizad98wjelncpce9jrtv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e570e1f8a118577f2b76ec

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2694-4wfpqicw5oehizad98wjelncpce9jrtv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e570e1f8a118577f2b76ec

**Comment by navneet0693** [comment]
We are not planning to support PHP 8 until Open Social starts supporting Drupal 10 I believe.

**Review by navneet0693 — APPROVED** [review]

**Comment by navneet0693** [comment]
🍒 -picked to 11.0.x, 10.3.x, 10.2.x and 10.1.x

**Pull request merged**
