### PR TITLE
Issue #3418051 by ronaldtebrake : Remove `drupal/swiftmailer` as dependency from our composer.json

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
In 12.0.0 we've moved away from drupal/swiftmailer to symfony mailer, it's time to remove our dependency.

## Solution
Remove drupal/swiftmailer

## Issue tracker
https://www.drupal.org/project/social/issues/3418051

## How to test
- [ ] Make sure e-mails still works and that the site is not broken(WSOD).

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Removed a not needed dependency `drupal/swiftmailer`

## Change Record
https://www.drupal.org/node/3418836

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by ronaldtebrake** [comment]
Thanks, one less dependency, woop woop! I've added a change record 🤞

**Review by ronaldtebrake — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3736-2xnikqefrpoqdgcc7dzpjetptqvb7usk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bbb4100be493272e4d8993

**Pull request merged**
