### PR TITLE
Issue #3191063 by SV: Allow use a parent of categories in tag filter on search content page

### PR DESCRIPTION
**Pull request by volodymyr-sydor-lemberg**
## Problem
Parent tag can be connected to discussions, but it does not show up under the filter tags on the search content page (when category option is disabled)

## Solution
When category split option:
a) is disabled - allow use a parent of categories in tag filter on search content page
b) is enabled - provide an ability to select parent of categories on the edit/search pages

## Issue tracker
- https://www.drupal.org/project/social/issues/3191063
- https://getopensocial.atlassian.net/browse/YANG-4274

## How to test
*For example*
- [ ] Using the latest version of Open Social with the social_tagging module enabled
- [ ] As a sitemanager
- [ ] Try to disable the tag split option on the `/admin/config/opensocial/tagging-settings` page
- [ ] Then go to edit page of discussion and select parent of categories in the `Tag content` section and save updates
- [ ] Next, open the `/search/content/all` page and that tag is not available to filter on

## Screenshots
Screenshot from 2021-01-05 16-25-22
Screenshot from 2021-01-05 16-25-01
* `bonus` tag displays only as label  

Adds a new option:
Screenshot from 2021-01-11 15-47-18

## Release notes
- Fixed a bug when parent of categories doesn't display on the search content page (when split option disabled)
- Fixed an error on the view page of the node where a parent of categories is selected (after the split option has been enabled)
- Provides an ability to use a parent of categories on the edit/search pages

### CODE REVIEW

**Comment by ribel** [comment]
@volodymyr-sydor-lemberg If this PR is ready for review - please switch it from Draft, and add `needs review` label.

**Comment by volodymyr-sydor-lemberg** [comment]
> @volodymyr-sydor-lemberg If this PR is ready for review - please switch it from Draft, and add `needs review` label.

done

**Comment by ribel** [comment]
@ronaldtebrake Can we add this small feature to the 9.7 milestones, and then also to 10.0 release?

**Comment by ronaldtebrake** [comment]
@ribel yes, code for 9.7 is still fine to merge and cherry-pick back :)

**Review by ribel — APPROVED** [review]
I have tested and it works like a charm.

**Comment by ribel** [comment]
I was not able to cherry-pick it to 9.x due to conflict in `SocialTaggingSettingsForm.php`.
But since this is a new feature I think it's fine to have it just in 10.0

**Pull request merged**
