### PR TITLE
Issue #33411083: Social Emoji isn't be shown after D10 upgraded

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Social Emoji ins't be shown at text-area field after the D10 is upgraded

## Solution
The D10 removed the Popper from core-library and it was removed from our library, but, the injection continue at javascript file.
Remove the injection from javascript file.

## Issue tracker
[PROD-27850](https://getopensocial.atlassian.net/browse/PROD-27850)
[#33411083](https://www.drupal.org/project/social/issues/3411083)

## Theme issue tracker
N/A

## How to test
- [ ] Enable the Social Emoji
- [ ] Clear cache
- [ ] Access the Dashboard with Verified User
- [ ] Looking for Emoji button at Post and Comment field

I advise to get database from Enterprise environment and restore locally to test it.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-27850]: https://getopensocial.atlassian.net/browse/PROD-27850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3666-igouodof0zuej7axdix2ixi5nwu5iklm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658c812bdd3e0563dff52057

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3666-igouodof0zuej7axdix2ixi5nwu5iklm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658c812bdd3e0563dff52057

**Comment by ronaldtebrake** [comment]
Nice work @vcsvinicius, can confirm it works! 
Screenshot 2023-12-28 at 08 08 22

I'll create a follow up for a behat test, to at least make sure we enable the module and verify the emoji picker is present as element

**Comment by ronaldtebrake** [comment]
Also cherry picked to 12.1.x and 12.0.x 🍒

**Pull request merged**
