### PR TITLE
Issue #2952203: Add Social Profile Organization Tag module

### PR DESCRIPTION
**Pull request by ribel**
## Problem
As a CM+ I want to indicate that user is part of an organization so that other users know where certain information comes from.

## Solution
**Acceptance criteria:**
- CM can create organization Taxonomy
- CM can associate profiles with Organization taxonomy
- This taxonomy will be an addition to the profile name of the associated profiles
- It has to be part of the name so it works in the social blue theme
- Maximum 1 value
- Should be added to the profile below other taxonomies
- Has to stand out from the rest of the name and Users can not fake it
- Separate module

**Concept:** https://marvelapp.com/c26c36j/screen/39089637

## Issue tracker
- https://www.drupal.org/project/social/issues/2952203
- https://jira.goalgorilla.com/browse/ECI-691

## HTT
- [x] Checkout to this branch
- [x] Check out the code changes
- [x] Enable experimental Social Profile Organization Tag module
- [x] Login as CM or SM
- [x] Add a new term to Profile Organization Tag vocabulary
- [x] Go to some user profile and fill the added term to Profile Organization Tag field
- [x] Check new icon near username on the different view modes
- [x] Compare it with the concept (in the activity stream message it says User from Organization for now)
- [x] Login as normal user and check that you can't edit Profile Organization Tag field and terms

## Documentation
- [x] This item is added to the release notes
- [ ] This item is documented on LGOS
- [ ] This item has been added to the feature overview

### CODE REVIEW

**Comment by ribel** [comment]
We created 3 follow-ups, to fix displaying of the checkmark in the activity stream and input fields:

- https://jira.goalgorilla.com/browse/ECI-700
- https://jira.goalgorilla.com/browse/ECI-704
- https://jira.goalgorilla.com/browse/ECI-705

**Comment by ribel** [comment]
@jochemvn Could you change the destination to 8.x-3.x or even 4.x and update this PR?

**Comment by jochemvn** [comment]
@ribel done! I've changed the base to 8.x-4.x

**Comment by jochemvn** [comment]
@bramtenhove / @jaapjan 
Do you think we can merge this? It's been running on SHN for a while now. Also it's marked as experimental and turned off by default (for both new and existing installations)

**Comment by jaapjan** [comment]
@jochemvn i think we can try to include this in 4.0. Can you get Project Moss result green?

**Comment by jaapjan** [comment]
@jochemvn just restarted PAC & SHNL build. Don't think that will help though.. could you still get project Moss green?

**Comment by ronaldtebrake** [comment]
All tests are greeeen :) thanks guys looks good!

**Comment by robertragas** [comment]
I think we should include in the release notes that this only works for the default profile type.

**Comment by ronaldtebrake** [comment]
Will do, thanks.

**Pull request merged**
