### PR TITLE
Issue #3206847 by navneet0693: Added accessCheck(FALSE) property to entity query for enabling event enrolment by default.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Follow up of https://github.com/goalgorilla/open_social/pull/2283

The post-update hook was only processing public events.

## Solution
1.  Add accessCheck(FALSE) to entity query for collecting nids of events to update.

## Issue tracker
https://www.drupal.org/project/social/issues/3206847

## How to test
- [ ] Run drush updb.
- [ ] See that existing events with different visibility options have enrollment options enabled.

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Review by ronaldtebrake — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2415-3bxigktmrbfmfrvcvkymznumwjkogq1a.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ee9e92742468f3d05d67f7

**Comment by navneet0693** [comment]
🍒 -picked to 10.2.3 !

**Pull request merged**
