### PR TITLE
Internal: Remove AvoidCleanupTrait from 11.9.x to avoid failing tests

### PR DESCRIPTION
**Pull request by robertragas**
IMPORTANT:
Should only be merged in 11.9.x

## Problem
In https://github.com/goalgorilla/open_social/pull/3423/commits/634a6c6c525c9ed092b551f267f41a0c6c628f13 a change has been added using the AvoidCleanupTrait which has been introduced in https://github.com/goalgorilla/open_social/pull/3393/files but this is got introduced in 11.10.x and higher so the tests will fail in 11.9.x as it cannot be found.

## Solution
Remove the AvoidCleanupTrait

## Issue tracker
Internal

## Theme issue tracker
*[Required if applicable] Paste a link to the drupal.org theme issue queue item, either from [socialbase](https://www.drupal.org/project/socialbase) or [socialblue](https://www.drupal.org/project/socialblue). If any other issue trackers were used, include links to those too.*

## How to test
- [ ] Wait for all the tests to be green again

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Internal. See problem/solution part

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3467-1avnbgla8bmzvzrn7jyxdjmybxirbtth.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ba521a47b8806d2fa93a44

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3467-1avnbgla8bmzvzrn7jyxdjmybxirbtth.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ba521a47b8806d2fa93a44

**Comment by Kingdutch** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3467-1avnbgla8bmzvzrn7jyxdjmybxirbtth.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ba521a47b8806d2fa93a44

**Review by ribel — APPROVED** [review]
The proposed change looks good to me

**Comment by Kingdutch** [comment]
@robertragas As an alternative solution, should we backport the AvoidCleanupTrait to 11.9.x? It's in testing, so from a versioning perspective it's really about how we want our CI/local development to work, and not a change to a public API.

**Comment by robertragas** [comment]
> @robertragas As an alternative solution, should we backport the AvoidCleanupTrait to 11.9.x? It's in testing, so from a versioning perspective it's really about how we want our CI/local development to work, and not a change to a public API.

Yeah, at first I wanted to revert the commit as it was the easiest and fastest solution, until we properly backport the cleanup but seeing the test failing I guess we can go for the backport right away.

https://github.com/goalgorilla/open_social/pull/3469
Lets see how the tests go there.

**Comment by robertragas** [comment]
other one is green, so closing this one in favor for the other one.

**Pull request closed without merging**
