### PR TITLE
Issue #3417867: Replace watchdog_exception deprecated function

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
In Drupal 10.1 the watchdog_exception function was deprecated to be removed on Drupal 11.
[watchdog_exception() deprecated](https://www.drupal.org/node/2932520)

## Solution
Replace the deprecated function.
[watchdog_exception() deprecated](https://www.drupal.org/node/2932520)

## Issue tracker
[PROD-28009](https://getopensocial.atlassian.net/browse/PROD-28009)
[#3417867](https://www.drupal.org/project/social/issues/3417867)

## Theme issue tracker
N/A

## How to test
That is a treatment to unexpected error and can't be tested.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

[PROD-28009]: https://getopensocial.atlassian.net/browse/PROD-28009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Review by nkoporec — APPROVED** [review]
LGTM

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3728-gvzalwvwla2yi0b5pzdechjf4ndyom8w.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65b7fca1ce09348d3b408d86

**Comment by ronaldtebrake** [comment]
As this wasn't cherry picked it'll be in 13.0.0 (or 12.3, if we decide to cherry pick later)

**Pull request merged**
