### PR TITLE
Issue #3414239: Escape formulas in CSV exports

### PR DESCRIPTION
**Pull request by bramtenhove**
## Problem
It's recommended to escape formulas in CSV exports.

## Solution
Follow Symfony's implementation escaping CSV values when they start with a formula character.

## Issue tracker
https://www.drupal.org/project/social/issues/3414239

## Theme issue tracker
N/a

## How to test
- [ ] Create a user with first name `=2+5`
- [ ] As a sitemanager export the user via the `admin/people` overview page
- [ ] Import the CSV in Google Sheets
- [ ] Observe that the formula is executed
- [ ] Repeat with this fix, observe the formula is imported as text
- [ ] 
### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/a

## Release notes
CSV exports now escape formulas so Spreadsheet software interprets them as text.

## Change Record
N/a

## Translations
N/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3698-8wbc5g0jo8sf8wcfg689xdjczmy2i35x.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a0f28ab9094afb0ae90a07

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3698-8wbc5g0jo8sf8wcfg689xdjczmy2i35x.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a0f28ab9094afb0ae90a07

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3698-8wbc5g0jo8sf8wcfg689xdjczmy2i35x.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a0f28ab9094afb0ae90a07

**Review by ronaldtebrake — APPROVED** [review]

**Comment by ronaldtebrake** [comment]
Works like a charm

**Comment by ronaldtebrake** [comment]
Also in 12.1.x and 12.0.x

**Pull request merged**
