### PR TITLE
Issue #3259585 by yaroslav-shandra: Private message text is rendered with html code

### PR DESCRIPTION
**Pull request by YaroslavShandra88**
## Problem
When user join a Group (or a course or a challenge) you can setup a welcome message and add style for the message text.
image
The welcome email message is sent to users when they join/added to the group and don't login to the platform.
Users get an email with HTML code in the body message.
image

## Solution
Fix twig templates for a welcome message

## Issue tracker
https://www.drupal.org/project/social/issues/3259585
https://getopensocial.atlassian.net/browse/SUP-1997

## How to test
1. Check if enabled sub module Social group welcome message
2. Create a group with a welcome message
3. Add user to the group

## Screenshots
*If this Pull Request makes visual changes then please include some screenshots that show what has changed here. A before and after screenshot helps the reviewer determine what changes were made.*

## Release notes
Fixed  massage template for render private message text.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2708-jhomgll406wzkija5e9t7xcv37rvok7z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e97aa0f8a118577f572e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2708-jhomgll406wzkija5e9t7xcv37rvok7z.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61e97aa0f8a118577f572e70

**Review by ribel — APPROVED** [review]
I have tested changes and they looks good.

**Comment by ribel** [comment]
🍒 picked to 10.3.x and 11.0.x

**Pull request merged**
