### PR TITLE
Issue #3250333 by yaroslav-shandra: The count of enrolled users is not displayed correctly after disabling checkbox ''Allow users to enroll to this event without an account'' at event

### PR DESCRIPTION
**Pull request by YaroslavShandra88**
## Problem
When disable checkbox ''Allow users to enroll to this event without an account'' at event.
Screenshot from 2021-11-19 13-37-39
And users enrolled in this event without an account (guests).
The count of enrolled users is not displayed correctly on the event preview page at enrollments block.
Screenshot from 2021-11-19 13-35-07

## Issue tracker
- https://www.drupal.org/project/social/issues/3250333

## How to test
- [x] Create event with selected ''Allow users to enroll to this event without an account'' checkbox.
- [x] Enroll to event in incognito window as guest.
- [x] Disable checkbox ''Allow users to enroll to this event without an account'' at event.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2611-8gci2tfiaqdd62zdaucjzbwbuacqywna.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61979a20e36865019142371b

**Comment by navneet0693** [comment]
@robertragas I see that your self requested a review, please let us know if this is ready :-)

**Comment by navneet0693** [comment]
@YaroslavShandra88 Please rebase your branch with main.

**Comment by YaroslavShandra88** [comment]
> 

@navneet0693 updated.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2611-fmn1nz6n1r6ihbohjyuuwvgdf86afrd9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6217bba4df1c1f9d5eb2a1f0

**Comment by Ressinel** [comment]
@YaroslavShandra88 Could you fix **PHPStan**?

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2611-xdyz0rkccjcwb7fjniyokspumtkkgqv5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625d4eccef17c6f5694f4450

**Review by Ressinel — APPROVED** [review]
I was able to reproduce the issue and these changes fix it.
LGTM.

**Comment by Ressinel** [comment]
🍒-picked to `11.0.x`, `11.1.x`, and `11.2.x`

**Pull request merged**
