### PR TITLE
Issue #3218654 by nkoporec: Display the correct event type when displaying event teasers

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
Currently when using the social blue theme with the new style (Sky) set, the event teasers are displaying 'event' text above the event title. When using the social_event_type module we can distinguish between different types, so it would make a lot more sense to display the actual event type above the title instead of the generic "Event" text.

## Solution
We need to pass the event type to node teaser rendering template.

## Issue tracker
https://www.drupal.org/project/social/issues/3218654

## How to test
1. Set social blue theme
2. Under theme configuration, set the style setting to Sky (New)
3. Enable the social_event_type module
4. Create new event types and create a new event
5. Go to /community-events page and see the teasers, even though we have different type set on an event, the text above the event title still displays "Event".

## Screenshots
Before:
Screenshot from 2021-06-14 11-34-23

After:
Screenshot from 2021-06-14 11-35-00

## Release notes

When using social_event_type module, the event teasers will now display actual event type above the event title.

## Change Record
/

## Translations
/

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Review by nachosalvador — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Review by Kingdutch — CHANGES_REQUESTED** [review]
Unfortunately, this PR sidesteps the actual issue.

The original functionality here was a clickable link to the event type. The proposed fix only adds a textual label.

The actual error is introduced in https://github.com/goalgorilla/open_social/commit/0aa5e986ea889ccb2968926add19e5a79e34246b#diff-85c8b224111324746c540e8ce52bca22867034af12f40b98cdc77cdda7f971b1R76

This adds a type-check on `Node` because `$event` is not named correctly. `$event` in that context should actually be named `$event_type` and it's type is actually `Term` because that's what `field_event_type` refers to.

https://github.com/goalgorilla/open_social/blob/0aa5e986ea889ccb2968926add19e5a79e34246b/modules/social_features/social_event/modules/social_event_type/social_event_type.module#L76

This also means the original type annotation (saying `$event` is a `Node`) is incorrect.

https://github.com/goalgorilla/open_social/blob/0aa5e986ea889ccb2968926add19e5a79e34246b/modules/social_features/social_event/modules/social_event_type/social_event_type.module#L74

**Comment by nkoporec** [comment]
@Kingdutch Yes you are right, I thought that node check is correct since it could be used in other context ... I have fixed the type check and  the annotation.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2380-obe89c7tx8yvap54eq1fn6sytjnoa2jc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c7239b7571464950a4bce8

**Review by Kingdutch — COMMENTED** [review]
For clarity we may want to change the `$event` variable from `foreach ($event_type_entities as $event)` to `$event_type` (and also change its uses). That makes the code easier to follow for any future developers arriving here and decreases the chance of an accidental regression in the future.

Other than that it looks like the code now fixes the issue originally outlined :)

**Comment by navneet0693** [comment]
Closing this PR in favor of : https://github.com/goalgorilla/open_social/pull/2462

**Comment by navneet0693** [comment]
@Kingdutch Please review this one as well : https://github.com/goalgorilla/open_social/pull/2462

**Pull request closed without merging**
