### PR TITLE
Issue #3272898 by navneet0693: Use Batch API in update hook to process events.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
This event is loading all the events of a platform and iterating over them to fill a field value. The save operation on entity can fire a lot of events which is written in Open Social. This code has a high potential to run into memory limits while updating the platform.

## Solution

This event hook was not implementing a Batch API. See: https://github.com/goalgorilla/open_social/blob/11.1.1/modules/social_features/social_event/social_event.install#L1952.

We have tested this on platform having approximately 6000 events. We were upgrading from Open Social 10.2.5 to Open Social 11.1.1. The platform's available PHP memory was 384M. Also, it is not good practice to do such operations without a Batch API.

So, we re-wrote this update considering two factors, which are stated as follows:

1. People who already updated to latest version of Open Social weren't affected by this code.
2. People who will still updating in future will not run into memory limit errors.

Please read more about Batch API here: https://www.hook42.com/blog/how-streamline-update-hooks-using-batch-api

We are using https://git.drupalcode.org/project/drupal/-/blob/9.4.x/sites/default/default.settings.php#L733 to ensure the size of the number of entities processed in a batch update.

## Issue tracker
https://www.drupal.org/project/social/issues/3272898

## Theme issue tracker
N.A

## How to test
- [ ] Using version 10.2.x of Open Social which Event enrollment feature is enabled.
- [ ] Create more than 6000 events.
- [ ] Update to Open Social 11.1.1
- [ ] Run `drush updb`
- [ ] You may face PHP memory outage.
- [ ] Checkout to this branch. You should not face any PHP memory outage on the execution of this particular hook.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [x] This pull request has all required labels (team/type/priority)
- [x] This pull request has a milestone
- [x] This pull request has an assignee (if applicable)
- [x] Any front end changes are tested on all major browsers
- [x] New UI elements, or changes on UI elements are approved by the design team
- [x] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
Screenshot 2022-03-31 at 7 18 07 PM

## Release notes
We changed our approach to update the value of `field_event_enroll` from the old field `field_event_enable_enrollment` which was running into a PHP memory outage for the platforms upgrading from Open Social 10 to Open Social 11.

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2849-jwf9gidvnvjueh70d1k9fchlqufilmhv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246c4b0b1a46a5aa1be6e37

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2849-jwf9gidvnvjueh70d1k9fchlqufilmhv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246c4b0b1a46a5aa1be6e37

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2849-jwf9gidvnvjueh70d1k9fchlqufilmhv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6246c4b0b1a46a5aa1be6e37

**Review by Ressinel — COMMENTED** [review]
@navneet0693 I have tried to update from 10.2.6 to this PR branch and I see a warning during the DB update:

```
>  [notice] Update started: social_event_update_10306
>  [warning] array_slice() expects parameter 1 to be array, string given social_event.install:1977
>  [notice] Update completed: social_event_update_10306
```
To reproduce it make sure that you have created events.

**Review by Ressinel — APPROVED** [review]

**Comment by navneet0693** [comment]
🍒 - picked in 11.2.x, 11.1.x and 11.0.x

**Pull request merged**
