### PR TITLE
Issue #3411253: Upgrade the Paragraph module to the major version

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Paragraph module has a new minor version with small bugfixes.

## Solution
Upgrade the Paragraph to minor version

## Issue tracker
[PROD-27857](https://getopensocial.atlassian.net/browse/PROD-27857)
[#3411253](https://www.drupal.org/project/social/issues/3411253)

## Theme issue tracker
N/A

## How to test
- [ ] Test different kind of landing pages which use a lot of paragraphs 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Paragraph releases notes: https://www.drupal.org/project/paragraphs/releases/8.x-1.16

## Change Record
N/A

## Translations
N/A

[PROD-27857]: https://getopensocial.atlassian.net/browse/PROD-27857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Review by ronaldtebrake — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3670-tcokptv7c2fssptvv6d9btmrl8lvhu9g.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/658dcfd1ecd18dd887caddee

**Comment by ronaldtebrake** [comment]
Screenshot 2024-01-03 at 08 36 18

Landing pages still work great :) approved!

**Comment by ronaldtebrake** [comment]
also cherry-picked to 12.1.x 🍒

**Pull request merged**
