### PR TITLE
Issue #3396674 by SV: Error on edit or create events and topics pages

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem
When I open `/node/add/event` there is an error:

Screenshot 2023-10-25 at 18 39 08

## Solution
Currently, in `termIsVisibleForEntities()`, there can be loaded terms that don't have a `field_category_usage` it causes an error and needs to add checks to prevent it.

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-27205
- https://www.drupal.org/project/social/issues/3396674
- https://www.drupal.org/project/social/issues/3396372

## Theme issue tracker
N/A

## How to test
- [ ] Using the latest version of Open Social with the social_tagging and social_event modules enabled
- [ ] As a sitemanager
- [ ] Try to create  or edit event/topic
- [ ] When opening "/node/add/event" page  I expect to seee edit but instead see error
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Fixes an issue on event/topics create/edit pages

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3569-qafcbex1hxhjq5sfceqiatse7fgtlbuz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65393ed3b8fea62d45109d45

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3569-qafcbex1hxhjq5sfceqiatse7fgtlbuz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65393ed3b8fea62d45109d45

**Review by ribel — APPROVED** [review]
Changes were tested and looks good to me.

**Review by kashandarash — APPROVED** [review]
Changes look good to me! 

Please do not forget to update Cablecar as well (calling of termIsVisibleForEntities)
cc @ribel @volodymyr-sydor

**Comment by ribel** [comment]
🍒 picked to 11.11.x and 12.0.x

**Pull request merged**
