### PR TITLE
Issue #3337612 by ronaldtebrake: Profile preview for Activities could cause errors

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
The profile preview activity alter incorrectly assumes an activity always has an Owner, but this could result in an error:

`TypeError: Drupal\profile\ProfileStorage::loadByUser(): Argument #1 ($account) must be of type Drupal\Core\Session\AccountInterface, null given, called in /app/html/profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module on line 37 in /app/html/modules/contrib/profile/src/ProfileStorage.php on line 33 #0 /app/html/profiles/contrib/social/modules/social_features/social_profile/modules/social_profile_preview/social_profile_preview.module(37): Drupal\profile\ProfileStorage->loadByUser(NULL, 'profile')
`

## Solution
Make sure we only alter if there is an actual Owner available for the activity.

## Issue tracker
https://www.drupal.org/project/social/issues/3337612
https://getopensocial.atlassian.net/browse/PROD-22893

## How to test
- [ ] A stream with multiple activities in it
- [ ]  Remove that user, and assign content to anonymous
- [ ]  Enable profile preview
- [ ]  See that the stream breaks
- [ ] After this PR that should be tackled gracefully

Because of the criticality of this and the lack of tests, I have created a follow up (internal ticket reference: https://getopensocial.atlassian.net/browse/PROD-23995) 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Profile preview now works if the author of an activity was deleted.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3299-z0asveatqc0o3au9onudrsuq23qqckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d7c8ac127cbc4c56a58ef5

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3299-z0asveatqc0o3au9onudrsuq23qqckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d7c8ac127cbc4c56a58ef5

**Review by Kingdutch — COMMENTED** [review]
@ronaldtebrake Can we document when there's no owner? It feels like maybe then the activity itself shouldn't exist?

Maybe we should implement some kind of `hook_user_delete` for activities if we don't already have it?

Will the activity render correctly if we don't fill in `content` for the items since we don't have a profile or do we need some other fallback?

If the answer to the above is "yes", "nah", "yes, no" then the more defensive code is the way to go :D

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3299-z0asveatqc0o3au9onudrsuq23qqckdc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63d7c8ac127cbc4c56a58ef5

**Comment by ronaldtebrake** [comment]
Thats why I've created several follow up tickets you can find in the related ticket @Kingdutch;
The issue in this case was that something went wrong with the deletion of a user and the content being assigned to anonymous; there were actual activities (several of them) who weren't updated to have their owner also reflect anonymous. 

Thats exactly the proposal in that ticket, to make sure we act on the user being deleted and also do a cleanup of activities and user_id's which are already gone as well as either it has never worked / we have never implemented this 🙏 

Yes, for this scenario it does, it's the preprocess that completely gets skipped, what gets skipped you ask? If you look closely you'll see that it's trying to render a profile preview for the Owner of the entity that triggered the activity, I expect that to be what we want as that is also what happens if there is no profile. :)

**Review by Kingdutch — APPROVED** [review]
Okay awesome! :D Lets get this merged

**Comment by ronaldtebrake** [comment]
Cherry picked 🍒 to 11.6.x, 11.7.x

**Pull request merged**
