### PR TITLE
Issue #3410322 by SV: Impossible to translate "ago" on the list of private messages

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

Currently, when we have a multilingual site we can't translate "Future format/Past format" for timestamp_ago formatter on the preview page of the private message list

## Solution

- Add a patch where FormattableMarkup is replaced with TranslatableMarkup that fixes the issue

## Issue tracker

- https://getopensocial.atlassian.net/browse/PROD-27560
- https://www.drupal.org/project/social/issues/3410322
- https://www.drupal.org/project/drupal/issues/3410052

## Theme issue tracker

N/A

## How to test
- [ ] Using the latest version of Open Social with the social_private_message module enabled and added a few languages on the site
- [ ] As a sitemanager try to find and add translations for: "@interval hence" and "@interval ago"
- [ ] Log in as LU with different prefered language as default one
- [ ] When I open "/user/inbox" I expect to see translated "ago" and "hence" but instead see them in English.
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots

Before:
Screenshot 2023-12-20 at 18 37 02

After:
Screenshot 2023-12-21 at 17 44 37
Screenshot 2023-12-21 at 17 44 49

## Release notes

Fixes the issue with untranslated "ago" on the private message list page

## Change Record

N/A

## Translations

N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3663-bg7ds77xvneb3t1l11yk5qiivttnajv9.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65845ec2ed5de7d37064f1b1

**Comment by ribel** [comment]
Closing as outdated. More details can be found in the JIRA ticket.

**Comment by UltraBob** [comment]
@ribel might it be possible to provide some updates for those of us who cannot see the JIRA ticket?  I'm having this issue in translating the private message interface, and it is unclear whether there is any way to accomplish the translation.

**Pull request closed without merging**
