### PR TITLE
Issue #3204071 by rolki: Remove all deprecated things from the social_gdpr accordingly with the data_policy

### PR DESCRIPTION
**Pull request by rollki**
## Problem
The data_policy module was updated [here](https://git.drupalcode.org/project/data_policy/-/merge_requests/1) and as a result, our social_gdpr module doesn't work with multiple entities, and a new version of that module

## Solution
Remove redundant code, to support multiple data policy entities.

## Issue tracker
- https://getopensocial.atlassian.net/browse/YANG-5043
- https://www.drupal.org/project/social/issues/3204071
- https://getopensocial.atlassian.net/browse/YANG-5710

## How to test
Now it is impossible to do any UI interaction within this module since we removed all forms and routes. This module only sets some default permissions and adds some small customization and test coverage.

## Screenshots
image

## Release notes
We minimize existing code for the `social_gdpr` module since it is duplicate forms and logic from the `data_policy` module, and the second one already covers all that `social_gdpr` have, but we still want this module for test coverage and probably basic permissions setup.

Also, we update the `data_policy` module from `1.0-beta6` to the latest `1.0@RC`, the newest version contains "Multiple checkbox functionality", see https://www.drupal.org/project/data_policy/issues/3201613 (https://git.drupalcode.org/project/data_policy/-/merge_requests/1).

### CODE REVIEW

**Comment by rollki** [comment]
@ribel 
Behat test for the data policy fixed, but this change depends on data policy PR (https://git.drupalcode.org/project/data_policy/-/merge_requests/1)

**Comment by robertragas** [comment]
Think we need to get this moving again, as currently we are having more clients adding this as a patch.

**Comment by ronaldtebrake** [comment]
Hi @ribel @rollki 

It seems to work nicely also with existing data policies.
Although we do need a new version of the data policy tagged in here before we can merge it.

I'm happy if you all agree (maybe with input from @robertragas as well) with the specific feature changes, I'm not very familiar with it and also couldnt really figure out what to test with the quite big amount of changes in there and lack of information. 

But considering the Distro is becoming super lean with these changes, i'm very happy if all of you are haha :D !

**Review by OH17L — APPROVED** [review]

**Comment by ribel** [comment]
Changes to the Data Policy was merged and released in version [RC1](https://www.drupal.org/project/data_policy/releases/8.x-1.0-rc1)
@rollki Please update this PR and add a bit more explanation for the Release Notes.

**Comment by rollki** [comment]
@ribel PR was updated, release notes also added.

**Comment by rollki** [comment]
It seems the test is failed because still use the old version of the data policy while the test running. I updated PR, let's see if it trigger a new version of the data policy.

**Comment by Kingdutch** [comment]
@rollki Tests show it's installing the correct version of the data policy module. It now also specifically fails on a data policy test: https://travis-ci.com/github/goalgorilla/open_social/jobs/510327137#L1892

This probably indicates that the changes broke something.

**Comment by rollki** [comment]
@Kingdutch 
I'm rechecking the changes, can be that we missed something or removed something unnecessary here.

**Comment by rollki** [comment]
I guess that test should pass now. Some tests for GDPR have changed accordingly with 1RC data policy version and one test was removed `data-policy-revisions.feature`, so this test was removed since we scrap forms and some pages from `social_gdpr` module, and revisions already covered by behat tests in `create-data-policy.feature`.

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2266-xoky4tmvlxuay5evira656ooqhwaasek.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0aa9bcde7204ea77a848e

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2266-xoky4tmvlxuay5evira656ooqhwaasek.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0aa9bcde7204ea77a848e

**Comment by rollki** [comment]
@ribel 
STR in this PR and d.org ticket was updated.

**Pull request merged**
