### PR TITLE
Issue #3225331 by Ressinel: Update the Token module from 1.5 to 1.9

### PR DESCRIPTION
**Pull request by Ressinel**
## Problem
Update the Token module to have compatibility with Drupal 9

## Solution
Update to the latest version.

## Issue tracker
- https://www.drupal.org/project/social/issues/3225331

## How to test
- [ ] Make some activity, like mention someone in a comment or create content in any group
- [ ] Should be sent notifications where tokens will be replaced properly

## Screenshots
N/A

## Release notes
The Token module has been updated to 1.9. Please view the release notes from [1.6](https://www.drupal.org/project/token/releases/8.x-1.6), [1.7](https://www.drupal.org/project/token/releases/8.x-1.7), [1.8](https://www.drupal.org/project/token/releases/8.x-1.8), and [1.9](https://www.drupal.org/project/token/releases/8.x-1.9) of that module for the changes.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2440-aqdwyxqpfrpnp5zyhsk7evtz3r4kbrke.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60feaec7742468e27d67e4f9

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2440-aqdwyxqpfrpnp5zyhsk7evtz3r4kbrke.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60feaec7742468e27d67e4f9

**Comment by ronaldtebrake** [comment]
Tested a full reinstall with all demo content generation of notifications.
Tested invites for events / groups
Tested a direct email through admin/people using the `[social_user:recipient] `
Tested the metatag/path manager using tokens

All seems to pass nicely.

Screenshot 2021-08-09 at 11 41 17

Screenshot 2021-08-09 at 11 47 45

**Review by ronaldtebrake — APPROVED** [review]
Can be merged once test passed, thanks @Ressinel

**Pull request merged**
