### PR TITLE
Internal: Update the address module to new version.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
Update address module due to new release.

https://github.com/commerceguys/addressing/releases/tag/v1.4.0 was released yesterday and it breaks compatibility with the address module.
Also, https://www.drupal.org/project/address/releases/8.x-1.11 was released fixing https://www.drupal.org/project/address/issues/3302484 which is now required.

## Solution
Update composer.json

## Issue tracker
N.A

## Theme issue tracker
N.A

## How to test
- [ ] All checks should pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3068-xafd4za8f4swvqjgzsl99xrwd5bshwj5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f203067e6c3f16da369593

**Comment by navneet0693** [comment]
This is false positive.

**Comment by tbsiqueira** [comment]
Cherry-picked to 11.1.x, 11.2.x, 11.3.x and 11.4.x

**Pull request merged**
