### PR TITLE
Issue #3317249 by SV: Changes of content-visibility in groups are not adjusted for PHP 8

### PR DESCRIPTION
**Pull request by volodymyr-sydor**
## Problem

Screenshot 2023-01-20 at 15 09 39

## Solution
Make a method for batch process callback as static

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-24011
- https://www.drupal.org/project/social/issues/3317249

## How to test
- [ ] Using php 8.0 or latest one
- [ ] Using the latest version of Open Social with the social_search module enabled and configured Social SOLR server
- [ ] As a sitemanager
- [ ] Add a new group with group-visibility "community" and group-content-visibility "community and group members"
- [ ] Add content to the group (event, topic) with content-visibility "community".
- [ ] Change in the group the group-content-visibility from "community and group members" to only "group members".
- [ ] When saving I expect the result to be saved but instead see an error page.
- [ ] The expected result is attained when repeating the steps with this fix applied.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Fix issue with updating group content visibility for PHP 8.0.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Review by ribel — APPROVED** [review]
LGTM.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3296-yuuk19ckreweanumddgz7vweqwi52zpb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63caaa775804da46dbddd029

**Comment by nkoporec** [comment]
:cherries: picked to 11.6.x, 11.7.x

**Pull request merged**
