### PR TITLE
Issue #3301083 by rolki: Event invites do not disappear from the notification center

### PR DESCRIPTION
**Pull request by rollki**
## Problem
If the user was invited to an event, and he enrolls for this event not from the `/event-invites` page, but from the event itself, then this event disappears from the `/event-invites` list, but the indicator that there are new invitations to the event still remains and it is almost impossible to get rid of it.

## Solution
If the user was invited to an event, and he enrolls for this event not from the /event-invites page, but from the event itself, then we also need to mark this enrollment as accepted, otherwise, the list of invites will be empty, but the notification center will say that there are new invites.

## Issue tracker
- https://www.drupal.org/project/social/issues/3301083
- https://getopensocial.atlassian.net/browse/PROD-20238

## Theme issue tracker
NONE.

## How to test
- [x] Create an event
- [x] Go to "Manage enrollments" -> Invite users
- [x] Invite another user
- [x] Log in under that other user
- [x] Go to "Invites" (`/user/{another_user_id}/event-invites`)
- [x] DO NOT CLICK "Accept invitation" but open the event you are invited to in a new tab
- [x] Click "ENROLL"
- [x] Return to the list of invites, accordingly the invite disappeared, but the counter did not decrease

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
image
image
image

## Release notes
*[Required if new feature, and if applicable] A short summary of the changes that were made that can be included in release notes.*

## Change Record
NONE.

## Translations
NONE.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3061-twiefyjhidt6swddeuztuxg9otnu1w6p.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e7a4b2fe6282831348a3e4

**Review by dmytriikaiun — APPROVED** [review]

**Review by ribel — APPROVED** [review]
I have tested changes on our Enterprise Demo site and all works as expected now.
Nice fix!

**Review by navneet0693 — APPROVED** [review]

**Comment by ribel** [comment]
I've tried to cherry-pick it to 11.3.x, but there was conflict in `EnrollActionForm.php`. 
So I have 🍒-picked it only to 11.4.x (actually as it was originally set in milestone)

**Pull request merged**
