### PR TITLE
Issue #3262433 by tbsiqueira: Create a new CM+ "quick access dashboard" for better user experience

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
Currently there are a lot of menu options that are not easily accessible to CM+ users. Usually they need to "hunt" down links since they are scattered around Open Social main menu.

## Solution
Create a menu structure, at level one of Open Social main menu with all relevant menu links for CM+ users, similar to the already existing link at "/admin/config" ( img1 ).

Besides creating a central place for options, this allows extensions to easily add items to this menu.

## Issue tracker
https://www.drupal.org/project/social/issues/3262433

## How to test
- [x] Log in as site/content manager;
- [ ] Check on the right side, if there is a new menu available, with a gear icon, it should be the first menu item;
- [ ] Hover over the gear icon, and check if a new menu tab with "Dashboard" title is displayed;
- [ ] Click at the gear icon, and check if the page /admin/dashboard is displayed;

## Screenshots
sidebar-menu-img1
Detail at the sidebar menu

open-menu-tab-2
Detail on the expanded menu tab

dashboard-menu
Detail at the dashboard menu

## Release notes
Content managers and Site managers now have access to a new dashboard directly on Open Social Core. Its purpose is to serve as a fast access dashboard, divided by category, providing easy access to some core Open Social functionalities/pages.

If necessary other roles may access the Dashboard, this is controlled by the new "Access administration dashboard" permission available at `/admin/people/permissions`

Developers can easily extern this menu by adding/modifying a custom `my_module.links.menu.yml` file. The suggested syntax should be like this:

```
my_module.social_core.dashboard.[parent_name].[menu_item_name]:
  title: 'My title'
  parent: [parent_menu_item]
  description: 'My description'
  route_name: my_route
  weight: [weight]
```

If necessary a custom, dynamic menu item can be provided by adding the suggested settings at `my_module.links.menu.yml`:

```
my_module.social_core.dashboard.[parent_name].[menu_item_name]:
  parent: [parent_menu_item]
  class: Drupal\my_module\Plugin\Menu\MyDinamicMenuItemLink
  weight: [weight]
```

Open Social already provides a custom implementation of the plug in here: `Drupal\social_core\Plugin\Menu\HomepageConfigurationHeroBlockLink`

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Review by Ressinel — COMMENTED** [review]
@tbsiqueira I think it makes sense to add dependence on `social_core` (`- social:social_core`) for each module where we use `parent: social_core.dashboard.*` in `*.links.menu.yml`.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2764-nksxmpyq7r46lrtxhiqc71nq3robigiv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62067e42046a4b8d29fb6fed

**Pull request merged**
