### PR TITLE
Issue #3413813: Enable Social Emoji to be enabled by default

### PR DESCRIPTION
**Pull request by vcsvinicius**
## Problem
The Social Emoji module isn't be enable by default, it would be great be enabled for all.

## Solution
Add Social Emoji module as dependency to be enabled for all and add an hook-update to be enabled for already installed system.

## Issue tracker
[PROD-27847](https://getopensocial.atlassian.net/browse/PROD-27847)
[#3413813](https://www.drupal.org/project/social/issues/3413813)

## Theme issue tracker
N/A

## How to test
Check if the Social Emoji module is enabled by default.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
The Social Emoji will be enabled by all and it will be installed by default in new installation.

## Change Record
N/A

## Translations
N/A

[PROD-27847]: https://getopensocial.atlassian.net/browse/PROD-27847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3694-h5vnfmmer4jqeewwbyk5gygxpjudybsy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ecfd06b340e1f8837c488

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3694-h5vnfmmer4jqeewwbyk5gygxpjudybsy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ecfd06b340e1f8837c488

**Comment by robertragas** [comment]
Also 1 test is failing, not sure if it's related, but we can't merge until its green

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3694-h5vnfmmer4jqeewwbyk5gygxpjudybsy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ecfd06b340e1f8837c488

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3694-h5vnfmmer4jqeewwbyk5gygxpjudybsy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/659ecfd06b340e1f8837c488

**Comment by vcsvinicius** [comment]
I cherry-picked it to 12.1.x branch

**Pull request merged**
