### PR TITLE
Issue #3405938: Declare social_core.layout in social_core.services.yml

### PR DESCRIPTION
**Pull request by VBaldych**
⚠️ Depends on socialblue 2.5.6

## Problem
After update to Drupal 10, the service 'social_core.layout' can't be declared via SocialCoreServiceProvider.

## Solution
Declare service 'social_core.layout' in .yml file and use it via \Drupal::service()

## Issue tracker
- https://getopensocial.atlassian.net/browse/PROD-27877
- https://www.drupal.org/project/social/issues/3405938

## Theme issue tracker
- https://www.drupal.org/project/socialbase/issues/3405919

## How to test
Test with updated Socialbase theme
- [ ] Be sure that Layout Builder is enabled 
- [ ] Be sure that Social Core is enabled
- [ ] Be sure that Social Event is enabled
- [ ] Create an event and save
- [ ] Check the event page - you shouldn't see an empty "right sidebar"

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by VBaldych** [comment]
@ribel need to remove Socialbase patch after new theme release

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3705-clrbhdnkinxce8y0mwiun86vrnop3wjo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65a7b7e6f8072d23f1488bb6

**Review by ribel — APPROVED** [review]
Changes were tested and works without regression on full-widh pages like Landing Pages (or pages with layout builder).
image

image

**Pull request merged**
