### PR TITLE
Issue #3222130 by nkoporec: Can't filter by content tags on /all-topics page

### PR DESCRIPTION
**Pull request by nkoporec**
## Problem
When I try to filter by content tags on /all-topics page, I receive a wsod. When looking through the logs, it shows up an SQL error:

`
Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Latest topics[latest_topics]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '9')) subquery' at line 6: SELECT COUNT(*) AS expression FROM (SELECT DISTINCT node_field_data.created AS node_field_data_created, node_field_data.nid AS nid, 1 AS expression FROM {node_field_data} node_field_data WHERE (node_field_data.status = :db_condition_placeholder_0) AND (node_field_data.type IN (:db_condition_placeholder_1)) AND (.social_tagging_target_id = :db_condition_placeholder_2)) subquery; Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => topic [:db_condition_placeholder_2] => 9 ) in Drupal\views\Plugin\views\query\Sql->execute() (line 1543 of /var/www/html/docroot/core/modules/views/src/Plugin/views/query/Sql.php).`

## Solution
In SocialTaggingOverrides.php, when overriding the view config, it will always try to join profile__social_tag table (when profile tagging is enabled), but this is not correct behavior, because if you are on /all-topics it should use node__social_tag table, since it will filter through nodes and not profiles. So this code needs to be changed, so it only uses the profile__social_tag table when on user views.

## Issue tracker
https://www.drupal.org/project/social/issues/3222130#comment-14153946

## How to test
1. Enable social_tagging module.
2. Enable tagging for all types (groups,topics,profiles...).
3. Create some tags and tag a topic with it.
4. Go to /all-topics page and try to filter by some tag.

## Screenshots
Before:
Screenshot from 2021-07-05 12-18-56

After:
Screenshot from 2021-07-05 12-17-51

## Release notes
1. Fixed an issue where filtering with content tags on topics views would throw an SQL error resulting in _The website encountered an unexpected error. Please try again later error_ page.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-t9z5mgo9nlwdxcgmxfbezhabdlgfcdtx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e2dd6057072df0ffeb6a3d

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-t9z5mgo9nlwdxcgmxfbezhabdlgfcdtx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e2dd6057072df0ffeb6a3d

**Review by nachosalvador — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-fsx9gerq0dfsjnevoeewnntd6lkgbyjy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d10f5378c5fee0a833cb0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-fsx9gerq0dfsjnevoeewnntd6lkgbyjy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611d10f5378c5fee0a833cb0

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-hfbkpuh3tl7qzlndcvbnxrlwhjm8ouwd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/616d54aa4dc8a8753f91bccb

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2399-hfbkpuh3tl7qzlndcvbnxrlwhjm8ouwd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/616d54aa4dc8a8753f91bccb

**Review by robertragas — APPROVED** [review]

**Pull request merged**
