### PR TITLE
Issue #3420088: [13.0.0] Remove references to public_group, open_group, closed_group, and secret_group for social_metatag module

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
We're removing the old group types from Open Social. This module has some references to the old group types which should be removed.

## Solution
Evaluate the references to the old group types. We might be able to remove the functionality that exists around it altogether and remove the dependency on any group type. If that's not possible just remove the references to the old group type. In any case the functionality itself should keep working for flexible groups.

### Relevant Distribution Changes
We're no longer using `social_metatag` as a dumping grounds for `metatag` configuration. Instead we now bundle metatag configuration with the module it is about and use the `config_modify` module to install it when `metatag` is enabled. Any module that has a `config/modify` folder should have a dependency on `config_modify` to ensure modules are installed in the correct order. The `metatag` module and `metatag_open_graph` module are installed by enabling them as default in the `installer_options_list` so that the `social_metatag` module is no longer needed for this.

There's one change left in `social_metatag` which is an alter hook. That should be changed in a follow-up so the module can be removed.

## Issue tracker

https://www.drupal.org/project/social/issues/3420088

## How to test
- [ ] Create public content/group before the upgrade and run it through [Facebooks Sharing Debugger](https://developers.facebook.com/tools/debug/)
- [ ] Perform an install with the new version
- [ ] Recreate the same content and run it through [Facebooks Sharing Debugger](https://developers.facebook.com/tools/debug/)
- [ ] The outcome should be the same (with proper meta information installed in both cases)

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes

The metatag information for the legacy group types has been removed.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3757-ojaqyhqehkxyjz481icvqga2wt2zvuzu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c5023898b7dc1049cec3ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3757-ojaqyhqehkxyjz481icvqga2wt2zvuzu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c5023898b7dc1049cec3ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3757-ojaqyhqehkxyjz481icvqga2wt2zvuzu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c5023898b7dc1049cec3ca

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3757-ojaqyhqehkxyjz481icvqga2wt2zvuzu.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65c5023898b7dc1049cec3ca

**Review by nechai — APPROVED** [review]

**Comment by ribel** [comment]
I also checked update hook locally and it looks good.
image

**Pull request merged**
