### PR TITLE
Issue #3408735 - Error suppression for file_mdm exif metadata issues.

### PR DESCRIPTION
**Pull request by ronaldtebrake**
## Problem
We're currently getting quite some issues which are in the form of:

```
Error getting exif ('Orientation') metadata for [IMAGENAME]. Message: Size of Canon Camera Settings does not match the number of entries. []
```

## Solution
Although this needs to have a fix upstream (see related drupal.org issue) it seems that's far from available. The attached patch is the one from the merge request from the linked issue made by the maintainer, which isn't ideal just removing it, but considering it's the maintainers choice for now perhaps our best bet especially as it's linked to the issue in the contrib module, which makes it easier for us to track it's progress.

Manual testing (and the fact it returns NULL on error) seems like there isn't much of a downside to suppress the error for now, alternatively if this stays open for long without an upstream fix we could decide to change the log level to warning perhaps. But the fact of the matter is that these images are coming from user input and we have no way of helping them fix the metadata of the image, nor can they do it themselves, it's just an issue with the modules interpretation of it.

## Issue tracker
https://www.drupal.org/project/social/issues/3408735

## How to test
It's hard to test, you'll need an image with the wrong metadata, I've tested this with an image that was broken from a customer but don't want to share that publicly obviously. There is no functional impact, just the error being suppressed and it returns the same. I think we can live without functional testing in that case. 

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Internal: Suppress error message for exif metadata issues with file_mdm.

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3739-xga0gyrprg5rhvrueb07zey4b9oprodz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bca69898b7dc1049550090

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3739-xga0gyrprg5rhvrueb07zey4b9oprodz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bca69898b7dc1049550090

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3739-xga0gyrprg5rhvrueb07zey4b9oprodz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bca69898b7dc1049550090

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3739-xga0gyrprg5rhvrueb07zey4b9oprodz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bca69898b7dc1049550090

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3739-xga0gyrprg5rhvrueb07zey4b9oprodz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/65bca69898b7dc1049550090

**Review by vcsvinicius — APPROVED** [review]
I approved the PR

**Comment by vcsvinicius** [comment]
I cherry-picked it to: 12.0.x, 12.1.x and 12.2.x

**Pull request merged**
