### PR TITLE
Issue #3173585 by navneet0693: Added condition to activity post visibility filter for restricting activities created for the private content.

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem
The "Explore" menu of Open Social presents with certain items that are not accessible for the LU but still, it can see the update about it.

## Solution
Add a query from https://github.com/goalgorilla/open_social/blob/10.0.x/modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php#L121 to https://github.com/goalgorilla/open_social/blob/10.0.x/modules/custom/activity_viewer/src/Plugin/views/filter/ActivityFilterPersonalisedHomepage.php#L132 in this file:
https://github.com/goalgorilla/open_social/blob/10.0.x/modules/custom/activity_viewer/src/Plugin/views/filter/ActivityPostVisibilityAccess.php

## Issue tracker
https://www.drupal.org/project/social/issues/3173585

## How to test
- [ ] As LU 1, create a flexible group set visibility to "Group members"
- [ ] Create a topic and event
- [ ] Run cron
- [ ] Go to /explore as LU 2 (different user)
- [ ] You should not see any updates regarding the creation of the contents in that group.

## Screenshots
**Before**
image

**After**
image

## Release notes
Private content will not appear in the "/explore".

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by navneet0693** [comment]
Note for the reviewer: Explore menu has a purpose: https://communitytalks.getopensocial.com/manual-explore. The current changes will also include the personalization part where the user will able to see it's own group-related activities.

**Comment by robertragas** [comment]
Travis still failing though that needs fixing

**Comment by navneet0693** [comment]
@robertragas Travis is passing now :-) We can merge it now.

**Comment by navneet0693** [comment]
Cherry picked on 8.x-8.x: c94a680c9c25ea88d154313328341936ca744cfb
8.x-9.x : 1d1ee9056546d5488730ecabcc77adcf24cd7c02

**Comment by navneet0693** [comment]
Follow up is https://github.com/goalgorilla/open_social/pull/2039

**Pull request merged**
