### PR TITLE
Issue #3278347 by navneet0693: Junk plugin data can crash activity entity related view

### PR DESCRIPTION
**Pull request by navneet0693**
## Problem

Certain scenarios like:

    1. configuration overrides
    2. undefensive code
    3. uninstalled modules not cleaning it's related data at the time of uninstalling

can lead to orphaned and/or junk data in entities in database. 

Sometimes the modules which are uninstalled may contain plugins and configuration overrides which can lead to the storage of unrequired data in the database. Also, on removal, these modules may not be related data from the database which leads to junk data.

These orphaned data crash pages and other views or blocks that render the "Activity" entity, for example.
    
A module declaring a plugin instance and attaching that instance with entities, for example, activities, was uninstalled; but during uninstall it didn't cleaned it's related data from activities. This will lead to PluginNotFoundException being thrown on the pages where activities are being processed. For example, home page, stream pages, group streams, notifications etc.

For example,

If there is a module that introduces an "ActivityDestination" plugin and activities containing that destination in the database. Upon uninstall, if the module doesn't cleans the data, then it will lead to PluginNotFoundException

## Solution
Make sure that before creating an instance of a plugin whose the plugin manager which extends 'DefaultPluginManager' class, we check that the plugin definition exists and it is successful in retrieving it without any errors.

    The hasDefinition function is defined as follows:
```

    public function hasDefinition($plugin_id) {
        return (bool) $this->getDefinition($plugin_id, FALSE);
    }

```
    which means that it is marking $exception_on_invalid parameter to be false, which simply says "If TRUE, an invalid plugin ID will throw an exception."

    now hasDefinition simply returns false in this logic if the plugin definition couldn't be found. This saves us from hard errors and we can safely say that call to "createInstance" will return a plugin instance.

## Issue tracker
https://www.drupal.org/project/social/issues/3278347

## Theme issue tracker
N.A

## How to test
- [ ] Perform general operations on Open Social installation.
- [ ] Check if notifications, emails and activities are being created.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] If applicable (I.E. new hook_updates) the update path from previous versions (major and minor versions) are tested
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N.A

## Release notes
N.A

## Change Record
N.A

## Translations
N.A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2917-onvzk6vyxylhfdhgglsgyt3c5r4oqtjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62711b7c8a4c5796e758f427

**Review by Ressinel — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2917-onvzk6vyxylhfdhgglsgyt3c5r4oqtjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62711b7c8a4c5796e758f427

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2917-onvzk6vyxylhfdhgglsgyt3c5r4oqtjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62711b7c8a4c5796e758f427

**Comment by navneet0693** [comment]
🍒 - picked to 11.2.x and 11.3.x

**Pull request merged**
