### PR TITLE
Add validation for users don't have the right roles

### PR DESCRIPTION
**Pull request by NickDaelemans**
## Problem
When adding people to a flexible group that is restricted to specific roles, people without the right role could be added to that group.
## Solution
Added an extra validation that checks if the selected users have the right roles. If they don't, an error is thrown.

## Issue tracker
https://www.drupal.org/project/social/issues/3250886
## How to test

1. Create a flexible group that is restricted on role.
2. Try to add a user (Add directly) to that newly created group that doesn't have the role.
3. You should get an error message, that you are not allowed to add the user, since he hasn't got the right role.

## Translations
*Translatable strings are always extracted from the latest development branch. To ensure translations remain available for platforms running older versions of Open Social the original string should be added to `translations.php` when it's changed or removed.*
- [ ] Changed or removed source strings are added to the `translations.php` file.`

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2616-xk5hb1kpxorjvwn6aqi2t1kuwgk6bwee.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d06a6908ae15e2f60dee1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2616-xk5hb1kpxorjvwn6aqi2t1kuwgk6bwee.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d06a6908ae15e2f60dee1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2616-xk5hb1kpxorjvwn6aqi2t1kuwgk6bwee.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d06a6908ae15e2f60dee1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2616-xk5hb1kpxorjvwn6aqi2t1kuwgk6bwee.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d06a6908ae15e2f60dee1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2616-xk5hb1kpxorjvwn6aqi2t1kuwgk6bwee.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/619d06a6908ae15e2f60dee1

**Comment by NickDaelemans** [comment]
Not supporting 10.3.x anymore

**Pull request closed without merging**
