### PR TITLE
Issue #3239402 by tBKoT: As a user I want to share the event for other users to join

### PR DESCRIPTION
**Pull request by dmytriikaiun**
## Problem
It is currently only possible to invite people as event managers, but we need to make the invite function accessible to LUs.

## Solution
- Add additional settings on the event invite settings page
- Create a new field in the event to allow event managers to decide if users can invite other users to the event
- Update permissions to the event invite page

## Issue tracker
https://www.drupal.org/project/social/issues/3239402
https://getopensocial.atlassian.net/browse/OEC-27
https://getopensocial.atlassian.net/browse/OEC-28

## How to test
- [x] Enable the `social_event_invite` module
- [x] As an SM+ go to the event invite settings(`admin/config/opensocial/event-invite`)
- [x] Enable `Event managers are able to allow users send invites`
- [x] Edit any event and enable `Allow users to share the event with others`
- [x] Go to the event as LU
- [x] Enroll event
- [x] You should see a new `Invite` dropdown

## Screenshots
зображення
зображення
зображення

## Release notes
Now, if it is allowed by SM+ and an event manager, users can share an event link or invite other users to this event.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-tgmlv1fkztdpe3gn5mau5qdy2t0uzvhi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6152d7194807c0be283d0e70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-algtmylpjjufnvlhevfuycgdzl2o298e.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61a4f621908ae11d8d6557fb

**Comment by dmytriikaiun** [comment]
To display invite/share buttons we should use this [patch](https://www.drupal.org/files/issues/2021-11-29/3238973-add-invite-button-6.patch) for the `socialblue` theme

**Review by Ressinel — APPROVED** [review]
@dmytriikaiun Nice improvement, thanks 👍🏼 

Changes look good to me. The functionality works properly.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-b8ittrrq4wpwe6i9y7sv3niqqnqkd1xa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3e866046a4b8d294bca70

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2525-b8ittrrq4wpwe6i9y7sv3niqqnqkd1xa.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61f3e866046a4b8d294bca70

**Comment by ribel** [comment]
Hi @navneet0693 
This PR is finished, but there is one false-positive test here (for private messages) that fails even after re-run.
Do you think we can merge it?

**Pull request merged**
