### PR TITLE
Issue #3343419 by chmez: Allow  few content tags fields per entity

### PR DESCRIPTION
**Pull request by ghost**
## Problem
Only one field based on content tags can be added to an entity.

## Solution
Provide a list of fields based on this taxonomy term vocabulary and they support the split option.

## Issue tracker
- https://www.drupal.org/project/social/issues/3343419
- https://getopensocial.atlassian.net/browse/PROD-24233

## How to test
- [ ] Enable the "Social Album" and "Social Tagging" modules.
- [ ] Add a field with the label "Album tags" and machine name "field_tags" based on the "Content tags" taxonomy vocabulary to the "Album" content type.
- [ ] Add the following code to the "social_album.module" file:
```
/**
 * Implements hook_social_tagging_type_alter().
 */
function social_album_social_tagging_type_alter(array &$items): void {
  $items['node']['sets'][] = [
    'bundles' => ['album'],
    'field' => 'field_tags',
    'label' => t('Album content tags'),
    'group' => 'tags',
    'wrapper' => FALSE,
    'weight' => 1.1,
  ];
}
```
- [ ] Check the "Note type: Album" checkbox on the "Tags settings" page.
- [ ] When you open the album creation/edit page then you should see the "Album content tags" section which contains the "Album tags" field.

## Release notes
Allow adding more than one tags field on a form and make some settings of these fields configurable.

## Change Record
https://www.drupal.org/node/3345488

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Review by ribel — APPROVED** [review]
@OH17L Code and functional changes were tested and looks good to me.
Just for the context, this refactoring is needed for our [Social Matchmaking](https://github.com/goalgorilla/social_matchmaking/pull/3) extensions.
But changes here doesn't cause any regressions in existing functionality. 
@tbsiqueira, @nkoporec, please review it when you have a time and would be good if it can land in the 11.8.x

image

image

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3317-doqjpdty8nltkclrnllh1frmxcxs1xi3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63f4e00ef67d5c1f3367b01f

**Review by nkoporec — APPROVED** [review]
The  code changes looks good and I also manually tested it and it works. Waiting for tests to pass then we can merge it.

**Comment by nkoporec** [comment]
Failing tests are not related to these changes, so it is save to merge.

**Comment by nkoporec** [comment]
:cherries:  picked to 11.8.x

**Pull request merged**
