### PR TITLE
Issue #3004793 by truls1502: Updated like_and_dislike from 1.0-alpha2 to 1.0-beta1

### PR DESCRIPTION
**Pull request by truls1502**
## Problem & Solution
[Full Changelog](https://cgit.drupalcode.org/like_and_dislike/diff/?h=8.x-1.x&id=8.x-1.0-beta1&id2=8.x-1.0-alpha2)
- https://www.drupal.org/project/like_and_dislike/releases/8.x-1.0-alpha3
- https://www.drupal.org/project/like_and_dislike/releases/8.x-1.0-beta1

## Issue tracker
- https://www.drupal.org/project/social/issues/3004793

## Need to be fixed:
- [x] tests/behat/features/capabilities/like/like-create-event.feature:7
- [x] tests/behat/features/capabilities/like/like-create-topic.feature:7
- [x] tests/behat/features/capabilities/like/like-post-stream.feature:8
- [x] tests/behat/features/capabilities/like/like-post-stream.feature:31

## Release notes
Update like_and_dislike  from 8.x-1.0-alpha2 to 8.x-1.0-beta1

### CODE REVIEW

**Comment by truls1502** [comment]
Need to fix behat tests so it match with newer version:
- [ ] tests/behat/features/capabilities/like/like-create-event.feature:7
- [ ] tests/behat/features/capabilities/like/like-create-topic.feature:7
- [ ] tests/behat/features/capabilities/like/like-post-stream.feature:8
- [ ] tests/behat/features/capabilities/like/like-post-stream.feature:31

**Comment by jaapjan** [comment]
I will close this for know - it will help us keep overview. Feel free to re-open once the .make files are changed and you believe the Travis tests will pass! Let us know if you need more help!

**Comment by truls1502** [comment]
## My steps:
Here I will show you how I approach to the challenging I have right now where I am trying to fix a Feature test file after I had it went unsucessful at https://travis-ci.org/goalgorilla/open_social/jobs/446626265#L2256

### 1. Modifided `composer.json`-file from `drupal_social` 
Modifided the file to like below where I have used my own branch [dev-fix/like_and_dislike ](https://github.com/signwo/open_social/tree/fix/like_and_dislike) from _my forked git repo_ which is actually is the current PR. So this allow me to use my git repo into `composer.json`:
```
{
    "name": "goalgorilla/social_docker",
    "description": "Social docker template for composer based Open Social projects.",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "composer/installers": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.0.0",
        "cweagans/composer-patches": "^1.0",
        "drush/drush": "8.*@stable",
        "goalgorilla/open_social": "dev-fix/like_and_dislike",
        "goalgorilla/open_social_scripts": "dev-master"
    },
    "require-dev": {
        "jcalderonzumba/gastonjs": "~1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
        "mikey179/vfsStream": "~1.2",
        "symfony/css-selector": "~2.8",
        "behat/behat": "3.*@stable",
        "behat/mink": "1.*@stable",
        "behat/mink-extension": "*",
        "behat/mink-goutte-driver": "*",
        "behat/mink-selenium2-driver": "*",
        "drupal/coder": "dev-8.x-2.x",
        "drupal/drupal-extension": "^3.4",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.1.0",
        "sebastian/phpcpd": "*",
        "phpunit/phpunit": "^6.5",
        "phpunit/php-timer": "^1.0.9",
        "drupal/console":"1.1",
        "squizlabs/html_codesniffer": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
            "type": "git",
            "url": "https://github.com/SignWo/open_social"
        },
        {
            "type": "package",
            "package": {
                "name": "squizlabs/html_codesniffer",
                "version": "1.0.0",
                "source": {
                    "url": "https://github.com/squizlabs/HTML_CodeSniffer.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    ],
    "scripts": {
        "post-install-cmd": [
            "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
        ],
        "post-update-cmd": [
            "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
        ]
    },
    "extra": {
        "installer-types": [
            "bower-asset",
            "npm-asset"
        ],
        "installer-paths": {
            "html/core": [
                "drupal/core"
            ],
            "html/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "html/profiles/contrib/social": [
                "goalgorilla/open_social"
            ],
            "html/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "html/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "html/libraries/{$name}": [
                "type:drupal-library",
                "type:bower-asset",
                "type:npm-asset"
            ],
            "scripts/{$name}": [
                "goalgorilla/open_social_scripts"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "enable-patching": true,
        "patches": {
            "squizlabs/html_codesniffer": {
                "Translatings does not work": "patches/DS-5443-accessibility.patch"
            }
        }
    }
}
```

### 2. The process with `drupal_social`
I did clone the `drupal_social` for testing Behat tests based on the tutorial from [how to run the behat tests locally](https://www.drupal.org/docs/8/distributions/open-social/how-to-run-the-behat-tests-locally):
```
Truls-MBP:drupal_social truls1502$ composer install
...[long installation list]..
Truls-MBP:drupal_social truls1502$ composer show drupal/like_and_dislike 
name     : drupal/like_and_dislike
descrip. : Like & Dislike
keywords : Drupal
versions : * 1.0.0-alpha3
type     : drupal-module
license  : GNU General Public License v2.0 or later (GPL-2.0+) (OSI approved) https://spdx.org/licenses/GPL-2.0+.html#licenseText
source   : [git] https://git.drupal.org/project/like_and_dislike 8.x-1.0-alpha3
dist     : [zip] https://ftp.drupal.org/files/projects/like_and_dislike-8.x-1.0-alpha3.zip 8.x-1.0-alpha3
names    : drupal/like_and_dislike

support
source : http://cgit.drupalcode.org/like_and_dislike
issues : http://drupal.org/project/issues/like_and_dislike

requires
drupal/core ~8.0
drupal/votingapi *
Truls-MBP:drupal_social truls1502$ docker exec social_web bash /var/www/scripts/social/install/install_script.sh
...[long installation list]..
Truls-MBP:drupal_social truls1502$ docker exec -it social_behat bash
root@fc882ddf363b:/var/www/html# cd /var/www/html/profiles/contrib/social/tests/behat
```

### 3. Modified `like-create-event.feature`-file
I went into `html/profiles/contrib/social/tests/behat/features/capabilities/like/like-create-event.feature` and added couple lines with `And I break` to the file where I can check how it looks on _VNC Viewer_:
```
@api @like @stability @DS-2968 @stability-4 @like-create-event
Feature: Create event like
  Benefit: In order to like an event
  Role: As a LU
  Goal/desire: I want to be able to like an event

  Scenario: Successfully like an event
   Given users:
     | name     | mail               | status | field_profile_first_name | field_profile_last_name |
     | user_1   | mail_1@example.com | 1      | Albert                   | Einstein                |
     | user_2   | mail_2@example.com | 1      | Isaac                    | Newton                  |
     And I am logged in as "user_1"
     And I am on "user"
     And I click "Events"
     And I click "Create Event"

    When I fill in the following:
      | Title | Event for likes |
      | edit-field-event-date-0-value-date | 2025-01-01 |
      | edit-field-event-date-end-0-value-date | 2025-01-01 |
      | Time | 11:00:00 |
      | Location name | GG HQ |
     And I fill in the "edit-body-0-value" WYSIWYG editor with "Body description text."
     And I press "Save"
    Then I should see "Event for likes has been created."

   Given I am logged in as "user_2"
     And I open the "event" node with title "Event for likes"
    Then I should see "Event for likes"
     And I should see "Albert Einstein"
     And I click the xth "0" element with the css ".vote-like a"
     And I wait for AJAX to finish
     And I break

    Given I am logged in as "user_1"
      And I break
      And I click the xth "0" element with the css ".notification-bell a"
      And I break
     Then I should see "Notification centre"
      And I should see "Isaac Newton likes your event"
      And I break
```

### 4. Running Behat test
Before running the beaht test, I opned VNC Viewer, so I can have look at it while it is running the specific test
```
root@fc882ddf363b:/var/www/html/profiles/contrib/social/tests/behat# /var/www/vendor/bin/behat --tags "@like-create-event"
@api @like @stability @DS-2968 @stability-4 @like-create-event
Feature: Create event like
  Benefit: In order to like an event
  Role: As a LU
  Goal/desire: I want to be able to like an event

  Scenario: Successfully like an event                                                 # /var/www/html/profiles/contrib/social/tests/behat/features/capabilities/like/like-create-event.feature:7
    Given users:                                                                       # Drupal\social\Behat\SocialDrupalContext::createUsers()
      | name   | mail               | status | field_profile_first_name | field_profile_last_name |
      | user_1 | mail_1@example.com | 1      | Albert                   | Einstein                |
      | user_2 | mail_2@example.com | 1      | Isaac                    | Newton                  |
    And I am logged in as "user_1"                                                     # Drupal\social\Behat\SocialDrupalContext::assertLoggedInByName()
    And I am on "user"                                                                 # Drupal\social\Behat\SocialMinkContext::visit()
    And I click "Events"                                                               # Drupal\social\Behat\SocialMinkContext::assertClick()
    And I click "Create Event"                                                         # Drupal\social\Behat\SocialMinkContext::assertClick()
    When I fill in the following:                                                      # Drupal\social\Behat\SocialMinkContext::fillFields()
      | Title                                  | Event for likes |
      | edit-field-event-date-0-value-date     | 2025-01-01      |
      | edit-field-event-date-end-0-value-date | 2025-01-01      |
      | Time                                   | 11:00:00        |
      | Location name                          | GG HQ           |
    And I fill in the "edit-body-0-value" WYSIWYG editor with "Body description text." # Drupal\social\Behat\FeatureContext::iFillInTheWysiwygEditor()
    And I press "Save"                                                                 # Drupal\social\Behat\SocialMinkContext::pressButton()
    Then I should see "Event for likes has been created."                              # Drupal\social\Behat\SocialMinkContext::assertPageContainsText()
    Given I am logged in as "user_2"                                                   # Drupal\social\Behat\SocialDrupalContext::assertLoggedInByName()
    And I open the "event" node with title "Event for likes"                           # Drupal\social\Behat\FeatureContext::openNodeWithTitle()
    Then I should see "Event for likes"                                                # Drupal\social\Behat\SocialMinkContext::assertPageContainsText()
    And I should see "Albert Einstein"                                                 # Drupal\social\Behat\SocialMinkContext::assertPageContainsText()
    And I click the xth "0" element with the css ".vote-like a"                        # Drupal\social\Behat\FeatureContext::iClickTheElementWithTheCSS()
    And I wait for AJAX to finish                                                      # Drupal\social\Behat\SocialMinkContext::iWaitForAjaxToFinish()
 [Breakpoint] Press [RETURN] to continue, or 'q' to quit...
```
screenshot 2018-10-30 13 06 22


For me, I can only see like mouse hover effect such as the sreenshot above, but not like I have clicked. I have also tried to click on the heart-icon. But no luck. The twig code from like_and_dislike-module looks alike, a bit different. But still have same html tag such as `.vote-like a`.

So how to solve this one? I have tried to change different click-formulate on my PHPStorm, but still no luck with any step. Do anyone from OS staff (@jaapjan @ronaldtebrake @Kingdutch @bramtenhove) or whoever mind to help me? So I can also help with the other behat tests and other PR I have created 🤓 😊

**Comment by jaapjan** [comment]
Hey @truls1502 thank you for the extensive report and looking into this!

Is this happening only in the Behat test or can you also reproduce it in your own browser?

The first thing which popped to my mind when seeing this issue is that it might be related to cache. But I can't find any issue related to that in the changelog of this module. Did you see anything which might be causing this? 🤔

**Comment by truls1502** [comment]
I have not reproduced on the browser. Only on Behat test-docker. I can try it later today 😊

**Comment by truls1502** [comment]
@jaapjan - It didn't work on local browser. Got tips and help from @robertragas about how to fix the PR.

I found out this PR needs to change the twig-file (`themes/socialbase/templates/like/like-and-dislike-icons.html.twig`), below it is diff between the version:
https://cgit.drupalcode.org/like_and_dislike/diff/templates/like-and-dislike-icons.html.twig?h=8.x-1.x&id=a763c1e13b54cba4fba51e6b01e997aa015d5b19&id2=13b265d93511c74ec63f72f475a2271e0f79459d

Working on changes of the twig-file and hope it solve the issue.

**Comment by truls1502** [comment]
👋 Not sure about who to ping, so I pinged to all: @jaapjan @bramtenhove @Kingdutch @ronaldtebrake @robertragas 🙈 

1. It seems that the changes in their file [js/like_and_disline.js](https://cgit.drupalcode.org/like_and_dislike/diff/js/like_and_dislike.js?h=8.x-1.x&id=a763c1e13b54cba4fba51e6b01e997aa015d5b19&id2=13b265d93511c74ec63f72f475a2271e0f79459d) might have affected to your own script [themes/socialbase/assets/js/like_and_dislike_service.min.js](https://github.com/goalgorilla/open_social/blob/8.x-3.x/themes/socialbase/assets/js/like_and_dislike_service.min.js), if I am wrong? 
Can someone confirm it? _Since I am not the javascript guy._ 😜 

2. Otherwise, as I have mentioned in the previous post, there is a bit changed on the twig-file [templates/like-and-dislike-icons.html.twig](https://cgit.drupalcode.org/like_and_dislike/diff/templates/like-and-dislike-icons.html.twig?h=8.x-1.x&id=a763c1e13b54cba4fba51e6b01e997aa015d5b19&id2=13b265d93511c74ec63f72f475a2271e0f79459d) to [themes/socialbase/templates/like/like-and-dislike-icons.html.twig](https://github.com/goalgorilla/open_social/blob/8.x-3.x/themes/socialbase/templates/like/like-and-dislike-icons.html.twig), but I believe it is not the reason of error, right? 👍

**Comment by robertragas** [comment]
I also said this to @truls1502 in slack, but this one is incorrect because the logic of the javascript files like above indeed changes, so this needs to be refactored. Also might need some twig changes to reflect the correct amount of likes, but you would notice that right away after changing the javascript file.

**Comment by truls1502** [comment]
I have now come to a step further on the issue which it has passed *three of four tests*. Please check if I am doing right so far. I hope so it is right.

However, the remaining test as `like-post-stream-anonymous` where javascript tries to post `disable-status` when not logged in or is the anonymous user doesn't succeed the test. I need the help to find out why it has not inserted the `disable-status`.

**Comment by robertragas** [comment]
This will not make it in 3.6 anymore. After trying to debug the problems mentioned above I was curious how the clean version of like-dislike would work and got the same problems here, so it seems like a contrib issue. Even if we would manage to fix this for the contrib we don't want a patched version with performance problems.

You can see the drupal ticket here
https://www.drupal.org/project/like_and_dislike/issues/3017244

**Comment by jaapjan** [comment]
Closing PR for now since we have to wait for https://www.drupal.org/project/like_and_dislike/issues/3017244 to be solved in the module.

**Comment by truls1502** [comment]
The last commit solved 3 of 4 Travis tests. The last one needs to fix something with disable-status.

**Comment by ronaldtebrake** [comment]
We still need the patch for https://www.drupal.org/project/like_and_dislike/issues/3017244 otherwise we can't use this update since it will still break it. (Or wait for a new release of their module) 

Clearing the milestone for now and closing it.

**Comment by truls1502** [comment]
Reopening the PR

**Comment by truls1502** [comment]
What was the reason change to 3.13? Did not the PR solve the issue?

**Comment by ronaldtebrake** [comment]
Tests were failing and we couldn't let the release wait on this PR. 
It's a pretty long thread and weren't able to properly review it within the last 2/3 days it was reopened.

**Comment by truls1502** [comment]
I see your point, do you mind to tell what test failed in MOSS since Travis all were passed? Maybe I can try to solve it if it is possible? :)

**Comment by ronaldtebrake** [comment]
As discussed with @truls1502 we will close this one and move this to a new PR for 4.x since we will move away from 3.x very soon. 
Thanks for that @truls1502 :)

**Comment by truls1502** [comment]
Trying to change branch base first to check if it works?

**Comment by ronaldtebrake** [comment]
Will be reopened with correct base branch.

**Pull request closed without merging**
