### PR TITLE
Internal: Remove usage of install_script.sh in Behat CI

### PR DESCRIPTION
**Pull request by Kingdutch**
This PR depends on https://github.com/goalgorilla/open_social/pull/3285 merge that first

## Problem / Solution
The install script tries to install demo content which doesn't work consistently between versions of Open Social. However as of a recent update the CI actually exits when it fails (previously it failed silently).

In our tests we're supposed to create everything we need so we shouldn't be installing demo content anyway. That's why we replace the usage of the script with a more transparent site-install command.

## Issue tracker
Internal no issue

## How to test
- [ ] CI should still pass

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Release notes
Internal change no release notes

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Review by navneet0693 — APPROVED** [review]

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3282-py9g9y2vvqyksk3blwg89ydhrpxzpfee.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63bece72af6a28e80b7d0773

**Pull request merged**
