### PR TITLE
Move PHPUnit testing from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem
Eventually we want to get rid of Travis. Additionally we want to use PHPUnit more and Travis does not give separate feedback on PHPUnit tests.

## Solution
This removes PHPUnit testing from Travis and instead move it to GitHub
Actions.

PHPUnit requires a proper Drupal set-up to execute so we add a
composer.json project file for testing. The GitHub action downloads this
test file and then configures composer to install the latest version of
the code for which the workflow is being run.

GitHub Actions runs PHPUnit directly rather than through run-tests in
social_scripts. This decouples the configuration of Open Social's CI
from other repositories. Additionally since XDebug is not installed on
our GitHub actions container we don't need long PHP config arguments to
disable it.

The PHPUnit configuration is updated to use a SQLite database which
works for all types of tests except browsertests (which requires more
infrastructure). This avoids the need for an external MySQL database and
has the added benefit of speeding up tests because database requests
don't need to go over the network.

## Issue tracker
CI change, no issue

## How to test
- [ ] Travis no longer runs PHPUnit tests
- [ ] Travis passes
- [ ] PHPCS passes
- [ ] PHPStan passes
- [ ] Tugboat builds
- [ ] New PHPUnit workflow passes.

## Future improvements
This has been open for quite long so didn't get around to it. However, the following changes can be made in the future.

- Move PHPCS and PHPStan into a single "Code quality" workflow (a single workflow can have multiple jobs with status output)
- Run PHPUnit on newer PHP versions as well (i.e. matrix test 7.4, 8.0 and 8.1 to ensure future version compatibility)
- Look at how PHPUnit reports results so they can be shown in the test result on the PR page (i.e. requires no clicking into the workflow)

## Screenshots
N/a

## Release notes
CI change n/a

### CODE REVIEW

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
Set-up seems to be working but for some reason it's not actually picking up the PHPUnit tests that are being found when running in Travis.

**Comment by Kingdutch** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-khg0qw1tofgdfhjuxslqfechowsk38ti.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c0756675714648eba0e2c1

**Comment by Kingdutch** [comment]
Turns out I previously killed `--testsuite social` for Travis but re-introduced it here. That's why no tests were found. With the current PHPUnit config we don't need to specify a test suite. I did make two other changes in my force push:

- Add the absolute path to `phpunit.xml` this is needed for the KernelTests which run in an isolated process in a different working directory. Without this they can't find the config file.
- Add mikey/vfsstream (as is the case in `drupal_social`) which is needed for those tests too.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
Additionally when using environment variables in `run` you can use `$VARNAME` as you would normally on a shell. If you pass it into an action however you need to use `${{env.VARNAME}}`. This distinction was probably also causing some issues in set-up 🙈

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
Okay so after re-reading the documentation closely. The `$GITHUB_WORKSPACE` variable is available in *runner*. The trick is that some actions will take their argument into a runner which allows the variable to be interpreted. The PHPUnit action takes what it gets as a literal string so no interpolation is used.

In those cases you need to use *[context](https://docs.github.com/en/actions/learn-github-actions/contexts)*. You can set your own environment variables which show up in the 'env' context (`${{ env.VARIABLE }}`). However, the default environment variables set for runners are not found there. They are found elsewhere. Thus in the variable for runners `$GITHUB_WORKSPACE` corresponds to the `${{ github.workspace }}` context which can be used in arguments to actions.

The only thing left to solve is why PHPUnit doesn't see the files that are clearly present.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
Success! Now we just need to get SQLite available in the Docker container.

**Comment by Kingdutch** [comment]
Okay so we already solved this in the PHPStan workflow. We can just update alternatives to use PHP 7.4 specifically and then we can just run everything as normal. This also means we don't need to pull in a bunch of actions. Our usage of composer is simple enough when PHP 7.4 is installed on the host that we can just run everything directly.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
It's running but it consistently isn't able to open the database for a single test. I'm not sure why that's the case. The database is needed in a lot of tests so I would expect it to fail more often. However, it's also very consistently the same test, which makes a false positive less likely.

An additional thing that still needs work is to get the test reporting working in such a way that it can show up in GitHub :)

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
Also no joy using a MySQL service container 🤯

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2376-gm5en4hpabvq48fahfh2co9e0fja0jzs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614c91fbb8fde5f0f4b54db8

**Comment by Kingdutch** [comment]
Discussed with Ronald, not waiting for Travis

**Pull request merged**
