### PR TITLE
Issue #3268097: Update social blue theme to the latest version

### PR DESCRIPTION
**Pull request by tbsiqueira**
## Problem
Update Social Blue theme to the latest 2.1.3 version

## Solution
Update Social Blue theme to the latest 2.1.3 version

## Issue tracker
https://www.drupal.org/project/social/issues/3268097

## How to test
- [ ] Check if Open Social is using the latest 2.1.3 social blue theme

## Screenshots
N/A

## Release notes
N/A

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2803-kxysgqxazqlcfy497ruhzrpp75rdlymg.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6225d701b1d827ef08912de6

**Review by navneet0693 — APPROVED** [review]

**Review by Ressinel — APPROVED** [review]

**Comment by tbsiqueira** [comment]
I"ll close this PR due to a bug on social base theme, we will reopen it once we have the fixed version

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2803-qlnle6gdnq1mpcaduvnenppbnia7kg9h.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62289fc2af445bb315bc20c2

**Comment by open-social-tugboat** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr2803-ojntoswdzgnsvaadql4dd6ruiqkeonqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62289fc2af445bb315bc216c

**Comment by tbsiqueira** [comment]
🍒  picked to 11.0.x and 11.1.x

**Pull request merged**
