### PR TITLE
Issue #3189520 by chmez: As a user I want to see logo in the footer

### PR DESCRIPTION
**Pull request by OH17L**
## Problem
As a user, I want to see a logo in the footer.

## Solution
Should be possible to replace: logo, text, link.

## Issue tracker
- https://www.drupal.org/project/social/issues/3189520
- https://getopensocial.atlassian.net/browse/ECI-1113

## How to test
- [ ] When you enable the "Social Footer" module then you should see a block with the following text in the footer section of a page: "powered by Open Social".
- [ ] When you click on that text then you should be redirected to [getopensocial.com](https://getopensocial.com/).
- [ ] Log in as SM+ and navigate to the "/admin/structure/block/manage/socialblue_footer_powered" page.
- [ ] You should see the following fields: "Logo", "Text", "Link".
- [ ] The "Logo" field should be empty.
- [ ] The "Text" field should contain the following text: "powered by Open Social".
- [ ] The "URL" sub-field of the "Link" field should contain the following link: "https://getopensocial.com/".
- [ ] The "Title" sub-field of the "Link" field should contain the following text: "Community Engagement Platform Software".
- [ ] Upload an image in the "Logo" field and press "Save block".
- [ ] When you navigate to the front page then you should see uploaded image in the footer section and this image should be clickable.

## Release notes
There is now an easy option to add your organizations logo to the footer next to the footer menu.

### CODE REVIEW

**Review by ribel — APPROVED** [review]
Look good to me.

**Comment by ribel** [comment]
Hi, @ronaldtebrake,
Since this is a new feature, as usual, we ask you to do the final review and confirmation.
So please let us know if it can be merged.

**Comment by ronaldtebrake** [comment]
Hi guys,

Don't forget to add an installer_options.yml file so this optional module can be installed during the Drupal installation process. 

Next to that it seems a bit weird the menu now moves to the right of the footer, is this per design? Couldnt get it out of the PR / Ticket information.

Screenshot 2020-12-24 at 12 05 41

Screenshot 2020-12-24 at 12 06 46

**Comment by agami4** [comment]
Hey @ronaldtebrake, we made a footer layout like on the `SparkBlue` project.
1. The first screenshot - when we have a logo block and menu.
social_footer
2. The second screenshot - when we have only the menu.
social_footer1

**Comment by ronaldtebrake** [comment]
Check, clear.

@ribel one last question, curious if we can easily do the following:
(not sure how much work it costs but it should be a better UX for our SM and developers)

1. Enable social_footer by default in the Distro
2. Only when there is content in the footer block, it renders the logo and moves the menu to the right
3. Without content we don't render the block and the footer menu links are shown from the left side.

This way nobody has to enable any additional modules and by default nothing changes, untill someone actually adds something to the block.

**Comment by ribel** [comment]
@ronaldtebrake I will ask @chmez and @agami4 to check if 2 and 3 are easy to fix, but in this case, I assume we need to remove all default values like _powered by Open Social_ from that block?
Then I think it will be hard to understand for managers what to add and where to change those values.
Because in the case with default Open Social values they can even use contextual links for edit.

**Comment by ronaldtebrake** [comment]
Thank you!

I'm ok with the default values being there for now. We will mention this in the release notes so users upgrading to 10.0.0 will know they can change it and write a manul on community talks so they know where to change this.

Also I'm not sure if contextual links are always enabled so we also need to create a manual to explain how to do this. But I can do this together with our customer success managers after the release notes are written :)

**Review by ribel — APPROVED** [review]
@ronaldtebrake I've tested that @OH17L implemented all items that you asked in the previous comment. I assume it can be merged now?

**Comment by ronaldtebrake** [comment]
Definitely @ribel, thank you and @OH17L as well!

**Pull request merged**
