### PR TITLE
Issue #3340217 by vnech: "Dropdown" render element doesn't set non-existent option as "active"

### PR DESCRIPTION
**Pull request by nechai**
If add any new group content visibility option to the flexible group (<em>/admin/group/types/manage/flexible_group/fields/group.flexible_group.field_group_allowed_visibility/storage</em>) 
alt

enable <strong>"Enable posts for members"</strong> and choose only this option in <strong>"Group content visibility options"</strong> field due creating a group 
alt

we get fatal error on group stream:
<code>The website encountered an unexpected error. Please try again later.
TypeError: _socialbase_get_visibility_icon(): Argument #1 ($title) must be of type string, null given, called in /var/www/html/html/themes/contrib/socialbase/src/Plugin/Preprocess/FieldDropdown.php on line 24 in _socialbase_get_visibility_icon() (line 80 of themes/contrib/socialbase/socialbase.theme).
_socialbase_get_visibility_icon(NULL) (Line: 24)
Drupal\socialbase\Plugin\Preprocess\FieldDropdown->preprocess(Array, 'dropdown', Array) (Line: 1443)
Drupal\bootstrap\Bootstrap::preprocess(Array, 'dropdown', Array) (Line: 118)
bootstrap_preprocess(Array, 'dropdown', Array)
call_user_func_array('bootstrap_preprocess', Array) (Line: 287)
Drupal\Core\Theme\ThemeManager->render('dropdown', Array) (Line: 478)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 75)
__TwigTemplate_eb9ba40db22317197998c9eb3d0c03becd2232b767050d8a7e8d8c3b492eb7bb->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('themes/contrib/bootstrap/templates/field/field-multiple-value-form.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field_multiple_value_form', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 201)
Drupal\Core\Render\Renderer->render(Array) (Line: 479)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 56)
__TwigTemplate_4bd2fc9abe6f1201de01478feea0f592aec76b21ad47a86c81a3e344ce3087eb->doDisplay(Array, Array) (Line: 405)
Twig\Template->displayWithErrorHandling(Array, Array) (Line: 378)
Twig\Template->display(Array) (Line: 390)
Twig\Template->render(Array) (Line: 55)
twig_render_template('themes/contrib/socialbase/templates/block/block--social-post.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('block', Array) (Line: 422)
Drupal\Core\Render\Renderer->doRender(Array, 1) (Line: 201)
Drupal\Core\Render\Renderer->render(Array, 1) (Line: 157)
Drupal\Core\Render\Renderer->Drupal\Core\Render\{closure}() (Line: 564)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 158)
Drupal\Core\Render\Renderer->renderPlain(Array) (Line: 172)
Drupal\Core\Render\Renderer->renderPlaceholder('callback=Drupal%5Cblock%5CBlockViewBuilder%3A%3AlazyBuilder&amp;args%5B0%5D=postongroupblock&amp;args%5B1%5D=default&amp;args%5B2%5D&amp;token=8ZSByMIrBTb3TyShsmie_pkvhoMwGaxi1gERGHbmvSU', Array) (Line: 693)
Drupal\big_pipe\Render\BigPipe->renderPlaceholder('callback=Drupal%5Cblock%5CBlockViewBuilder%3A%3AlazyBuilder&amp;args%5B0%5D=postongroupblock&amp;args%5B1%5D=default&amp;args%5B2%5D&amp;token=8ZSByMIrBTb3TyShsmie_pkvhoMwGaxi1gERGHbmvSU', Array) (Line: 547)
Drupal\big_pipe\Render\BigPipe->sendPlaceholders(Array, Array, Object) (Line: 305)
Drupal\big_pipe\Render\BigPipe->sendContent(Object) (Line: 112)
Drupal\big_pipe\Render\BigPipeResponse->sendContent() (Line: 381)
Symfony\Component\HttpFoundation\Response->send() (Line: 20)</code>

## Solution
"Dropdown" render element should not set non-existent option as "active"

## Issue tracker
- https://www.drupal.org/project/social/issues/3340217
- https://getopensocial.atlassian.net/browse/PROD-24094

## Theme issue tracker
n/a

## How to test
- [ ] Login as admin
- [ ] Make steps described on **"Problem"** section

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
n/a

## Release notes
"Dropdown" render element doesn't set non-existent option as "active"

## Change Record
n/a

## Translations
n/a

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Review by ribel — APPROVED** [review]
I've tested changes on the project where we had fatal error on Group Stream and it fix the issue.

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3307-rzy68bthp3ekgcvp5jlxyerh8af3ipgg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63e3829799029408a83a25cc

**Review by nkoporec — APPROVED** [review]

**Comment by nkoporec** [comment]
:cherries: picked to 11.6.x, 11.7.x,11.8.x

**Pull request merged**
