### PR TITLE
Issue #3306139 by vnech: Replace event icons format from "img" to "svg"

### PR DESCRIPTION
**Pull request by nechai**
## Problem
Event have icons in `img` format which made them less flexible to styling by social themes (`socialbase` and `socialblue`).
Also, if we replace the icons format we need to add appropriate changes in these templates `digestmail.html.twig` and `directmail.html.twig` otherwise we can't get these icons in the emails.

## Solution
- Replace event icons format `img` with `svg`.

## Issue tracker
- https://www.drupal.org/project/social/issues/3306139
- https://getopensocial.atlassian.net/browse/PROD-19286

## Theme issue tracker
N/A

## How to test
- [x] Login as SM
- [x] Create an event with filled "date" and "location" fields
- [x] Make sure icons available on event view page

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

## Screenshots
N/A

## Release notes
Replace event icons format from `img` to `svg` to be able to use the in emails.

## Change Record
N/A

## Translations
N/A

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3081-6ptpp7epo33h0uejlr1eb45vrtecfcxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6308738cf08423f9ad1b33ac

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3081-6ptpp7epo33h0uejlr1eb45vrtecfcxn.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6308738cf08423f9ad1b33ac

**Review by ribel — APPROVED** [review]
I have checked changes and all looks good to me.

**Before:**

image

**After:**

image

**Review by tbsiqueira — APPROVED** [review]

**Comment by tbsiqueira** [comment]
Great PR ! Great documentation, comments on code were really helpful! Excellent work!

Approved

**Comment by ribel** [comment]
🍒 picked to 11.4.x and 11.5.x

**Pull request merged**
