### PR TITLE
Internal: Restructure EmailContext to provide better debug information

### PR DESCRIPTION
**Pull request by Kingdutch**
## Problem/Solution

The EmailContext mail handling was created quite some years ago. In case an email in a test didn't match, the developer only got information that there was no match, there was no useful information about what didn't match (for example that a subject wasn't found, or that a specific line didn't match).

The test steps are rewritten so that the developer gets as much actionable information as possible. This can be that a specific subject wasn't found, or that one or more lines of the body did not match. This makes it easier for the developer based on just the test output and the changes they may have made to determine where the error comes from.

Providing this information in the test output requires some new functions to be rewritten. This opportunity is used to also restructure the other functions of the file and provide PHPStan output:

- Behat hooks are placed at the top
- Followed by developer usable test steps
- Followed by protected functions which are used to support the test steps, in the order in which they were first called.

## Issue tracker
Test infrastructure change only, no issue.

## How to test
- [ ] Write an email test that fails for different reasons and inspect the output.
- [ ] The changes should not break any tests already in the CI, so Behat for this PR should be green without test changes.

### Before merge
- [ ] Code/peer review is completed
- [ ] All commit messages are [clear and clean](https://open-social.slite.com/app/docs/DnmermZDIx_0OQ). If applicable a rebase was performed
- [ ] All automated tests are green
- [ ] Functional/manual tests of the acceptance criteria are approved
- [ ] All acceptance criteria were met
- [ ] New features or changes to existing features are covered by tests, either unit (preferably) or behat
- [ ] Update path is tested. New hook_updates should respect update order, right naming convention and consider hook_post_update code
- [ ] Module can be safely uninstalled. Update/implement hook_uninstall and make sure that removed configuration or dependencies are removed/uninstalled
- [ ] This pull request has all required labels (team/type/priority)
- [ ] This pull request has a milestone
- [ ] This pull request has an assignee (if applicable)
- [ ] Any front end changes are tested on all major browsers
- [ ] New UI elements, or changes on UI elements are approved by the design team
- [ ] New features, or feature changes are approved by the product owner

### After merge
- [ ] Code is tested on all branches that it has been cherry-picked
- [ ] Update hook number might need adjustment, make sure they have the correct order
- [ ] The Drupal.org ticket(s) are updated according to this pull request status

### CODE REVIEW

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Comment by open-social-tugboat** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr3500-nvnqfiickpvij9r2nhb4i1tdlzy7fkrg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/64ef23d4722387719c0f91ba

**Review by robertragas — APPROVED** [review]

**Comment by robertragas** [comment]
This was tested some while ago, also used functionally in another PR 2705.

Approved, it adds a lot more helpful information, but also feels more stable.

**Pull request merged**
