### PR TITLE
by robertragas: add user profile statistisc blocks to the courses pro…

### PR DESCRIPTION
**Pull request by robertragas**
…file page

## Problem
When going to the courses page on the user profile page it does not show the profile statistics block so it leaves a big gap there.

## Solution
Add the courses profile page url to the block settings. 

## Issue tracker
https://www.drupal.org/project/social/issues/3181791

## How to test
- [ ] Enable social_courses
- [ ] Create a course and enroll to it
- [ ] Go to your user profile and click on courses tab
- [ ] See the profile block missing
- [ ] Check out to this branch and check again

## Release notes
When Social Courses has been enabled it add an extra page on your profile to see your courses. This page was missing the profile block on the left which has been added now.

### CODE REVIEW

**Review by jochemvn — CHANGES_REQUESTED** [review]
The location of the secondary menu and the card differs per item... on the courses page it's below the header image, on other pages it's on top of it... see attached screenshots:
Screenshot 2020-11-24 at 11 10 59
Screenshot 2020-11-24 at 11 11 07

**Comment by robertragas** [comment]
@jochemvn ready to be review again with the new fixes.
Also I am closing this one in favor of https://github.com/goalgorilla/social_course/pull/29
So we can keep the social_course changes within the social_course module.

**Comment by jochemvn** [comment]
@robertragas alright fair enough... you can close it then

**Comment by robertragas** [comment]
Closed in favor of the course repo pr

**Pull request closed without merging**
