### PR TITLE
issue #3116229 by robertragas: also apply hide content fixes to sky t…

### PR DESCRIPTION
**Pull request by robertragas**
P.S.Same issue as https://github.com/goalgorilla/open_social/pull/1734 but we forgot to also do it for the sky theme.

## Problem
The number of enrollments and enrolled status displays in the content sections of Events.

## Solution
Exclude not needed fields from the full event template.

## Screenshots
image

image

## Issue tracker
- https://www.drupal.org/project/social/issues/3116229
- https://getopensocial.atlassian.net/browse/ECI-1002

## How to test

- [ ] Enroll to event

- [ ] Go to the Event page and you should not see the number of enrollments and status above the description.

### CODE REVIEW

**Comment by robertragas** [comment]
> Nice, looks good!
> 
> Can you fix Travis still?

Travis is due to the social_pwa and failing in all PR's or is this now fixed again?

**Comment by robertragas** [comment]
I merged in the base branch again and will see, because the changes I did are not related to the failing of travis.

**Comment by ronaldtebrake** [comment]
> > Nice, looks good!
> > Can you fix Travis still?
> 
> Travis is due to the social_pwa and failing in all PR's or is this now fixed again?

I have fixed this.

**Comment by robertragas** [comment]
Travis was now green so merged and cherry-picked to 8.x-8.x

**Pull request merged**
